### ISSUE TITLE
ha-paper-slider is now ha-slider in 0.116.0 beta

### ISSUE THREAD

**Issue by noxhirsch** [nielsfaber/scheduler-card#102]
Since 0.116.0b0 `ha-paper-slider` has changed to `ha-slider`. This leads to missing sliders in 0.116
Sadly I don't know how to implement this change into the scheduler-card with backwards compatibility - else I'd have opened a PR.

**Comment by nielsfaber** [comment]
I am aware of this change.
I was involved in the decision to remove it.
When 0.116 comes out the card will get an update. The `ha-slider` is a merged from `ha-paper-slider` and `ha-slider`. If I make the change now i will also get complaints (since `ha-slider` in 0.115.x has different looks)

**Comment by noxhirsch** [comment]
No need to change anything for a beta version, of course (in this case I already fixed it locally)! Just wanted to make you aware of the upcoming change - I didn't know that you were involved in the decision 👍

**Comment by nielsfaber** [comment]
I decided to update it already.
I think it will be more annoying if the slider disappears completely when users update to 0.116.
For now it looks a little different, but will be only for a while.
