### ISSUE TITLE
Global card enable/disable scheduler

### ISSUE THREAD

**Issue by GianCann** [nielsfaber/scheduler-card#104]
Hi,

there is a way to enable/disable ALL scheduled entities in specific card?

I want to enable/disable all the entities in a specific card based on the value of other entity (a rain sensor).

**Comment by nielsfaber** [comment]
No this is not possible. Also not being considered.
Support will come for adding conditions to timers. These conditions will be checked before executing the actions, if they don't pass they are skipped.
I think this is a better way of solving your situation.

**Comment by Misiu** [comment]
> Support will come for adding conditions to timers. 

Awesome 🎉🎉🎉

**Comment by nielsfaber** [comment]
@Misiu between you and me:
Conditions are already supported in the custom-component actually.
![Capture](https://user-images.githubusercontent.com/16861605/95068371-82770080-0705-11eb-8b34-9943981d44e1.PNG)
I just have to make a UI for the scheduler-card.

**Comment by Misiu** [comment]
> @Misiu between you and me:

I'll not speak a word to anybody 😁

**Comment by nielsfaber** [comment]
@GianCann With v1.8.0 of the card, you can set `show_header_toggle: true` to show a global toggle switch.

**Comment by KTibow** [comment]
@nielsfaber time for a UI?

**Comment by GianCann** [comment]
Thank you @nielsfaber 
I will try later today ;)

**Comment by GianCann** [comment]
I try with the 1.8.2 but I get this error:
![Screenshot_20201021_055840_io homeassistant companion android](https://user-images.githubusercontent.com/45897944/96671815-09adb080-1363-11eb-8d9d-c0fc423f394a.jpg)

**Comment by nielsfaber** [comment]
That can't be 😕 
Maybe you should refresh the browser or something.
Do you see the other changes in the card?
E.g. the switches for each item?

**Comment by GianCann** [comment]
Ok, I restart HA and now it work well.
It's possible to manage the toggle via code?
For example, with a binay switch in another card?

**Comment by nielsfaber** [comment]
Good!
Well, this switch is only added to the card, so you cannot trigger it from another place.
That would require some changes to the scheduler-component.
But the scheduler-component has no knowledge of which schedule is in which card..

**Comment by GianCann** [comment]
ok, thank you for the fast reply/support.

For the future, take in consideration the option to enable/disable via script all sheduled item in a card, even if it's possible to do.

**Comment by nielsfaber** [comment]
I am afraid it will never become possible.
Also for other (non-scheduler) entities, you cannot create an automation that applies to all entities in a certain card.
There is no way to see which entity is in which card.

**Comment by GianCann** [comment]
> There is no way to detect which entity is in which card.

Yes, it have a sense...
I need to rethink my idea of how manage the scheduling of open/close a roof windows based to a rain sensor.
