### ISSUE TITLE
PIN to disarm alarm

### ISSUE THREAD

**Issue by ajobbins** [nielsfaber/scheduler-card#105]
There is an option in the scheduler to disarm an alarm panel, but this fails without the pin code to the alarm. Could this be added to to scheduler card so that the PIN can be sent as part of the service call to disarm?

**Comment by KTibow** [comment]
Is it possible to look for the pin in config, so you don't need it?

**Comment by KTibow** [comment]
That is Home Assistant config, somewhere in `configuration.yaml` or `.storage` there's a PIN.

**Comment by ajobbins** [comment]
Yes, it's set in the config when setting up the alarm, but you have to pass it into the service call to disarm (I guess to ensure that you're not able to call a disarm without knowing the disarm PIN). 

If doing it with a service call (say in an automation), you have to pass in the PIN in the service data, e.g.

- service: alarm_control_panel.alarm_disarm
   entity_id: alarm_control_panel.alarm_name
   data:
     code: 1234
     entity_id: alarm_control_panel.alarm_name

**Comment by KTibow** [comment]
I think this just requires being able to disable the slider for a variable and use a text field instead.

**Comment by nielsfaber** [comment]
The pin code of the `alarm_control_panel` is not a property that I could detect, so you will have to enter manually.
You could customize the action for disarming and add the pin:
```
customize:
  alarm_control_panel.my_alarm:
    actions:
      - service: alarm_disarm
        service_data: {code: 1234}
```
Adding a text field in the scheduler for setting it up would be another option (as @KTibow says).

But I must warn you. The pin code will not be encrypted, it will be visible in the properties of the schedule entity.
And there is also the safety hazard that if you go out of town for a couple of days, you really need to disable the schedule.
If you're OK with these risks, no problem.

**Comment by KTibow** [comment]
There's a reason most non-HA automation only lets you arm an alarm and not disable it automatically, for security. It could help, but *is it really worth the risks*?

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.
