### ISSUE TITLE
Set variable using text input box

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#106]
Sometimes you need a text input box instead of a slider. It'd be nice to have an input box instead of the text here:
![image](https://user-images.githubusercontent.com/10727862/95147931-01386180-0737-11eb-8642-518fb69368ce.png)

**Comment by nielsfaber** [comment]
In which cases?
Only action i can think of would be `notify`, where you could type a message and schedule a reminder.

**Comment by KTibow** [comment]
Well if you need more accuracy, or I was thinking in the example with the PIN. I guess that this is a bit uncommon for this scheduler, but it's fairly common in general UI.

**Comment by nielsfaber** [comment]
I added this option to V2.1.0.
Documentation still needs to be updated for it though.
