### ISSUE TITLE
Changing AC sent command

### ISSUE THREAD

**Issue by mottibz** [nielsfaber/scheduler-card#107]
Hello Niels again, I have a question. I would like to distinguish between commands sent by the user manually from the Simple Thermostat UI that I am using and from the Scheduler Card. The AC Controller device that I developed is using MQTT for receiving commands and for sending status. Is there a way for example that when executing the "off" command, the Scheduler Card will send "timeroff" instead of "off"?

**Comment by nielsfaber** [comment]
I don't really understand the situation.
Is your AC controller an [MQTT climate](https://www.home-assistant.io/integrations/climate.mqtt/) entity?
If so, how did you configure it to send 'timeroff' command?
Is it included in the `hold_states` of the entity?

**Comment by mottibz** [comment]
Expanded explanation: My device is fully controlled via MQTT. When it starts, it uses the MQTT Discovery mechanism to register itself with HA and am I using the Simple Thermostat card to control it. All works well. I added the Scheduler Card in order to set timers and all works fine. The issue is that I would like to distinguish in my device between commands sent manually from the Simple Thermostat card and commands sent by the Scheduler Card. For example, I need to implement a different behavior of the device when the "off" command is sent manually from Simple Thermostat and when the same command is sent from the Scheduler Card. That is why I asked if the command sent from the Scheduler Card to execute "off" can be changed to something like "timeroff"

**Comment by nielsfaber** [comment]
> That is why I asked if the command sent from the Scheduler Card to execute "off" can be changed to something like "timeroff"

The scheduler card does not send commands.
It only calls the services that are supported by the entity.
What kind of entity are we talking about? Is it a `climate` device?
If so, supported actions are `turn_off`, `set_hvac_mode` and `set_preset_mode`.
See [climate integration](https://www.home-assistant.io/integrations/climate/).
Which action are you talking about?

**Comment by mottibz** [comment]
Yes, it is a climate device and I understand that you are not sending the commands but calling the device's services.
Question is if there is a way to change the behavior of the "turn_off" command to send a different command string, or inform my device that the "off" command is coming from the Scheduler Card

**Comment by nielsfaber** [comment]
No this is not possible.
This is defined by HA itself.
Turn_off command send by scheduler card is identical to turn_off command send by simple thermostat card.

If you really want a difference here, you could define an extra [hold mode](https://www.home-assistant.io/integrations/climate.mqtt/#hold_modes) for the climate device, called 'timeroff'. In scheduler card it will automatically show up as preset 'timeroff', so you could schedule this action.
But you will have to add hold_command and hold_state topics in the MQTT driver. 

Personally I don't really see the point of this. Turn_off is meant to turn your device off. Doesn't matter if you clicked a button yourself, or it was a scheduled job. Are you sure you want to go this direction?

**Comment by mottibz** [comment]
Thanks for the info. I will continue thinking about that. The reason for this is that when the timer goes off, I want my device to do a few additional things compared to the manual off by a user...

**Comment by mottibz** [comment]
OK, I implemented the "hold mode" and defined one hold mode called "timeroff". What happens now is that when I add a new timer item, I see that a new action option was added to the list, called "set preset" and when I select it and push "next", it shows the options "none" and "timeroff". Is there a way to configure the card that the "set preset" will not be displayed and the "turn off" action will call the new "timeroff" command instead of the standard "off" command? If not possible, is there a way to remove the "turn off" action and instead add an action that will call the "timeroff" command?

**Comment by mottibz** [comment]
1. After more research, I was able to add the "timeroff" action to the action list, using the "customize" config feature. I tested it and it works :-)  Now I need to remove the "turn off" and "set preset" actions from the displayed list of actions. How do I configure that? I could not find a way to do that. See current display:
![image](https://user-images.githubusercontent.com/11439987/95332037-89dc0c80-08b3-11eb-85f1-7a62a5e56e5c.png)

2. After selecting "set mode", I get a display of the available modes. See display:
![image](https://user-images.githubusercontent.com/11439987/95332208-c3147c80-08b3-11eb-9e32-8e11a2474cab.png)
How can I remove the "off" from the list so that the only off is the newly added "timeroff" feature?

Thanks a lot!

**Comment by KTibow** [comment]
`standard_configuration: false` and `customize`, read the docs

**Comment by mottibz** [comment]
Hi, I know about the option to set "standard_configuration: false". I am using it to add my own "turn off" action. My questions, when using it, are:
- I tried to define in the "customize" section the two actions: "set mode" and "set temperature" but could not figure out how to add them and have them work as in the standard configuration
- In the "set mode" option, I would like to remove the "off" option from the hvac_modes options list. Can this be done?
Thanks for your help!

**Comment by mottibz** [comment]
Hello again, what I have achieved so far is below and the current issue is listed below that:
                        customize:
                          '[[my_climate_entity]]':
                            actions:
                              - service: climate.set_preset_mode
                                name: Turn AC Off
                                icon: 'mdi:hvac-off'
                                service_data:
                                  preset_mode: timeroff
                              - service: set_hvac_mode
                                name: Set mode
                                icon: 'mdi:cog-outline'
                                variable:
                                  field: hvac_mode
                                  name: Operation mode
                                  options:
                                    - value: heat
                                      icon: fire
                                    - value: cool
                                      icon: snowflake
                              - service: set_temperature
                                name: Set Temperature
                                icon: 'mdi:coolant-temperature'
                                variable:
                                  field: temperature
                                  name: Temperature
                                  min: 16
                                  max: 30

Now, I did a few setting and the display is not correct. See below:
![image](https://user-images.githubusercontent.com/11439987/95565348-bbc2af80-0a28-11eb-8e25-92a36d327174.png)

What am I doing wrong?

**Comment by nielsfaber** [comment]
I'm closing this issue because it becomes a support thread.
Github is only intended for feature requests and bug reports.
Please use the forum thread for support on how to use this card.
I cannot read your code. I also don't understand your question.
The shared screenshot looks fine to me.
