### ISSUE TITLE
Scheduler / add service not found

### ISSUE THREAD

**Issue by RENEPLUS** [nielsfaber/scheduler-card#108]
Hello. I have installed the card on HA version 0.115-6, I have followed the steps described and I have not had problems in the installation, but when I press the button to save any type of programming it does not do it and the message "Error when calling the service Shedule / add service nof found ". I have reinstalled and the problem persists. No type of service related to Shedule Card appears in HA Services. You know what it can be ... thanks and good job.

**Comment by nielsfaber** [comment]
Did you add it to the integrations in HA?

**Comment by RENEPLUS** [comment]
How should I add to the integrations? I know that in configuration> integrations, button +, but what name should I add or what do I do from there? I use HA in YAML mode.
Sorry for such basic issues, but I'm very interested in using your card and any help is greatly appreciated.

**Comment by nielsfaber** [comment]
How about 'scheduler'? You should add it first, is also explained in the readme of the scheduler-component

**Comment by RENEPLUS** [comment]
Sorry. This is all that appears in the INSTALLATION section of your readme file.

"Installation
click to show installation instructions

HACS installation:

    Add https://github.com/nielsfaber/scheduler-card as a custom frontend repository.
    Click on "Install" under the new card that just popped up.

Manual installation

    Download the latest release of scheduler-card.js here and place it into www/scheduler-card.

    Use the GUI to add /local/scheduler-card/scheduler-card.js?v=0, or add a reference to the card in the resources section of configuration.yaml:

resources:
  - url: /local/scheduler-card/scheduler-card.js?v=0
    type: module

    Add the card in the view where you want it to be shown:

type: custom:scheduler-card
domains:
 ...
entities:
 ...
groups:
 ..."

**Comment by nielsfaber** [comment]
your problem is with the scheduler-component, not the card.
