### ISSUE TITLE
Odd behavior with disabled schedules in 1.7.3

### ISSUE THREAD

**Issue by clau-bucur** [nielsfaber/scheduler-card#113]
If there are more than one disabled schedule, they will get sorted randomly and creates some confusion in the card.
![scheduler-card](https://user-images.githubusercontent.com/47672949/95357374-768b6a00-08d0-11eb-9762-0c144dff66c0.gif)

Maybe disabled cards should be sorted by other means than "time until trigger", like "start time" which is a defined and fixed value.

**Comment by nielsfaber** [comment]
I agree that this doesn't look nice.
But the big question is why the list updates so often.
The view should only refresh when something changed in the entities list.
I will check if i can improve this.

**Comment by nielsfaber** [comment]
I improved the sorting and reduced the amount of refreshing (saw that any update in any HA entity would refresh the card, but too much). It is released in v1.7.4.
Close this issue if you see it improved.
