### ISSUE TITLE
2h offset - timezone problem? 

### ISSUE THREAD

**Issue by Yourigh** [nielsfaber/scheduler-card#117]
Hi, scheduler card works great, but one little detail is off. I need to set up 2h smaller time to actually get the wanted result. 5:30 makes an action on 7:30.

Have anyone of you encountered this? 

![Screenshot_20201009-073900_Home Assistant](https://user-images.githubusercontent.com/25552139/95547674-c585ec00-0a03-11eb-8d24-ce06ee09b5d3.jpg)

Thank you!

**Comment by nielsfaber** [comment]
In HA check 'configuration' -> 'general'.
Do you have your location and timezone configured right?
You could also try to add the [time sensor](https://www.home-assistant.io/integrations/time_date/) to check if HA configuration is correct.

**Comment by Yourigh** [comment]
Thank you for a blazing fast reply,
It was the timezone 🙃.
