### ISSUE TITLE
"Make scheme" is currently untranslated

### ISSUE THREAD

**Issue by giggo** [nielsfaber/scheduler-card#128]
Currently there is no translation string for "Make scheme"
<img width="482" alt="grafik" src="https://user-images.githubusercontent.com/213763/95848169-f93b7b80-0d4d-11eb-9e6f-301069b4af85.png">

**Comment by nielsfaber** [comment]
I deliberately did not implement localization options for the new features.
The main reason is that perhaps this will change significantly.
I'm not happy yet with this editor since a timeslot shorter than two hours is hard to define (due to the markers being close to each other).

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.
