### ISSUE TITLE
Missing "validate" button but twice "delete" button

### ISSUE THREAD

**Issue by JSteunou** [nielsfaber/scheduler-card#129]
When in *schedule scheme* view, there is twice the "delete" button and you have to go into *option* to get a *save* or *validate* button

![Capture d’écran du 2020-10-14 08-55-44](https://user-images.githubusercontent.com/2323127/95954650-eda68e00-0dfb-11eb-8f6c-71d3210475e1.png)

PS : *effacer* means *delete* in French

**Comment by nielsfaber** [comment]
oh wow that's weird. I'm surprised no one saw this before. 
It looks like you can fix it by clicking 'options'. There is a save button there 👍 
I will make sure to fix it

**Comment by nielsfaber** [comment]
Thanks for reporting, i removed it in v1.8.0.
