### ISSUE TITLE
Please add sorting

### ISSUE THREAD

**Issue by giggo** [nielsfaber/scheduler-card#13]
The items seem to be randomly arranged in the card:
![image](https://user-images.githubusercontent.com/213763/91670716-5a9de700-eb20-11ea-8d39-eb38e8ff2886.png)
It would be great if they would be sorted A-Z instead.

Example Card Config:
`
domains:
  light:
    actions:
      - service: turn_on
      - service: turn_off
type: 'custom:scheduler-card'
`

**Comment by nielsfaber** [comment]
Good idea!
Currently the entities appear in the same order as they are in the HA registry, I suppose this is sorted on entity_id.
I don’t have as many devices as you do, but it makes sense to provide sorting for better overview.
I will pick this up somewhere this week, I wil keep you posted.

**Comment by nielsfaber** [comment]
This feature is implemented in [v1.2.2](https://github.com/nielsfaber/scheduler-card/releases/tag/v1.2.2)

**Comment by z4rn0x** [comment]
Hello @nielsfaber 
First of all, thank you so much for this plugin, it's so powerful and it looks great, I'm a huge fan!
Quick question, same mindset, but a little bit different, would it be possible to organize the order of the actions displayed?
With my thermostat, I'd like to reorganize them:
![image](https://user-images.githubusercontent.com/34210703/101936725-eb1fa500-3bae-11eb-8599-721e870ac740.png)
A logical order would be: Comfort - Eco - Away - Off... But it's not in alphabetical order. I tried with 1- Comfort 2- Eco 3- Away - 4- Off. That works, but that's not nice to see the 1/2/3/4... What do you think?

**Comment by nielsfaber** [comment]
@z4rn0x i’m afraid it will stay alphabetical.
It doesn’t seem like a big issue to me, considering that the amount of options here is usually only a few.

**Comment by z4rn0x** [comment]
> @z4rn0x i’m afraid it will stay alphabetical.
> It doesn’t seem like a big issue to me, considering that the amount of options here is usually only a few.

Ok, understood. Not a big deal, just details... Thanks again for this great scheduler!
