### ISSUE TITLE
Actions are still available even when no time slot are selected

### ISSUE THREAD

**Issue by JSteunou** [nielsfaber/scheduler-card#130]
![Capture d’écran du 2020-10-14 08-56-35](https://user-images.githubusercontent.com/2323127/95954820-3100fc80-0dfc-11eb-8070-2e8b7f5f36d4.png)

Still possible to play with *actions* which can be confusing when no time slot are selected

**Comment by nielsfaber** [comment]
Good call, I have seen this before, but thought i fixed it.
Will check it out.

**Comment by nielsfaber** [comment]
It should be fixed in v1.8.0.
