### ISSUE TITLE
Input Boolean not supported as condition

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#133]
I tried to start a live test, but at the moment (I know it's beta) the input-boleans are not taken into account in the conditions...

Normal, or I'm the one who missed something.

![image](https://user-images.githubusercontent.com/45459269/95999810-8e19a400-0e36-11eb-9b3c-b84999bc6331.png)

![image](https://user-images.githubusercontent.com/45459269/95999849-983ba280-0e36-11eb-99fe-101fc98a2baf.png)
or
![image](https://user-images.githubusercontent.com/45459269/96000004-bc977f00-0e36-11eb-8879-6322891889ab.png)

**Comment by nielsfaber** [comment]
I added support for input_boolean to conditions in v1.8.0.
Besides, you can add any entity in a condition, by defining _states_ configuration.

**Comment by mycanaletto** [comment]
Thanks. But same problem for input_select...
