### ISSUE TITLE
Add support for group entities

### ISSUE THREAD

**Issue by hidzirAdam** [nielsfaber/scheduler-card#137]
I just try out creating a New Group Originate pickup from Scenes but I can only add Swiit it On at  Scheduler Entry, unfortunately i can't insert new entry to Switch 'Off' in Action for group because the Action which is  pre-set to Turn ON only.
Please varify my issue or it could be that i miss out any of the parameter setting. thank you.

<img width="372" alt="ha sch1" src="https://user-images.githubusercontent.com/19533894/96386168-8148d780-11cb-11eb-801c-a3b6da8b8b2c.png">
<img width="374" alt="ha sch2" src="https://user-images.githubusercontent.com/19533894/96386169-827a0480-11cb-11eb-8d5e-fa32326d5366.png">

**Comment by nielsfaber** [comment]
@hidzirAdam  I think your issue is with the scheduler-card (not the component).
Can you explain a bit more about your problem?
As far as I know, for `scene` entities, `turn on` is the only available action in HA.

**Comment by hidzirAdam** [comment]
I have a group of devices which I wanted to activate the switch with 'ON'
rather than needing to add each device  with its own timing schedule.
Can i use your  scheduler-card to achieve my intention.
I enclosed 2 images for your reference.

Thank You very much Sir.

Best Regards,

Hidzir Adam

**Comment by KTibow** [comment]
@hidzirAdam this isn't the fault of scheduler-card, it's the fault of Home Assistant. Try a Home Assistant group instead of a Home Assistant scene.

**Comment by hidzirAdam** [comment]
Hi ,
Actually i'm no longer using HA Scenes for Grouping, the latest image which
is enclosed is a group created inside configuration.yaml.
scheduler-card  recognises the group but it lists as individual entities
for the group.

**Comment by KTibow** [comment]
Scheduler groups != Home Assistant groups. Scheduler groups group related entities when you make a new schedule, but you control each one separately. Home Assistant groups let you control multiple entities at once.

**Comment by nielsfaber** [comment]
@hidzirAdam  Can you explain your issue a bit more?

> I have a group of devices which I wanted to activate the switch with 'ON'
rather than needing to add each device  with its own timing schedule.

What group of devices are you talking about?
Are they of the same type?

Did you consider using a [scene](https://www.home-assistant.io/integrations/scene/) or [light group](https://www.home-assistant.io/integrations/light.group/)?

Currently, the scheduler only supports controlling 1 HA entity at a time. But this can be a scene, group, automation, script... So it is possible to turn multiple lights (or other) on simultaneously.

**Comment by hidzirAdam** [comment]
Hi Sir,

i) What group of devices are you talking about?  I create the group in
configuration.yaml

group:
  baja:
    name: Baja
    entities:
      - switch.racundoser1_pump1
      - switch.racundoser1_pump2
      - switch.racundoser1_pump3
      - switch.racundoser1_pump4
      - switch.sonoff_10005108d3
      - switch.sonoff_1000cd7542
      - switch.sonoff_1000cd7550
      - switch.sonoff_1000cd90f7
      - switch.sonoff_1000cd92d7


 2) Are they of the same type? YES (SWITCHES)

 3) Did you consider using a scene
<https://www.home-assistant.io/integrations/scene/> or light group
<https://www.home-assistant.io/integrations/light.group/>?

    I already Group it in  Scene, your scheduler-card listed the Scene and
and i can insert the Scene to Switch it 'ON' in Action column, but can't
select it in  scheduler-card to Switch 'OFF' the scene.

4) In the latest grouping created in configuration.yaml ,  scheduler-card
listed the group as individual entities ID, so i need to add each of the
entities into the Scheduler. What expect is to add group name into

     scheduler-card as one Schedule timing rather than list of entities. Is
that possible ?


Thank You.

**Comment by nielsfaber** [comment]
Ok, I understand now 👍 
I will try to add support for [group ](https://www.home-assistant.io/integrations/group/) entities.
Currently it is not possible yet. 
This is because you can combine different types of entities in a group (such as climate, switch and cover).
It makes it difficult to determine which actions should be possible for the group.
For your use it is very clear, so i will see what i can do.

**Comment by hidzirAdam** [comment]
Thank you for your email,

I’m looking forward for any future updates.

**Comment by nielsfaber** [comment]
I added a basic support for group entities in v1.8.2.
Turn on and turn off actions will be available now.

In a future update i am planning to improve it more, by detecting which actions are supported by the entities in the group.
This is quite some work though, so will take a while.

**Comment by hidzirAdam** [comment]
Good to hear from you Mr Niels,

Awesome, thank you so much, i really appreciate it.

Best wishes,

Hidzir Adam

**Comment by nielsfaber** [comment]
I saw that this group entities give me the following error when the scheduler should trigger:
```
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 91, in async_call_from_config

    await hass.services.async_call(*parms, blocking, context)

  File "/usr/src/homeassistant/homeassistant/core.py", line 1296, in async_call

    raise ServiceNotFound(domain, service) from None

homeassistant.exceptions.ServiceNotFound: Unable to find service group/turn_on
```
This is because group.turn_on does not work. It should become homeassistant.turn_on instead.

As a result, the schedules will not trigger the action.

I will have to make some changes, sorry about it.

**Comment by hidzirAdam** [comment]
Hi Niels,

I take note about this matter. Thank You very much for the updates.

**Comment by nielsfaber** [comment]
In v1.8.4 I added full support for `group` entities.
The card will now check which entities are in the group, and will automatically show the actions that can be applied to all of them.
So it is allowed to combine multiple types (`switch` and `light` for example), the card will see that both have option to _turn on_ and _turn off_.

I did a quick test, for me the actions work now.

**Comment by hidzirAdam** [comment]
Hi Nielsfaber/Scheduler-Card,

Wow, Thank you so much, i will test it tonight.
Will updates you on any problem.

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.

**Comment by hidzirAdam** [comment]
Yup , I agreed , Thank You Very Much
