### ISSUE TITLE
Can't add or see more than switches.

### ISSUE THREAD

**Issue by alfonsolsl** [nielsfaber/scheduler-card#141]
hi Niels, i update today and notice i can't add more than switches (and only a few of them). I don't have any custom config, is the stock setting. I'm adding a screenshot to this.

![image](https://user-images.githubusercontent.com/6255385/96534811-198b9e80-1256-11eb-9804-b5cca1152c03.png)

**Comment by nielsfaber** [comment]
This should be fixed by updating to v1.8.1
