### ISSUE TITLE
Error after upgrading to 1.8.1

### ISSUE THREAD

**Issue by MaurizioScala** [nielsfaber/scheduler-card#144]
After upgrading to 1.8.1 I see all my scheduling like this:

![image](https://user-images.githubusercontent.com/26275485/96550625-618bdf00-12b1-11eb-96ca-29e201017d8f.png)

Yesterday with the 1.8.0 it was all fine... I also tried to go back to the 1.80 but the issue remains

**Comment by nielsfaber** [comment]
Can you share your card config?
The error suggests that this climate entity is not included in the card, while there are still schedules existing that use it.

**Comment by MaurizioScala** [comment]
This is my configuration and it's the same that i used yesterday with 1.8.0 (I didn't changed it):

title: Schedulatore
icon: mdi:calendar-clock
path: schedulatore
badges: []
cards:
  - type: custom:scheduler-card
    groups:
    - name: "Illuminazione"
      icon: lightbulb
      include:
      - light
      - switch.lampadario_ingresso
      - switch.lampadario_corridoio
      - switch.lampadario_soggiorno
      - switch.lampadario_bagno
      - switch.lampadario_cucina
      - switch.lampadario_studio  
      - switch.sonoff_1
      - switch.sonoff_3
      - switch.sonoff_th16_3
      - switch.houzetek_awp07l_2
      - switch.sonoff_th16_4
      - switch.sonoff_th16_6
      - switch.sonoff_4
      - switch.specchio_bagno
      - switch.houzetek_smartplug_1_1
      - switch.houzetek_smartplug_1_4
      - switch.houzetek_smartplug_1_2
      - switch.presa_sara    
    - name: "Riscaldamento"
      icon: radiator
      include:
      - climate   
      exclude:
      - "*daikin*"
      - "*esprit*"

**Comment by MaurizioScala** [comment]
The climate.ingresso_mts100v3 is working

![image](https://user-images.githubusercontent.com/26275485/96554372-c1d14f80-12b6-11eb-932d-347c3d69bfac.png)

**Comment by MaurizioScala** [comment]
I tried also to leave only climate but I have the same error

title: Schedulatore
icon: mdi:calendar-clock
path: schedulatore
badges: []
cards:
  - type: custom:scheduler-card
    groups:
    - name: "Riscaldamento"
      icon: radiator
      include:
      - climate

**Comment by nielsfaber** [comment]
Ok, thanks for sharing. It looks like your config is correct and the card has a bug.
I will try to fix it later today.

**Comment by MaurizioScala** [comment]
ok, thanks!

**Comment by nielsfaber** [comment]
I found a mistake, it should be corrected by updating again.

**Comment by MaurizioScala** [comment]
yes now it works, thanks!

![image](https://user-images.githubusercontent.com/26275485/96593743-23f77800-12ea-11eb-9342-4174ff096b1f.png)
