### ISSUE TITLE
Card issues after upgrading to the latest rev + suggestion to the card layout display

### ISSUE THREAD

**Issue by mottibz** [nielsfaber/scheduler-card#146]
Hi, the latest update broke the operation of my timers card. Please help resolve. Thanks!

1. When selecting “set mode”, I get this:
![image](https://user-images.githubusercontent.com/11439987/96580049-63b96200-12e0-11eb-95b0-6949e608322a.png)
ISSUE: No HVAC modes or other things are displayed…

2. When selecting “set temperature”, I get this:
![image](https://user-images.githubusercontent.com/11439987/96580089-76339b80-12e0-11eb-87fd-40b8655d21f9.png)
ISSUE: No way to select the temperature…

3. Another issue is that the operation text on the card, if it does not fit on one line with the entity name, it does not go to the next line but is truncated and has the “…” at its end. I suggest to update the view which will be similar to the Sensibo display.

a. Add config option to not display the entity name

b. Do something similar to the Sensibo display:
![image](https://user-images.githubusercontent.com/11439987/96580151-88add500-12e0-11eb-805c-2f4004eb0fcc.png)

It shows per scheduled operation:
- Time
- Turn AC On or Off (green=on, gray=off)
- Days of week (light red=will take place on this day, gray=will not take place on that day). Should also add a config option to define the first day of the week (Sunday or Monday)
- On/Off for this operation (slider on the right side)
- To see additional details (mode, temperature, etc.), you need to click on the scheduled item and a window will open with the details. I think that instead, you can show icons right to the “turn on/off icon”, symbolling the mode (cold/hot) and the temperature number

My script for reference:

`card:
  type: 'custom:scheduler-card'
  title: false
  discover_existing: false
  standard_configuration: false
  include:
    - '[[my_climate_entity]]'
  customize:
    '[[my_climate_entity]]':
      actions:
        - service: climate.set_preset_mode
          name: Turn AC Off
          icon: 'mdi:hvac-off'
          service_data:
            preset_mode: timeroff
        - service: climate.set_hvac_mode
          name: Set mode
          icon: 'mdi:cog-outline'
          variable:
            field: hvac_mode
            name: Operation mode
            options:
              - value: heat
                icon: fire
              - value: cool
                icon: snowflake
        - service: climate.set_temperature
          name: Set Temperature
          icon: 'mdi:coolant-temperature'
          variable:
            field: temperature
            name: Temperature
            min: 16
            max: 30
`
Thanks a lot, Motti

**Comment by mottibz** [comment]
Looks like the script code got messed up. Here it is again as a pic:
![image](https://user-images.githubusercontent.com/11439987/96580650-446f0480-12e1-11eb-90b3-daf4f38786f9.png)
Thanks!!!

**Comment by nielsfaber** [comment]
I don't like the proposal of changing the overview. 
A lot of people (including myself) will miss some essential information.

The other items are (hopefully) fixed in v1.8.2, sorry for the inconvenience.

**Comment by mottibz** [comment]
Hi, thanks for helping in resolving the issues!
Regarding the overview display, what I propose enables presenting all the information in less space and concise manner, without losing anything. What are the issues you see in that (what essential information is missed)?
Any way, will highly appreciate it if you add the following config options:
1. Remove the display of the entity in the overview display (select if to display or not)
2. Select the first day of the week (Sunday or Monday)
Thanks a lot!!!

**Comment by KTibow** [comment]
@mottibz as for request #1, you can use discover_existing.

**Comment by mottibz** [comment]
When I change discover_existing to true, how can I config the card not to display the entity name in the overview display? Also, when doing it, I get errors from schedule set for other climate entities:
![image](https://user-images.githubusercontent.com/11439987/96598505-9c186a80-12f7-11eb-9781-06ac18cfd1a8.png)

**Comment by KTibow** [comment]
Can you please clarify a bit?

**Comment by nielsfaber** [comment]
> When I change discover_existing to true, how can I config the card not to display the entity name in the overview display? 

You can't. The overview display is fixed. You can only choose which entity name to display. I guess if you leave it empty (or a space), you might get the result you want

> Also, when doing it, I get errors from schedule set for other climate entities:

This error suggests that this entity is not included in the card.
Its a protection, in case you create a schedule and next day decide to hide the entity used in this schedule.
Without the protection, the schedule would keep running on the background but you cannot control it anymore.

**Comment by mottibz** [comment]
Hi Kendell,

I will try to clarify:
As I wrote some time ago, I developed an AC Controller device based on the ESP32 (I am an embedded guy that develops these things for fun). I interfaced with HA and using multiple cards including the schedule card. I have a climate card per climate device and wanted to attached to each climate card the schedule card, thus I am using one schedule card per climate device. The combined card per climate device looks like this:
![image](https://user-images.githubusercontent.com/11439987/96613423-9e82c080-1307-11eb-8b50-6f8338af5244.png)
The schedule card is used as a pop up (invoked using the "Timers" button).

1. Looking at the timers pop up:
![image](https://user-images.githubusercontent.com/11439987/96613720-f5889580-1307-11eb-8e2e-47abd5dbc2be.png)
You can see that each set action includes first the entity name, ":", and a text describing the action. As this timer is attached to one defined climate entity, it will be good to have a config option not to display the entity name on each entry (as it is known what device the timer entries are for).

2. Looking at the settings windows:
![image](https://user-images.githubusercontent.com/11439987/96614055-616afe00-1308-11eb-9bc1-a2c33e2b4eee.png)
You can see that the "custom" settings dates start on "mon". Some countries workweek  start on "sun" (like where I live - Israel). This is why I asked for a config option to set the start day of the week.

I hope that I made it clearer :-)

Thanks a lot for all the you are doing to support our community!

Best regards, Motti

**Comment by nielsfaber** [comment]
Hi Motti.
These requests are new to me.
They have nothing to do with this bug issue you opened, do they?
If the issues of your first post are solved please close this topic.

For new requests you can always open new topics.
They seem like small requests so I could add them, but I like to keep things structured.
Thank you.

**Comment by mottibz** [comment]
Hi Niels, No problem. I will open a new topic for the two requests.
One item that is left which is how to set an action using "customize" that will allow me to select "cool" or "heat" (instead of "set mode" etc.) and after clicking "next" will allow me to set also the temperature? I have seen that working when I removed the "standard_configuration: false", but I have to use it in order to support my present timer off operation... Please see above my "customize" section and I will very highly appreciate your help in telling me how to modify it to support that. Thanks!

**Comment by nielsfaber** [comment]
I don't recommend disabling standard_configuration.
> but I have to use it in order to support my present timer off operation...

I don't see why this is the case.
You can keep using your 'set preset timer off' action, with standard_configuration enabled.
The cool / heat actions will be there for you out-of-the-box, and they should work with your thermostat.

**Comment by mottibz** [comment]
If I do not use it, I get the following possible actions displayed:
![image](https://user-images.githubusercontent.com/11439987/96629513-60dc6280-131c-11eb-9fc5-811a5102ecc3.png)
- COOL, HEAT are OK
- SET MODE should be removed (it gives DRY and FAN ONLY which I do not need)
- SET PRESET should be removed (as using "customize" I expose it as the "turn ac off" action)
- TURN OFF should be removed (as I already added the "turn ac off" present action)
I only want "cool", "heat", and  my preset "turn ac off" actions displayed (may decide to later add "dry" and "fan only" in the same way).
Is there a way to config what will be displayed as the available actions?

**Comment by nielsfaber** [comment]
Oh right, I forgot to tell you.
I added a new feature to help you:
```
customize:
  climate.motti_custom_thermostat:
    actions_exclude: 
      - set preset
      - set mode
      - turn off
```
Just write any name of action you want to hide.
Unfortunately I don't have anything to hide options from the preset list, so you will have to define your own version (as you do now).

**Comment by mottibz** [comment]
Hi, Thanks for adding this option, very highly appreciated!
I added it but when I am now getting the following error:
![image](https://user-images.githubusercontent.com/11439987/96681571-29070680-1380-11eb-9ffc-3a69636a808c.png)
Please help :-(

**Comment by nielsfaber** [comment]
Sorry, it should be `exclude_actions` instead of `actions_exclude`

**Comment by mottibz** [comment]
Yup, it's working :-)
Thanks a lot!!!
I filed a feature request for the 2 small items.
