### ISSUE TITLE
No elements for translation in language jsons

### ISSUE THREAD

**Issue by AlexKash500** [nielsfaber/scheduler-card#149]
No elements for translation in language jsons
![image](https://user-images.githubusercontent.com/69472472/96591699-35438300-12f0-11eb-8ffc-d63fb8b9881f.png)
![image](https://user-images.githubusercontent.com/69472472/96592014-98cdb080-12f0-11eb-9139-a38fc4a93ed5.png)
![image](https://user-images.githubusercontent.com/69472472/96592083-ac791700-12f0-11eb-8391-12f8819e02b2.png)
![image](https://user-images.githubusercontent.com/69472472/96601396-a425d980-12fa-11eb-82f5-7edb424cf17f.png)
![image](https://user-images.githubusercontent.com/69472472/96601498-bf90e480-12fa-11eb-973b-14a1704dce15.png)

**Comment by pepe59** [comment]
"day_type_workday": "pracovní dny",
"day_type_weekend": "víkend",

in translation is.
The others are not.

**Comment by nielsfaber** [comment]
@AlexKash500  @pepe59  I am planning to do a big update in translation.
It would (unfortunately) mean that the JSON file will be restructurized, I am hoping you can help me with the modifications for your languages.

**Comment by pepe59** [comment]
Yes for sure. It is also important for me to have a complete translation of the card

**Comment by pepe59** [comment]
Just a little question. When is a major translation update planned? I have a few minor fixes here and I'm wondering if I should wait because it's not very important now.

**Comment by KTibow** [comment]
@pepe59 It doesn't matter, do it anytime you want.

**Comment by nielsfaber** [comment]
> When is a major translation update planned? I have a few minor fixes here and I'm wondering if I should wait because it's not very important now.

There's not really a planning.
But I'm currently working on, will throw away half of the translations and rewrite the structure for what's left.
I found out there is a function to get translations that were made for the frontend.
So apart from service names and domain (group) names, there is little left.

Will take few days more!

**Comment by AlexKash500** [comment]
rus done

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.
