### ISSUE TITLE
Allow the editing of an action once it has been setup.

### ISSUE THREAD

**Issue by jameshiscott** [nielsfaber/scheduler-card#150]
Once i have setup an action with a time and all the options, i then what to change what the action is doing but i cant. I can change everything else (times, brightness, etc.) but not what the outcome of the action is.

It would be good to be able to edit this as well on the edit screen.

![image](https://user-images.githubusercontent.com/3490711/96614094-a5093c00-12f7-11eb-8866-5b954c58a88f.png)

**Comment by nielsfaber** [comment]
This should be doable 👍 
Actually I never had this option because there was no space for an extra 'back' button.

**Comment by nielsfaber** [comment]
This is added in v1.9.5.
Small guide for it:
![EditSchedule](https://user-images.githubusercontent.com/16861605/99062451-4f951780-25a3-11eb-873d-c59aec4d4e78.png)

**Comment by jameshiscott** [comment]
Works perfectly! thanks
