### ISSUE TITLE
Feature requests:  Config options to (1) remove entity name in overview, (2) set first day of the week

### ISSUE THREAD

**Issue by mottibz** [nielsfaber/scheduler-card#152]
1. The schedules overview display shows each action with its entity name + ":" + text describing the action. As I use the timer card for one defined climate entity, it will be good to have a config option not to display the entity name on each action (as it is known what entity the timer entries are for).

2. Looking at the settings windows, the "custom" dates setting starts on "mon". Some countries workweek start on "sun". Can you add a config option to set the start day of the week?

Thanks a lot!

**Comment by nielsfaber** [comment]
> Looking at the settings windows, the "custom" dates setting starts on "mon". Some countries workweek start on "sun". Can you add a config option to set the start day of the week?

Done!
Try updating the card to v1.8.3, and adding:
```
first_weekday: sun
```
Its not yet added to the UI editor, YAML only..

**Comment by mottibz** [comment]
Great, it is working!
Will highly appreciate also supporting #1 (config option to remove entity name in overview display).
Thanks a lot!

**Comment by nielsfaber** [comment]
I added your request in v1.8.4.
The idea is the following:

- In customize, give the entity an empty name (`name: ""`).
- The card will now detect this empty string and hide it (including the `: `) in the overview page.
- In the other pages, you will still see the entity name (friendly name of the entity as defined in HA)

I hope this is a good compromize for you.

**Comment by mottibz** [comment]
Works great, Thanks!!!!
Closing this :-)
