### ISSUE TITLE
Feature request: auto delete scheduled task after running

### ISSUE THREAD

**Issue by bertybassett** [nielsfaber/scheduler-card#161]
Feature request: auto delete scheduled task after running

something like this

![Screenshot 2020-10-21 at 18 16 25](https://user-images.githubusercontent.com/5606175/96754823-b91d6e00-13c9-11eb-991f-5e1d06e32fda.png)

**Comment by KTibow** [comment]
Maybe something like this:
![image](https://user-images.githubusercontent.com/10727862/96770052-d84dd880-1394-11eb-9b32-001beb686d1c.png)

**Comment by bertybassett** [comment]
Yes even better.

**Comment by nielsfaber** [comment]
![repeat_option](https://user-images.githubusercontent.com/16861605/97137002-fe88c500-1754-11eb-8d0f-efdabf8bb2b1.PNG)
How about something like this?
To keep it in the same style as the rest of the card.

**Comment by KTibow** [comment]
@nielsfaber That looks good!

**Comment by bertybassett** [comment]
P

> ![repeat_option](https://user-images.githubusercontent.com/16861605/97137002-fe88c500-1754-11eb-8d0f-efdabf8bb2b1.PNG)
> How about something like this?
> To keep it in the same style as the rest of the card.

Perfection!

**Comment by nielsfaber** [comment]
This is in place in v2.0.0 of the card.
