### ISSUE TITLE
Feature request: toggle_switch

### ISSUE THREAD

**Issue by bertybassett** [nielsfaber/scheduler-card#162]
In addition to the actions on turn_on and turn_off can we also have a toggle_switch

**Comment by KTibow** [comment]
This doesn't make sense. Please give a use case.

**Comment by nielsfaber** [comment]
You can call service switch.toggle for a schedule.
So with some automation you can get what you want.
But it will never become part of the card I'm afraid.

**Comment by KTibow** [comment]
Please close? Read the docs.
