### ISSUE TITLE
Missing schedule switches

### ISSUE THREAD

**Issue by daha76** [nielsfaber/scheduler-card#165]
Hi, 

I experiencing issue that I missing schedule switches and I haven't found information whether it is indented or not. Your screenshot has switches next to the every schedule, but suddenly after several last updates I missing them see screenshot:
![image](https://user-images.githubusercontent.com/16493975/96850615-4f4ba580-1457-11eb-94ca-98fdad5e560b.png)

**Comment by nielsfaber** [comment]
Looks like you need to update your card 😄

**Comment by daha76** [comment]
I have a latest version, at least HACS haven't found newer version as I currently have.

**Comment by nielsfaber** [comment]
I can see from your screenshot that you are at least 5 versions behind..
So you should refresh your browser or something.
And read the docs please: https://github.com/nielsfaber/scheduler-card#how-do-i-check-which-version-i-am-using

**Comment by daha76** [comment]
Sorry, I enabled developer console in Chrome and force reload with emptying caches and now it work .
