### ISSUE TITLE
Scheme editor does not show AM/PM times

### ISSUE THREAD

**Issue by electrickite** [nielsfaber/scheduler-card#168]
Version 1.8.4

It seems that the "Scheme" editor does not respect the AM/PM display option.

  1. Set the Time Display to AM/PM
  2. Create a new item
  3. Select Make Scheme
  4. Observe the times on both the timeline and the time slots are still displayed in 24hr time.

I would guess the issue is one or both of these lines:
  * https://github.com/nielsfaber/scheduler-card/blob/913f28a7286e31ebc92208b7467403077e22fcc6/src/custom-elements/timeslot-editor.ts#L94 
  * https://github.com/nielsfaber/scheduler-card/blob/3dbf891ab2e6db6682c3c3bd055308beb11971aa/src/scheduler-card.ts#L245

The `formatTime` calls do not use the `amPm:` option, which will cause `formatTime` to default to a 24hr display.

**Comment by KTibow** [comment]
Actually feature request.

**Comment by nielsfaber** [comment]
what comes after 12:00 PM then?
I really don't know..
not my thing.

**Comment by KTibow** [comment]
- 12:00AM
- 1:00AM
- 2:00AM
- 3:00AM
- 4:00AM
- 5:00AM
- 6:00AM
- 7:00AM
- 8:00AM
- 9:00AM
- 10:00AM
- 11:00AM
- 12:00PM
- 1:00PM
- 2:00PM
- 3:00PM
- 4:00PM
- 5:00PM
- 6:00PM
- 7:00PM
- 8:00PM
- 9:00PM
- 10:00PM
- 11:00PM

**Comment by nielsfaber** [comment]
you mean 12:30 instead of 0:30 ?
Funny, it was always in the card.
Also with the normal timepicker.

**Comment by KTibow** [comment]
How hard would it be to fix the time? Did you already start working on a commit?

**Comment by electrickite** [comment]
I never noticed that issue in the time picker. The expected AM/PM sequence would be:

11:30PM 
11:45PM
12:00AM
12:15AM
12:30AM
...
11:30AM 
11:45AM
12:00PM
12:15PM
12:30PM

**Comment by nielsfaber** [comment]
Its just hilarious to me.
The thing is that 24 hour clock, the clock doesn't go past 24, goes back to 0.
So i assumed for 12 hour clock the same happens.
Never even checked this or heard anyone complain 😄 
Do we keep it in?

**Comment by nielsfaber** [comment]
ok ok.... Sorry guys.
It is fixed in v1.9.1.

**Comment by electrickite** [comment]
Tested 1.9.1. Looks like it’s fixed!
