### ISSUE TITLE
Impossible turn off 'disable automatically after triggering'

### ISSUE THREAD

**Issue by robertopiumatti** [nielsfaber/scheduler-card#175]
If I turn off the option 'disable automatically after triggering' and after I save this is the result:
<img width="357" alt="Schermata 2020-10-29 alle 08 48 13" src="https://user-images.githubusercontent.com/3177263/97540415-e5398000-19c3-11eb-926e-4280a37efe08.png">

**Comment by nielsfaber** [comment]
will take a look, thanks!

**Comment by nielsfaber** [comment]
it's fixed in v1.9.0

**Comment by KTibow** [comment]
consider closing?

**Comment by robertopiumatti** [comment]
Yes, thank you!! 😊
