### ISSUE TITLE
Scheme has a 3 minimum slots

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#181]
Right now, you need at least 3 slots in the scheme editor:
![image](https://user-images.githubusercontent.com/10727862/97740342-5ea5a100-1a9e-11eb-81fe-c166cb661e15.png)
Once you have more than that, the delete button becomes reenabled:
![image](https://user-images.githubusercontent.com/10727862/97740424-8432aa80-1a9e-11eb-92de-f97a6eba642b.png)

**Comment by nielsfaber** [comment]
The behaviour as you described is how it was from day 1.
Only the alignment of the text looks weird.

**Comment by KTibow** [comment]
Why can't you have two slots? Scheduler component thing?

**Comment by nielsfaber** [comment]
No, it simply makes no sense.
Because you want 2 sliders to be able to choose a start and end time.
Thats what defines a timeslot.

The one on the left and right are a limitation of the GUI. 
But you can leave them unassigned if nothing needs to happen here.

**Comment by KTibow** [comment]
Testing the new CI. Fixed in
