### ISSUE TITLE
Feature request: Functional CI

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#182]
Using modern GitHub Actions, you can easily deploy a testing Home Assistant instance and bring up Chromium and take screenshots or use Selenium. It'd be good to have the ability to check that all of the functions work.

**Comment by nielsfaber** [comment]
I have no idea how to set this up.
But sounds great! 👍

**Comment by nielsfaber** [comment]
As said, I have no idea how to do this.
I will close the issue to clean up the list.
If you want to help, this is much appreciated.
