### ISSUE TITLE
Feature request: remove last condition

### ISSUE THREAD

**Issue by nelim** [nielsfaber/scheduler-card#186]
Feature request: removing last condition if added

I've added condition to card and want to remove it now without deleting schedule with tasks, is it possible ?
When i remove it and try to save, error popup:
Failed to call service scheduler/edit. length of value must be at least 1 for dictionary value @ data['entries'][0]['conditions']['list']

**Comment by KTibow** [comment]
Nope, this is a feature request. Could you reword it?

**Comment by nielsfaber** [comment]
This is a bug.
I will look into it.
Thanks for reporting

**Comment by nielsfaber** [comment]
I cannot reproduce this problem.
For me deleting conditions work fine, also if it is the last one in the list.
Are you using the latest version of the card?

**Comment by nelim** [comment]
Yes on 1.9.1 it does not work, today i upgraded to 1.9.2 and it is OK now :)
Thanks you can close that issue

**Comment by nielsfaber** [comment]
I didn't change anything but OK 😅
