### ISSUE TITLE
FritzDect301 and CometDect not set to destinated Temperature

### ISSUE THREAD

**Issue by HelmutEsterer** [nielsfaber/scheduler-card#188]
Hello,

at first I like to say my compliment to Niels Faber and assistant!
- You do a great work! - Many thanks.

Please excuse my terrible english!

Since version 117 of HomeAssistant, I afraid already since 116, I see a strange behavior on FritzDect301 and CometDect
thermostate.

They don't set the configured temperature in the scheduler-card, instead they are set to
the temperature that ist set for comfort-mode in the FritzBox.

To solve this, I removed the entry ".....hvac_mode:"heat"....." in the file scheduler-card.js on "....set_temperature...".

More detail of the origiinal: ...||(a.push({service:"climate.set_temperature",service_data:{hvac_mode:"heat"},variable.....
Modified: ...||(a.push({service:"climate.set_temperature",variable.....

- At the moment ist works.

With best regards

Helmut

**Comment by nielsfaber** [comment]
Hi,

The card implements actions according to the Home Assistant documentation.
The action for set_temperature is described [here](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature).

As you can see, this service accepts parameters `temperature` and `hvac_mode`.
* If your climate entity supports `hvac_mode: heat`, the scheduler card will give you an action `heat` where the `hvac_mode` is automatically set to `heat` and you can choose the temperature with a slider.
* If your climate entity does **not** support `hvac_mode: heat`, the scheduler card will give you an action `set temperature` with only temperature parameter.

Now you say that your thermostat does not respond OK to the scheduler-card action `heat`, correct?
Could you check in the properties of the entity (under Developer Tools -> Entities), which `hvac_modes` are supported?
You can also try in Developer Tools -> Services, to trigger the same service action (set temperature with temperature + hvac_mode parameters).
It could be that there is an issue with the integration of your device..

**Comment by HelmutEsterer** [comment]
Hello,
thank you for your respond.

>Now you say that your thermostat does not respond OK to the scheduler-card action heat, correct?
- correct

>You can also try in Developer Tools -> Services, to trigger the same service action
- I tested with developer Tools too:

  If I call the service "climate.set_temperature" with following parameters, the predefined temperature of the
  comfort-mode will be set:

  entity_id: climate.kuche_hk
  temperature: 25
  hvac_mode: heat

  If I call the service without "hvac_mode" the desired temperature ist set correct:

  entity_id: climate.kuche_hk
  temperature: 25

I think it ist possible, that the error stays on the side of HomeAssistant, or what do you think?

With best regards

Helmut

**Comment by nielsfaber** [comment]
> If I call the service "climate.set_temperature" with following parameters, the predefined temperature of the
comfort-mode will be set:

This is very bad. Thermostat may not switch to a predefined comfort mode when switching to `hvac_mode: heat`. Such behaviour would correspond to the service `set_preset_mode` (which you don't use).

So, there is something wrong with the integration. 
It's good to create an issue in the HA core for it.

Please [check here](https://github.com/nielsfaber/scheduler-card#my-climate-entity-does-not-work-when-i-create-a-schedule-to-change-the-temperature) for a workaround which may help you.

**Comment by HelmutEsterer** [comment]
Hello,

thank you for your tip.

I also think there is somthing wrong with the integration.

I could set the workaround, but it show no effect. The thermostat switched again to the temperature of the comfort-mode.
As primary workaround I reomve the part 'hvac_mode:"heat" ' manually from the "scheduler-card.js" at the moment and
hope for updates of the integration.

- Thank you very much.
- You made a very good and useable tool with scheduler-component and scheduler-card!

Wth best regards

Helmut

**Comment by HelmutEsterer** [comment]
Thank you for your help.

I am with you and think the error is in the integration.

With best regards

Helmut

**Comment by mithomas** [comment]
This is actually most likely due to home-assistant/core#60823 - a workaround to this on the scheduler-card side could be to also allow _set temperature_ instead of _heat_ even if the climate entity does support it. Nonetheless I also believe this should be addressed on the integration side.
