### ISSUE TITLE
Scheduler card disappeared with versions above 1.8.4

### ISSUE THREAD

**Issue by TRon993** [nielsfaber/scheduler-card#190]
Hi, after applying latest updates (1.9.0, 1.9.1) the scheduler card in Lovelace disappeared. Only a roll back to 1.8.4 brought them back. I'm running latest 0.117.1 HA version in docker on a raspi 4.

Only thing that I could find was when in editing mode. Normal view would hide those cards.

My setup is:

All schedules available/visible in first tab. Other, more specific tabs that have only their room-specific settings activated, were hidden.

If you need more information that I could possibly provide, please let me know. Supervisor is also latest available stable version 2020.10.0

Thanks and keep up the great work!

**Comment by pepe59** [comment]
The same problem. The tab appears when the page refreshes. If I go to another page, it will disappear.
I also noticed a slow loading of other pages or a jam when I pressed another button.
After the downgrade, everything returned to normal. Chrome browser. HA 0.117.1

**Comment by KTibow** [comment]
Same problem here. Note: Please hit the +1 button instead.

**Comment by ASNNetworks** [comment]
The strange part is: the card loads fine under Edge and Chrome (Chromium) but doesn't on iOS ( HA app and Safari). I'm running HA 116.4 btw. On iOS it shows very briefly before disappearing when reloading the page.

**Comment by pepe59** [comment]
Yes I use the chrome browser in win10

**Comment by nielsfaber** [comment]
I saw that the card sometimes keeps waiting for translation files to be loaded from the HA core forever.
In the meantime the card will not show anything (so it disappears for you).

There is a problem in the lazy-loading implementation of the HA frontend, I'm discussing a solution with the dev team.
I added a workaround that should take care of this.
Could you try updating to v1.9.2 and see if this fixes the problem for you?

**Comment by ASNNetworks** [comment]
I can confirm v1.9.2 fixes it 👍

**Comment by TRon993** [comment]
Me 2. Thanks a bunch for taking care! Appreciated 👍

**Comment by pepe59** [comment]
Add a scheduler card and the configuration is fine.
Creating a schedule is fine, but the remaining time until activation is not displayed.
The countdown begins until the plan is activated. The remaining time is displayed for the last 30 seconds. The countdown does not match. There is 1 minute left until the actual event. At the moment, everything is fine so far.
The schedule starts and at this point the browser freezes and activating another page does not respond for 20 seconds. After a short time, he does not react at all.
Refresh the page and it will work until you start another schedule process. The process is repeated.
Verified several times by setting the schedule to 10 minutes. Version 1.9.2
