### ISSUE TITLE
Add schedule delete confirmation

### ISSUE THREAD

**Issue by clau-bucur** [nielsfaber/scheduler-card#191]
Would it be possible to add a confirmation dialog when deleting a schedule?
I've, more than once, deleted by mistake schedules, when I actually wanted to delete a timeslot :(

**Comment by nielsfaber** [comment]
No, I will not add dialogs to the card.
Best I can do is move the button to another place.
For example:
![Capture](https://user-images.githubusercontent.com/16861605/97802796-3b1d5a80-1c46-11eb-82c0-f38e1d79d29c.PNG)

**Comment by KTibow** [comment]
Why not? Is that something that a small section of the UI like a card shouldn't be doing?

**Comment by nielsfaber** [comment]
I don't know what _should_ be done and what not.
I just don't like it.

**Comment by KTibow** [comment]
Makes sense. Maybe you can add an undo button, or only get the ability to delete a disabled schedule?

**Comment by clau-bucur** [comment]
I understand.

Please consider that the schedule delete action is, IMHO, the most critical and destructive action that can take place inside the card.
You can end up deleting a pretty complex schedule and it's nasty to recreate it.
Maybe some thing can be done so that the user can recover from an accidental click of the nasty Delete button.

HA itself has a built-in confirmation dialog for Restart, which also is a critical action.

I myself, for now, I'm writing down all my schedules so I can recreate them the next time I'll delete by mistake :))

**Comment by Misiu** [comment]
@nielsfaber please reconsider this.
I also think that delete is a crucial action and a confirmation should be added.
HA has such dialogs (as @clau-bucur mentioned) maybe this can be reused?

**Comment by nielsfaber** [comment]
Well it appears I'm outvoted this time.
And I prefer democratic decision-making 😉 

So here it is:
![Capture4](https://user-images.githubusercontent.com/16861605/97956666-90be4800-1da9-11eb-9637-e08b6d5e2068.PNG)
It is added in v1.9.3

**Comment by clau-bucur** [comment]
You're great! Thank you, and long live democracy :))

**Comment by clau-bucur** [comment]
I have to reopen it. The text is not readable when using dark themes:
![image](https://user-images.githubusercontent.com/47672949/97965067-73e23e80-1dc2-11eb-8577-21197d32b251.png)

**Comment by Misiu** [comment]
@nielsfaber thank you 🙂

**Comment by KTibow** [comment]
Nice! I'm a bit not sure about a card taking up the fullscreen, but it's good. Also, maybe you put the wrong name: It's `scheduler`, not `entity`.

**Comment by nielsfaber** [comment]
I just created a new release [v1.9.4](https://github.com/nielsfaber/scheduler-card/releases/latest) that improves the color for dark theme.
