### ISSUE TITLE
The card blocks the browser

### ISSUE THREAD

**Issue by pepe59** [nielsfaber/scheduler-card#195]
Add a scheduler card and the configuration is fine.
Creating a schedule is fine, but the remaining time until activation is not displayed.
The countdown begins until the plan is activated. The remaining time is displayed for the last 30 seconds. The countdown does not match. There is 1 minute left until the actual event. At the moment, everything is fine so far.
The schedule starts and at this point the browser freezes and activating another page does not respond for 20 seconds. After a short time, he does not react at all.
Refresh the page and it will work until you start another schedule process. The process is repeated.
Verified several times by setting the schedule to 10 minutes. Version 1.9.2

**Comment by nielsfaber** [comment]
if you really think the memory consumption is due to the updating of the remaining time, could you try hiding it (through display_options) and see if it solves the problem for you?

**Comment by pepe59** [comment]
Not by updating the time, but at the time of activating the plan.
This is the exact moment.

**Comment by ChrisPiel70** [comment]
With the update to 1.9.0 i had both this problem and the problem wih cards disapearing.  I thougth is was due to HA Update 117. Made a rollback to 1.8.4 and it all worked again.

The problem with dispearing Card has benn solved with 1.9.2 but they steill freeze the Browser.

**Comment by nielsfaber** [comment]
Please update to v1.9.3 and see if it fixes your problem.
I cannot really reproduce this issue, but I optimized some stuff in the updating of the relative-time.

**Comment by pepe59** [comment]
I confirm that version 1.9.3 has fixed the issue with blocking browser pages.
Thank you

**Comment by ChrisPiel70** [comment]
Version 1.9.3 seems to have fixed the "blockung browser" problem.

Thank you.

**Comment by KTibow** [comment]
Can we close then?

**Comment by ChrisPiel70** [comment]
Yes, as far as I am concerned.

**Comment by pepe59** [comment]
Yes, I think we can close.

**Comment by KTibow** [comment]
@pepe59 well then can you hit the close button?
