### ISSUE TITLE
Card does not seem to trigger my devices

### ISSUE THREAD

**Issue by cfgroenewald** [nielsfaber/scheduler-card#198]
Hi
I installed the card last night, however the card does not seem to trigger/controll the devices as it should. Not sure where to look for the problem.

**Comment by nielsfaber** [comment]
Couple of suggestions (in order):
- Check the HA logs for errors.
- Check the history of the schedule entities. The state should change from `waiting` to `triggered` when they fire.
- Check the history and logbook of your devices for events when they should be triggered
- Try with a simple input boolean. See that it can be turned on by a schedule.
- Share your schedule config + device properties with us
