### ISSUE TITLE
Allow any user (not administrator) to create/modify schedules for smart devices.

### ISSUE THREAD

**Issue by edpvic** [nielsfaber/scheduler-card#199]
Really good Lovelance card for HA!!!
Can other users than the administrator create or modify time schedules?
I will appreciate your comments.
Thks!!

**Comment by KTibow** [comment]
Might be a restriction in HA but might be possible.

**Comment by nielsfaber** [comment]
> Can other users than the administrator create or modify time schedules?

Create - No, Modify - Yes.
Creating a schedule requires adding a new entity in HA. This is restricted to admin-only (not by me, but by HA itself).

**Comment by edpvic** [comment]
hello,

I just found this addon https://github.com/arthurdent75/SimpleScheduler that can do it!!  So, maybe is possible!!

**Comment by nielsfaber** [comment]
OK please send me a PR for it

**Comment by gurkburk76** [comment]
I usually create schedules for the wife that she later can do as she wants with, but after updating the component a few times it seems like her user (not admin) can't modify a schedule that i've created.
I think it used to work sometime in october or something, one does not add new stuff all t hat often sp hard to keep track of what versions work.
How can i help troubleshooting this ?

**Comment by nielsfaber** [comment]
It’s due to this issue https://github.com/nielsfaber/scheduler-card/issues/282
Unfortunately I’m blocked by limitations in HA.
I’m trying to convince the dev team to open it up, but it might take some time.
