### ISSUE TITLE
Using Before/After uses 12 instead of 0

### ISSUE THREAD

**Issue by wvoigt** [nielsfaber/scheduler-card#200]
I'm using v1.9.3
When selecting a before or after time, the scroll goes from 2 down to 1 down to 12 (like a clock) instead of 0.  And the offset is then calculated 12 hours before / after. It is currently not possible to schedule something exactly at sunrise/sunset or anything within an hour of it.

**Comment by nielsfaber** [comment]
I have no idea what you are talking about.
What is a before time?
Please explain.

Triggering at sunrise not possible?
![Capture7](https://user-images.githubusercontent.com/16861605/98199602-c9862a80-1f2b-11eb-9787-b7afd7b7c5c6.PNG)

**Comment by wvoigt** [comment]
I cannot trigger at sunrise.  I can never get 00:00   I get 12:00.   If I start at 02:00 AFTER and click the hour down, I get 01:00 AFTER.  Click again, I get 12:00 AFTER.  Click again 01:00 BEFORE, Click again 02:00 BEFORE.
I have reinstalled the latest from HACS.

**Comment by KTibow** [comment]
I get this issue too:
https://www.loom.com/share/6ca3cc61dad944c799856a504075dbc4

**Comment by nielsfaber** [comment]
I just created a new release [v1.9.4](https://github.com/nielsfaber/scheduler-card/releases/latest) that fixes this bug.
It was related to the AM/PM time display calculation (which I changed recently). For offset the AM/PM display-rules do not apply ofcourse.
Sorry for the inconvenience

**Comment by nielsfaber** [comment]
Can this issue be closed?

**Comment by wvoigt** [comment]
Yes, it can be closed.  release v1.9.4 fixed it for me.
