### ISSUE TITLE
Feature Request: Season

### ISSUE THREAD

**Issue by Ak1rA78** [nielsfaber/scheduler-card#201]
I would really appreciate the possibility to schedule also by the season.
thanks!

**Comment by KTibow** [comment]
Sure, it makes it easier, but it's not too hard to hit the toggle switches.

**Comment by nielsfaber** [comment]
I'm afraid this is out-of-scope for now.
As @KTibow says, you can easily control the enabling/disabling of schedules.

You can also add a condition to evaluate when a schedule should be triggered, ofcourse you are free to create a condition that applies to a season.
