### ISSUE TITLE
Schedule switch incorrectly refreshed

### ISSUE THREAD

**Issue by woniol** [nielsfaber/scheduler-card#203]
Hi,
I've noticed, with two schedules example and an additional entites card, I see that schedule switches are not properly refreshed.
![Home Assistant shceduler switch](https://user-images.githubusercontent.com/73957881/98351599-33cac800-201d-11eb-91e3-12673485f0b7.png)

**Comment by nielsfaber** [comment]
How did you do this? For me it does not happen.
Can you share steps to reproduce this?

**Comment by woniol** [comment]
For the simplest example I use two disabled schedules:
1. Turn on
2. Turn off
![step1 Home Assistant](https://user-images.githubusercontent.com/73957881/98841032-d7660f00-2447-11eb-8d93-78fb004dd683.png)

then I try to activate the second one (2 Turn off). As the result the one I enabled goes to the top of the list and both switches are
shown as active.
![step2 Home Assistant](https://user-images.githubusercontent.com/73957881/98841050-ddf48680-2447-11eb-91df-e6dc43eb7419.png)

Below scheduler card I placed entitis card just to present the real state of the schedules

**Comment by woniol** [comment]
Seems like it is related to #204 Disabling one scheduler disable an other one

**Comment by nielsfaber** [comment]
I think it's related too.
Next update (which i will release in a couple of days), maybe solves this issue for you.
I hope you can test it.

**Comment by woniol** [comment]
Perfect, thanks.
I'll test it as soon as you release it.

**Comment by nielsfaber** [comment]
Please try updating to v.1.9.5. I hope it fixes this behaviour.

**Comment by woniol** [comment]
It works like a charm now.
Thank you very much for the fix.

**Comment by KTibow** [comment]
Consider closing @woniol?

**Comment by woniol** [comment]
Reported issue was fixed
