### ISSUE TITLE
Customise/Options/Condition

### ISSUE THREAD

**Issue by chinezbrun** [nielsfaber/scheduler-card#208]
I was not able to select an entity in order to set a condition. 

![Capture](https://user-images.githubusercontent.com/35501848/98860710-c4196a80-246c-11eb-8870-445e25c6480d.jpg)

I read documentation but i couldn't figure out what was missing.
Need help.

**Comment by nielsfaber** [comment]
Add some entities to `include` list (like `binary_sensor`)

**Comment by chinezbrun** [comment]
finally i understand - i have to select the entity from the "Included entities" present in card configuration... I supposed in the beginning that i have to configure something in HA configuration.yaml... 
sorry for my ignorance and congrats for your work. well done!
