### ISSUE TITLE
possibility to add "fake" scheduler

### ISSUE THREAD

**Issue by pszafer** [nielsfaber/scheduler-card#209]
Hello,

I'm author of custom Bosch component for HA - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
Bosch devices have it's own schedule which is invoked in thermostat itself.
Example here: https://github.com/pszafer/bosch_scans/blob/7d58fe3f20abff7a71465cc296555efc600c352e/rc300/1.json#L690-L822

Would be possible to edit this card and/or your scheduler component in which factor this scheduler would add posibility to at least display such program and not invoke time based action in HA itself?

**Comment by nielsfaber** [comment]
Its not desirable to have different schedulers living in the devices themselves.
Its also not desirable to create a card specific to a Bosch thermostat.
The goal of HA is to provide an integrated platform, such that all devices can be controlled in the same way.

I also have a thermostat that supports a weekly schedule, and some other devices that have integrated timers.
But I prefer to have HA controlling the schedules.

I recommend you to follow the same approach for your integration.
It will give more flexibility to the users.
If your component provides the `supported_features`, `hvac_modes` etc. , then it will be already compatible with scheduler.
Users can create multiple scheduler cards, so the Bosch thermostat could have its own card.

It is very desirable to have a thermostat automatically switching to HEAT mode when users increase the setpoint.
Please take a close look at your `async def async_set_temperature` implementation.
It currently does not support the `hvac_mode` to be set directly, so is not fully compatible with the [HA service](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature).
This is one of the major limitations that users of my card are facing.

If you see compatibility issues between the scheduler-card and your integration, I'd be happy to collaborate to improve it.
I think this is the best way forward..

**Comment by pszafer** [comment]
I know that it is already compatible with your components if user has manual mode enabled.

about `async def async_set_temperature`, it gets complicated... because it is bad idea to set mode in set_temperature...
in case of bosch it takes about 3 minutes to switch between modes and then you have to set different temperature in "different place"

I'm asking about it because there are many users who prefer (or tell it is better) to have schedule in bosch itself.
In manual mode it is trying to reach target temperature as fast as possible.

In auto/schedule mode in program called eco thermostat is going to reach target according to outdoor temperature changes and it will do it more efficiency (at least that is what they advertise), so I can understand why some prefer to have schedule in device and HA could be only frontend for this schedule.

**Comment by nielsfaber** [comment]
OK clear.
In that case there is not really common ground here..
I recommend you to expose the JSON schedule through websocket API and provide some basic add/edit/remove functions.
If that is in place, you could create a card for managing the schedule.
At that point maybe I could help you out by cherry-picking some parts of this card. You will only need some pieces of it..
Scheduler-component / scheduler-card will migrate to websocket API soon as well (when I find the time for it).

**Comment by nielsfaber** [comment]
I will close this issue, since the answer to your original request is a "no".
Please re-open or comment if you want further discussion.
