### ISSUE TITLE
Humidifier entities not showing in UI editor

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#210]
I was noticing that in the UI editor for the scheduler card none of the humidifier entities were showing up. Yes, I'm sure none of them were hidden. Sorry for the lack of context, I'm writing this on a mobile device.
![Screenshot_20201112-082214_Home Assistant](https://user-images.githubusercontent.com/10727862/98966617-5565fc80-24c0-11eb-9b3f-0e30d69ec51f.jpg)

**Comment by nielsfaber** [comment]
Strange.
There are predefined actions for it (`turn on`, `turn off`, `set humidity`, `set mode`).
Any entity that has predefined actions should show up in this list..

I don't have any `humidifier` entities myself, so I cannot test it.
I looked at the documentation for it, and I declare it the worst [documented](https://www.home-assistant.io/integrations/humidifier/) component.
No idea how to set it up in HA for a quick test..

**Comment by KTibow** [comment]
Just go to Home Assistant core, search for "hygrostat", and place the files in the PR into your custom components.

**Comment by nielsfaber** [comment]
This component is still a work-in-progress?
What is with `humidifier` vs `hygrostat`? They didn't settle on a domain name yet?
I will wait for this component to become integrated in HA, then I will take a look at it again..
Looks like it's still subject to change.
In the meantime users can just include it via `customize`.

**Comment by KTibow** [comment]
It's another name. It still makes `humidifier.blank` entities. You are right that at the moment no PRs are merged for humidifiers, and not too many people use this.

**Comment by nielsfaber** [comment]
Closing for now (to clean up the issues list).
Once the hygrostat / humidifier components make it to core we can discuss it again.

**Comment by KTibow** [comment]
Personally I don't use it, but it has made it to core in the form of Homekit Controller: https://www.home-assistant.io/integrations/#humidifier
