### ISSUE TITLE
Want to update the preview GIF?

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#214]
It looks like the gif with a preview was at least 5 versions behind in both HA and the card. It should probably be updated.

**Comment by Otamay** [comment]
The gif suggests that I can schedule automations, but I can't find the option anywhere in the program. I think if the gif is updated I would tell if something is wrong with my installation .

**Comment by nielsfaber** [comment]
I will take it into account for the layout-change I am working on 👍
