### ISSUE TITLE
issue with scheduling climate heat on

### ISSUE THREAD

**Issue by malliaso** [nielsfaber/scheduler-card#215]
Hi,

thank you for the great work. i noticed an issue. when i set up a schedule for a climate entity (heating thermostat), choose make scheme and set up the heat and turn off time ranges, it seems that although the turn off function works, the heat on function does not. i can see that the thermostats target temperature is changing correctly as per what i have setup in the scheme, but the climate entity remains in the off state, despite having chosen HEAT. Not sure what is the issue 

thanks again for the great work

**Comment by KTibow** [comment]
This may be a duplicate, read the docs and closed issues.

**Comment by nielsfaber** [comment]
This probably is a problem with your climate integration.
Not all integrations allow automatically changing the operation mode when changing the setpoint.
See also here: https://github.com/nielsfaber/scheduler-card/issues/207#issuecomment-725499290

**Comment by malliaso** [comment]
thank you for the quick reply, i will follow your suggestion. I could also add an automation as an overlay where it turns climate on at certain points. One more question. I want to create two cards one for weekend schedule and one for weekday schedules. The reason that i have them in separate tabs in lovelace as per other functions of switches during weekdays and weekends. However i noticed that i cannot separate the weekday and weekend schedules into two separate cards. Everytime i add the climate entities it automatically adds in the card both the weekday and weekend schedule of this entity. Is there a way around this so i can have two separate cards located in two different tabs one with weekend and one with the weekday scjedules?
thanks again

**Comment by KTibow** [comment]
Could you please use correct grammar and separate your topics into separate paragraphs?

**Comment by nielsfaber** [comment]
@malliaso It's not possible to split the card between weekend vs week schedules. You can only split by entity.

Also this is not really related to your issue, please stay on topic.
Use the HA forum for questions.

**Comment by nielsfaber** [comment]
I'm closing this issue, because your initial question is answered.
I will make an option soon that allows you to combine multiple actions (so change setpoint + change hvac mode), it will help.
