### ISSUE TITLE
Bug in list of presets in climate components

### ISSUE THREAD

**Issue by guigeek38** [nielsfaber/scheduler-card#216]
Hi, 
First of all, thank you for this great work!

I think there is an error in the automatic retrieval of the list of presets for the climate.

I have custom presets in HA for my climate component, and the scheduler card cannot retrieve them and shows me the default ones (none, eco, away, boost, comfort, home, sleep, activity). 
The functionality of retrieving custom presets seems to be provided by these lines:
https://github.com/nielsfaber/scheduler-card/blob/bad0af7b9ec5d6711fc7554da745f2b2d39c4616/src/standard-configuration/climate.ts#L95-L99

However, as we can see in the HA documentation, it's the `preset_modes` attribute which contains the list of preset modes and not the `preset_list` which does not exist.
https://developers.home-assistant.io/docs/core/entity/climate/#properties

As I am a newbie with HA, I prefer not to do the PR directly, but I have tried doing a fix locally, just replacing `preset_list` with `preset_modes` and it seems to work.

**Comment by nielsfaber** [comment]
Good point!
Looks like you did your homework 👍 
I will fix it and send out a new release soon..
Thanks for reporting.

**Comment by guigeek38** [comment]
It works perfectly with this new release. Thank you very much!

**Comment by nielsfaber** [comment]
Wow you're quick 😄 
I didn't even inform you about the update yet.
Enjoy the change, keep me noted on bugs or improvements 👍
