### ISSUE TITLE
scheduler card registration problem

### ISSUE THREAD

**Issue by pimpon59** [nielsfaber/scheduler-card#217]
Hello,
first of all thank you for this great job. I start with HA and I encounter a problem with the sheduler card when I test an action whether it is on the shutters, the heating or the alarm when I record it I have the following message:
"sheduler / add. service not found call failed"
Can someone explain to me the reason?
thanks in advance

**Comment by nielsfaber** [comment]
Not to be rude, but you're like the 100th user to ask this.
Please take the effort of reading the documentation (I wrote it for you guys 😉  ):
https://github.com/nielsfaber/scheduler-card#how-do-i-fix-error-failed-to-call-service-scheduleradd-service-not-found-
https://github.com/nielsfaber/scheduler-component#step-3-add-integration

**Comment by KTibow** [comment]
Consider closing?
