### ISSUE TITLE
With sunrise offset, the displayed times in the card are out of sync

### ISSUE THREAD

**Issue by nielsfaber** [nielsfaber/scheduler-card#22]
Card uses sun.sun state to calculate the times for which actions fire.
The component uses the sun.sun state, but does not update while the timer is set.
Needs to be in sync.

**Comment by KTibow** [comment]
Just curious, what does "but does not update while the timer is set" mean?

**Comment by nielsfaber** [comment]
@KTibow The component sets timers either at startup or when a timer has expired.
If timers are sunset/sunrise related then the last known state of sun.sun is used for setting the timer.
This could get a little off, especially when setting a timer that fires in a week from now.
The misleading thing is that the card performs its own calculation of trigger time, based on the sun.sun state as well. 
The result is that a timer could be triggering at 6:00 while the card shows 6:10 or so. 
Very ugly.

**Comment by KTibow** [comment]
@nielsfaber did you get around to this yet? How hard is it to implement?

**Comment by nielsfaber** [comment]
quite hard if you don't know anything about python 🙂 
but i am working on changing stuff there. Also to make things robust for the daylight saving time which will come in a month.

**Comment by nielsfaber** [comment]
fixed in new scheduler_component update.
component will listen for state changes in sun.sun, and reschedule items that are outdated
