### ISSUE TITLE
Missing field in localization files?

### ISSUE THREAD

**Issue by acseven** [nielsfaber/scheduler-card#224]
Hi,
I believe there's a relative time string missing in the translation fields. Considering the screenshot below as reference and the localisation files' strings:

- "At" (yellow arrou) is at: services > ui > components > time > absolute
- "In" (light blue arrow) isn't available

![image](https://user-images.githubusercontent.com/1176371/99393508-54c0d200-28d5-11eb-9002-e3ca17654df6.png)

Or am I missing something?

**Comment by nielsfaber** [comment]
It's stolen from HA frontend.
https://github.com/home-assistant/frontend/blob/473e381d756ce11b1842901dc04d72bf55719e98/translations/frontend/en.json#L685

A lot more stuff is re-used from there actually... The word 'minutes' is also not in the localize file..

**Comment by acseven** [comment]
Ah, so maybe these here? 

```
"relative_time": {
                "duration": {
                    "day": "{count} {count, plural,\n  one {day}\n  other {days}\n}",
                    "hour": "{count} {count, plural,\n  one {hour}\n  other {hours}\n}",
                    "minute": "{count} {count, plural,\n  one {minute}\n  other {minutes}\n}",
                    "second": "{count} {count, plural,\n  one {second}\n  other {seconds}\n}",
                    "week": "{count} {count, plural,\n  one {week}\n  other {weeks}\n}"
                },
                "future": "In {time}",
                "future_duration": {
                    "day": "In {count} {count, plural,\n  one {day}\n  other {days}\n}",
                    "hour": "In {count} {count, plural,\n  one {hour}\n  other {hours}\n}",
                    "minute": "In {count} {count, plural,\n  one {minute}\n  other {minutes}\n}",
                    "second": "In {count} {count, plural,\n  one {second}\n  other {seconds}\n}",
                    "week": "In {count} {count, plural,\n  one {week}\n  other {weeks}\n}"
                },
                "just_now": "Just now",
                "never": "Never",
                "past": "{time} ago",
                "past_duration": {
                    "day": "{count} {count, plural,\n  one {day}\n  other {days}\n} ago",
                    "hour": "{count} {count, plural,\n  one {hour}\n  other {hours}\n} ago",
                    "minute": "{count} {count, plural,\n  one {minute}\n  other {minutes}\n} ago",
                    "second": "{count} {count, plural,\n  one {second}\n  other {seconds}\n} ago",
                    "week": "{count} {count, plural,\n  one {week}\n  other {weeks}\n} ago"
                }
            },
```

In particular: `"future": "In {time}",`


> A lot more stuff is re-used from there actually... The word 'minutes' is also not in the localize file..

Ah, that's weird, because `minutes` actually does get translated, but not the prefix `In {time}`

**Comment by nielsfaber** [comment]
As you can see the bug is on their side: https://github.com/home-assistant/frontend/blob/dev/translations/frontend/pt.json#L685

Feel free to open an issue in the HA frontend repo.

I already told them weeks ago that they broke their translations (in many languages), but no one is patching it.

**Comment by acseven** [comment]
Thanks for the pointer. I'll wait for you to push a new release just to check something before pursuing this with the frontend side (easier to wait than to explain the entire issue).

**Comment by nielsfaber** [comment]
Your translation updates are released in v1.9.7.

**Comment by acseven** [comment]
Ok, thanks for updating this. After a bunch of back and forth, I think the translation system is working as intended, but now I can't replicate the issue I pinpoint in the OP. Could it be you changed something in v1.9.7?  The main difference is that I no longer see absolute times, whereas before I could only see relative time references when under 60 minutes, I think. 

My current homeassistant instance has this in place for the translated string:

`"ui.components.relative_time.future":"À {time}"`

And that's what is appearing in your component:

![image](https://user-images.githubusercontent.com/1176371/99576735-460c1500-29d2-11eb-88d6-53e27fb9d13b.png)

And in a test component I created for the next sunrise time in relative time format:

![image](https://user-images.githubusercontent.com/1176371/99576813-5b813f00-29d2-11eb-8768-1482b7651ac6.png)

In the case of my language, it's unfortunate that someone translate this incorrectly adding further confusion. I.e. "`À`" is wrong, and it was further modified in Lokalize (to a past reference string "`Há`") and I can't seem to be able to fix it (other users already voted up the wrong translation by mistake):
https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?k=10210591
I.e. it probably could be sorted for your component with a "future" field, but not for the entire HA frontend, I think.

**Comment by nielsfaber** [comment]
Feel free to check my code [here](https://github.com/nielsfaber/scheduler-card/blob/master/src/custom-elements/my-relative-time.ts#L82).
Last update was 13 days ago so from my side there shouldn't be any new surprises..

I made my own implementation of the relative-time function, because I see the one of HA too inaccurate. 
I wanted to show 'in 1 hour and 30 minutes' instead of 'in 2 hours' (which HA would show). 
Same for minutes: when less then two minutes, I show minutes + seconds.
When the time is more than 6 hours in the future, i don't show relative time any more, I show 'At <time>'.

Balloob wanted me to commit my version as the new detault relative-time module actually 😄 
But i asked him to clean up the translation mess first..

In the code there are some hacks added, because some translations miss the `ui.components.relative_time.future` string (even the [english ](https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/translations/en.json#L393)one), others miss the `ui.components.relative_time.future_duration.minute` string.
Its a real mess on the side of HA, which i reported already about a month ago.

Anyway, I cannot really help solving this as far as I know..

**Comment by acseven** [comment]
Ah, cool. So that's why there's such a difference to the custom template I created for testing. You're right, it's much better. 

In any case, I think this is all displaying correctly now. If I happen to come across the same issue again, I'll let you know. 

One thing though, there's something that isn't correct with your implementation. Although in English the `at` string be used in both cases:

![image](https://user-images.githubusercontent.com/1176371/99583351-41982a00-29db-11eb-8820-3186185ee58b.png)

In my language's (and probably some others) case it is not the same. We would use `às` for absolute time, `à` for midnight (female noun) and `ao` for noon (male noun). Have no idea on how that's sorted in localisation, though.

**Comment by nielsfaber** [comment]
Since `midnight` and `noon` are in the localize file of scheduler, I could update them to `at_noon` and `at_midnight`

**Comment by acseven** [comment]
That sounds good!

**Comment by nielsfaber** [comment]
> Since midnight and noon are in the localize file of scheduler, I could update them to at_noon and at_midnight

In v2.0.0. this is in place.
For portuguese translation, the following is used:
```
        "absolute": "Às {time}",
        "interval": "das {startTime} às {endTime}",
        "at_midnight": "ao meia-noite",
        "at_noon": "ao meio-dia",
        "at_sun_event": "ao {sunEvent}"
```
If this needs to be improved, you can create a PR with the changes.
I will close this issue now.
