### ISSUE TITLE
Problem with scheduler service

### ISSUE THREAD

**Issue by aal7** [nielsfaber/scheduler-card#226]
Hello. I can see in the FAQ that you've people not to raise an issue for 'Failed to call service scheduler/add. Service not found.', but you don't offer any solutions and I'm stuck. I wonder if I could ask for some help? I've installed the scheduler-component Integration and the schedule-card Card both according the instructions provided but I get the dreaded error message when I try to add any type of schedule. Is there anything you can suggest in the way of fault-finding, please? Thank you for any help you can offer.

**Comment by nielsfaber** [comment]
You are opening an issue in the wrong repo.
It kind of emphasizes that you didn’t read the FAQ..

**Comment by aal7** [comment]
I did read the FAQ, I just didn't understand that by "Please do NOT file an issue in this repo" you actually meant "please file issues in the scheduler-component" repo. For someone new to all this, that was too subtle. I'm sorry to have wasted your time.
