### ISSUE TITLE
New entities do not appear to choose

### ISSUE THREAD

**Issue by JaVier-Lloret** [nielsfaber/scheduler-card#227]
I transfer here my question from scheduler-component. 

when i installed the integration i had two C.A. machines both in the climate.yaml file, and four lights and two ligths groups in light.yaml file. All was OK and I could make my firts schedule programation.

Now I have a new  machine (boiler) like a generic thermostat and a new group of lights ( all in their respective .yaml files ) and none appear. 

I read in the documentation :"The card scans the entities in your HA configuration and suitable candidates should automatically show up in this view" but this don´t funcion for me.

II don't understand  how use the include or exclude list. where is it.

i copy my climate file for your comentary:
**********************************************************************
#######################################
# Configuracion BroadLink por smartir #
#######################################

  - platform: smartir
    name: Aire Acondicionado Salón
    device_code: 1101
    unique_id: salon_ac
    controller_data: remote.broadlink_salon_remote
    temperature_sensor: sensor.broadlink_salon_temperature
    humidity_sensor: sensor.broadlink_salon_humidity
#    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Aire Acondicionado Dormitorio
    device_code: 1101
    unique_id: dormitorio_ac
    controller_data: remote.broadlink_salon_remote
    temperature_sensor: sensor.broadlink_dormitorio_temperature
    humidity_sensor: sensor.broadlink_dormitorio_humidity
#    power_sensor: binary_sensor.ac_power_2

#######################################
#  TERMOSTATO GENERICO CALDERA
#######################################

  - platform: generic_thermostat
    name: Calefacción
    heater: switch.control_caldera
    target_sensor: sensor.average_temperature
    min_temp: 15
    max_temp: 24
    ac_mode: false
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 15
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

****************************************************

could somebody help me.

Thanks for read my problem

![Captura](https://user-images.githubusercontent.com/67537170/99581462-203a3c80-29e1-11eb-99ed-856b28b599b2.JPG)

**Comment by nielsfaber** [comment]
Do you use YAML for configuring your card settings?
Or do you use UI editor?

**Comment by JaVier-Lloret** [comment]
thanks for your quick answer

I am use UI editor.

**Comment by nielsfaber** [comment]
Then go to edit mode, and go to the settings for scheduler-card.
Here you can pick which entities show up. Your climate entity will be in this list.

**Comment by JaVier-Lloret** [comment]
I read your mind while you was write and i went to the card edition and find it before .

Thank for all. 

what a good development of this integration.

You are then best one. 
![Captura2](https://user-images.githubusercontent.com/67537170/99584039-bae84a80-29e4-11eb-972e-449f1dd36193.JPG)
