### ISSUE TITLE
Better time selection

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#23]
First of all, it'd be nice if you could choose sunrise or sunset, without having to manually find sunrise/sunset and checking "automatically adjust time to sunrise/sunset".
Next, it'd be nice if you could configure to 5 minutes, instead of just 10 minute accuracy. Also the ability to click on the time to adjust it to be more accurate.

**Comment by nielsfaber** [comment]
Working on it!

**Comment by anarro** [comment]
I think it would be very good if it could be adjusted minute by minute.

Antoni

**Comment by nagyrobi** [comment]
+1 for minute by minute

**Comment by KTibow** [comment]
@nagyrobi reactions button?

**Comment by nagyrobi** [comment]
I don't think anybody looks at those LOL :-)

**Comment by nielsfaber** [comment]
This is fixed with the v1.3.0 release

**Comment by anarro** [comment]
> I don't think anybody looks at those LOL :-)

I'm sorry I look at.
