### ISSUE TITLE
Question / Feature Request - have the possibility to show friendly name instead of the action in the scheduler card

### ISSUE THREAD

**Issue by thesorin** [nielsfaber/scheduler-card#230]
Is there a way to name the schedules to show that name instead of what action it performs?
I assumed the name would help out here, but I guess that is visible only in the Overview of Entities.
I was also looking into a method to change the icon, but it seems it takes the default one from the entity that is affected by the schedule.
![scheduler_ft_req](https://user-images.githubusercontent.com/12372349/99790244-7e276b00-2b2c-11eb-8f06-9631410529b6.gif)

**Comment by nielsfaber** [comment]
Did you read [this](https://github.com/nielsfaber/scheduler-card#display-options)?
It allows you to configure how items are displayed, through YAML.
The setting applies to the whole list btw (not per item).

**Comment by nielsfaber** [comment]
And when will you decide to help me with improvements 😉 ?
![image](https://user-images.githubusercontent.com/16861605/99794369-56cf9e80-2b2a-11eb-8e0f-0e3dd431db01.png)

**Comment by thesorin** [comment]
Ah, to be honest, I did not saw the section regarding ```Note: This is a YAML-only feature currently, Not available in the UI editor.``` I was looking at [friendly-name](https://github.com/nielsfaber/scheduler-card#friendly-name) and did not saw anything there. :D

I guess the RTFM still stands.

Hey, I might help you out, give me some time to make room in my schedule. ( ha... see what I did there... )
