### ISSUE TITLE
BUG? Precision in standard configuration's actions for climate component is constant, not as configured in the climate component

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#235]
At lines [climate.ts#L150](https://github.com/nielsfaber/scheduler-card/blob/master/src/standard-configuration/climate.ts#L150) [climate.ts#L168](https://github.com/nielsfaber/scheduler-card/blob/master/src/standard-configuration/climate.ts#L168) [climate.ts#L187](https://github.com/nielsfaber/scheduler-card/blob/master/src/standard-configuration/climate.ts#L187) standard configuration uses constant 1°F/0.5°C values, but it is a configurable property in the climate component.

It is also a bug in the core's thermostat card, see https://github.com/home-assistant/core/pull/41972.

I'm not familiar with HA's internals, I don't know whether this property is available for the frontend currently (and only the generic thermostat integration doesn't provide it), or it will be available in the frontend after the above mentioned PR.

**Comment by nielsfaber** [comment]
Good point.
I see that `climate` entities should have a `target_temp_step` attribute, so I can read which stepsize to use.
I will make it happen 👍

**Comment by nielsfaber** [comment]
This should be fixed by updating to v2.0.0 of the card.
Let me know if you still have issues.

**Comment by lmagyar** [comment]
FYI: Finally with new HA core update 2021.2.0 it is tested: works as required.
