### ISSUE TITLE
[Enhancement?] Make the exclude_actions: customization UI language independent

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#236]
Currently the `exclude_actions:` customization is UI language dependent.

See [compute_entity_actions.ts#L37](https://github.com/nielsfaber/scheduler-card/blob/master/src/data/compute_entity_actions.ts#L37).

Is it possible to extend it to filter not only on action name, ie. `e.name` but additionally `e.service`? This way the card configuration could be language independent but also backward compatible.

I see, that `service` is not always unique, but concatenated `service` and `service_data` values seems to be unique, eg. even this could work:
```
exclude_actions:
  - climate.set_temperature[hvac_mode=heat]
```
Disclaimer: I'm very new to HA, it's internal structure, Python, TS, JS and everything, so I dare not to create a PR.

**Comment by nielsfaber** [comment]
Yeah, I’m not happy with this either.
It’s an attempt to keep things user friendly, but it has big drawbacks (as you see).
I will think about what’s best here, I’m not sure whether your proposal is really the solution or yet another workaround..

**Comment by lmagyar** [comment]
It is still a valid, though low priority enhancement option.
