### ISSUE TITLE
Show something better if scheduler-component isn't installed

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#239]
Right now, it just says `scheduler.add` is not found. It'd be better if it made sure that it was there when it initialized, and if it wasn't, it showed a custom error message.

**Comment by nielsfaber** [comment]
Agreed, work in progress!

**Comment by nielsfaber** [comment]
From v2.0.0 of the card, you will see this:
![image](https://user-images.githubusercontent.com/16861605/102868717-d22eb380-443a-11eb-94d2-e5ef6723dbf8.png)

As you can see, also the 'Add' button is disabled. So I think it's pretty clear now.
