### ISSUE TITLE
Feature Request: Fine tuneing Time Slot Editor slots

### ISSUE THREAD

**Issue by febalci** [nielsfaber/scheduler-card#241]
As indicated in [this post](https://community.home-assistant.io/t/scheduler-card-custom-component/217458/998?u=febalci) , if i set Time Step Resolution less than 5 minutes; then Time Slot editor is not usable. If i set it for 1min, it still moves with 3 to 5 minutes randomly. What i realized is 5min is the absolute best minimum for time slot editor. The thing is i try to set let’s say for 8 minutes or 13 minutes etc, it simply is not possible even if i use a large monitor.

I know that probably need a change in the design and i do not have the right to want this from you; i only wanted to ask if the card stores these values in any file; so that i can change the time slot values manually there?

@neliss suggests:

> In my opinion the solution is to add more functionality to the editor.
> Ideally I would like to combine the standard time picker with the timeslot editor, to give you the option to fine-tune the timings.
> Another option would be to add some ‘zoom’ function, to be able to see only a portion of the 24 hours scale.
> 

I personally think 'zoom' will require more work and complexity. Combining the standart time picker with the timeslot would be the most elegant solution.

Pressing 'Details' button/link in Time Slot Editor page or just pressing the start or end line of the slot might bring a standart time picker screen. This way, instead of sliding the line with the mouse, a more precise time could be entered including very narrow slots. At least that's my opinion.

**Comment by KTibow** [comment]
Mind using GitHub rich formatting, such as `**text**` to make stuff **bold**,
```
> quoted text

then non-quoted text with a line before
```
> to show quoted stuff

and using
```
### for headers
```
### to indicate major points?

**Comment by nielsfaber** [comment]
Making some great progress on this!
Stay tuned for more.

I'd like to hear why people need time slots of <15 mins duration though. What kind of use-cases are we talking about?

**Comment by febalci** [comment]
I am using it for garden water sprinklers. I have a 4 channel relay ESPHome, which is connected to 4 different areas in the garden for watering. According to the weather conditions and seasons, the slots change from 1 minute to 15 minutes.

**Comment by febalci** [comment]
Any news on this?

**Comment by nielsfaber** [comment]
Yes. Definitely coming, but not ready for releasing.
Unfortunately there are many things running in parallel, I have to prioritise some behind-the-scenes updates before I can work on the GUI improvements.

This is my current concept for the editor:
![image](https://user-images.githubusercontent.com/16861605/114447953-43a19600-9bd3-11eb-8617-7bdfb0d54341.png)

If you click a narrow slot (in this case slot 2) it slides open and expands:
![image](https://user-images.githubusercontent.com/16861605/114448210-8bc0b880-9bd3-11eb-9d12-0bfc889613b5.png)

There is also an open request for involving sunset/sunrise in time slots. 
It's giving me some headaches to combine this visually in a nice way, but I'd like to add this.

**Comment by JasonBSteele** [comment]
Hi, any up date on this issue? I have run into this also with an irrigation schedule:

![image](https://github.com/nielsfaber/scheduler-card/assets/1202763/d6d910f7-02f1-44b2-984c-11320efa502a)

It is very difficult to edit the slots or to see what they are because they are so small. Ideally we would be able to zoom in :)

**Comment by KTibow** [comment]
If that's toggling between off and on, you might want to try an automation

**Comment by JasonBSteele** [comment]
> If that's toggling between off and on, you might want to try an automation

Yeah, thanks, just came to that conclusion too. Especially since I actually want to control how long the ON periods are for with logic based on moisture sensors, and to therefore move the other events up if the period is shorter. So yes, an automation with delays set according to logic seems a better solution in this case. Thanks!

**Comment by ankostis** [comment]
Why not allow to control the the slots with keyboard?

Eg. select a slot with mouse and then:

- `tab`/`shift`+`tab` to cycle thhrough the slots,
- `left`/`right` to control the _start-time_,
- `shift`+`left`/`shift`+`right` to control the _end-time_(duration).
