### ISSUE TITLE
Clarification in Heading

### ISSUE THREAD

**Issue by brandondb1** [nielsfaber/scheduler-card#242]
Wow, this is a fantastic component/card!  Should be part of Core, imo.

Anyway, on the card, the first level of descriptor is 'Group'.  I know the distinction is made in the documentation that this isn't the same as HASS groups, but HASS groups show up under groups if you include them, which is potentially confusing.  Maybe 'Device Type' might be a better descriptor for the card.

![Capture](https://user-images.githubusercontent.com/54447239/100785793-2b2c9e00-33df-11eb-8b61-d5b4c38f8fc8.PNG)
?  Just an idea.

Thanks again for your work on this!

**Comment by KTibow** [comment]
You can create custom groups, they’re just grouped by device type by default.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brandondb1** [comment]
Hi @KTibow, I realize you can create groups within scheduler.  I have a groups.yaml file that I use to group lights and sensors for use throughout homeassistant, and the groups from this show up as Groups, under Groups on the scheduler card (see the two circles on the screen cap).  My comment was just that this might be confusing for some, and perhaps renaming the Groups section on the Scheduler card to something like 'Device Types' would solve that.

**Comment by KTibow** [comment]
How about keeping the heading the same and changing the name to device groups?

**Comment by brandondb1** [comment]
I didn't make the name 'Groups', it is inherited from HASS (I just did include *) and not editable as far as I know.  That's my concern...
