### ISSUE TITLE
Enable Transition when activating a scene

### ISSUE THREAD

**Issue by derekoharrow** [nielsfaber/scheduler-card#243]
Firstly - loving Scheduler Card! It's really useful and helps simplify a lot of things.

When you create a schedule entry with a light you can specify the brightness.

It would be great if you could do similar with a scene to specify the Transition period, using probably very similar logic to the brightness code.

For example, I have scenes that I regularly run at 23:30 to turn off lights, but I transition this scene over 5 minutes or so.

Thanks

**Comment by KTibow** [comment]
You can do this with custom actions, ask on the HA forums for help.

**Comment by derekoharrow** [comment]
Got it - thank you!
