### ISSUE TITLE
Scheduler card crashes when there is a non-existing group inside a group

### ISSUE THREAD

**Issue by massive** [nielsfaber/scheduler-card#246]
Version 1.9.7

In relation to Issue #158 I believe I've found a new bug, which renders scheduler card inoperable.

Given the following config:

```yaml
group:
  subgroup:
    name: Sub-group
    entities:
      - group.a_group_that_doesnt_exist
```

The card emits a following error:

```
Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined
    at Ii (scheduler-card.js:formatted:4549)
    at scheduler-card.js:formatted:4543
    at Array.map (<anonymous>)
    at Ii (scheduler-card.js:formatted:4543)
    at Ri (scheduler-card.js:formatted:4805)
    at Bi (scheduler-card.js:formatted:4877)
    at scheduler-card.js:formatted:7937
    at Array.filter (<anonymous>)
    at HTMLElement.getDomainSwitches (scheduler-card.js:formatted:7937)
    at HTMLElement.render (scheduler-card.js:formatted:7857)
```

As hinted in the comments in #158 the pretty printed indicates that the issues happens in the "group" handler.

By commenting my groups I was able to eliminate the issues to the similar configuration as above. This leads to a hypothesis that card's group handler does not play well with nested groups if a nested group has an invalid, non-existing, entity.

**Comment by nielsfaber** [comment]
Can you share the attributes of these group entities?
The card tries to read which entities are contained in the group, but if these cannot be read I can imagine it could crash.

**Comment by massive** [comment]
Hi,

My bad. It was (as usual) a user error. There was no such thing as `group.downstairs_decorative_lights`. I had renamed it to something else. After renaming it to the correct entity, the card started to work.

So, the unhandled exception seems to happen when there is a group that includes another group, that doesn't exist.

**Comment by KTibow** [comment]
Could you edit the issue title and content then?

**Comment by massive** [comment]
Done

**Comment by massive** [comment]
There is still something funky with nested groups. I have three groups selected in scheduler card, one of them being a group of groups, the two others regular groups of switches and lights. Now, only the regular groups are visible in entity selector.

**Comment by nielsfaber** [comment]
Group inside group is not supported and will not be supported in the future either.

**Comment by massive** [comment]
Fair enough. If anyone bumps to same issue, there is a easy workaround here which basically does the same thing but without nested groups https://community.home-assistant.io/t/create-combinatoric-groups-including-and-excluding-entities-from-other-groups/121259
