### ISSUE TITLE
schedules is not switching

### ISSUE THREAD

**Issue by marcin77** [nielsfaber/scheduler-card#247]
I have two schedules for one thermostat, for working days and for the weekend, in case one period ends (e.g. for working days), the schedule does not switch to the next one, turning it off and on does not help (temperature does not change) , I have to edit and click save, and it starts the schedule.
btw, also missing setting the temperature by one degree (0,1).

**Comment by KTibow** [comment]
Could you show a screenshot? What does the `scheduler.test` service do?

**Comment by nielsfaber** [comment]
Closing due to lack of response.
