### ISSUE TITLE
Scheduled operations do not start

### ISSUE THREAD

**Issue by mauxi73** [nielsfaber/scheduler-card#249]
The installation is ok (no configuration errors) the devices are visible and selectable, the countdown is correct but nothing happens! what could be the problem?
(Homeassistant is currently installed on Imac)
Thanks
![HA](https://user-images.githubusercontent.com/66701635/101995824-27492780-3ccd-11eb-8f84-d038d7b49470.png)

**Comment by KTibow** [comment]
Are you sure the entity is correct? What happens if you use `scheduler.test`?

**Comment by mauxi73** [comment]
The entities I have selected from the list and they seem correct ... forgive my ignorance but how should I do for use scheduler.test?

**Comment by KTibow** [comment]
It's a service, call it with HA devtools.

**Comment by mauxi73** [comment]
calling the service from scheduler.test it works

**Comment by nielsfaber** [comment]
I recommend to check in the history/logbook whether the schedule was triggered and if this was at the correct time.
Maybe you didn't set up the correct time in HA?

**Comment by mauxi73** [comment]
It works great! I didn't set the time zone correctly in HA
Thanks a lot

**Comment by KTibow** [comment]
Consider closing?

**Comment by mauxi73** [comment]
yes!
Thanks
