### ISSUE TITLE
bug [v2.0.0b]:  "discover_existing: false" does not hide out of context schedules

### ISSUE THREAD

**Issue by brianhanifin** [nielsfaber/scheduler-card#252]
This is a problem because my boys could disable the network access schedule and stay up all night gaming on a school night. 😅

The new version is looking great!

**Comment by brianhanifin** [comment]
To be clear: the out of context schedules are hidden under "+2 excluded items". However, they should definitely not have access to  disable those schedules. However, I do want to grant access on the kitchen tablet to allow anyone to set or adjust a light schedule

**Comment by nielsfaber** [comment]
woops. I admit I made some changes there, must have overlooked this.
I will work on a fix.

**Comment by nielsfaber** [comment]
This issue is solved by in v2.0.0 (non-beta).
