### ISSUE TITLE
failed to add new scheduler tasks in lovelace card

### ISSUE THREAD

**Issue by wmlms** [nielsfaber/scheduler-card#253]
after upgrading the scheduler-component from v2.1.1 to the newest version v3.0.0b all my scheduler tasks created in the lovelace component disapeared. The scheduler entities are still available but can no longer be configured. Deleting the entities is not possible. I deinstalled both components scheduler component and scheduler card and rebooted HA several times but no success. After deinstalling the components also the schedculer entities disapeared but appeared again after new installation of the components. Any idea how i can delete the scheduler entities to start from scratch. Were are the scheduler entities stored?

**Comment by nielsfaber** [comment]
What a drama!
Never heard of such disaster.

To remove the stored schedules, go to the .storage folder and the delete scheduler.storage file.

I will add something to have this file automatically removed when you uninstall (sorry for your troubles!)

Updating the scheduler-card should also give you the ability to edit/delete these schedules BTW

**Comment by wmlms** [comment]
Hi Niels,

I deleted the scheduler integration v3.0.0b; deleted the scheduler.storage as suggested; restarted HA and reinstalled the version v3.0.0b again but i still failed to define new schedules. 
Finally i  went back to version 2.1.1. and now everything is working again as expected.

**Comment by nielsfaber** [comment]
> but i still failed to define new schedules.

Why? What did the card do/show?
I'd like to know, since v3.0.0 will soon be released, so maybe more users will have the same issue.

**Comment by wmlms** [comment]
well the card was empty and i started to add a new schedule: it was possible to define a new entry but when finally saving the new entry it simply disappeared

**Comment by rodolfovento** [comment]
Hi, I have the same problem. I can configure the card, but when I click on save, nothing is seen.

**Comment by rodolfovento** [comment]
> 
> 
> Hi, I have the same problem. I can configure the card, but when I click on save, nothing is seen.

Hi, I wanted to update you. After updating Hassio to version 5.9 the problem was solved.
I did not notice the presence of this update.

**Comment by nielsfaber** [comment]
@wmlms  I improved some things in release v2.0.0 and v2.0.1. I recommend to update to the latest version, hope it solves the problems.
Please let me know if you still experience problems.

**Comment by wmlms** [comment]
today i updated both scheduler card and scheduler component to the newest versions 
first step was to update scheduler card from v2.0.0 to v2.0.1 ==> causes error message on lovelace entity card: scheduler component not installed ; right after updating scheduler component to version v3.0.0 and reboot everything works like a charm. all scheduler entries are still available, adding new entries works as expected.

system versions:
Scheduler component v3.0.0
Scheduler Card v2.0.1
Supervisor Version 2020.12.7
Operating System Debian GNU/Linux 10 (buster)
Docker version 19.03.13
Home Assistant Community Store 1.9.0

**Comment by nielsfaber** [comment]
I will close this issue, assuming all works OK now. 
If there are still problems, please re-open the issue.
