### ISSUE TITLE
Feature: Skip Next

### ISSUE THREAD

**Issue by alexyao2015** [nielsfaber/scheduler-card#254]
A way to skip the next triggered action would be great. This would allow you to not trigger the action for a particular day without having to remember to turn it on the next day.

**Comment by nielsfaber** [comment]
This has been requested+discussed a while ago..
I am also in favor of such functionality, but I don't see a place for it in the GUI.
IMO it only makes sense to add this on the overview page, but it wouldn't be in-line with the Lovelace layout to add more buttons to each item.

I tried to make the icon clickable and open a dropdown menu, but there is some bug in the material-design framework that HA uses, causing it to be hidden under the item below (CSS z-index issue).

**Comment by Cyriuz** [comment]
This would be a great addition to the already awesome integration!

I can see a few ways that I think would work for me at least:
- Simply an optional button on the line below the schedule.
- A link after the next scheduled time, or a small fast forward icon button. Or maybe arrows on both sides of the text so you can undo a skip next, or skip multiple.
- A separate card or just exposing the functionality as an entity/action or something so we can build our own ui for it.
