### ISSUE TITLE
The plan cannot be deleted 2.0b

### ISSUE THREAD

**Issue by pepe59** [nielsfaber/scheduler-card#255]
The Scheduler tab version 2.0.0b cannot delete unnecessary schedules.
I tried to delete the old plan. The plan is not deleted.
I created a new plan and tried to delete it. The plan is not deleted.
HA restart and plans still remain.
HA 2020.12.1  HassOS 5.8

**Comment by alex-tomin** [comment]
Same here, cannot remove schedules in 2.0.0b (component is 3.0.0b).

**Comment by nielsfaber** [comment]
This should be solved by updating to v2.0.0 (non-beta).

**Comment by pepe59** [comment]
Yes deleting the plan in the latest version works well.
If no one else has, I'll close the problem today.
