### ISSUE TITLE
Feature Request: Scedule Overview on the card (tabe mode?)

### ISSUE THREAD

**Issue by alex-tomin** [nielsfaber/scheduler-card#256]
The problem 
- Schedule times are not visible form card.
-  So when I want to check schedule times, I have to open an indivudual entry.
- If I have a logical dependency (I don't want two entries to be "on" at the same time), I need to open every entry. If there are more than fiew becoems very confusing.

Suggestion
- Allow to display the card in a Detailed/expanded View
E.g. something like
![image](https://user-images.githubusercontent.com/8026849/102726679-a0e8a300-42d5-11eb-9ed5-f085bf8562c8.png)

Just to represent an idea, pardon my paint skills. (a real change wouuld probably require a different design/fields to be displayed)

**Comment by KTibow** [comment]
> (I don't want two entries to be "on" at the same time)

Could you give an example?

**Comment by alex-tomin** [comment]
well, that was just one of examples why it can be handy to see timing. 

specifically in my case, radiant heat is better (for the water tank) and more efficient if operated zone by zone, rather then entire house at once. And yes, it can be solved an automation or a script, but the sheduler is more attractive with simplicity and flexibility. 

Teapot and cofee machine running together sometimes flip my circuit breaker. Again, that's better to be solved on electrical level, but meanwhile sheduling them 10 min apart would do the job.

Another example - I'm curious when my christmas lights are supposed to turn on, nicer to just have a look on dashborad and save a few clicks.

**Comment by KTibow** [comment]
@alex-tomin I agree with you, this would be nice, but this might be a bit hard to implement. You can also just make multiple scheduler cards.
>  I'm curious when my christmas lights are supposed to turn on

![image](https://user-images.githubusercontent.com/10727862/102735307-e79ac500-42f6-11eb-9a30-7a74aceeb1f9.png)
it already says the next action.

**Comment by alex-tomin** [comment]
Thanks for the promt reply, 

> it already says the next action.

Example in the picture says when it will be off, but not when it did turn on :).  (Using "Make Scheme" option).
And it shows "diff", which for some cases is obviously nicer, but I catch myself everytime doing the math to find absolute time. 
Especially when I need to review whole schedule (with all devices), I can go back to history to see what it looked like
![image](https://user-images.githubusercontent.com/8026849/102736202-2df12380-42f9-11eb-8db7-e98ab80aa131.png)
That kinda works, but when I make changes... No way to see result instantly.

>You can also just make multiple scheduler cards.

I'm not sure  I got the idea. Do you mean like one card would be for "On" switches. another one for "Off's"?

> might be a bit hard to implement
to design it might not be easy either, so it looks professional and usable, e.g. like in honewell devices.

**Comment by KTibow** [comment]
First of all, how would you toggle this mode? Would it be in card config, or in the UI?
Second, would the card's width stay the same, or would it be a bigger width?

**Comment by alex-tomin** [comment]
Good questions
>how would you toggle this mode? Would it be in card config, or in the UI?

I think card config should be just fine, not to overload the UI with additional toggle. And I don't know if there is a use case to have it "dynamic". A user would perhaps want either a simple card or detailed.

>Second, would the card's width stay the same, or would it be a bigger width?

I think wider would be nicer, but is it possible? Seems the cards are sized for the 1/3 of the window.
Just thinking, maybe to have the suggested details below schedule name (not to the right), e.g. in place of existing one (_+2 more tasks_)

**Comment by nielsfaber** [comment]
Please allow me to join the discussion 🙂 

> Schedule times are not visible form card.
> So when I want to check schedule times, I have to open an indivudual entry.

The choice has been made to show only the next job.
Clicking an item reveals all the details.
The main reason for this is to keep the card as minimalistic as possible, to be in-line with other HA cards (such as the entities card).
There has been quite some discussion about this in the past. It seems to be mostly a taste matter.

> If I have a logical dependency (I don't want two entries to be "on" at the same time), I need to open every entry. If there are more than fiew becoems very confusing.

You can assign a name to a schedule for identification.
It is also possible to have the name displayed in the card.
It is not recommended to create conflicting schedules, so having such dependency seems bad practice.

> Just to represent an idea, pardon my paint skills. (a real change wouuld probably require a different design/fields to be displayed)

Ideas are always welcome.
Your layout proposal is not realistic, since the available width is very limited.
The card is designed to fit a standard lovelace column, and to be mobile-friendly.

**Comment by HelmutEsterer** [comment]
Hello,

as idea, I would suggest the possibility to export the schedules and controlled entities as a .csv-file.

In my eyes it is not the biggest problem to loose all schedules in case of a breaking update.
For me the biggest issue is to have no overview of the many used schedules.
- And, honest, who is so correct to make a paper notice of every added or changed schedule.... ;-)))

So, I think it would be a great easement to have a exported csv.

Today I found a very satisfying solution:

I copied the file config/.storage/schedule.storage to my local HD and converted it with the online "YAML Lint"
to a better readable textfile.

After the update I was afraid, I loose all entries, **but after immediate updated the schedule-card and reboot of the whole
host, in my case the raspberry, all entries came back! **

@Niels Faber and co worker:

Great job, and a very nice christmas-present! - Thank you !!!!!

With best regards

Helmut

**Comment by nielsfaber** [comment]
@HelmutEsterer Your comment is misplaced here.
Schedule entities are (as of v3.0.0 of the scheduler-component) contained in the .storage file as you say (as also other HA components do), as long as you keep a backup/snapshot of this folder the schedules can be restored.

**Comment by HelmutEsterer** [comment]
Hello Niels,

yes, of course I can restore the backup.

But what is the benefit if I would like the new version with a breaking change,
if this is the reason for the schedule entries are gone?

In this case I prefer a csv-file with this it is possible for me to restore the entries
Manual.

At last I have to say you asked for ideas for a complete overview of the entered entries.
- The csv-file was one IMHO.

Helmut


Sent from my Handy.


24.12.2020 19:00:29 Niels Faber <notifications@github.com>:
