### ISSUE TITLE
Error when change conditions after update to 2.0

### ISSUE THREAD

**Issue by TobiasKneidl** [nielsfaber/scheduler-card#257]
Error message: 

Something went wrong!
Message format incorrect: extra keys not allowed @ data['timeslots'][0]['type']

Response error: 400

Please report the bug.

**Comment by KTibow** [comment]
If you delete the schedule and make it again, does it work?

**Comment by TobiasKneidl** [comment]
On a new schedule, I can't even add a condition. After saving, the condition is disappeared.

The error above only appears, if I have multiple conditions and change the condition behavior from "none" to "all".

**Comment by nielsfaber** [comment]
I didn’t see that problem before.
I will investigate when I have the time (hopefully before Christmas).
Thanks for reporting it

**Comment by nielsfaber** [comment]
This should be fixed after updating to v2.0.1.

**Comment by TobiasKneidl** [comment]
Yes it works now, thank you!
