### ISSUE TITLE
Not upgraded correctly

### ISSUE THREAD

**Issue by panenka** [nielsfaber/scheduler-card#258]
After upgrade and a few restarts still not working.
I see integration with items, maybe schedules?
Lovelace card show none of schedules. All schedules has been missed.
When I try add new one, an error is shown that is not possible to call service scheduler/add.

**Comment by nielsfaber** [comment]
Please update the card to V2.0.0 as well.
If you did, then clear your browser cache or go in private mode.
The scheduler/add is not present with the new version.

**Comment by panenka** [comment]
Clear cache cache of application after each restart solved problem. Clear after first restart only didn't solved problem. So please close case, many thanks.

**Comment by KTibow** [comment]
You can hit the close button for yourself.
