### ISSUE TITLE
Option to set Temperature Step for climate schedules

### ISSUE THREAD

**Issue by twproject** [nielsfaber/scheduler-card#259]
Hi,
with latest release temperature steps for climate devices is 1 degree, is it possible to set lower? In my case i prefer to have 0.1 degree steps as I have on physical thermostat and on HA climate entity

Thanks

**Comment by KTibow** [comment]
You can try setting custom actions.

**Comment by nielsfaber** [comment]
After updating to v2.0.1, the card should automatically take the temperature step as defined for the climate entity.

**Comment by twproject** [comment]
> 
> 
> After updating to v2.0.1, the card should automatically take the temperature step as defined for the climate entity.

Quite well, now i'm able to set temperature but if climate device is turned off, it set only the temperature without calling heat or cool mode

See the screenshot

![image](https://user-images.githubusercontent.com/7046065/103075613-359c1b00-45cc-11eb-9c47-9ce1c59d4136.png)

**Comment by nielsfaber** [comment]
> Quite well, now i'm able to set temperature but if climate device is turned off, it set only the temperature without calling heat or cool mode

This is not related to this issue.
It is due to your climate integration.
Probably the integration does not support setting the mode together with the temperature setpoint (also not with the thermostat card). 
It would be best to keep the thermostat in heat mode and only change the setpoint.

**Comment by twproject** [comment]
> 
> 
> > Quite well, now i'm able to set temperature but if climate device is turned off, it set only the temperature without calling heat or cool mode
> 
> This is not related to this issue.
> It is due to your climate integration.
> Probably the integration does not support setting the mode together with the temperature setpoint (also not with the thermostat card).
> It would be best to keep the thermostat in heat mode and only change the setpoint.

Yes i'm doing as you suggest.

But to understand better, is there a way to debug the call? So I can see which is the command that scheduler send to climate and I can implement that (I'm using a custom modbus climate made by me)

**Comment by nielsfaber** [comment]
The card follows the service call definition as defined by Home Assistant:

![image](https://user-images.githubusercontent.com/16861605/103169572-38517700-483d-11eb-9adb-7f369ba43693.png)

See here: https://www.home-assistant.io/integrations/climate/#service-climateset_temperature

When selecting 'heat' action, `hvac_mode: heat` is added in the service call.
Some integrations are known to ignore this property completely, and will accept the new temperature setpoint without doing anything with it (if they are currently in `hvac_mode: off`).
The same would happen if you change the setpoint through the thermostat card.

This is really out of my hands, only thing I can do to help is to add support for programming a sequence of separate service calls (so first set `hvac_mode` and then the temperature setpoint).

Consider closing this issue, as we're getting off-topic.

**Comment by twproject** [comment]
> 
> 
> The card follows the service call definition as defined by Home Assistant:
> 
> ![image](https://user-images.githubusercontent.com/16861605/103169572-38517700-483d-11eb-9adb-7f369ba43693.png)
> 
> See here: https://www.home-assistant.io/integrations/climate/#service-climateset_temperature
> 
> When selecting 'heat' action, `hvac_mode: heat` is added in the service call.
> Some integrations are known to ignore this property completely, and will accept the new temperature setpoint without doing anything with it (if they are currently in `hvac_mode: off`).
> The same would happen if you change the setpoint through the thermostat card.
> 
> This is really out of my hands, only thing I can do to help is to add support for programming a sequence of separate service calls (so first set `hvac_mode` and then the temperature setpoint).
> 
> Consider closing this issue, as we're getting off-topic.

yes you can close the issue, thanks for support!!
