### ISSUE TITLE
Feature Request: Random option

### ISSUE THREAD

**Issue by poudenes** [nielsfaber/scheduler-card#26]
This Add-On will be great when you can add random option between 2 times. This is very handy to create a holiday scene

Random light on between 19:00 and 19:30 and random off between 23:00 and 23:59
Then you can create multiple lights that goes on and off when you're on holiday.

Maybe even a Random option between 2 times and to turn it on for 2 min and turn of itself but how many times turn on and off between the 2 times. (For example kitchen to get something and you walk back to living room the kitchen light goes off again

**Comment by nagyrobi** [comment]
+ 1 for randoms

**Comment by KTibow** [comment]
@nagyrobi use the reactions button.

**Comment by nagyrobi** [comment]
I don't think anybody looks at those LOL :-)

**Comment by KTibow** [comment]
@nielsfaber how hard is this to implement?

**Comment by nielsfaber** [comment]
This has been discussed many times in the mean time, there seem to be different (and better) ways to accomplish this, outside of the scheduler (or combined with the scheduler).
Example: https://github.com/slashback100/presence_simulation
I am not considering to add randomisation to scheduler at this point.
