### ISSUE TITLE
Customize card

### ISSUE THREAD

**Issue by Kalypox** [nielsfaber/scheduler-card#260]
Hi,
Is there a way to customize the card ?

![image](https://user-images.githubusercontent.com/2879180/103040940-3d7ca080-4575-11eb-9e63-94f0b019b456.png)

For exemple I would replace:

```
Toilettes thermostat: Eteindre
Dans 42 minutes
+2taches à venir
```

by
```
Toilettes
```

I prefer simple and light things, i don't need more informations.

Thanks !

**Comment by nielsfaber** [comment]
Yes you can.
See here: https://github.com/nielsfaber/scheduler-card#display-options

**Comment by Kalypox** [comment]
I'll try thanks !
