### ISSUE TITLE
Ideas...

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#266]
To resume ideas that I put in the forum, I think that for thermostats it would be interesting to do this in the schedule by time slot:

- define a base temperature (eco)
- in a time slot, adjust a new temperature and at the end return to the base temperature.

Another solution :
- plan a start action and an end action

Improvements: 
- thermostat replanning within a time limit to be defined. This can be useful to face an electrical failure... (although modern actuators know how to recover their state).

For other actions (non timeslot) : 
- have the possibility to execute several actions

**Comment by nielsfaber** [comment]
Please create separate issues for each feature, and give them an appropriate title.
I like to keep things organized here.
Thank you.

**Comment by mycanaletto** [comment]
OK, I do ;-)

**Comment by mycanaletto** [comment]
Here I have created all the subjects, once again don't take this for absolute demands but for ideas... 

Thanks again et bonnes fêtes de fin d'année !
