### ISSUE TITLE
Feature request: customizable holidays

### ISSUE THREAD

**Issue by elchanly** [nielsfaber/scheduler-card#267]
First this first: stunning job. Simply amazing, nice interface and very useful. 
I have a little bug. As i define schedules, switch.schedule comes alive but it says "defective schedule entity: switch.schedule_*" 
I havent tested if it works. Just because (here comes the request) I have done it by myself, not as beautifully as yours, just defining hours and making automations in Node-Red. My tip is I also define my own working days, just to adapt to my childrens working days. Could it be possible to add it to yours? A way to define "alternative" working days. 

Thanks anyway, ill keep on testing your magnificent work.

**Comment by KTibow** [comment]
You can manually select days.

**Comment by elchanly** [comment]
Not in a period. I mean: these days, from 22/12 to 8/1 i consider we are on holidays, affecting to climate and waking up alarms, between these days nothing sound on early morning and blinds go down.... I can select days in a week but not in a period.

**Comment by nielsfaber** [comment]
> I have a little bug. As i define schedules, switch.schedule comes alive but it says "defective schedule entity: switch.schedule_*"

I am investigating this bug. Multiple users seem to have this problem, although I don't experience it.
I am hoping to be able to release an update that fixes this.

> A way to define "alternative" working days.

The scheduler integration is compatible with the [workday integration](https://www.home-assistant.io/integrations/workday/).
You can use this integration to define your workdays (monday to friday or different), but also define holidays which are excluded from the workdays.
If you have it installed and create schedules that should trigger on workdays only, these schedules only fire on days that are marked as workdays by thr workday integration.
Creating a schedule that should trigger on weekends only, has the opposite effect: they trigger on non-workdays, which include holidays.

**Comment by elchanly** [comment]
Thanks for your efforts!
Regarding to holidays, I don't want user to mess with yaml, so my workaround includes this, two input date-time, but I'll try to figure out how to adapt it to workday integration. 
Thanks!!!! 
![IMG_20201229_091121](https://user-images.githubusercontent.com/49251727/103269413-18918e80-49b6-11eb-98e1-71fd0bb3bf5a.jpg)

Just thinking... Could it be possible to adapt your card to a timer? Instead of selecting hours of days, selecting duration to trigger actions? 

Thx!!!

**Comment by nielsfaber** [comment]
The card allows conditions, so you could create some input_boolean or template binary_sensor that is switched based on your vacation start/stop dates.
You can also choose to turn off schedules using an automation.
Both options should give you the result you want.

There are no plans for adding any additional functionality for this.

**Comment by elchanly** [comment]
Will dig into this, thanks!
