### ISSUE TITLE
Replanning time slot

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#269]
In the context of a time slot, it would be interesting to be able to activate a rescheduling mode of the thermostat within a time period to be defined. This can be useful to face an electrical failure... (although modern actuators know how to recover their state).

It would be interesting that this replanning is optional in order to give the user the possibility to manually adjust a thermostat, or not.

**Comment by nielsfaber** [comment]
Did you read the [documentation about timeslots](https://github.com/nielsfaber/scheduler-card#timeslots)?
When HA restarts, the scheduler will automatically trigger the actions of the current timeslot.
If the entity is not available yet, it will postpone the actions until it is available.

What kind of additional functionality do you have in mind?
Can you provide an example?

**Comment by mycanaletto** [comment]
Actually I was thinking of two cases:

- The one where a user modifies a thermostat (a child with Alexa for example) and where the re-planning puts things back in order after one year if it was decided so (lock).

- A user changes a thermostat to go to the shower for example and the thermostat will return to its initial position (for example, we can decide that the bathroom thermostat will reset itself after 30 minutes...).

- the case where the switch does not receive the first order for a technical reason (radio interference) and where the rescheduling would allow to catch up...

**Comment by nielsfaber** [comment]
I decided to not add such functionality.
My goal for this scheduler is to create an easy interface for controlling schedules through the GUI.
I don't want to handle advanced or device-specific features, users can combine/extend scheduler with scripts or automations if they need more control.

**Comment by mycanaletto** [comment]
You're probably right and I understand that you can't endlessly stack the possibilities for more complex things that can be done in YAML or with Schedy to which it remains possible to add some interface (https://canaletto.fr/post/home-assistant-and-planification-schedy).
