### ISSUE TITLE
Multiples actions

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#270]
For simple actions (non timeslot) : 
- have the possibility to execute several actions

**Comment by nielsfaber** [comment]
I was planning to add this functionality to allow users to set temperature setpoint and hvac_mode independently.
Do you have the same use-case in mind, or do you want to combine other actions?

The schedules are limited in allowing one or more entities of the same type/domain.
The actions will be applied to all entities (you cannot choose action per entity).
So the usages of multiple actions are only a few (as far as I know).

**Comment by nielsfaber** [comment]
> for thermostats where it can be interesting to change several at a time (time slot).

Can you clarify your comment?
Change several what?
There is already support for multiple entities.
Regarding actions I think it can be practical to set the temperature + operation mode.
Did I forget any other use-cases?

**Comment by mycanaletto** [comment]
I extrapolate...

I was thinking for example to manage several termostats or several different lamps in a schedule:

For example..: 
- thermostat 1 : 21°.
- thermostat 1: 20°.
- light 1 : on
- sw1 : off

But indeed in this case it may be better to be able to call a "scene", what I just saw is already provided in the scheduler...

**Comment by nielsfaber** [comment]
OK clear.
Let's distinguish between:

1. Multiple actions. e.g.: _set temperature->21 and mode->heat_
2. Multiple entities of same type. e.g.: _climate.thermostat_A, climate.thermostat_B_
2. Multiple entity types, _e.g.: switch + light + thermostat in single schedule_
2. Assigning action per entity, _e.g.: switch->on, light->off_

As for 1. I think this is useful (especially for climate entities, as mentioned before).
As for 2., this is now in place.
3 + 4 are out-of-scope. This will overcomplicate the GUI. People can use a scene or create separate schedules.

**Comment by mycanaletto** [comment]
We agree

**Comment by nielsfaber** [comment]
> 1. Multiple actions. e.g.: set temperature->21 and mode->heat

This is actually now in place. Since it’s the only scenario for which 2 service calls are required, this is solved in the component.

Since cases 3+4 are considered out-of-scope, this issue can now be closed.
