### ISSUE TITLE
Translation / terminology

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#272]
The translation “FIN DE SEMAINE” doesn’t mean anything in France, everyone uses “WEEK-END”.

But since this function is used in association with the component workday: (in the HA sense), wouldn’t it be better to use “Workday ON” and “Workday OFF” for this selector ?

**Comment by nielsfaber** [comment]
The translations are user maintained. 
You can make changes to the French translation as you wish.
The file is here: https://github.com/nielsfaber/scheduler-card/blob/main/src/localize/languages/fr.json

> But since this function is used in association with the component workday: (in the HA sense), wouldn’t it be better to use “Workday ON” and “Workday OFF” for this selector ?

I think will be very confusing to many users.
I assume 90% does not use the workday integration, so for them workday vs weekend is very clear.
For the 10% that use the workday integration, it is important to know that weekend = non-workday = weekend + holidays.
This is documented, and it seems that people are fine with it (I didn't get any complaints for far).
I would like to keep the displayed text in the card as it is now.

**Comment by nielsfaber** [comment]
I will close this issue since this will not be worked on.
I guess there is a difference in opinions regarding the display of workday/weekend options. I don’t consider the proposal to be an improvement.
For the translations, improvements are always welcome. These changes can be directly submitted to the files.
