### ISSUE TITLE
Services are not created

### ISSUE THREAD

**Issue by paoloantinori** [nielsfaber/scheduler-card#277]
The only service I can find available is: `scheduler.run_action`
Version: `v3.0.1`

Although I can create schedules correctly with the UI component.

**Comment by KTibow** [comment]
Services have been removed by @nielsfaber, because the common audience didn't use them, but `scheduler.run_action` remains for troubleshooting (used to be `scheduler.test`). Now the card communicates via websockets.

**Comment by nielsfaber** [comment]
As @KTibow, the card no longer needs these services, so they are removed.
The scheduler-component is intended to be used together with the card.

**Comment by paoloantinori** [comment]
is there a way to create schedules programmatically from a script or an action?

**Comment by nielsfaber** [comment]
Not using this scheduler integration, its really meant to be controlled using the provided UI.
But HA already offers functionality to switch devices on fixed times, there would be no need for using this IMO.

**Comment by paoloantinori** [comment]
As you were saying the UI o scheduler is useful, reason why having it as a frontend for both manually created and programmatically created entries would be a useful feature.

**Comment by nielsfaber** [comment]
I added back these services and updated the documentation a little bit. 
Hope this solves the problem for you.

**Comment by paoloantinori** [comment]
Great!
Thank you very much!
