### ISSUE TITLE
Schedule "Name" Field Ignored

### ISSUE THREAD

**Issue by aniceberg** [nielsfaber/scheduler-card#278]
The optional name field on the options page is not being used to name the scheduled automation-- it ignores that entry and simply uses the device name, or if it's a schedule for multiple devices, it specifies the number of devices, e.g. "2x switches: Turn on" .

**Comment by nielsfaber** [comment]
It is used as name/entity_id for the schedule itself, not for the entity/entities used.
Similar to naming an automation.
Please refer to the forums for questions.

**Comment by aniceberg** [comment]
> It is used as name/entity_id for the schedule itself, not for the entity/entities used.
> Similar to naming an automation.
> Please refer to the forums for questions.

Thanks for the reply- does that mean that the below is inaccurate?

[https://github.com/nielsfaber/scheduler-card#friendly-name](https://github.com/nielsfaber/scheduler-card#friendly-name)
"Note if a custom friendly name is provided it shall be displayed in the overview page as well."

**Comment by nielsfaber** [comment]
That statement is a bit outdated, yes. Thanks for letting me know.
Nowadays the user can configure what they want to display on the overview page.
See [display options](https://github.com/nielsfaber/scheduler-card#display-options).
Default setting is _entity_: _action_ format, but you can also choose to display _name_.
Only downside is that it applies to the whole list, not per item.
