### ISSUE TITLE
add person entity for conditions?

### ISSUE THREAD

**Issue by vikdb** [nielsfaber/scheduler-card#279]
Hi,

I cant seem to find the possibility to select a person for the conditions.
Is this possible?

**Comment by nielsfaber** [comment]
You have to include it. 
See [here](https://github.com/nielsfaber/scheduler-card#include) for the yaml way, otherwise you can do it via the UI card editor.

**Comment by vikdb** [comment]
its not avaible in the ui but i included it through the YAML file, thnx!
