### ISSUE TITLE
Multiple conditions

### ISSUE THREAD

**Issue by drlauridsen** [nielsfaber/scheduler-card#280]
Scheduler is getting more and more impressive and useful, thanks..

Maybe its already possible, but I just dont know how.. but is it possible to add multiple conditions like date range and entity location (from entity tracker)?

**Comment by nielsfaber** [comment]
You can create multiple conditions for a schedule, and you can also choose whether you want ALL or ANY condition to be valid for allowing the schedule to be triggered.

A date range is not directly possible through the card, but you could create some input_boolean or binary_sensor that is only active while the date is in a certain range.

Device tracker is not supported yet, but It could be added (home / not_home state). It seems similar to person entities, which are already supported.

**Comment by nielsfaber** [comment]
`device_tracker` is now supported in v2.0.3 of the card.
