### ISSUE TITLE
Non-admin user has no permissions to modify schedules

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#282]
Several HA log lines when card is used by non-admin user (you have to refresh the UI, reopen the app):
> ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1894345840] Error handling message: Unauthorized

Versions: scheduler 3.0.2 & 3.0.1 (3.0.0 not tested), card 2.0.2 & 2.0.1 (2.0.0 not tested), HA 2020.12.2 (Hass OS)

When I remove scheduler card from the dashboard and refresh it, the error disappears, when I add the card back, there are new lines of the error. So I'm not sure that the card is the source of the bug, but it seems to be a good guess. I have turned on debug level logging for websocket_api, but this is huge. I can send it upon request.

**Comment by nielsfaber** [comment]
This authorization is handled by HA internally. 
As far as I know there is no way to solve this.

**Comment by lmagyar** [comment]
Filling the log with ERROR messages every time a family member simply opens the UI, can't be accepted as normal behavior.

**Comment by nielsfaber** [comment]
I checked and saw that HA only allows a number of events to be subscribed for a non-admin user:
https://github.com/home-assistant/core/blob/a6e474c7c9027568ab21d0b82bfbc0b964efd69e/homeassistant/components/websocket_api/commands.py#L65
Since there is no way to add the scheduler-updated event to the whitelist, I don't have any solution for this.
As a result the card will not be able to update when something changes in the backend (this is when the event fires).

This means that after editing the card or even enabling/disabling a schedule, the card will not be properly refreshed for a non-admin user.
The only way to get rid of the error would be to not allow users to make changes to the schedules, and thus registering to events unnecessary.

**Comment by nielsfaber** [comment]
I do agree with you that the loggings are not acceptable.

So I decided to do as I said before:
> The only way to get rid of the error would be to not allow users to make changes to the schedules, and thus registering to events unnecessary.

This is added in the v2.0.3 release.

In the meantime I will open a discussion with the dev team, to add support for this, because the changes I had to make seem more like a workaround, it would be better if event subscription is not limited to admin users only.

**Comment by lmagyar** [comment]
Without knowing HA internals around events, your argument seems quite justifiable!

**Comment by lmagyar** [comment]
Currently "to not allow users to make changes to the schedules" means non-admin users can't change even an existing schedule (not just unable to add/delete). That was previously possible!

Currently we have to give admin rights to family members to change their room's heating schedule! From a HA user's point of view, this is equivalent to giving admin right's to be able to turn on your light or change your room temperature. Makes no sense.

This seems to be a serious shortcoming in HA's architecture, if HA can't be used by non-admin users.

**Comment by KTibow** [comment]
Could you theoretically add a custom_component named websocket_api that's patched?

**Comment by lmagyar** [comment]
@KTibow Are you asking me? To help testing? Sure.

**Comment by nielsfaber** [comment]
@KTibow It would work.
Basically all that’s needed is to add an extra event to the whitelist (the one that you renamed to allowlist).
I want to have this implementation changed in core though. It’s really poorly designed currently. It needs the flexibility for a component to add its event(s).
But forking it and adding the functionality we need could be a starting point.

**Comment by Misiu** [comment]
@nielsfaber maybe open an issue in the HA architecture repo (if one doesn't exist yet).
As @lmagyar wrote the need to add admin rights to all users seems like a bad architecture decision (on the HA side).
With the architecture issue, we will be able to comment and vote. That's the least we can do.

**Comment by nielsfaber** [comment]
@Misiu  I agree. I just have a bad feeling that the issue will be completely ignored (unless I create a PR myself with the improvements).
I also created an architecture issue to have the logbook entries show that an entity was changed by scheduler (or by automation in general). No one ever responded to it.

**Comment by Misiu** [comment]
@nielsfaber I wish I could help, but I already got banned two times for commenting too much on issues and PR.
You will always have my vote on your ideas 🙂

**Comment by nielsfaber** [comment]
Thanks for that 👍  
If I opened an issue i will make sure to post it here

**Comment by nielsfaber** [comment]
@lmagyar I updated the title a bit so other users will know that this is the place for discussing this limitation (I don't consider it a bug anymore).

**Comment by nielsfaber** [comment]
I opened an architecture issue for discussing this with dev: https://tinyurl.com/yybvyv6j

**Comment by lmagyar** [comment]
Thorough investigation! Just a minor typo, the last link to commands.py is broken (in Consequences chapter), has a missing "/" in ...dev/homeassistant...

**Comment by lmagyar** [comment]
This is still a valid issue! In https://github.com/home-assistant/architecture/issues/488#issuecomment-841405354: "found a workaround to do this for my custom_components", though admin right is still needed to add/modify schedules (tested now again).

**Comment by nielsfaber** [comment]
Don't get intimidated about the stale label. 
I just didn't find the time to do this.

**Comment by sebastianeferrer** [comment]
Hi every one! Any news about this issue? Let me know if I can help you in any case. Thanks a lot!

**Comment by andkuzmich** [comment]
Hi guys! I've also stuck with this issue. This is great scheduler component, thanks to @nielsfaber for it, but its completely unusable if you want to add user management into your homeassistant. Do you have any updates? I ready to help in any way just let me know if we have a plan how to resolve this. Thanks!

**Comment by nielsfaber** [comment]
I made some changes in both the scheduler-component + scheduler-card to give back editing access to non-administrator users.
Will be released in one or two weeks.

**Comment by bnjroos** [comment]
> I made some changes in both the scheduler-component + scheduler-card to give back editing access to non-administrator users.
> Will be released in one or two weeks.

First, thanks for the awesome component, has the feature been released in a branch for example ?

**Comment by nielsfaber** [comment]
@bnjroos its in queue for the next release.
Which I’m planning to make later this week.

**Comment by lmagyar** [comment]
Wow! Tested, and it works again! Really thank you, finally my family lost it's admin status. :)
