### ISSUE TITLE
[BUG] Zero length time slot freezes the UI

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#284]
When a schedule has 3 time slots, and the last has zero length, the normal state should be:
> times: 00:00:00, 07:00:00, 00:00:00

Meaning: 00-07, 07-24, 24-24

Currently I have this:
> times: 00:00:00, 00:00:00, 07:00:00

It simply freezes the GUI, when anybody (admin or non-admin user) tries to edit the timeslots. Simply clicking on the schedule results in a frozen UI (app and browser (chrome)). I can't even delete it.

Update/how to recreate: Stopped HA, deleted erroneous schedule from scheduler.storage, HA start, created new schedule (with zero length 3rd timeslot), saved, worked. Reopening it, it shows a zero length 1st (!) timeslot, re-saving it causes the errorneous state, after this resave, the next opening freezes the UI, browser results in out of memory error.

**Comment by nielsfaber** [comment]
I will check this out. It looks concerning!
A zero length time slot should not be allowed actually. A day should start at 00:00 and end at 24:00 (meaning 00:00 the next day).
Time slots should span at least a full minute.

**Comment by nielsfaber** [comment]
I could reproduce this situation, thanks to your instruction.
I made some changes to the card that prevents the crashing but also will prevent the user to create zero-length slots.
Will send out a new release for it soon.
Thanks for reporting!

**Comment by nielsfaber** [comment]
The v2.0.3 release should fix these issues and also adds some restrictions in the timeslot editor to avoid zero-length time slots.

**Comment by nielsfaber** [comment]
Can you confirm the problem is gone now?

**Comment by lmagyar** [comment]
Tested: v2.0.4 & v3.03
- creating zero length slots is still possible
- if the 3rd slot (out of 3) is zero length, save, reopen: it will be the first
- if the 2nd slot (out of 3) is zero length, save, reopen: the 2nd won't be the 1st, it disappears, but you get 2 additional new slots at the end after 12h, and all the times are divided by 2 when displayed (eg. 08h slider is around 04h position), but when you move them again, it gets quite weird (basically the remaining slots are duplicated and squeezed into 24h, quite strange)
- if you create 2 zero length slot, all the sliders go to 0h immediately

So, it doesn't crash, but it still has problems.

**Comment by nielsfaber** [comment]
@lmagyar Could you perhaps demonstrate the problems you are seeing?
You seem to be better than me in "monkey testing" this card, I am not able to create a zero-length timeslot.

**Comment by lmagyar** [comment]
Tested: v2.0.5 & v3.03

It works flawlessly now, 1 time_step: is kept between schedules, and after/before 00/24h.
