### ISSUE TITLE
V3.02 - Groups and presences are not available for conditions

### ISSUE THREAD

**Issue by Cavekeeper** [nielsfaber/scheduler-card#285]
It still worked in previous versions.
In Version 3.02 you cannot insert groups and presences for the conditions. Presence was added via custom components. These can no longer be selected in the options. Like other groups, you can no longer choose it.
`customize:
  group.family_presents:
    states:
      - home
      - not_home`

**Comment by nielsfaber** [comment]
This problem was reported earlier by someone in the forums. The support is already created and will be in next update of the card.
Don’t know what you mean about presence though. I’m just talking about groups.

**Comment by Cavekeeper** [comment]
Hello Niels, yes please have a look to my comment above. I realized the presence tracker via the custom entry home / not_home. That can no longer be used as a condition.

**Comment by nielsfaber** [comment]
I added the support for `group` entities in the v2.0.3 release.
Hope it answers your request.

**Comment by Cavekeeper** [comment]
Yes well, I could check it and it works as expected. Many thanks for the fast solution.
