### ISSUE TITLE
Feature request: Multiple variables in an action

### ISSUE THREAD

**Issue by hdejongh** [nielsfaber/scheduler-card#287]
Hello,

i would like to be able to select multiple variables in an action. Currently it's only possible to have 1 variable. 
For example with lights within a schedule i would like to be able to choose the color profile, the transition time and brightness.
Of course it would be possible to do this with a scene. But to do it within the schedule makes it more simple and flexibel.

Regards,

Hans

**Comment by nielsfaber** [comment]
I will check this out, i think it should be possible.
A color picker is requested before, I think this is a little bit too much for this scheduler.
But I agree it would be nice to have the ability to choose from a range of values, without being restricted to max. 1 parameter.

**Comment by nielsfaber** [comment]
This is finally in place.
With `variables` (Used to be `variable`) you can now define as many as you would like.
I wish I had done it like this in the beginning, it took quite some effort to update the code for this 😅
