### ISSUE TITLE
Feature request: schedule by timer instead time

### ISSUE THREAD

**Issue by twproject** [nielsfaber/scheduler-card#291]
Hi all,
 is possible to add a feature so I can schedule using a timer?
My idea is when an events happen do something for x minutes

Thanks

**Comment by nielsfaber** [comment]
You can create a schedule using the scheduler.add service, which triggers X minutes from now and automatically removes itself afterwards.
There will be no features added to trigger on a device state instead of time. For this you should use the standard HA automations.
