### ISSUE TITLE
Specified action after x minutes/hours

### ISSUE THREAD

**Issue by Hajsiu** [nielsfaber/scheduler-card#292]
Hi

First of all - really nice project, good job!

The only option im really missing is to have a possibility of running specific action based on timer instead of action at specified time during the day (lets say "Turn off the light after 10 minutes from now"). Would be possible that you add this feature soon? I would really appreciate!

**Comment by KTibow** [comment]
Why would you not be able to manually turn it off?

**Comment by Hajsiu** [comment]
> Why would you not be able to manually turn it off?

I do not want to be kindless but are you asking for real? Why you make automations if you can go and switch all devices manually?
But if you ask i can find some example for you - i just recognized that my swimmingpool is dirty and i want to go for swim soon so i want to turn on the waterpump just now for 30min so i turn on the pump and set the timer to turn it off after 30min and do not have to remember about it.

**Comment by KTibow** [comment]
If you always do that, then you could just set an automation so whenever it's turned on for 30 minutes turn it off.
> Why you make automations if you can go and switch all devices manually?

Automations are automatically triggered. What you're talking about is a script or something.

**Comment by Hajsiu** [comment]
No, i do not do that always and that was just one of examples. It can't be set to turn off after 30min every time its turned on because the water pump works lets say 20:00-22:00 each day (thats the automation) so it would interfere each other. The feature im talking about is for irregular situations that can't or shouldn't be automated.

**Comment by nielsfaber** [comment]
I agree that it would be nice to be able to schedule something for a fixed duration 👍 
Maybe it would already be helpful when you're creating a schedule, the clock does not start at 12:00 but at the current time (or adding a button to quickly set it to the current time).
I understand it would be nicer if you can program the duration and reset the schedule to re-activate, but it will take some work to get that in place.
Unfortunately i'm very short on time currently. There are more requests+ideas than I can handle...

**Comment by Hajsiu** [comment]
> Maybe it would already be helpful when you're creating a schedule, the clock does not start at 12:00 but at the current time (or adding a button to quickly set it to the current time).
Yeah, thats what i was thinking about too, would work temporarily.

> I understand it would be nicer if you can program the duration and reset the schedule to re-activate, but it will take some work to get that in place.
> Unfortunately i'm very short on time currently. There are more requests+ideas than I can handle...
I totally understand and hope you will sort this out at some stage. Thanks!

**Comment by KTibow** [comment]
I agree with this; however I would like to still for your use case recommend
> because the water pump works lets say 20:00-22:00 each day

adding a condition to the automation that turns it off. That way you wouldn't need to go to the scheduler.

**Comment by nielsfaber** [comment]
I don't want to create false hope here, the requested feature will not be added.
The main reason is that I want to keep the card as simple as possible, its already too complex for my liking.
I am working on a new layout, aiming at less whistles and bells (but not drop functions that are now in place).
I do think that the scheduler-component does have room for adding provisions to do as you please.
For example, I could consider adding a `reschedule` service, which could allow you to overwrite the configured time to `now` or `10 minutes from now` etc. It would still need a automation or blueprint etc to work smoothly for the user.
Please open an issue in the scheduler-component repo if you would like to see something like this added.
I am closing this request as part of a "cleanup". Sorry.

**Comment by stevem405** [comment]
I also would like to see this added but in a simplified form which may be(?) easier to implement and less clutter on the UI.
HAI (leviton) Omni uses the syntax `<some entity> ON FOR 20 MINUTES` which cuts the number of schedule entries down dramatically because most often, you don't need to specify an off time.
