### ISSUE TITLE
Add proximity sensor

### ISSUE THREAD

**Issue by fiorentino77** [nielsfaber/scheduler-card#294]
Hi, 
what do you think about insert proximity sensors like a condition?
Now, it's not possible.

Regards,

Alessandro

**Comment by KTibow** [comment]
Shouldn't be too hard for the maintainer to add it. Could you give a use case?

**Comment by fiorentino77** [comment]
Yes, sure.
If i'm above 100kilometeres from house set my thermo 1 or 2 degrees less.
When i'll come back (below 100km) set my thermo to the confort temp.
Proximity sensor here: https://www.home-assistant.io/integrations/proximity/

Thank anyway!
Regards,

Alessandro

**Comment by nielsfaber** [comment]
I will see what I can do

**Comment by nielsfaber** [comment]
I added proximity sensor in v2.0.5.
Hope it satisfies your request.
