### ISSUE TITLE
language question

### ISSUE THREAD

**Issue by thygeL** [nielsfaber/scheduler-card#295]
Hej thanks for at very nice card, 
I have translated the language file to Danish, but for checking for correct translation every where, how can I make "a test run", and would you want the file, how do i Uploads it for you
is it possible to change UI language manuel, not only following Homeassistant UI language.

thyge

**Comment by KTibow** [comment]
All issues should be separate. Would you mind creating a separate issue for
> is it possible to change UI language manuel, not only following Homeassistant UI language.

?
As for 
> how do i Uploads it for you

Click here:
https://github.com/nielsfaber/scheduler-card/tree/main/src/localize/languages
Click add file, and choose upload file. Upload the file you made. It should walk you through it.

**Comment by nielsfaber** [comment]
Hello Thyge,

Thanks a lot for helping out!
For me it's OK if you just create a PR with your file, I will include it in the next release.
If there are later improvements needed, this is very easy to do.
As @KTibow says, you can just upload the dk.json file and it would make a PR automatically. 

Testing locally is also possible but you will need to have node.JS / NPM and some packages to compile the card.
I could help you out with this if you prefer this method.

**Comment by thygeL** [comment]
okay, but I get this when I try to upload

Uploads are disabled.
File uploads require push access to this repository.

**Comment by KTibow** [comment]
Oh. Then hit the new file button and paste the contents. It should make a PR.
