### ISSUE TITLE
Feature Request: Add a button that will execute the schedule/scene

### ISSUE THREAD

**Issue by prbtt** [nielsfaber/scheduler-card#298]
As the title says it'd be really usefull if we had a button that could execute the scene that I just configured. Also, i don't necessarily need a timer for this "schedule" card. This is a good way to make scenes that I want to execute with ease with just a push of a button.

edit: I just noticed there is a scheduler.run_action that can trigger the scene. That will do what I want, but having that built in button to trigger it will still be very usefull. I also noticed you can't turn some lights on and some lights off in the same schedule. They all have to be ON or OFF.

**Comment by KTibow** [comment]
> This is a good way to make scenes that I want to execute with ease with just a push of a button.

Could you just create an HA scene, and then trigger it via both a button and the scheduler?

The name of this repo is `scheduler-card`. `scheduler.run_action` is mainly meant for troubleshooting (IMO).

As for
> I also noticed you can't turn some lights on and some lights off in the same schedule. They all have to be ON or OFF.

Go give a +1 to #270.

**Comment by KTibow** [comment]
Actually #270 is a different thing. The maintainer's opinion on
> I also noticed you can't turn some lights on and some lights off in the same schedule. They all have to be ON or OFF.

is
> This will overcomplicate the GUI. People can use a scene or create separate schedules.

**Comment by nielsfaber** [comment]
Where would you like to see such a button?

**Comment by prbtt** [comment]
> Where would you like to see such a button?

On the header maybe. Something like "Run".
I made this manually, when I tap the image I get a confirmation message to run the scene.
![SmartSelect_20210111-090015_Home Assistant](https://user-images.githubusercontent.com/60021461/104180045-762cce80-53eb-11eb-85bd-008c81f51844.jpg)

**Comment by nielsfaber** [comment]
I thought we are talking about the scheduler-card?
Else your request is in the wrong place.

**Comment by KTibow** [comment]
@nielsfaber
> I made this manually

I think this was made using a picture elements card.

**Comment by prbtt** [comment]
> @nielsfaber
> 
> > I made this manually
> 
> I think this was made using a picture elements card.

By manually I mean with a combination of cards using picture elements.



> I thought we are talking about the scheduler-card?
> Else your request is in the wrong place.

This is about scheduler. I just posted that image as an example. I think having a tap_action button in the scheduler would be very useful.

**Comment by nielsfaber** [comment]
Could you repeat your request?
What would you like to see added to the scheduler-card and where?

**Comment by prbtt** [comment]
> Could you repeat your request?
> What would you like to see added to the scheduler-card and where?

![Screenshot_20210111-131151_Home Assistant](https://user-images.githubusercontent.com/60021461/104206686-99b54080-540e-11eb-8c80-a0afcf422b73.jpg)
There

**Comment by nielsfaber** [comment]
this will not fit, since the text may be much longer for some people.
Maybe i could make the icon clickable or something..

**Comment by LazyTarget** [comment]
Hi, I am looking for something similar
I have set up some schedules to be run on chosen times, but sometimes I want to manually trigger them ahead of time.

Instead of having to edit the schedule and move the time, to 1 minute in the future. It would be nice if, like @nielsfaber 's suggestion that I could click on the icon and it triggers the schedule instantly, until the stop time (so that it won't be run twice)
