### ISSUE TITLE
Using HA areas?

### ISSUE THREAD

**Issue by danplant** [nielsfaber/scheduler-card#301]
Hi! Firstly, thanks so much for making this! As far as I'm concerned this sort of scheduling should be a core part of any automation system.
I have a quick question: Can I use an area instead of an entity and if so how would I go about it? 

My use case would be to set the temperature for an area rather than the individual entities within that area.
I made an automation to do this but it's considerably more awkward to set up and modify than using something like your card. And impossible if I expected anyone else in my family to do it themselves.

Regards,

   Dan.

**Comment by KTibow** [comment]
No, but you can create an HA group.

**Comment by danplant** [comment]
Ah, shame.
I've got everything all set out nicely in areas now so I don't think I'll bother with the groups.
Are areas a fairly new thing in HA?

**Comment by KTibow** [comment]
Well they weren’t available in the first release. Try hass-magic-areas, it creates entities based on your already-existing areas.

**Comment by nielsfaber** [comment]
The card allows you to create a schedule for controlling multiple climate entities simultaneously.
Combine that with some custom grouping and you should have something that works for you.
AFAIK areas are only used for frontend/visualization purposes, they are not actionable.

**Comment by danplant** [comment]
> The card allows you to create a schedule for controlling multiple climate entities simultaneously.
> Combine that with some custom grouping and you should have something that works for you.
> AFAIK areas are only used for frontend/visualization purposes, they are not actionable.

You can do a climate.set_temperature, area_id: living_room, temperature: 18 type thing.

**Comment by danplant** [comment]
> Well they weren’t available in the first release. Try hass-magic-areas, it creates entities based on your already-existing areas.

Yes, I installed it before the scheduler card but it didn't look as interesting or useful so I haven't looked at it yet :)

**Comment by danplant** [comment]
I think I'll mark this as closed as the question was answered.

Thanks.
