### ISSUE TITLE
Run schedule every x minutes/days/etc.

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#302]
Hello !

I had a request to carry out a planning, the electric water heater for example, every other day at 01:00.

I think it would be interesting to be able to plan orders every x minutes or x days...

**Comment by KTibow** [comment]
A better title would be "Run schedule every x minutes/days/etc." It already recurrently runs every day by default.

**Comment by mycanaletto** [comment]
> A better title would be "Run schedule every x minutes/days/etc." It already recurrently runs every day by default.

I see that you are an expert in dialectics, too bad we don't speak the same language...
