### ISSUE TITLE
Question: Option to let lights fade/how to use customization

### ISSUE THREAD

**Issue by Janderatelslang** [nielsfaber/scheduler-card#303]

**Comment by KTibow** [comment]
You mean using just the `transition` attribute?

**Comment by nielsfaber** [comment]
As @KTibow says, you can set the transition parameter for this.
Through `customize` you can define your own actions for certain entities, so you can replace the `turn_on` action for lights with an extended version.

**Comment by Janderatelslang** [comment]
That is indeed what it meant. When i was making this "Feature Request" I was quite sleepdrunk and I didn't know what the `customize` was because I couldn't find how to get to the `customize` section or the place where you can add your customization. And to be honest, after reading the instructions page again this morning I still can't figure it out.
