### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by bakaufman** [nielsfaber/scheduler-card#304]
Instructions are minimum verbosity. How about a 5 steps literal set of instructions that are compatible with the current version of hassio? HACS installation instructions are equally difficult and the instructions on the HACS website are out of date.

**Comment by nielsfaber** [comment]
I don’t know which problems you ran into, it’s hard for me to update the readme accordingly. 
IMO all the steps are there to be able to set it up,  and 100+ people managed to do this.

Some users took the initiative to make improvements to the readme themselves and opened a PR for their changes. This way you can help contributing as well, it is much appreciated!
