### ISSUE TITLE
Schedule including covers do not launch correctly

### ISSUE THREAD

**Issue by Matssa56** [nielsfaber/scheduler-card#305]
Hi all,

I wanted to switch from an automation to this integration for my covers and surely everything else.

However I can't seem to make it work. I correctly created the lovelace card with the integration and added the devices with the hour and days of execution.

When the time arrives, nothing is launches. I tried to launch it through a service in the dev tools and it works correctly. 

Where does it but? How can I help with logs? Can't seem to find any in the HA logs.

Thanks!

**Comment by nielsfaber** [comment]
Could you check the history of the switch.schedule entity to see if it triggered?
If not, then it’s probably your timezone setting.

**Comment by Matssa56** [comment]
> Could you check the history of the switch.schedule entity to see if it triggered?
> If not, then it’s probably your timezone setting.

Thanks for your help, just checked the time zone and it is correctly added in HA and my server is good as well.

For the history I'll check tomorrow cause I didn't include it in the recorder integration.

**Comment by Matssa56** [comment]
> Could you check the history of the switch.schedule entity to see if it triggered?
> If not, then it’s probably your timezone setting.

Ok so just checked and it is correctly triggered when checking the history of the switch. However nothing has moved ^^'

**Comment by nielsfaber** [comment]
Ok.
Then it’s a matter of comparing the configured action with the service you use which works.
In the switch.schedule properties you can read the service parameters used for the action.
Could you paste them here?
There’s also the schedule.run_action service, you could use it to instantly trigger the action for testing purposes.

**Comment by Matssa56** [comment]
> Ok.
> Then it’s a matter of comparing the configured action with the service you use which works.
> In the switch.schedule properties you can read the service parameters used for the action.
> Could you paste them here?
> There’s also the schedule.run_action service, you could use it to instantly trigger the action for testing purposes.

Here are the properties:
```
weekdays:
  - mon
  - sat
  - sun
  - tue
  - wed
  - thu
  - fri
times:
  - '22:20:00'
actions:
  - service: cover.close_cover
    entity_id: cover.premier_volet_salon
  - service: cover.close_cover
    entity_id: cover.quatrieme_volet_salon
  - service: cover.close_cover
    entity_id: cover.volet_bureau
  - service: cover.close_cover
    entity_id: cover.troisieme_volet_salon
  - service: cover.close_cover
    entity_id: cover.volet_chambre_d_amis
  - service: cover.close_cover
    entity_id: cover.volet_chambre_eliott
  - service: cover.close_cover
    entity_id: cover.volet_chambre_parentale
  - service: cover.close_cover
    entity_id: cover.cinquieme_volet_salon
  - service: cover.close_cover
    entity_id: cover.deuxieme_volet_salon
next_trigger: '2021-01-14T22:20:00+01:00'
friendly_name: 'Schedule #99e3de'
icon: 'mdi:calendar-clock'
```

I tested using the service and it works, it's just the scheduling that doesn't work :S

**Comment by Matssa56** [comment]
> Ok.
> Then it’s a matter of comparing the configured action with the service you use which works.
> In the switch.schedule properties you can read the service parameters used for the action.
> Could you paste them here?
> There’s also the schedule.run_action service, you could use it to instantly trigger the action for testing purposes.

Is there a way to put this in debugging mode and see where is blocks the launch at the specific time?

**Comment by nielsfaber** [comment]
You can set log level to debug for the custom component (in configuration.yaml), it will show much more.
The `run_action` service is meant for debugging as well.
Internally it executes exactly the same code as the triggering of the schedule does.
So if manually it works but on schedule not, that is very peculiar..

**Comment by Matssa56** [comment]
> You can set log level to debug for the custom component (in configuration.yaml), it will show much more.
> The `run_action` service is meant for debugging as well.
> Internally it executes exactly the same code as the triggering of the schedule does.
> So if manually it works but on schedule not, that is very peculiar..

Ok so here is the debug message. Really strange that the devices are not available right now since I can use them :S

FYI I also have an automation that does basically the same thing and if works fine.

![Screenshot_20210116-212023](https://user-images.githubusercontent.com/16662808/104822146-c7501e80-5840-11eb-960a-ef40e7799dc0.png)
![Screenshot_20210116-212246](https://user-images.githubusercontent.com/16662808/104822184-02525200-5841-11eb-8fb2-5692f6235945.png)

**Comment by nielsfaber** [comment]
The scheduler checks whether entities are available before executing the actions.
Otherwise the actions will fail (they have no effect).
Apparently these cover entities have state `unavailable` or `unknown` when the schedule is triggered, and also don’t recover with the 10 mins timeframe.
You should be able to see this in the HA history of these entities.

**Comment by nielsfaber** [comment]
Did you check the entity history to see if they actually become `unavailable`?

**Comment by Matssa56** [comment]
> The scheduler checks whether entities are available before executing the actions.
> Otherwise the actions will fail (they have no effect).
> Apparently these cover entities have state `unavailable` or `unknown` when the schedule is triggered, and also don’t recover with the 10 mins timeframe.
> You should be able to see this in the HA history of these entities.

In the history I don't see anything of the sort

> Did you check the entity history to see if they actually become `unavailable`?

Yeah just checked and they are only in the unknown status since the state is unknown. There are other attributes though if needed.

![Screenshot_20210118-181813](https://user-images.githubusercontent.com/16662808/104945820-90e9df00-59b9-11eb-9f89-d549c281767c.png)

I'll keep the history on and see when it triggers if it works or not.

**Comment by nielsfaber** [comment]
The unknown status should never occur.
It suggest that the cover is neither open or closed.. so the status cannot be shown in a Lovelace card either.
It points to a problem in the integration of your covers.
I’m afraid I cannot help you with that.

**Comment by Matssa56** [comment]
> The unknown status should never occur.
> It suggest that the cover is neither open or closed.. so the status cannot be shown in a Lovelace card either.
> It points to a problem in the integration of your covers.
> I’m afraid I cannot help you with that.

Arg crap not sure how I can make it work since I'm using localtuya to control my covers. When using it it becomes either closing or opening but after that it goes back to unknown...

Gonna open a ticket on their side and see if they can help. Other evolution that I asked was concerning the current position, it doesn't refresh realtime but at then end of the action.

On your side, is there a way to not use the unknown status? :D

**Comment by yaccri** [comment]
Same problem here (:
