### ISSUE TITLE
feature request: ability to drag around schedule entries.

### ISSUE THREAD

**Issue by gurkburk76** [nielsfaber/scheduler-card#306]
It would be really good for visibility if one could change the order of the different schedlud entries, possibly by dragging it around if you use the app.
Sometimes you add something, add something else and delete other things and stuff goes out of order, can get messy.

**Comment by nielsfaber** [comment]
This is impossible to do since the card has nowhere to store the list order you defined.
The sorting is done based on which one fires first. 
If you experience inconsistencies with that, there might be a bug.
But the drag-drop function i cannot add.
