### ISSUE TITLE
Dont understand? Did the install fail?

### ISSUE THREAD

**Issue by realjax** [nielsfaber/scheduler-card#307]
Hello, I followed the instructions to the letter for installing both the card as well as the component. Double checked it and everything seems to be in order. However, when I am to add a scheduler card I don't know how to start.. Am I supposed to be able to simply select it from the templates shown ('add card'), cause if that is the case, it doesn't show up.  Or is there another way to start with an actual scheduler card manually??

**Comment by nielsfaber** [comment]
You should make sure that the card is added as module in the lovelace resources.
See here: https://www.home-assistant.io/lovelace/dashboards-and-views/

In case you configure your Lovelace GUI without YAML (only via UI), you should be able to access the resources through this menu item (in HA configuration):
![image](https://user-images.githubusercontent.com/16861605/104566185-92c84100-564d-11eb-9041-5edd660ba476.png)

Note that resources only show up in that menu in case you check this optionin your HA user profile settings:
![image](https://user-images.githubusercontent.com/16861605/104566662-2bf75780-564e-11eb-83ab-7e4257cf9cfd.png)
(at least it used to be like that)

After that you should be able to add the card.

Is this the first custom card you're adding to your HA config?

**Comment by realjax** [comment]
Yes, It is added as a module:

![Screenshot 2021-01-14 at 11 00 50](https://user-images.githubusercontent.com/883435/104575906-da53ca80-5657-11eb-871c-33d7cd087fe4.png)

Still.. no go.. :(

**Comment by realjax** [comment]
Also, I have a www/community folder where all my other HACS cards are installed. The scheduler one is not there although I installed it using HACS

**Comment by realjax** [comment]
Ja het is gelukt.  Ik had uit de documentatie niet kunnen halen dat het bij HACS  *zowel* als integratie als frontend moet worden geinstalleerd. tnx

**Comment by KTibow** [comment]
Consider closing this issue?
