### ISSUE TITLE
Feature request: Allow setting cover tilt not only postion

### ISSUE THREAD

**Issue by kstaniek** [nielsfaber/scheduler-card#308]
Currently only setting the cover position can be scheduled. The cover tilt can't be set.

**Comment by KTibow** [comment]
I think multiple variables needs to be implemented first.

**Comment by nielsfaber** [comment]
@KTibow 
From what I can see, the tilt level is set using a separate service.
I can add the support for setting the tilt level, but it will not be combined (or combinable) with another action.
So multiple variables are not involved here.

**Comment by kstaniek** [comment]
That is perfectly fine. For the facade blinds the most common operation is the tilt angle change not the whole blinds move up/down. Just a new action is needed. Currently there is "set position" and we also need "set tilt position".

**Comment by nielsfaber** [comment]
I added this feature in release v.2.0.5.
I saw that there are also services `close_tilt_cover` and `open_tilt_cover` for fully opening/closing covers, but they don't seem to be supported by all integrations
I'm hoping the set_tilt_position action will help users to achieve what they want.
The range is defined from 0 to 100, I couldn't find documentation on this so I'm hoping this works for all integrations.

**Comment by kstaniek** [comment]
What is supported is returned by _supported_features_ properties.
Look at: https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/__init__.py

Of course close_cover_tilt and open_cover_tilt would be nice to have. I can also see that at leat the translation to some languages is missing for cover position action.
