### ISSUE TITLE
Climate scheduler condition based on outside temperature value

### ISSUE THREAD

**Issue by Frederik-V** [nielsfaber/scheduler-card#309]
Dear.

I'm a great fan of the scheduler integration!

As a possible future improvement, it could be great to implement a condition that influences a climate scheduler based on an outside temperature sensor value.

For example, the climate scheduler is only active if the outside temperature is dropping below a certain value.
Can be useful for weather based climate control.

Kindest regards,
Frederik

**Comment by nielsfaber** [comment]
Hi Frederik,

I think what you are looking for is already possible actually.
If you have a sensor entity for the outside temperature, you can include it in the card.
When you create a schedule you can click the “options” button to define a condition using that sensor.
Please try it out 👍

**Comment by Frederik-V** [comment]
Hi Niels.

I already have tried several times, but I can not enter a reference value (for example 10 for 10 degrees) under the state field.
Select an entity (boiler outside temperature - sensor entity) and a condition (above/below) is accessable.

See screenshot in attachment:
![Screenshot_20210119-195045_Home Assistant](https://user-images.githubusercontent.com/51418912/105079676-0922d400-5a90-11eb-8517-f118d02533af.jpg)

 Therefore I can not save condition with the options menu.

What could be the reason?

Kindest regards,
Frederik

**Comment by nielsfaber** [comment]
From your screenshot I would expect a text field below “staat” where you can (manually) enter the number to compare against.

The fact that it’s missing is strange, suggests that the card failed to read the sensor properties or something.
Could you go to “developer tools” and make a screenshot of the state+attributes of this sensor?

I will try to reproduce it myself then, see if it shows up the same.
I must say that the conditions option have recently changed, so it wouldn’t surprise me if the problem is caused on my side.
I’m sure we can fix this though 🙂

**Comment by Frederik-V** [comment]
As requested, screenshot below:

![Screenshot_20210119-201043_Home Assistant](https://user-images.githubusercontent.com/51418912/105081548-9f57f980-5a92-11eb-8627-8490e831720b.jpg)

Hopefully it makes things clear for you in order to understand my issue.

**Comment by nielsfaber** [comment]
I found a problem that causes the text field to not show up when it should.
If you update the scheduler-card to v2.0.5 you should be able to enter a value.

**Comment by lucode** [comment]
I had first a similar problem with my thermostats (Komforthaus Spirit), but now it works like a charm. Unfortunetally I can't remember the steps I did to make it work. But maybe it helps to share my results. The state attributes are as follows:
```
hvac_modes:
  - 'off'
  - heat
min_temp: 7
max_temp: 35
preset_modes:
  - none
  - Heat Eco
  - Full Power
  - Manufacturer Specific
current_temperature: 18.6
temperature: 19.5
preset_mode: none
node_id: 2
valve_position: 49 %
friendly_name: 'Tstat Sal de Bain: Temp'
supported_features: 17 
```
The Scheduler card code looks as follows:
```
type: 'custom:scheduler-card'
include:
  - binary_sensor
  - climate
  - scene
domains:
  climate:
    actions:
      - service: climate.set_temperature
        name: Set Temperature
        variable:
          field: temperature
          name: Temperature
          min_temp: 5
          max_temp: 24
          step: 0.1
```

**Comment by mycanaletto** [comment]
> Dear.
> 
> I'm a great fan of the scheduler integration!
> 
> As a possible future improvement, it could be great to implement a condition that influences a climate scheduler based on an outside temperature sensor value.
> 
> For example, the climate scheduler is only active if the outside temperature is dropping below a certain value.
> Can be useful for weather based climate control.
> 
> Kindest regards,
> Frederik

It would indeed be very practical and I wanted to ask Niels...

For the moment I've got around that by creating a binary_sensor that switches to on if the outside temperature is too low to not ventilate.

It seems to me that there are also weather unevennesses that provide binary in case of frost.

**Comment by nielsfaber** [comment]
@Frederik-V Can you confirm that the changes I made allowed you to accomplish what you want?
If so, this issue can be closed.

**Comment by Frederik-V** [comment]
I can confrim that the issue is solved. Item can be closed. Sorry for my late reply.
