### ISSUE TITLE
Feature Request: Include Vacuums

### ISSUE THREAD

**Issue by n8detar** [nielsfaber/scheduler-card#31]
A great addition to the standard configuration would be to include vacuums as an option by default. I realize that you can add vacuums fairly easily through yaml, but I think including it by default would be great.

**Comment by KTibow** [comment]
This is kinda hard because some use different services:
- start
- start_pause
- turn_on

**Comment by KTibow** [comment]
Fairly easy to do though, just create an entry like this for each item:
https://github.com/nielsfaber/scheduler-card/blob/60f6f34056d5a449683d241261a0f26ec266fb33/src/default-config.ts#L55-L66
https://github.com/nielsfaber/scheduler-card/blob/60f6f34056d5a449683d241261a0f26ec266fb33/src/default-config.ts#L127
https://github.com/nielsfaber/scheduler-card/blob/60f6f34056d5a449683d241261a0f26ec266fb33/src/default-config.ts#L136
https://github.com/nielsfaber/scheduler-card/blob/60f6f34056d5a449683d241261a0f26ec266fb33/src/localize/languages/en.json#L66

**Comment by nielsfaber** [comment]
I like the idea but I also agree with @KTibow that it will be hard to standardize.
I use the scheduler for my roborock S5, but it requires a very specific service call including coordinates of the zone.
So I think it is best to leave it as configurable through yaml.
Maybe it would be helpful if I create some template yaml in this repo, and you could use it as a starting point, copying parts that apply to your config.

**Comment by n8detar** [comment]
I didn't realize that there was so much variation in services for vacuums. I think including more examples would be extremely helpful, I find it easier to understand how to configure new devices/services when I have an example to look at and tweak as needed.

**Comment by nielsfaber** [comment]
In v1.5.0 i added the option to add vacuums. They have `turn_on` and `start` actions defined (depending on the type). I think other actions (like pause, go back to dock, clean spot) are not very practical for schedules. But i could add them as well.

Let me know if it helps you!

**Comment by KTibow** [comment]
@n8detar consider closing?

**Comment by sstefanowski** [comment]
Hi,  I have a roborock vacuum integrated via xiaomi gateway (https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-mi-robot-vacuum) and it's not showing as option in Scheduler card. Do you have a clue why?

```
vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.***
    token: ******************************
```

**Comment by nielsfaber** [comment]
@sstefanowski what is the configuration of your scheduler-card?

**Comment by sstefanowski** [comment]
OK,
It was just my browser - it didn't reload Javascript. After emptying browser cache I can see all the options in the card config...

**Comment by nielsfaber** [comment]
Glad you fixed it 👍 
BTW: the xiaomi_miio integration in HA is a bit weird. It defines model specific services, which i cannot make available out-of-the-box.

But if you want to create a scheduled zone cleaning, you can add something like this:
```yaml
customize:
  vacuum.roborock:
    actions:
      - service: xiaomi_miio.vacuum_clean_zone
        service_data: {zone: [[20250,18514,23100,22714], [20250,22714,23360,27000], [23150,20814,25960,27200]], repeats: 1}
```
There are some guides around on how to find zone coordinates.

I will close this issue now.

**Comment by Marcoske23** [comment]
> In v1.5.0 i added the option to add vacuums. They have `turn_on` and `start` actions defined (depending on the type). I think other actions (like pause, go back to dock, clean spot) are not very practical for schedules. But i could add them as well.
> 
> Let me know if it helps you!

Sry for open a closed post. Can you agree pause, stop, return to base? I was thinking of making a new post to ask but I see that the subject was discussed here
