### ISSUE TITLE
(enhancement request) to also alow start/stop automation

### ISSUE THREAD

**Issue by ELANDJEA** [nielsfaber/scheduler-card#312]
since discovering the scheduler-card I use it with great pleasure (wonder why I did not miss this feature within HA before).

However, while creating a schedule I miss the possibility to start/stop automations....I can overcome this by making a script that I execute (to start/stop automation) based on a schedule....but if it can be done directly via the scheduler card, it will reduce even more double configurations.

**Comment by nielsfaber** [comment]
Hi,
You can add the turn_on / turn_off functionality for automations to the card yourself using `customize`: https://github.com/nielsfaber/scheduler-card#actions
I will add it to the built-in actions in a next release so it will work for everyone.

**Comment by nielsfaber** [comment]
This functionality is added in https://github.com/nielsfaber/scheduler-card/commit/6e2acf8599268f8b306e6025d0b21d3b73500627.
It will be included in the upcoming release.
