### ISSUE TITLE
{time} in display_options is empty at sun event

### ISSUE THREAD

**Issue by Schrolli91** [nielsfaber/scheduler-card#313]
The `{time}` var is empty if a event is direct n sunset or sunrise.
If i will set a delay in front or after the event it will showed correct.

![image](https://user-images.githubusercontent.com/6043382/105404268-12e03f00-5c2a-11eb-9c99-a32bb5fdaf87.png)
![image](https://user-images.githubusercontent.com/6043382/105404084-d9a7cf00-5c29-11eb-8e9e-3a15e0e1fc6b.png)
![image](https://user-images.githubusercontent.com/6043382/105404111-e2000a00-5c29-11eb-9ad9-cf67eecae926.png)

btw: WOW - Thanks for that awsome project :-)

used Version: v2.0.5

**Comment by nielsfaber** [comment]
Sorry for the lack of response, and thanks for informing me.
I will pick this up when I can.

**Comment by nielsfaber** [comment]
This should be fixed by https://github.com/nielsfaber/scheduler-card/commit/29a29c7e0806804ae2aa28a65f47f9056d7b32d1
It will be added in the upcoming release.

**Comment by Schrolli91** [comment]
Thanks for your efforts so far :-)

**Comment by nielsfaber** [comment]
I am closing the issue, assuming this is fixed now.
Please shout if you still have problems with recent releases of the card 🙂

**Comment by Schrolli91** [comment]
Short Feedback - Fix works, problem is gone ... Thanks :-)
