### ISSUE TITLE
Add possibility to program automations

### ISSUE THREAD

**Issue by npirtube** [nielsfaber/scheduler-card#316]
Hello my friend,

I am using your add-on in HA for about a month now and I miss not being able to schedule automations.

This forces me to create a Script, but the performance is not quite as expected.

Have you thought about incorporating this feature?

**Comment by KTibow** [comment]
What do you want the automation to do?

**Comment by npirtube** [comment]
I think my request has not been understood.

I have created some "automation", and what I want is to be able to program the switching on and off of these "automation".

Unfortunately, I can't do it, I can only program the switching on and off of scripts.

What I would like is for the programmer to be able to detect the "automation" in order to turn it on or off.

**Comment by nielsfaber** [comment]
You can add your own actions to the card as you desire.
See https://github.com/nielsfaber/scheduler-card#actions for an example.
Please note that an automation is not triggered by turning it off/on. Nothing will happen directly.

**Comment by nielsfaber** [comment]
Discussion can be continued in https://github.com/nielsfaber/scheduler-card/issues/312
