### ISSUE TITLE
Strange values every .4 of input_number scheme schedule

### ISSUE THREAD

**Issue by TTLucian** [nielsfaber/scheduler-card#317]
Hi.
First, this card is awesome. Can't imagine that HASS doesn't have an "official" card like this. Congrats and thank you for your work!

I believe I found a small bug. I don't know where it come from but the scheduler card is the only place I've noticed it.
Every time I hit a .4 value in scheduling an input_number helper, I run into this:
![1](https://user-images.githubusercontent.com/1855276/105623996-da598480-5e26-11eb-96e8-f71a57600efd.jpg)
![2](https://user-images.githubusercontent.com/1855276/105623997-daf21b00-5e26-11eb-83fe-5d9bf8938459.jpg)
The entity displays fine in the dashboard and other cards:
![3](https://user-images.githubusercontent.com/1855276/105624033-1856a880-5e27-11eb-8392-a800c82453cf.jpg)
It's a simple input_number helper with 0.1 step size.
I've edited the scheduler.storage file to delete the decimals.
Any ideas?

**Comment by nielsfaber** [comment]
Hi, thanks for liking scheduler!
I seen such problems in multiple places in HA, but I thought scheduler didn’t have these rounding problems.
It looks easily fixable though.

1 question back: why don’t you use your climate entity directly in the scheduler?

**Comment by TTLucian** [comment]
Glad to hear it's easy to fix.
The climate entity comes from Node Red. It's a Salus iT500 thermostat which doesn't have any integration at all except for 3 nodes in Node Red. The input_number helper triggers a "Set Temperature" node for the iT500.
And thanks to your great work, I can use schedules outside the crappy official app that Salus provides! 😃 👍

**Comment by KTibow** [comment]
As a side note, here's a custom component to create a `climate` entity: https://github.com/jcwillox/hass-template-climate

**Comment by TTLucian** [comment]
Thanks for the tip. 😉 I've just started to use Home Assistant and I'm still learning.
I've set it up in the generic thermostat platform but the problem is that Node Red only has "set temperature" and "current temperature" nodes for the Salus iT500. I haven't figured out a way to turn the thermostat on and off. I've set up a switch that sets temp to 5 degrees for "off" and 20 degrees for "heat" but this creates other problems in different scenarios. Any thoughts?

**Comment by TTLucian** [comment]
Same thing happens with climate entity (generic thermostat):
![1](https://user-images.githubusercontent.com/1855276/105639480-423cb900-5e81-11eb-8e89-279c1b4b3ea2.jpg)

**Comment by KTibow** [comment]
> Node Red

Do you have to use Node Red? Personally I don't know too much about it.

> "current temperature"

So can you create a sensor entity in HA?

**Comment by nielsfaber** [comment]
This should be fixed in https://github.com/nielsfaber/scheduler-card/commit/4f4bc7d6f0096266e53152547882bcfd0cd519bd.
Will be included in the upcoming release.

**Comment by nielsfaber** [comment]
I am closing the issue, assuming this is fixed now.
Please shout if you still have problems with recent releases of the card 🙂
