### ISSUE TITLE
Set a friendly name of a scheduler task to enable/disable

### ISSUE THREAD

**Issue by anarro** [nielsfaber/scheduler-card#32]
And add the specific name of a scheduler task.

Example:

I have created a schedule and I like to activate / deactivate with a certain automation or condition e.g. It's raining today? Well, I don't activate the programming, etc.

![image](https://user-images.githubusercontent.com/8436433/92831247-733ab680-f3d6-11ea-8e61-9293be3bbd61.png)

it's correctly?

**Comment by nielsfaber** [comment]
Maybe you could use the scheduler to trigger an automation instead?
I mean an automation that checks if it rains before operating the cover.
The scheduler works very well for automations, I think this way is nicer then disabling/enabling schedules very often.

**Comment by KTibow** [comment]
@nielsfaber you're getting off topic, the automation part isn't really part of the feature request. How about when you add a new schedule, you set its name, and then that's the `friendly_name`, and the device is used as a fallback name?

**Comment by nielsfaber** [comment]
@anarro would you like an extra text field to define the name of the schedule?
Or would you like the name to be derived from the action, e.g. `switch.schedule_dani_1_set_cover_position` ?

**Comment by KTibow** [comment]
How about by default, the name is what's shown on the card (the name of the device), and you can set it to anything you want?

**Comment by anarro** [comment]
I'm so sorry I couldn't connect earlier.

**Comment by KTibow** [comment]
```diff
-connect
+correct
```
correct²

**Comment by anarro** [comment]
Hi,

What you believe best. It would be nice to be able to stop a schedule through automation, so I think the schedule needs a more intelligible name, an easier switch.

We can have different schedule of the same cover/light/etc.. with different positions/intensity/etc at different times.

so the name of this schedule can do similar at your proposal:

switch.schedule_dani_1_set_cover_position_x 

I don't know if you could understand me..

Thank you very match!

**Comment by nielsfaber** [comment]
@anarro if you update the scheduler_component to v2.10, you can change the friendly_name of your schedules (via HA).
I will add something to input a text for a name in the card later.

**Comment by anarro** [comment]
Thank you very much @nielsfaber, I'll try again later.

**Comment by nielsfaber** [comment]
This function is added in v1.7.5 of the card.
Please try it out and close the issue if you’re happy with it.

**Comment by KTibow** [comment]
Can you put some placeholder text in the field?
