### ISSUE TITLE
Failed to call service scheduler/add. extra keys not allowed @ data['entries']

### ISSUE THREAD

**Issue by chomarus** [nielsfaber/scheduler-card#321]
Hello,
I use version card beefore 2 and commponent beefore 3 - works great (there was only some issuse with switch on/off schedule on card wen You have more then one).
Now I install card 2.0.5 and commponent 3.0.3 and I have get error during save Scheduler. I can edit and save Card Configuration, but not Scheduler.
Have You idea what is wrong?

**Comment by nielsfaber** [comment]
You need to refresh your browser cache, because the card seems still outdated.
The docs also tell you how you can check the card version (see FAQ)

**Comment by chomarus** [comment]
Thank You for quick answer.
Now I try update again and after clear cache, everything started to work nicely again.
In Lovelace Resources I had /local/scheduler-card/scheduler-card.js?v=0, after update I found that in www is new folder community so I change to /local/community/scheduler-card/scheduler-card.js?v=0 and now card start working :-).
