### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by suneworld** [nielsfaber/scheduler-card#322]
Great card!
One issue though: the option to select 24hr clock has been deprecatad with the following description:
"Option is removed in v1.9.0. This setting is now automatically determined from the browser."

Is it possible to bring this back? I would like to override my browsers/OS regional settings as it does not detect correctly. I am in Norway but it provides me with only am/pm.
Have a great weekend!

**Comment by nielsfaber** [comment]
I think nowadays the card determines the hour format based on the language setting in your HA account.
Do you have it in Norwegian set?
If it is in English (default), maybe you should use GB English instead.

**Comment by ShlomiPorush** [comment]
this also does not work for me. Please bring back the option to select a 24-hour clock 🙌

**Comment by KTibow** [comment]
> this also does not work for me.

Could you say more about what you've tried to do?

**Comment by mwasowski** [comment]
> 
> 
> I think nowadays the card determines the hour format based on the language setting in your HA account.
> Do you have it in Norwegian set?
> If it is in English (default), maybe you should use GB English instead.

Oh man..I've gave up on that tbh :D I was trying all sorts of things when I read `This setting is now automatically determined from the browser`. Now I went to my user profile, changed to English (GB) and it works. Maaan I'm dumb! Thank you! 🙏

**Comment by nielsfaber** [comment]
This functionality is improved in https://github.com/nielsfaber/scheduler-card/commit/6fd76490024266ca44378ed5fea111de750e0109. 
The card will now _truly_ use the browser locale, rather than using the hass account language setting.

**Comment by Misiu** [comment]
@nielsfaber take a look at upcoming changes in frontend: https://github.com/home-assistant/frontend/pull/9042 the user will be able to choose the format of the time.

**Comment by nielsfaber** [comment]
@Misiu thanks for the trigger!
It looks like a much needed addition to HA, I will wait a bit until it is released but will definitely link it to this card.

**Comment by Misiu** [comment]
This is still actual

**Comment by kukudemajia** [comment]
Please bring back the option to select a 24-hour clock ,Thanks~

**Comment by kukudemajia** [comment]
what a bummer!Expect a miracle.

> > Please bring back the option to select a 24-hour clock ,Thanks~
> 
> just change the time format in User Profile
> https://my.home-assistant.io/redirect/profile/

404: Not Found
Home Assistant 2021.8.6  Container

**Comment by ShlomiPorush** [comment]
> what a bummer!Expect a miracle.
> 
> > > Please bring back the option to select a 24-hour clock ,Thanks~
> > 
> > 
> > just change the time format in User Profile
> > https://my.home-assistant.io/redirect/profile/
> 
> 404: Not Found
> Home Assistant 2021.8.6 Container

setup your Home Assistant URL here: https://my.home-assistant.io/

**Comment by nielsfaber** [comment]
I got tired of waiting for updates in [custom-card-helpers](https://github.com/custom-cards/custom-card-helpers), so implemented some workarounds to not be blocked from implementing this feature.
The card will now take the configuration from the user profile.
This will become available for everyone in the upcoming release.

Example:

Setting in HA user profile:
![image](https://user-images.githubusercontent.com/16861605/129687190-adcb32d7-c724-4259-ac9d-662d9bc55889.png)
Result in the scheduler card:
![image](https://user-images.githubusercontent.com/16861605/129687107-f2bf0cd9-81d2-4765-9de3-dcd50badecdb.png)

Setting in HA user profile:
![image](https://user-images.githubusercontent.com/16861605/129687301-55b1bde0-d997-4a82-8a56-f1857c44bde5.png)
Result in the scheduler card:
![image](https://user-images.githubusercontent.com/16861605/129687340-23165b9e-6220-4335-ad63-3d8ee94af752.png)

**Comment by kukudemajia** [comment]
> I got tired of waiting for updates in [custom-card-helpers](https://github.com/custom-cards/custom-card-helpers), so implemented some workarounds to not be blocked from implementing this feature.
> The card will now take the configuration from the user profile.
> This will become available for everyone in the upcoming release.
> 
> Example:
> 
> Setting in HA user profile:
> ![image](https://user-images.githubusercontent.com/16861605/129687190-adcb32d7-c724-4259-ac9d-662d9bc55889.png)
> Result in the scheduler card:
> ![image](https://user-images.githubusercontent.com/16861605/129687107-f2bf0cd9-81d2-4765-9de3-dcd50badecdb.png)
> 
> Setting in HA user profile:
> ![image](https://user-images.githubusercontent.com/16861605/129687301-55b1bde0-d997-4a82-8a56-f1857c44bde5.png)
> Result in the scheduler card:
> ![image](https://user-images.githubusercontent.com/16861605/129687340-23165b9e-6220-4335-ad63-3d8ee94af752.png)

Great, looking forward to the update.

**Comment by lmagyar** [comment]
Tested the new version of the card, it is fixed now! :) Issue can be closed.
