### ISSUE TITLE
Feature suggestion: Grouping in scheduler overview

### ISSUE THREAD

**Issue by henriklund** [nielsfaber/scheduler-card#323]
This is a brilliant way of managing schedules, however, with +40 of those, I tend to lose the overview from time to time. Therefore, would it be possible to allow grouping of the output in Scheduler overview (for instance climate, outdoor lighting, indoor lighting etc.)? The grouping could by entities, Friendly name or similar. Whether it is implemented through YAML or as an additional attribute that could set for each schedule, is not really important. Inside each group, the current display (sorted by next run) should kept.

**Comment by nielsfaber** [comment]
The suggested way to do so, is by creating multiple scheduler-cards.
You can customise which entities or entity types show up in each card.

**Comment by henriklund** [comment]
Hmmm...I see. So a panel, with a vertical stack inside built with multiple schedulers. This is quite doable. One questions remains; is there a way of copying schedules from one scheduler to another (aside from tweaking /config/.store/core.* files)

**Comment by nielsfaber** [comment]
Some people choose to divide scheduler-cards over multiple pages (e.g. all climate stuff together), some have one page with several scheduler-cards, etc. This is up to you. You can treat it the same as a standard Lovelace entities-card.

I don't understand your question regarding copying of schedules.
Schedules are stored as HA entities, it is not recommended to manipulate them.
For the sake of backups, the `.storage` folder contains a file `scheduler.storage` which holds the configuration of the entities. So this file can be used for recovering/transferring schedules to another HA instance. 
If you use the HA snapshot function, the file should be automatically backupped.
There's no need/use for installing multiple instances of the scheduler-component. The scheduler-component can be used with multiple cards.

**Comment by henriklund** [comment]
I think I asked the question prematurely (before trying myself). Sorry about that. I can see Scheduler takes care of 'copying' (sorry for that ill-phrased word) if the entity is used in another Scheduler card. So for me suggestion; this is solvable by using multiple cards (stacked or otherwise is not of any consequence) and then simply including the same entities in the new card. Elegant.

Thanks!
