### ISSUE TITLE
Custom integrations now require 'version' key in manifest.json

### ISSUE THREAD

**Issue by Misiu** [nielsfaber/scheduler-card#326]
A recent change in core (https://github.com/home-assistant/core/pull/45919) will require the `version` key in the manifest.json file.
Consider adding it to https://github.com/nielsfaber/scheduler-component/blob/main/custom_components/scheduler/manifest.json

**Comment by nielsfaber** [comment]
Yeah I saw it (getting a daily report from GitHub action).
Thanks for the heads up.
I really don’t like having to keep updating the version number in 2 places though.
Do you know of any way to keep them in sync automatically? Also for the python counterpart of the scheduler?

**Comment by Misiu** [comment]
Sadly no.
Maybe @KTibow can help with this.

**Comment by KTibow** [comment]
Huh. This might be a bit hard. I'm not sure how you would modify a tag once set. The easier method would be to make it so you manually call a GitHub Action when you're ready to release, which sets it in the manifest and makes a release.

**Comment by Misiu** [comment]
@ludeeus maybe you could give us a hint on this? What is the best way to avoid updating two places?

**Comment by ludeeus** [comment]
> @ludeeus maybe you could give us a hint on this?

Just automate it :man_shrugging: 
<https://github.com/hacs/integration/pull/1851>

**Comment by KTibow** [comment]
@ludeeus here's the problem repo: https://github.com/nielsfaber/scheduler-component

**Comment by KTibow** [comment]
Sending in a fix.
