### ISSUE TITLE
Enhancement: extended weekend days selection

### ISSUE THREAD

**Issue by MarkusHornbach** [nielsfaber/scheduler-card#329]
For my climate schedules I need some extended day (weekend) selection: for action triggered 18:00 - 23:55 they should check if next day is weekend, not current day. So evening scheduling depends on if or not I have to get up early next day ;-)

e.g. Friday action on 7:00 acts as non weekend, 20:00 action as weekend, Sunday 9:00 weekend, but 20:00 as working day.

Of course this can be implemented with an extra condition (weekend check) sensor, but it would be great to have it integrated.
btw: very good integration/card, thanks for this one!

**Comment by nielsfaber** [comment]
The only way users can tell scheduler which days should be considered as weekend, is using the workday integration (https://www.home-assistant.io/integrations/workday/).
Unfortunately this component does not feature an hour setting, it only has a setting per day.

I would like to see this component extended with the functionality you propose, but it is out of my control.
Scheduler is not the right place to add such function (as it could be useful for other automations as well).
I suggest you to make a `binary_sensor.workday` entity yourself, which mimics the workday sensor but with the on/off state transitions at the times that you like.
In the meantime you could try placing this feature request for the workday integration, it could be useful for other users as well.

**Comment by MarkusHornbach** [comment]
Ok, so do I understand it right that scheduler is not detecting "original" workday integration but just looking for a "binary_sensor.workday" entity and using that one for proposing weekend day selection? That would in fact solve my problem, because I already have this sensor but with other name. Thanks very much for this quick hint!

**Comment by nielsfaber** [comment]
Scheduler indeed only checks for this entity name, and automatically recalculates schedules when it changes.
The only challenge is that the workday sensor has some attributes, such as a list of days comprising the workdays. It should be mimiced as well or it might give errors.

**Comment by MarkusHornbach** [comment]
one last question: do you use this workdays attribute list for the schedule algorithm? 
Because if that is the case, it would not be enough to set on/off state transition at my custom times, but also I would have to remove e.g. Friday from that list after 18:00?

**Comment by nielsfaber** [comment]
Both the state and the `workdays` attribute are used.
This is because the state only tells if _today_ is a workday, but for scheduling purposes, this info is needed for up to a week ahead.
If you use `mon`, `tue`, `wed`, `thu`, `fri` as `workdays` attribute, a schedule set for weekends only will after Sunday be automatically rescheduled to the next Saturday.
This means that in the card you will see "next Saturday at X" in the description.

If you change the state of the workday sensor to `off` at 18:00 on Friday, this will trigger the re-evaluation of ALL schedules which are either set for workday or weekend.
Any schedules configured to weekend will start executing from then on, all schedules configured for workdays will be skipped until the state goes `on` again.
The same mechanism is used for holidays, which cannot be seen in advance but only in the morning of the day itself (since the workday sensor does not expose a list of holiday dates).

**Comment by MarkusHornbach** [comment]
finally I tried it the way you proposed, but unfortunately it does not work:
when state of my workday sensor changes at Friday 18:00 to "off", a rescheduling takes place, weekend timers are activated, but next schedules for weekend timers are somehow set to Saturday 00:00. Any remaining actions for Friday (18:00 - 23:59) are ignored, but this is exactly what I want to prevent.
Then as a try I changed workdays attribute at Friday 18:00 from "Mon-Fri" to "Sun-Thu", but this has no effect.
Any ideas what is going wrong?

**Comment by nielsfaber** [comment]
Sorry for the late response. 
I improved some things in the scheduler-component regarding the support for the workday sensor.
I discovered that in some cases the schedules were not updated based on the `on`/`off` state of the sensor.
There's a good chance it will work with the new version, which I will release in the upcoming days.

**Comment by MarkusHornbach** [comment]
unfortunately for my scenario it still does not work. Actions from weekend schedules are still not activated automatically after on/off change. Only  after editing schedule and saving it, actions are activated.

**Comment by nielsfaber** [comment]
Could you share some details to allow me to reproduce this locally? (ideally an example schedule job + config of the workday entity)
I am really surprised to hear you are still having problems with workday non-workday separation.

**Comment by MarkusHornbach** [comment]
just checked it again today: when workday sensor changes e.g. on Sunday, 18:00, the remaining actions for that day are ignored and all action starting with Monday are scheduled. Maybe it depends on the ``workdays`` and ``exclude`` attributes? Before the change "sun" is  included in ``workdays`` and after the changing it is part of ``exclude``.
I will provide same sample config to reproduce the problem...

**Comment by nielsfaber** [comment]
Yesterday I found a typo in my code which can result in issues with the workday sensor: https://github.com/nielsfaber/scheduler-component/commit/928ff56422195d26e336d15f0d06fe969b426896

Maybe your issues are caused by this?
You could manually apply the change to your local files to test it, otherwise I will include the fix in an upcoming release.

The `exclude` function has nothing to do with timekeeping.

**Comment by nielsfaber** [comment]
Scheduler does not use `exclude`, only the `workdays` list and the on/off state of the binary sensor.

**Comment by MarkusHornbach** [comment]
yes, that typo was obviously causing that is_same_day() did not work well, but still rescheduling did not happen :-(

So not only to request help here, I did some investigations for myself:

in `timer.py`, in `async_workday_updated`:
```
                    # we are re-scheduling an existing timer
                    delta = (ts - self._next_trigger).total_seconds()
                    if abs(delta) >= 3600:
                        # only reschedule if the difference is at least an hour (usually it will be approx. 24 hrs)
                        await self.async_start_timer()
```
why only reschedule if delta is at least an hour?
When I remove this, it seems to work! 

In my cases the `delta` is 0 at that time, no `current_trigger`, only `next_trigger` exists and `watched time` is the same -> `diff` is 0.

here my debugs:
```
2021-05-20 21:59:08 WARNING (MainThread) [custom_components.scheduler.timer] fasync_workday_updated: ts 2021-05-21 00:00:00+02:00 next_trigger 2021-05-21 00:00:00+02:00 watched_times ['00:00:00']
2021-05-20 21:59:08 WARNING (MainThread) [custom_components.scheduler.timer] fasync_workday_updated: delta 0.0
2021-05-20 21:59:08 DEBUG (MainThread) [custom_components.scheduler.timer] Calculating timer for 8ffe53
2021-05-20 21:59:08 INFO (MainThread) [custom_components.scheduler.timer] day_in_weekdays: ts 2021-05-20 23:25:00+02:00 is same day
2021-05-20 21:59:08 INFO (MainThread) [custom_components.scheduler.timer] day_in_weekdays: ts 2021-05-20 20:00:00+02:00 is same day
2021-05-20 21:59:08 WARNING (MainThread) [custom_components.scheduler.timer] current slot 3 timestamp_end 2021-05-20 23:25:00+02:00 next slot 4 timestamp_next 2021-05-20 23:25:00+02:00
2021-05-20 21:59:08 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 8ffe53 set for 2021-05-20 23:25:00+02:00
```
do you see anything else that is wrong there?

**Comment by nielsfaber** [comment]
If delta = 0 the timestamp remains unchanged, so resetting it will (or should) have no effect.

Usually a job changes from e.g. “12:00 today” to “12:00 tomorrow” if the state of workday sensor changes, hence we can expect a difference of approx 24 hours (not exactly, in case of a DST change or sunrise dependent time).
IMO that condition is there for a reason and should not be removed.

If removing works for your case, something else most go wrong.
I must say the functionality was not designed for a workday sensor to change in mid day, the HA integration recalculates around midnight.
Doing so may cause some corner case, although i think the current code should be able to deal with all.

For me it’s not really clear how you are using it and what is failing.
If I could create a reproduction scenario myself I would probably be able to figure out what’s going wrong in a few mins.
Perhaps you could share enough info to do so?

**Comment by MarkusHornbach** [comment]
I know that my use case is a corner case, but as you said current code should cover it also.
You can reproduce it with this:
some helper:
```
input_boolean.scheduler_test
input_boolean.workday_test
```
two schedules:
- one should turn off->on scheduler_test at 23:00 on weekdays
- other should turn off->on scheduler_test at 23:30 on weekend
```
{
    "version": 1,
    "key": "scheduler.storage",
    "data": {
        "schedules": [
            {
                "schedule_id": "18b605",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "23:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "input_boolean.turn_on",
                                "entity_id": "input_boolean.scheduler_test",
                                "service_data": {}
                            }
                        ]
                    },
                    {
                        "start": "23:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "input_boolean.turn_off",
                                "entity_id": "input_boolean.scheduler_test",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "workday"
                ],
                "repeat_type": "repeat",
                "name": "test workdays",
                "enabled": true
            },
            {
                "schedule_id": "8ffe53",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "23:30:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "input_boolean.turn_on",
                                "entity_id": "input_boolean.scheduler_test",
                                "service_data": {}
                            }
                        ]
                    },
                    {
                        "start": "23:30:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "input_boolean.turn_off",
                                "entity_id": "input_boolean.scheduler_test",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "weekend"
                ],
                "repeat_type": "repeat",
                "name": "test weekend",
                "enabled": true
            }
        ]
    }
}
```
and finally a simulated template `binary_sensor.workday_sensor`, triggered by `input_boolean.workday_test`:
```
- binary_sensor:
  - name: "workday_sensor"
    state: "{{ states('input_boolean.workday_test') }}"
    attributes:
      workdays: >
        {% if is_state('input_boolean.workday_test', 'on') %}
          ["mon", "tue", "wed", "thu", "fri"]
        {% else %}
          ["mon", "tue", "wed", "thu"]
        {% endif %}
```
With this config you can test simulated workday-weekend transition on any Friday, for other days list has to be adapted.

**Comment by MarkusHornbach** [comment]
my expected behavior looks like this:
![image](https://user-images.githubusercontent.com/38568564/119168159-e534c680-ba60-11eb-85aa-ccc66dff7ce3.png)
![image](https://user-images.githubusercontent.com/38568564/119168181-ec5bd480-ba60-11eb-8989-9af8a78135ef.png)
Next trigger attribute is shown from both schedules...

**Comment by nielsfaber** [comment]
Thanks for the extensive info!
I set up a test exactly as you have it.

I noticed that indeed the timers were not consistently updating.
After diving deeper into the code I found that this is due to the fact that the code only re-evaluated the time of the slot that was previously the closest.
Due to a change of the workday sensor it could shift from "this evening" to "tomorrow morning", i.e. totally different timeslots.
So you were quite right that the condition of 24 hours time shift shouldn't be there.
I made some changes that consider all timeslots and any change in time: https://github.com/nielsfaber/scheduler-component/commit/13c4c0cbf368eb0df545ff61e4a4bf6b67d1e1b8
Please update to v3.1.3, it should resolve your issues.

**Comment by MarkusHornbach** [comment]
After last update it works perfect, thank you for the effort! 
Because for check of current day schedule times, the state of the sensor is used and not the days included in the `workdays` attribute, my use case still works without changing this attribute at all :-)
Think this issue can be closed now. 
If someone else wants to create a workday_sensor for a self defined weekend period e.g. Fri 18:00 until Sun 18:00, here is my template binary sensor:
```
- trigger:
    - platform: time
      # trigger update at 18:00
      at: "18:00"
    - platform: homeassistant
      # trigger after HA start
      event: start
  binary_sensor:
    - name: "workday_sensor"
      # set 'off' from Fri 18:00 until Sun 18:00
      # else 'on'
      state: >
        {% set curhour = now().hour %}
        {% set curday = now().weekday() %}
        {% if curhour >= 18 and curhour < 24 %}
          {% if curday in (4,5) %}
            False
          {% else %}
            True
          {% endif %}
        {% else %}
          {% if curday in (5,6) %}
            False
          {% else %}
            True
          {% endif %}
        {% endif %}      
      attributes:
        workdays: >
          ["mon", "tue", "wed", "thu", "fri"]
```
