### ISSUE TITLE
Different (room) temperature sensor for scheduled thermostat

### ISSUE THREAD

**Issue by Jaytie2k7** [nielsfaber/scheduler-card#331]
First of all, thank you so much for your work on this scheduler! For me it is a key element, that makes Home Assistant such a nice solution.
I'm quite new to all this and I'm not even sure if my isses/request is related to the scheduling (maybe not)

So I wanna create time schedules for my Fritz Dect 301. I can set custom target temperatures or trigger the modes 'eco' or 'comfort', which makes the thermostat use the predefined (in the Fritzbox) 'eco' and 'comfort' temps.

But what I wanna achieve is, that I can use the values of any temperature sensor in my HA to act as the 'current' temperature for my thermostats. By default the integrated dect 301 sensors are used (or external sensors from 'fritz' (like dect440) which are also predefined in the Fritzbox) 
But not all my thermostats have external sensors from avm fritz (the integrated are not a nice solutions since it's way hotter next to the radiators and setting an offset is not the best solution in my eyes)
 
Is there a way, that I can implement other sensors which are in my HA (i.e. aquara temp sensors or so) to act as the temperature sensor, which the thermostats can orientate itself on?

Or is this an issue of the climate entity itself and has to be done before even schedulung anything?

Help would be much appreciated!

Best regards
Jonas

**Comment by nielsfaber** [comment]
Scheduler only takes care of executing actions on predefined times.
It cannot help regulating your thermostat on an external sensor. 
I suggest you look elsewhere for a solution.
Perhaps you can use the generic thermostat integration (https://www.home-assistant.io/integrations/generic_thermostat/).
It can toggle an input_boolean that represents heating on/off. You will need to create an automation to link it to actions for your actual thermostat.

**Comment by Jaytie2k7** [comment]
> It cannot help regulating your thermostat on an external sensor.
That's what I expected. 
The solution with 'generic thermostat' came in my mind, too. I already created a switch template to switch the thermostate on/off which I could use with generic thermostat. But I'm not sure if this solution is really the way to go for me.
Maybe someday it is possible to force another attribute (from another sensor) directly to the climate.entity itself. This would be the best solution for me.

Nevertheless, thank you for you answer! I will still use you scheduler, since it is more flexible than the AVM one. (I can toggle between eco and comfort presets **plus** custom temperatures throughout the day)
Also, when I read that right, I can make an on/off toggle out of the schedules and quickly activate and deactivate specific schedules, which is nice, too.

**Comment by nielsfaber** [comment]
I assume your question is answered.
