### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Reynders1** [nielsfaber/scheduler-card#334]
Hi,

I just tried to install the scheduler-card. I did it both manually and through HACS. In both case, when I add it as a card, I receive the following message: "Could not connect with the scheduler component. It needs to be installed as integration before this card can be used."
Any clue what the problem might be?
Many thanks.
<img width="412" alt="Screenshot 2021-02-14 at 16 42 05" src="https://user-images.githubusercontent.com/44923513/107881210-a9c7b080-6ee3-11eb-8713-38515aa317a2.png">

**Comment by KTibow** [comment]
Please actually read what the error message says. You need to install nielsfaber/scheduler-component as well.

**Comment by Reynders1** [comment]
Indeed. I missed that step. Many thanks for your quick reply!

**Comment by KTibow** [comment]
Consider closing?

**Comment by Reynders1** [comment]
Yes please. It now works perfect.

Many thanks.

Christian Reynders

**Comment by KTibow** [comment]
You can do that for yourself.

**Comment by Reynders1** [comment]
Great support!
