### ISSUE TITLE
Weekend/Weekdays

### ISSUE THREAD

**Issue by RalphM77** [nielsfaber/scheduler-card#335]
Hey

I dont know if I am doing it wrong or if it is an issue ...
Scheduler works fine but:
When I hit e.g. Weekend and change some Temp just for the Weekend the numbers are also taken for die Weekday schedule ... I can not set different time slots and temperatures though...

Any hints?

Ralph

**Comment by KTibow** [comment]
> the numbers are also taken for die

What do you mean by that?
