### ISSUE TITLE
Feature request: allow filtering of schedules by weekdays for discovery

### ISSUE THREAD

**Issue by MPC7819** [nielsfaber/scheduler-card#337]
I'm tryng to use two cards to manage my AC.
One card for the weekdays and another for weekends.
So I forced to false de discovery mode, but when I creat the second card, and chose the entities, all the schedules of the first card appear, so it becomes a copy of the first card.

What I need to do to ensure two differents schedule cards?

Thanks

**Comment by KTibow** [comment]
Share exact config?

**Comment by MPC7819** [comment]
I'm using lovelace still with UI, not yaml.

type: 'custom:scheduler-card'
include:
  - climate
  - sensor.quarto3
  - sensor.rh3052_2
  - sensor.sensor_escritorio
  - sensor.sensor_jantar
  - sensor.sensor_quarto1
  - sensor.sensor_quarto2
  - sensor.sensor_sala
title: AC Fim de Semana
discover_existing: false

**Comment by MPC7819** [comment]
I,ve just copy the same yaml, (above) for another dashboard, this one in yaml mode and immediatly appear with the same entities and schedules of the other dashboard.

**Comment by nielsfaber** [comment]
You cannot split your schedules between cards based on workdays / weekend. You can only split by entities.

**Comment by MPC7819** [comment]
OK, clear, thanks

Any sugestion how can I make diferent schedules, weekend and workday for the same entities?

**Comment by nielsfaber** [comment]
> Any sugestion how can I make diferent schedules, weekend and workday for the same entities?

No, you could make a feature request for adding such filtering options to the card.
But it will take a while before I can add this.

**Comment by glenn20** [comment]
I may be missing something here, but I have separate weekday and weekend schedules for my heating. Using the scheduler card, I create and save a weekday schedule using "Make Scheme". Then I click "Add" to create a second schedule for the weekend using "Make Scheme". The two schemes are then show in the same Scheduler Card. I use "include: [climate.downstairs]" to limit that scheduler card instance to just show my heating schedules.

NOTE: This does not structly address the requirement of the OP (two separate scheduler cards), but seems to meet the requirements in the comment two above this.

**Comment by bikeymouse** [comment]
> > Any sugestion how can I make diferent schedules, weekend and workday for the same entities?
> 
> No, you could make a feature request for adding such filtering options to the card.
> But it will take a while before I can add this.
> For the time being, it's is not possible.

To make it more generic, the filter-option for the card could not only work on weekend/workdays but just work on any chosen boolean entity. That would make it very flexible/customizable.

Or what about filtering/indicating the schedules for which the conditions are evaluated to be "true"? 
That would mean you would only see the cards that are actually relevant.
