### ISSUE TITLE
Feature Request: Show schedule name in card

### ISSUE THREAD

**Issue by crazyfx1** [nielsfaber/scheduler-card#338]
I've created a schedule and set a name in the options. I expected to see the name in the schedule overview, but it didn't show up. Then I had to read the documentation to check what the name is supposed to do ;)

Imo the schedule name should be visible in the list of schedules.
![image](https://user-images.githubusercontent.com/9930385/109610838-99434700-7b2d-11eb-8f52-6ce4ad79d625.png)

![image](https://user-images.githubusercontent.com/9930385/109610855-a7916300-7b2d-11eb-9240-a4c26a355a4a.png)

**Comment by nielsfaber** [comment]
You can choose what properties show up in the overview, see: https://github.com/nielsfaber/scheduler-card#display-options
It is (and will stay) a matter of taste, everyone has different preferences on this.

**Comment by crazyfx1** [comment]
Ok thanks
