### ISSUE TITLE
Temperature value not applied 

### ISSUE THREAD

**Issue by mythfx** [nielsfaber/scheduler-card#339]
Hi,
I'm currently struggling with a thermostat where the temperature value set in the schedule card is not applied.
The mode (off, auto, heat) changes correctly.

Details:
HomeAssistant, Zigbee2MQTT, SchedulerCard and everything else is running on the latest version.
https://www.zigbee2mqtt.io/devices/GS361A-H04.html#siterwell-gs361a-h04
![image](https://user-images.githubusercontent.com/4218537/109688999-2960ab00-7b85-11eb-8176-c6da54fee723.png)

The log with a manual temperature change on the lovelace card:
![image](https://user-images.githubusercontent.com/4218537/109689937-1bf7f080-7b86-11eb-9e63-856917d412db.png)

The log with a change triggered by scheduled card:
![image](https://user-images.githubusercontent.com/4218537/109689227-5f9e2a80-7b85-11eb-8e85-7f93f7efecc8.png)

**Comment by nielsfaber** [comment]
Hi,
I cannot really help you on the zigbee side.
Most important/relevant information is whether the HA climate entity changes its state as you would expect.
The rest (mqtt traffic) should be handled by the mqtt component of HA together with zigbee2mqtt (this is out of my hands).
You could try to listen to the HA mqtt data to see if it sends the hvac_mode and setpoint as it should.

**Comment by mythfx** [comment]
Okay, got some more testing done today. I think it's a timing issue.
The thermostat receives both messages, but respondes to the first message (system_mode) with the old value of "current_heating_setpoint" and overwrites the new value in HA.

Is there any way to delay the command to set the temperature for a second or two?
