### ISSUE TITLE
"Zero" is not valid criteria in condition

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/scheduler-card#341]
![image](https://user-images.githubusercontent.com/15225823/110241814-93999700-7f5b-11eb-982a-cb7074ee4cd4.png)

Does not allow to save condition "Below 0", for temperature sensor, f.e..

**Comment by nielsfaber** [comment]
I need to check out what causes this, I don't remember adding such rule.
Btw: do you have your own hangar ?

**Comment by Masterz69** [comment]
English not may native. Probably wrong word used for :)
Looks like overhang is more suitable.
