### ISSUE TITLE
Feature Request: RTL support

### ISSUE THREAD

**Issue by yaccri** [nielsfaber/scheduler-card#342]
The time in Right to Left languages looks awkward. The hours are on the right side and the minutes on the left.
![image](https://user-images.githubusercontent.com/50799117/110248042-da958580-7f77-11eb-91e6-90f326a09faf.png)

Can you switch the sides of the hours and the minutes in RTL languages?

**Comment by nielsfaber** [comment]
That looks wrong in so many ways...
Could you maybe help with a list of things that need to be changed for this card to play nice with RTL languages?

**Comment by yaccri** [comment]
The most annoying is hours/minutes flip.
Other than that:
- The arrow direction at the top (between the device and the action) is pointing at the other way.
- Some text is in the local language, and other text appears in English. It would be nice to have all in the local language.
  This include: the 'days' part and the strings in the Options section.

**Comment by nielsfaber** [comment]
Thank you for your input.
I will try to improve these things in a next update.

As for:
> Some text is in the local language, and other text appears in English. It would be nice to have all in the local language.
This include: the 'days' part and the strings in the Options section.

You're invited to provide a translation for the card in your local language.
As a starting point you can take [the English file](https://github.com/nielsfaber/scheduler-card/blob/main/src/localize/languages/en.json), and translate all texts to your language.
If you submit the file (via pull request) as` <your-language>.json` the card will become translated to your language (for all users with your language).
Thanks in advance.

**Comment by yaccri** [comment]
That's great! thank you!
I'd like to test the translated json file before submitting. Is it possible?

**Comment by nielsfaber** [comment]
If you make a full checkout of this repository, you could.
With `npm i` all dependencies are locally installed.
With `npm start` the source files are watched for changes, as soon as you save file the scheduler-card is recompiled.
Note that you need to register the translation in localize.ts`.

For me it’s also OK if you just send in the initial file and test it when the next update is published. It’s OK if changes follow later on (happens all the time).

**Comment by yaccri** [comment]
Hi,

I translated the file to Hebrew and created a pull request.

The file name is 'he.json' because usually Hebrew is marked 'he'. 
However, sometimes 'heb' is used. I don't know what HA uses.

Thank you!

**Comment by yaccri** [comment]
hmmmm, I received a 'language_validate' error. 
I'm not sure what went wrong.
I edited the file with 'Notepad++' under windows,

Do you think that it's a code page error?

Here's the file that I submitted.
[he.zip](https://github.com/nielsfaber/scheduler-card/files/6136382/he.zip)

**Comment by nielsfaber** [comment]
Thank you for your contribution.
I saw 2 errors in your file, I added comments to your pull request.

> The file name is 'he.json' because usually Hebrew is marked 'he'.
However, sometimes 'heb' is used. I don't know what HA uses.

`he.json` is fine.
HA uses the [same](https://github.com/home-assistant/frontend/blob/dev/translations/frontend/he.json).

**Comment by yaccri** [comment]
Thank you!

**Comment by nielsfaber** [comment]
I’m sorry @yaccri, I don’t have much time currently to work on this.
I made release V2.1.0 which adds your Hebrew translation, you can test your work.
For the RTL support I need some more time (especially for the slider and the time scheme editor).

**Comment by yaccri** [comment]
Sorry for the delay. My system was down till now.
I updated the plugin and the Hebrew translation is OK.
However, without RTL support it looks odd. 

Thank you so much for this plugin. It's a very useful contribution.

**Comment by nielsfaber** [comment]
I'm afraid I have to break my pledge that I will pick this up, I am sorry for this.
I am noticing that adding support for RTL mode will take quite some changes, which I'm not eager to make. 
Also RTL is not in my nature, so I'm not sure which changes will be needed to make all look OK.
So far you seem to be the only user who has benefit from this, so this doesn't have any priority for me.
If you want this feature added, please consider to contribute it via PR.

**Comment by adizag** [comment]
Hi @nielsfaber 
He is not the only one, just we usually use English GUI because there are problems with some components fully supporting RTL... :)

Here is another example for the RTL problem, the scheme times are not in position, which makes it very difficult to use:
![image](https://user-images.githubusercontent.com/17390016/187381794-1abe94e5-f3c0-4a0f-945e-b0116cbf39ff.png)

If in any case you are going to deal with it sometime - that's another issue to be considered.

Tnx for your super amazing work here 👍 🥇
