### ISSUE TITLE
HASS complaining about lack of version key in manifest file.

### ISSUE THREAD

**Issue by derekoharrow** [nielsfaber/scheduler-card#344]
Every time HASS starts, I get this:

`2021-03-08 14:36:50 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'scheduler'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'scheduler'`

I'm currently using Scheduler v3.0.3.

Thanks

**Comment by KTibow** [comment]
Fix in https://github.com/nielsfaber/scheduler-component/pull/90. This is the third issue someone has opened about this.

**Comment by nielsfaber** [comment]
Should be fixed now.
