### ISSUE TITLE
Feature request: Hide "Addd Item" button

### ISSUE THREAD

**Issue by Cyr-ius** [nielsfaber/scheduler-card#346]
First of all thank you and great job for the Scheduler
A question: Is it possible to hide the "Add Item" button on card ?

**Comment by nielsfaber** [comment]
By removing that button you will become unable to change schedules.
This is kind of the whole purpose of this card.
Why would you want to do this?

**Comment by KTibow** [comment]
My guess is it's a kiosk tablet.

**Comment by nielsfaber** [comment]
In that case he could just log in as non-admin user in HA, it would have the desired effect.

**Comment by doctorjames** [comment]
I'd like to see this as well, probably via a YAML boolean option. I've started stacking individual scheduler cards under their related entity cards with the scheduler filtered via `include` to just show that entity. Once I've configured the scheduler card's schemes, I have no need to add any more to this dedicated card. The card would therefore look cleaner without the add button. In this case it's not about stopping other people interfering via non-admin accounts. Here's an example:

<img width="304" alt="Scheduler Screenshot" src="https://user-images.githubusercontent.com/317443/111873471-47514c80-8988-11eb-93d1-dad0ce5b6d94.png">

Conceptually the schedule's scheme then becomes part of the device, rather than thinking about a big set of schedules as a group applying to lots of entities. So here I would click on the schedule title to modify its scheme, and this is the place to go to disable the automated schedule if away from the house etc.

**Comment by KTibow** [comment]
Couldn't you use auto-entities with a custom secondary text or something like that?

**Comment by doctorjames** [comment]
Not as far as I know: as well as enabling/disabling a schedule, here I can click on these two schedule entries to modify their on/off times. Is there any other way to pop up the schedule editor?

Is looks like making the card inject a `display: none` CSS style would be enough to hide that `card-actions` bar?

**Comment by KTibow** [comment]
Yup, just
```
card_mod:
  style: |
    .card-actions {
      display: none;
    }
```

**Comment by doctorjames** [comment]
> Yup, just
> 
> ```
> card_mod:
>   style: |
>     .card-actions {
>       display: none;
>     }
> ```

Looks good on the normal view but sadly also kills off the 'Save', 'Delete' and 'Options' buttons when the card is in 'edit schedule' mode which defeats the whole point of using the scheduler card in this location. It would need some extra CSS classes included in the scheduler card component to discriminate what the card was currently displaying to make this solution work.

**Comment by KTibow** [comment]
Try also adding another one with `.summary + .card-actions` and make it `display: block;`.

**Comment by doctorjames** [comment]
> Try also adding another one with `.summary + .card-actions` and make it `display: block;`.

Unfortunately it's the `.card-content` that immediately precedes the `.card-actions` (`.summary` is within the `.card-content`)

**Comment by KTibow** [comment]
So `+` only works within the same parent element?

**Comment by doctorjames** [comment]
> So `+` only works within the same parent element?

Yes, unfortunately so. Here's a reasonable description of it: [Adjacent sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator)

There's also a [General sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator) but that also requires a common parent.

**Comment by nielsfaber** [comment]
I will give the button bar some unique css class in the next update, or even better, make it hideable through yaml config.
These hacks really hurt my eyes.

**Comment by doctorjames** [comment]
> I will give the button bar some unique css class in the next update, or even better, make it hideable through yaml config. These hacks really hurt my eyes.

Thanks Niels. 

It really is an impressively slick and polished component and is working beautifully.

**Comment by nielsfaber** [comment]
I added the `show_add_button` configuration option in release V2.1.0 for this.
You can set it to false to hide.

**Comment by doctorjames** [comment]
> I added the `show_add_button` configuration option in release V2.1.0 for this.
> You can set it to false to hide.

That works absolutely perfectly for my purposes. Thanks! 

For anyone else considering doing what I did (displaying entity specific schedules under other device related content): you can add another scheduler card elsewhere on some kind of admin page that includes schedules for all entities. By leaving the "add" button enabled there, you can easily add more schedules controlling the device.
