### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by alnavasa** [nielsfaber/scheduler-card#348]
I pues I might missed this in the documentation, I can't find it, 

The situation:
I can edit the program from my user,
I want another user who is not administrator to be able to edit the program, but I don't want to give them full administrator privilege.

**Comment by alnavasa** [comment]
Could we add a 


```
users_allowed:
  - admin
  - Paul
  - James


```

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/282
