### ISSUE TITLE
[Feature Request] Schedule Suggestions

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#35]
Something to add in the future would be looking at the history of entity states, and based on that, auto-generating schedule suggestions.

**Comment by nielsfaber** [comment]
Im sorry to say that such AI is out of scope for now.
Unless you want to program it yourself :)

**Comment by KTibow** [comment]
Wait, wait wait...
AI != analyzing history, like:
If the outside light historically gets turned on at 10PM every day and historically gets turned off at 10AM every day, suggest a schedule.
You can just see what happens most of the time.
