### ISSUE TITLE
Scheduled time if off after daylight saving change

### ISSUE THREAD

**Issue by oferbar** [nielsfaber/scheduler-card#354]
Hi,

I just noticed a problem after the daylight saving started in my region (Israel).
I restarted HA host and the service couple of times, still the same issue the next day.
The problem is visible in the UI when I create a scheduler scheme and set the time for example to 6 AM, it immediately changed to 5 AM (one hour back).

HA:
core-2021.3.4
supervisor-2021.03.6
Home Assistant OS 5.12

Scheduler
by @nielsfaber
Firmware: 3.0.4

Looks like it is now got fixed after 2 days from the time change, but was very much visible yesterday.

**Comment by nielsfaber** [comment]
Hello,
I am aware that scheduler does not automatically adjust for start/stop of daylight saving time.
What is new to me, is that you still have problems the day after.
I thought the problems would be solved by restarting HA once or disabling+enabling all schedules (causes the timers to be recalculated).
Tonight the DST starts in my country, so I will be able to observe the behaviour myself.

There are a couple of issues here:
- Timers are handled by the HA core (I only call a function with the desired moment in time where a schedule should trigger)
- There is no function in HA that I could call to detect a DST change (as far as I know)
- I don't know a way to reproduce/test the behaviour except for 2 tunes per year. I tried setting a docker container to a specific date but it failed.

I would like to solve this issue, but right now I don't see a way to do this.

**Comment by nielsfaber** [comment]
I did some investigation on this and [found](https://github.com/home-assistant/core/blob/938a4cc1b6fff2c118f379452e19d150805b8b54/homeassistant/util/dt.py#L320) a piece of code in HA that seems to handle DST changes.
I will prepare some test timers to trigger tomorrow morning, hopefully one of the cases will trigger on the correct time.
If so, I can make an update so next time this issue will not occur.

**Comment by lmagyar** [comment]
See https://github.com/nielsfaber/scheduler-component/issues/94
I think I've found a DST bug in scheduler-component!

**Comment by oferbar** [comment]
> Hello,
> I am aware that scheduler does not automatically adjust for start/stop of daylight saving time.
> What is new to me, is that you still have problems the day after.
> I thought the problems would be solved by restarting HA once or disabling+enabling all schedules (causes the timers to be recalculated).
> Tonight the DST starts in my country, so I will be able to observe the behaviour myself.
> 
> There are a couple of issues here:
> 
> * Timers are handled by the HA core (I only call a function with the desired moment in time where a schedule should trigger)
> * There is no function in HA that I could call to detect a DST change (as far as I know)
> * I don't know a way to reproduce/test the behaviour except for 2 tunes per year. I tried setting a docker container to a specific date but it failed.
> 
> I would like to solve this issue, but right now I don't see a way to do this.

Actually I think it missed only one day. I thought about it after posting the problem.

In Israel, DST switched on Friday March 26 at 2:00 AM. The problem with the scheduler was indeed noticed during Friday, but on Saturday it was gone and back to normal operation.

I saw that the bug in the code was already found, so great job! I really like this integration! 
Thank you
