### ISSUE TITLE
Feature request: scheduling for odd/even day/week-numbers

### ISSUE THREAD

**Issue by bikeymouse** [nielsfaber/scheduler-card#356]
Hi, I would really like to have the option to start a schedule on odd/even day-numbers of week-numbers.

I know this can be implemented with helper variables and conditions, but I would love to have this all in one place and with an easy UI.
So the picker would look like this:
![odd-even](https://user-images.githubusercontent.com/34967010/113418459-d36e6580-93c5-11eb-9160-3c8345ecffd9.png)

And for some inspiration for a user-friendly UI to create/edit a timers and to see the current setting I would encourage you to look how this is solved in Domoticz. As you can see it has all the options (x time before/after sunrise/sunset, randomness) to set, show and change the current scheme in one-overview screen.
Just a suggestion ;-)

![timer-editor](https://user-images.githubusercontent.com/34967010/113420523-c6537580-93c9-11eb-97e1-6fa37e47a58f.png)

**Comment by KTibow** [comment]
The scheduler shouldn't be a replacement for automations. It shouldn't get too complex; automations should be used for that.

**Comment by nielsfaber** [comment]
I'm afraid I agree with @KTibow on this.
I prefer to keep scheduler minimalistic, so I think the current functionality is sufficient.
Having the GUI become bloated with additional options would be killing the whole idea of the card, the fewer whistles&bells, the better.
I _might_ consider to extend the "conditions" section of the card at some point, to allow a certain window of dates to be set, but this is not a priority currently.
