### ISSUE TITLE
The card does not see any entities

### ISSUE THREAD

**Issue by cmarcant** [nielsfaber/scheduler-card#358]
I have installed scheduler-component and scheduler-card. I can open the scheduler card in lovalace, but it does not see any groups or entities. I did not have any issues with the installations, but when I restart home assistant I have the following messages in the logs:

2021-04-04 21:38:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-04 21:38:17 ERROR (MainThread) [homeassistant.setup] Setup failed for serial: No setup function defined.

**Comment by nielsfaber** [comment]
I think the card works fine, but you have to tell it which entities should show up.
You can do this either by editing the card settings in UI mode, or by adding `include` to the yaml code.
Most people choose to have their climate, cover and light entities showing up.

**Comment by cmarcant** [comment]
Thanks for you quik answer, it works! 
Is there a way to show all the entities? I tried with
 include:
 - "**"
 it looks to work

**Comment by nielsfaber** [comment]
`"*"` will work to show all entities.
You can also use `exclude` on top of it to hide some unwanted entities (some people prefer to keep the card clean).
It’s really up to your own preferences.
Please close the issue if it’s solved.

**Comment by cmarcant** [comment]
Thanks!
