### ISSUE TITLE
Card Configuration isn't reflecting changes real time

### ISSUE THREAD

**Issue by Misiu** [nielsfaber/scheduler-card#362]
When changing options (title in my case) the card isn't reflecting changes:
![scheduler_card](https://user-images.githubusercontent.com/1741838/114860776-b76abb00-9dec-11eb-808e-230dd2956adc.gif)

**Comment by nielsfaber** [comment]
It _used_ to work.
I will check what happened in the meantime.
Thanks for the trigger.

**Comment by Misiu** [comment]
I have scheduler-card: 2.0.5
home assistant: core-2021.4.4
I cleared cache a couple of times.
No logs in the console.
If there is something I can check please let me know.

**Comment by sym0nd0** [comment]
I've just installed this and am seeing the same behaviour.

**Comment by nielsfaber** [comment]
Should be fixed with the new V2.1.0 release. Let me know if there are still issues.

**Comment by Misiu** [comment]
I can confirm it works in 2.1.0.
Thank you ☺
