### ISSUE TITLE
Can't find scheduler component in HACS

### ISSUE THREAD

**Issue by ArlenCheng** [nielsfaber/scheduler-card#363]
![image](https://user-images.githubusercontent.com/35172094/115120243-1001aa00-9fdf-11eb-888a-515cd9466232.png)
scheduler card can be successful install but seem scheduler component cant be found in HACS

**Comment by nielsfaber** [comment]
It is listed under "integrations" (not "frontend")
![image](https://user-images.githubusercontent.com/16861605/115134683-91266480-a012-11eb-802d-23433995d107.png)
