### ISSUE TITLE
When creating multiple scheduler-card all schedules apears in all cards

### ISSUE THREAD

**Issue by pbranly** [nielsfaber/scheduler-card#364]
Hi
There was already the same
https://github.com/nielsfaber/scheduler-card/issues/300
with a solution but this does not work for me.
I would like to add 1 or 2 cards for my lamps and 3 cards for my covers.
I can create one but as soon as I add a new one, the entities of the existing card are added.
if I edit the lovelace.yaml as adviced 
-switch -----> - switch.entity_1 and - switch.entity_2, the switches deseapear .If I edit, -switch comes back for both cards and I have all the configured switches in both cards
Any solution ?
Regards
Phil

**Comment by KTibow** [comment]
> If I edit

What do you mean?

**Comment by nielsfaber** [comment]
You can configure which schedules are visible in which card via `include`.

**Comment by pbranly** [comment]
> > If I edit
> 
> What do you mean?

I made reference to this comment:
 «            include:
              - climate
Which occurs in 2 cards.
Change it to climate.entity_1 and climate.entity_2 and it should be fine.« 
I tried but it does not fix my issue

**Comment by nielsfaber** [comment]
We can only help you if you share your yaml configuration.

**Comment by pbranly** [comment]
> You can configure which schedules are visible in which card via `include`.

Sorry but I don’t understand what I have to do .
If I create 1  scheduled card with 2 switches for exemple, when I create a second one, i have the ones of the first card. If I remove one switch from one card, it is removed as well from the second one.
If I edit the Lovelace card with switch.entity_1 and switch.entity_2, the 2 switches are masked . And after confirmation, the name « switch » comes back without the .entity_x !
I surely make a mistake somewhere but I don’t know which one 
Thanks 
Philippe

**Comment by Didier-Fouen** [comment]
Hi, 
I have exactly the same problem and I am very interested about a solution.
Best regards 
Didier

**Comment by nielsfaber** [comment]
We can only help you if you share the yaml configuration of the cards.

**Comment by pbranly** [comment]
Hi
I just tried to add 2 cards:
objective of the test is to have one switch in one card and another switch in another.
Whatever configuration I try, i find the 2 switchs in each card.
if I remove one switch from one card, it is removed from the other
Lovelace part as follow:
      - type: 'custom:scheduler-card'
        include:
          - switch
        discover_existing: false
      - type: 'custom:scheduler-card'
        discover_existing: false
        include:
          - switch
     Regards
Philippe

**Comment by nielsfaber** [comment]
You shouldn't include the whole switch domain to both cards, it implies that you want to see all switches..
Try this.

Card 1:
```
- type: 'custom:scheduler-card'
  include:
    - switch.my_first_switch
```

Card 2:
```
- type: 'custom:scheduler-card'
  include:
    - switch.my_second_switch
```

**Comment by pbranly** [comment]
The issue is that if I don’t include the whole domain, I cannot add any entity ( grey on the right)



Envoyé depuis mon IPhone SE 2020

**Comment by pbranly** [comment]
So What dont I understand ?

**Comment by pbranly** [comment]
Understood !
Select off
Then click on the group
It opens a list 
Select the desired one .
wonderful !
Phil
