### ISSUE TITLE
Schedule entities unavailable on v 2021.4.5

### ISSUE THREAD

**Issue by kaizersoje** [nielsfaber/scheduler-card#365]
After upgrading to Hassio version 2021.4.5, all of the schedules that I had set up are showing up as unavailable.

![Screenshot](https://user-images.githubusercontent.com/54566217/115363098-81bb3d00-a205-11eb-9ffe-872e2aa78bf6.png)

I have neither changed the scheduler component or card.

**Comment by nielsfaber** [comment]
They show up as restored, so likely the scheduler component is not running.
Can you check under integrations if it’s still there?

**Comment by kaizersoje** [comment]
Yes, it is still there.

**Comment by nielsfaber** [comment]
Ok. Could you check the contents of the “scheduler.storage” file in the “.storage” folder in your HA config dir?
Are your schedules still there?

**Comment by kaizersoje** [comment]
I can't find any such file.

**Comment by nielsfaber** [comment]
Then I’m afraid your schedules are wiped (somehow).
Or you must be running at a version of scheduler from last year or something.

**Comment by kaizersoje** [comment]
I have got version 3.0.4 installed. I actually just set up the integration only last month.

**Comment by nielsfaber** [comment]
In that case the schedules got wiped by the update.
Never heard of it before I must say, also I haven’t updated anything recently.
Could you check the logs for a clue of what went wrong?
if you create a schedule with the card, you probably will see a scheduler.storage file appearing again. But with only a single item probably.

**Comment by kaizersoje** [comment]
I have looked at previous old backups as well. I just cannot see the "scheduler.storage" file in the .storage folder in those backups. Yet, it was working before.

**Comment by nielsfaber** [comment]
That seems very odd to me, because this file is needed by scheduler to recover previous items after restarting HA.
Just to double check, you do see this folder:
![image](https://user-images.githubusercontent.com/16861605/115388915-c41c5400-a1dc-11eb-96ee-fdff78dbfc5b.png)

But you don't see this file:
![image](https://user-images.githubusercontent.com/16861605/115388951-cd0d2580-a1dc-11eb-8480-6cbb268a6f6a.png)

And it cannot be that some extensions are made invisible for you by your OS or something?

**Comment by kaizersoje** [comment]
This is what I see in the .storage folder. No scheduler.storage file. As I said previously, I cannot see the file in 2 of the oldest backups.

![Screenshot1](https://user-images.githubusercontent.com/54566217/115390708-e5ebfa00-a221-11eb-903b-8d217c575ac0.png)

**Comment by nielsfaber** [comment]
Please try to create a new schedule, I hope the file will appear.
Unfortunately I have no idea what went wrong, can also not guarantee that this will not occur in a future update.

**Comment by kaizersoje** [comment]
So I will have to set up all my schedules from scratch again??

**Comment by kaizersoje** [comment]
I created one schedule and I can see the scheduler.storage file. So looks like I have to set it all up from scratch.

**Comment by nielsfaber** [comment]
I’m afraid so. 
I have never seen such issue before, I understand it is very annoying.
Please keep an eye on this file for a while, make sure to include it in your backups (it will be part of a standard snapshot).
Unless more issues follow, I will consider  this as an incident.

**Comment by kaizersoje** [comment]
Up to avoid stale.

**Comment by kaizersoje** [comment]
Hi, I just noticed the `scheduler.storage` file just disappeared without me doing anything, I had to go and copy the `scheduler.storage` file from the last backup. Any reason why this happens?

**Comment by nielsfaber** [comment]
It only seems to happen in your setup.
Never heard of such issue from anyone else.
I have no clue how to help you.
