### ISSUE TITLE
Ability to set max and min temperatures in heat_cool mode [Feature request]

### ISSUE THREAD

**Issue by liquidbear99** [nielsfaber/scheduler-card#370]
Currently I can set a target temp for cool and heat modes but I can't set max/min temps for heat_cool modes.

Also

This is an amazing integration and props to the devs making it happen. I hope to see this feature added soon so I can use it

**Comment by KTibow** [comment]
I think you can manually add services.

**Comment by nielsfaber** [comment]
Done 🙂 
It should automatically appear if you update the scheduler-card to the latest release.

**Comment by liquidbear99** [comment]
It did! Thanks so much!
