### ISSUE TITLE
Allow custom temperature entity for reading temperature [Feature Request]

### ISSUE THREAD

**Issue by liquidbear99** [nielsfaber/scheduler-card#371]
My thermostat's built in thermometer is very faulty. I have a sensor in the living room that picks up temperature values. I would love the ability to customize which temp sensor the thermostat uses to see if it has reached the desired temp.

Thanks so much for considering this addition.

**Comment by nielsfaber** [comment]
Scheduler only sends the setpoint for the thermostat.
For controlling the temperature based on a sensor you need something like [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/).
I cannot help you with this.
