### ISSUE TITLE
Friday 30.4.2021 is not working day

### ISSUE THREAD

**Issue by panenka** [nielsfaber/scheduler-card#372]
Current version has bug. For example, Friday 30.4.2021 is not working days and scheduled actions are not not tomorrow but at Monday 3.5.2021.

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/scheduler-component/issues/86
Actually this should be solved by updating scheduler-component to the newest version.

**Comment by panenka** [comment]
I have been updated this component a few minutes before I have been found this bug. There is no newer version now.
