### ISSUE TITLE
Entity can not be selected if only 1 entity type is configured

### ISSUE THREAD

**Issue by bikeymouse** [nielsfaber/scheduler-card#373]
I think I found a bug. If I create a Schedule-card and in the settings "included items" just select to show only 1 entity type (e.g. lights), then when trying to create a new schedule, the entities (e.g. all the light entities) are shown in the first step, but it is not possible to actually select them. 

<img width="553" alt="configuration" src="https://user-images.githubusercontent.com/34967010/116669607-16a8fd80-a99f-11eb-8b70-b9b7aeda705a.png">

Once another entity type is added in the included items list, everything works as expected again.

**Comment by nielsfaber** [comment]
Thanks for spotting this, I see it happening too. 
I will try to fix it soon.

**Comment by nielsfaber** [comment]
The issue should be fixed by updating to v2.1.1.
Let me know if you still experience issues, else you can close the issue.

**Comment by bikeymouse** [comment]
Yep, that is fixed now thanks!
