### ISSUE TITLE
Action "cool" shows up as "heat", cannot create schedule if card only has 1 group

### ISSUE THREAD

**Issue by NIghtHawkATL** [nielsfaber/scheduler-card#376]
I have been using the scheduler card and integration for a few weeks and really liked it. I updated to the new version and my schedules were all messed up. I tried to edit them and it would't save. I removed the schedules and tried to add them back one at a time and they wouldn't get past selecting the group and then the entity. I was never given the next button to continue. I have now removed the integration and card and hope to regain the ability to use them again.

First thing I noticed about there being an issue was that when creating a new schedule, going straight from the standard name to the custom name, it breaks the code and just gives me a red bar. I have to click from standard to hidden to custom.

After uninstalling everything and then reinstalling in the correct order and rebooting after each uninstall/reinstall, the card no longer connects to the scheduler integration.

**Comment by NIghtHawkATL** [comment]
After further review and having to restore from a snapshot to get functionality back, i see that you HAVE to select multiple groups to be able to move further in setting up the card.

After do ing that and building a schedule just for 1 of my thermostats for cooling only, the schedule still auto-names itself to heat.
![Screen Shot 2021-04-30 at 10 33 46 AM](https://user-images.githubusercontent.com/8395658/116710363-ac448d00-a99f-11eb-9d99-13138dd7e7b6.png)
![Screen Shot 2021-04-30 at 10 33 57 AM](https://user-images.githubusercontent.com/8395658/116710370-aea6e700-a99f-11eb-94f7-7a93180803a6.png)

**Comment by nielsfaber** [comment]
> I have been using the scheduler card and integration for a few weeks and really liked it. 

Good! I hope we can get back to that situation 😉 

> I updated to the new version and my schedules were all messed up. I tried to edit them and it would't save.

This is strange, haven't heard it before.
Why wouldn't it save? Your changes are ignored, or clicking save didn't do anything?

> I removed the schedules and tried to add them back one at a time and they wouldn't get past selecting the group and then the entity. I was never given the next button to continue. I have now removed the integration and card and hope to regain the ability to use them again.

This problem seems related to your own discovery:

> After further review and having to restore from a snapshot to get functionality back, i see that you HAVE to select multiple groups to be able to move further in setting up the card.

I managed to reproduce this issue (I didn't discover it while testing).
Thanks for pointing to this, i will work on a fix for it.

> After do ing that and building a schedule just for 1 of my thermostats for cooling only, the schedule still auto-names itself to heat.

Another totally different issue.
Also this I didn't catch myself, but I see it happening here as well. I will let you know when I fixed this.

Sorry about the inconveniences.
There were quite some changes (under the hood) involved in this release, more than usual.

**Comment by NIghtHawkATL** [comment]
Thanks for looking into this! Sorry for the heated initial post. I was just worried that I would have to spend a lot of time recreating the schedules and it turned out to be a bit easier than initially thought. I apologize. I think that because I only had one group selected for my old schedules and the big found with having to select at least two to continue, also meant that the schedule only having one group wouldn’t allow for the save to take. I guess when you add the feature to allow for multiple variables (changing variable to variables) was set as a decimate feather than being an option.

Thanks for looking into this and I look forward to the update and seeing the fix!

**Comment by nielsfaber** [comment]
The scheduler-card works on top of the scheduler-component.
So no matter how messed up the card is, your schedules stay in your system and they will still work as they did before.
If you're afraid of losing data, look for the file `scheduler.storage` in the `.storage` folder of your HA config folder. 
That file holds all schedule data, so if you keep a copy you will always be able to restore them.

> I apologize. 

No need for that. 
I understand that people rely on the stability of this project for their homes and the frustration that comes with breaking changes.
On the other hand I do not have the ability to test all scenarios with each change I make, so the bug reports are unavoidable.
Best I can do is fix them fast 👍

**Comment by NIghtHawkATL** [comment]
My primary computer is a Mac and I had not enabled the option to view hidden (.) files so I have enabled this so that I can find it next time.

Thanks for the assistance and let me know when I can test again.

**Comment by nielsfaber** [comment]
Both issues should be fixed by updating to v2.1.1.
Let me know if you still experience issues, else you can close the issue.

**Comment by NIghtHawkATL** [comment]
I was able to confirm by adding a new card that the issue of not being able to select just 1 group has been fixed. I was also able to go from “hidden” to “custom” for the card name. Lastly, the names of the schedules are showing correctly on the completed card.

thanks for the quick turnaround!
