### ISSUE TITLE
Vacation mode scheduler [Feature request]

### ISSUE THREAD

**Issue by liquidbear99** [nielsfaber/scheduler-card#384]
I would love to have the ability to have a custom schedule for most days and then an additional schedule for vacation. One way that I was thinking this could be implemented is basically this:

1) Create multiple schedule cards
2) Create a switch entity to turn each individual schedule on or off
3) The user could then make custom automations to turn the switches on or off allowing one schedule to be active over another (such as with a vacation mode activating when they leave town)

Let me know if there is a better way to implement this or if this functionality exists in some way already in this integration and card. I love this integration/card and really appreciate the work that you are putting into this.

**Comment by nielsfaber** [comment]
There is an ongoing discussion related to assigning “tags” to schedules:
https://github.com/nielsfaber/scheduler-card/issues/353

You will be able to assign a tag “holiday” and have these all show up under one scheduler-card. Also you will be able to turn them on/off together.

Maybe it’s better to call them “sets” actually.
It seems to cover pretty much what you are looking for, what do you think?

**Comment by liquidbear99** [comment]
Yes, I think this would be great and accomplish the same thing
