### ISSUE TITLE
2.1.1: Not able to set a preset or heating temperature when picking more than one entity to control

### ISSUE THREAD

**Issue by Jaytie2k7** [nielsfaber/scheduler-card#386]
Hi!

I have many different schedules for my thermostats. 

Since upgrading to version 2.1.0/2.1.1 I'm not able to set a preset or heating value anymore, if I pick more than one entity unter the 'climate' group. (see screenshots)

![scheduler_problem_1](https://user-images.githubusercontent.com/63009998/117444228-75d7b680-af39-11eb-9810-bf37433ec48b.jpg)
![scheduler_problem_2](https://user-images.githubusercontent.com/63009998/117444278-8b4ce080-af39-11eb-8120-998492e3625c.jpg)

Reverting back to version 2.0.5 brings back the functionality.

![scheduler_problem_4](https://user-images.githubusercontent.com/63009998/117444390-b2a3ad80-af39-11eb-8303-2b34bb438370.jpg)

Am I doing something wrong? 
I'm not quite sure about this yet, but I also think, that under 2.1.1 the scheduler doesn't always work as programmed. 
Just had some wrong adjusted thermostats the past few days.

Greetings
Jaytie

**Comment by nielsfaber** [comment]
This should be fixed by updating to v2.1.2
