### ISSUE TITLE
Customize configuration - Multiple actions won't work anymore

### ISSUE THREAD

**Issue by z4rn0x** [nielsfaber/scheduler-card#389]
Hello
I have a customized configuration for my thermostat mode schedule, and it worked fine for many months but suddenly it's doing weird things...
1- I had to remove "standard_configuration: false" from the yaml because I can't get access to anything whit that:
![image](https://user-images.githubusercontent.com/34210703/117545811-661da800-aff5-11eb-8ff1-8aab702a11a2.png)
2- I had 3 actions, but the scheduler will take only the last one in consideration:
`type: 'custom:scheduler-card'
discover_existing: false
include:
  - climate.study_mqtt
time_step: 5
display_options:
  primary_info:
    - '{entity}:'
  secondary_info:
    - '{action} mode {relative-time}'
customize:
  climate.study_mqtt:
    name: Thermostat
    icon: home-thermometer-outline
    actions:
      - service: climate.set_preset_mode
        name: Comfort
        icon: 'mdi:home-thermometer-outline'
        service_data:
          preset_mode: none
      - service: climate.set_preset_mode
        name: Eco
        icon: 'mdi:leaf'
        service_data:
          preset_mode: Eco
      - service: climate.set_preset_mode
        name: 'Off'
        icon: 'mdi:power'
        service_data:
          preset_mode: 'Off'`
![image](https://user-images.githubusercontent.com/34210703/117545877-a67d2600-aff5-11eb-909b-e44878c114ca.png)

I tried to reinstall the previous versions, but same result, even after emptying the cache.

Is something wrong with my HA or with the scheduler?

**Comment by z4rn0x** [comment]
![image](https://user-images.githubusercontent.com/34210703/117547497-e516de80-affd-11eb-842d-e91fe7ac61de.png)

**Comment by nielsfaber** [comment]
I am seeing the same problem.
Will investigate what’s going on, it should be fixable.

**Comment by nielsfaber** [comment]
I released a new version of the scheduler card today which contains some improvements related to this.
Could you update to v2.1.3 and test it?
Let me know if you still experience problems, else you can close the issue.

**Comment by z4rn0x** [comment]
You did it! Problem fixed, thank you very much!
