### ISSUE TITLE
Group only shows turn off

### ISSUE THREAD

**Issue by LeonPro12** [nielsfaber/scheduler-card#391]
Hi,
When I add a group, I can only turn it off in the scheduler.

**Comment by nielsfaber** [comment]
The card looks in the group which entities it has and determines which actions all entities have in common.
Could you share which entities are under the group?

**Comment by LeonPro12** [comment]
Only lights.

**Comment by nielsfaber** [comment]
I could reproduce your problem, it should be fixed by updating the card to the latest version.
Let me know if you still experience problems, else you can close the issue.
