### ISSUE TITLE
Condition based on Sun state

### ISSUE THREAD

**Issue by b4dpxl** [nielsfaber/scheduler-card#396]
Hi. Really liking this integration so far, definitely fills a gap in HA in my opinion. But there's one thing I can't seem to work out. I currently have an automation which turns on my outside lights in the morning at 7am, if it's before sunrise.  I've added the following to my card:

```
customize:
  sun.sun:
    states:
      - above_horizon
      - below_horizon
```

But the sun doesn't appear as an option. Is this configuration wrong? I also have a template sensor, `sun_state`, which has the states "Up" and "Down", which does appear in the list. However, the card shows the 0-255 slider, and the option to choose "above" or "below"; I can't pick the states I've specified. 

```
  sensor.sun_state:
    states:
      - Up
      - Down
```

Thanks

**Comment by nielsfaber** [comment]
I think you use it right, but there is a problem in the card.
I will look into:
- why you get a slider with the template sensor (should show on/off as options)
- Why you cannot manually define states
- Integration of sun states so it will be there for everyone

**Comment by b4dpxl** [comment]
Thanks @nielsfaber

**Comment by nielsfaber** [comment]
The three items mentioned above should all be fixed by updating the card to the latest version.
Let me know if you still experience problems, else you can close the issue.

**Comment by b4dpxl** [comment]
Looks good, thanks 👍
