### ISSUE TITLE
Scheduler Card does not start - Logs in Supervisor Corse

### ISSUE THREAD

**Issue by Baggerfahrer** [nielsfaber/scheduler-card#398]
Hi,

my Scheduler Card does not start, resulting in the issue, that i do not have a menu on the left hand side of the Hassio Menu.
I can see the following errors in Supervisor Core log:

`2021-05-12 06:21:06 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Scheduler for scheduler
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/scheduler/__init__.py", line 42, in async_setup_entry
    coordinator = SchedulerCoordinator(hass, session, entry, store)
  File "/config/custom_components/scheduler/__init__.py", line 169, in __init__
    handle_startup()
TypeError: handle_startup() missing 1 required positional argument: '_event'
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.`

I have the following versions:
- Scheduler Card: 2.1.2
- Scheduler Component: 3.1.1

Any ideas concerning this issue?
Many thanks!

Tobi

**Comment by elkarto** [comment]
I was having the same issue.

It is already answered in this thread: https://github.com/nielsfaber/scheduler-component/issues/107

Everything is working after the change.

**Comment by nielsfaber** [comment]
This should be fixed by updating scheduler-component to latest version
