### ISSUE TITLE
Where is a difference between "everyday" and "week days"?

### ISSUE THREAD

**Issue by shevu** [nielsfaber/scheduler-card#40]
My first thing was that there is wrong name "week days". Maybe it should be "work days?

**Comment by nielsfaber** [comment]
Not really no.
See https://en.wikipedia.org/wiki/Workweek_and_weekend
_"A weekday or workday is any day of the working week"_
I don't mind changing weekdays to workdays if that makes things more clear, but in my country it is pretty common.

**Comment by shevu** [comment]
Ok. So maybe it could be better to change it in translation file for my national language (polish). Now it doesn't have sense :)
