### ISSUE TITLE
Lit2

### ISSUE THREAD

**Issue by Misiu** [nielsfaber/scheduler-card#406]
The frontend is migrating to LIt2 - https://github.com/home-assistant/frontend/pull/9199.
Just want to let you know there might be some changes

**Comment by nielsfaber** [comment]
Thanks for the heads-up.  
I will update my docker to the next beta and see what happens 🙂 
It seems pretty harmless so far.

I will post a follow up here once I checked this.

**Comment by Misiu** [comment]
@nielsfaber there is a blog post describing what changed: https://developers.home-assistant.io/blog/2021/05/19/lit-2.0

**Comment by nielsfaber** [comment]
Migration is now complete: https://github.com/nielsfaber/scheduler-card/commit/c31eac4dd11961e18ed59223c8cced12cd2071c9
Thanks again for the trigger 👍
