### ISSUE TITLE
Simple thermostat : Even Better with Scheduler Component !

### ISSUE THREAD

**Issue by dadge** [nielsfaber/scheduler-card#409]
Hi !

I just wanted to thank you for your good work ! and also tell you that I mention your project in my climate implementation, because your preset mode management fit perfectly with my needs : 

https://github.com/dadge/simple_thermostat

1. I hope it's not problem for you
2. Don't hesitate to mention my component if you find it useful ;)

Cheers !

**Comment by nielsfaber** [comment]
Sorry for the late response.
Ofcourse you're free to combine scheduler with your custom component 👍 

I couldn't find an appropriate place in the documentation of scheduler to refer to your project, sorry for that.
There is not really a section specific to usage in combination with climate entities.
Scheduler is intented to play nice with (almost) all entity types.
If you would like to promote your project, I suggest to create a page in the "share your projects" section in the HA forums ([link](https://community.home-assistant.io/c/projects/9)).

Let me know if you encounter any problems regarding integration with scheduler.
