### ISSUE TITLE
Show schedule's name in Schedule Card

### ISSUE THREAD

**Issue by eode** [nielsfaber/scheduler-card#410]
The only identifying information for any given schedule is the next event -- and the order, if you happen to know it.

So, for example, I have a lot of schedules that say

"Pump: turn off"
"Pump: turn off"

..but no way to distinguish them other than clicking on them to edit them, and then looking at their schedules, or clicking again to look at the name in options.  It would be nice if the card had the name that has been assigned to the schedule.

**Comment by eode** [comment]
Edit: For example, rather than:

Pump: Turn Off
in 6 hours
Pump: Turn Off
in 6 hours

..it instead said:
Pump Default Schedule
Pump: turn off in six hours
Pump Manual Override
Pump: turn off in six hours

..for schedules named "Pump Default Schedule" and "Pump Manual Override".

Identifying the schedule you're looking at by the next action it will take is awkward.

**Comment by nielsfaber** [comment]
You can choose how the list is displayed, see https://github.com/nielsfaber/scheduler-card#display-options
