### ISSUE TITLE
Feature request: Set state when condition is changed

### ISSUE THREAD

**Issue by wormiedk** [nielsfaber/scheduler-card#413]
Hi

I use scheduler card to control the heating of my home in intervals. E.g. 18 degrees during the night and 23 degrees during the day. I use a condition on a group containing all persons in my home to only increase the temperature to 23 degrees if someone is home. It  would be great if scheduler-card could detect when the allperson group changes state and apply the new temperature.

As an alternative it would be great to be able to call a service to update the value to the current interval value

**Comment by nielsfaber** [comment]
Scheduler is meant to trigger on time only, not on entity states.

**Comment by wormiedk** [comment]
Fair enough but would you concider exposing a service to "reset" back to schedule similar to what the script does if an unvailable device becomes available?

**Comment by nielsfaber** [comment]
There is a run_actions service which can be used to re-trigger the schedule.
