### ISSUE TITLE
multiple items show indistinct descriptions

### ISSUE THREAD

**Issue by felix63** [nielsfaber/scheduler-card#414]
Love your scheduler, it was really the missing feature for me. I made a scheduler card for my radiators. As I use them to switch on pairs of radiators I get multiple very similar descriptions like '2x climate: Set temperature to 20.5º C'. This makes it impossible to discern which radiators are being switched. Could there be an option to show the 'Name' of the schedule as it can be set in option page as a title?

![Schermafbeelding 2021-05-27 om 14 12 18](https://user-images.githubusercontent.com/16501940/119824195-ee58e400-bef5-11eb-8d55-d4832a394a40.png)

**Comment by nielsfaber** [comment]
You can choose which properties show up in the overview. See here:
https://github.com/nielsfaber/scheduler-card#display-options

**Comment by felix63** [comment]
Did I mention that I was a noob? Thanks for your reply to my question. RTFM - once more. But my respect for the power of HA and your integration grows ;-)
