### ISSUE TITLE
Names not showing up in Set up panel

### ISSUE THREAD

**Issue by menocode** [nielsfaber/scheduler-card#418]
When I set up a schedule in the Lovelace card and add a name of the card. The name does not show up in title of the card (see attached - example "Vacation). If I set up a new toggle for the entity the name is shown in the Lovelace toggle (see attached screen). Is it designed to only show up with the name in a new entity or is something wrong. 
[Screenshot 2021-05-31 23.10.44.pdf](https://github.com/nielsfaber/scheduler-card/files/6572105/Screenshot.2021-05-31.23.10.44.pdf)
[Screenshot 2021-05-31 23.09.20.pdf](https://github.com/nielsfaber/scheduler-card/files/6572106/Screenshot.2021-05-31.23.09.20.pdf)

**Comment by nielsfaber** [comment]
I don't understand what you mean.
Can you explain the problem more clearly?

Are you talking about the title of the card, or name of a schedule?

> If I set up a new toggle for the entity the name is shown in the Lovelace toggle...

What do you mean?

In your screenshot I see "Vacation" for a schedule, so name is shown?

**Comment by menocode** [comment]
Hi 

Sorry, hope this is clearer. 

I circled the same schedule on both sides of the screen. The left screen is where I create the schedule and the right is if I add it to Lovelace via the entity interface. 

I assign the specific schedule a name, and that name shows up properly on the right side. The name I assigned does not show up on the left side. 

[Screenshot 2021-06-12 21.51.45.pdf](https://github.com/nielsfaber/scheduler-card/files/6642791/Screenshot.2021-06-12.21.51.45.pdf)
[Screenshot 2021-06-12 21.54.05.pdf](https://github.com/nielsfaber/scheduler-card/files/6642792/Screenshot.2021-06-12.21.54.05.pdf)

**Comment by nielsfaber** [comment]
Did you configure display_options for the card?

**Comment by menocode** [comment]
I set it a up a while ago. I believe that I set up all the schedule using the visual editor in Lovelace. I did not make changes in the YAML files.

**Comment by nielsfaber** [comment]
By default, the card shows entity/entities + action on the first line.
If you want to show the name instead, you can set display_options.
Please read here: https://github.com/nielsfaber/scheduler-card#display-options

**Comment by menocode** [comment]
Ok. Got it. do I add this in the service.yaml file or configuration.yaml?

**Comment by nielsfaber** [comment]
You need to go to the Lovelace page that has the scheduler-card and then go to edit mode and edit the scheduler-card (which you also used to define which entities can be controlled from the card).
There you have the option to change the YAML code of the card and provide display_options.

**Comment by menocode** [comment]
Great. I have that working now. Thanks!
