### ISSUE TITLE
Wrong start value for input_value percentage

### ISSUE THREAD

**Issue by MacHoel** [nielsfaber/scheduler-card#419]
If an input_value representing a percentage starts at non 0 value (e.g. 50%), then the scheduler interface (in lovelace card) starts at 0 nonetheless, and the value applied is not the desired one.

**Comment by nielsfaber** [comment]
I have no idea what you mean.
What is input_value anyway?
Are you talking about a condition you're trying to configure?
Perhaps you can share some pictures of the problem.

**Comment by nielsfaber** [comment]
Closed due to no response from OP.
