### ISSUE TITLE
How can saparate a scheduler task in differents scheduler-car?

### ISSUE THREAD

**Issue by anarro** [nielsfaber/scheduler-card#42]
Hello again!

How can I show different tasks on different scheduler-cards?

Is it possible to add different programming cards in the same lovelace menu but with different tasks ?, and / or add different programming cards with different programming tasks, different panels?

Example: I have two children and I would like to show the different schedules in each panel.

<img width="1005" alt="Captura de pantalla 2020-09-15 a las 22 35 50" src="https://user-images.githubusercontent.com/8436433/93262139-02174c80-f7a4-11ea-9819-4a02a43c7577.png">

**Comment by KTibow** [comment]
By using `discoverExisting` and manually configuring.

**Comment by anarro** [comment]
> By using `discoverExisting` and manually configuring.

How?

I try with this:
<img width="1004" alt="Captura de pantalla 2020-09-16 a las 0 04 49" src="https://user-images.githubusercontent.com/8436433/93269914-47da1200-f7b0-11ea-9d6d-11f01e14c2fe.png">

**Comment by KTibow** [comment]
Mind reading the docs thoroughly?
BTW this repo isn't for support, it's for bugs. Try asking your question in the forum thread.

**Comment by anarro** [comment]
Yes, I'm sorry.
