### ISSUE TITLE
strange second trigger

### ISSUE THREAD

**Issue by bram2202** [nielsfaber/scheduler-card#420]
i'm using the scheduler to trigger my robot vacuum to start 3 times a week, on a fixed time.
Tuesday - Thursday - Saturday on 10:30, set via the card.
And it works great!!
But from the start i have some weird behavior, the vacuum start again at exactly 20:30 on the days i have set for the morning cleaning.
And this is the only scheduler i use.
The vacuum itself has no scheduler, and if so i have never set it to start on 20:30.

I had enabled the logs for the component, and logged:

On start
```
021-06-03 10:07:14 DEBUG (MainThread) [custom_components.scheduler.timer] Calculating timer for 8fb07b
2021-06-03 10:07:14 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 8fb07b set for 2021-06-03 10:30:00+02:00
```

On trigger time
```
2021-06-03 10:30:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer 8fb07b has reached slot 0
2021-06-03 10:30:00 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 8fb07b is triggered, proceed with actions
2021-06-03 10:30:00 DEBUG (MainThread) [custom_components.scheduler.actions] [8fb07b]: Executing service vacuum.start on entity vacuum.valetudo_robot
2021-06-03 10:30:00 DEBUG (MainThread) [custom_components.scheduler.timer] Calculating timer for 8fb07b
2021-06-03 10:30:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 8fb07b set for 2021-06-05 10:30:00+02:00
```

But nothing in the logs for the seccond trigger???

<br/>

| Soft/Firmware  | Version  |   
|---:|---:|
| HomeAssistant | 2021.5.5  |  
| Scheduler-card |   3.1.3 |  
| Scheduler-intergration | 2.1.3   |   
| Vacuum  | Xiaomi mi Robot Mop |   
| Valetudo | 2021.05.0 |

**Comment by nielsfaber** [comment]
The debug logs you share pretty much indicate that it’s not scheduler who triggers this.
Why do you suspect it still?

**Comment by nielsfaber** [comment]
https://github.com/nielsfaber/scheduler-component/blob/931a3f0d09427f9ed9a37c5f33d4fe6f34e328a0/custom_components/scheduler/actions.py#L272

Here you can see that scheduler logs “executing service …” every time a job is performed.
If these logs don’t show up at 20:30 I think you should start looking in other places.

**Comment by bram2202** [comment]
Ah i see.
I did still suspect it because i had no such troubles before using the scheduler.

**Comment by bram2202** [comment]
Oke, so i disabled the schedule for a day, at the point it would start it didn't, which is good.
but at 20:30 is started again, on its won. I checked the logs and found this:
```
2021-06-08 20:30:31 DEBUG (MainThread) [custom_components.scheduler.timer] Calculating timer for 8fb07b
2021-06-08 20:30:31 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 8fb07b set for 2021-06-10 10:30:00+02:00
```
Why is this `Calculating` triggered at this time, and could this execute the task accidentally?

**Comment by nielsfaber** [comment]
Could you check the `.storage` folder and look for `scheduler.storage`?
I'd like to see the entry for `8fb07b`. 

Otherwise its a bit like this for me:
![image](https://user-images.githubusercontent.com/16861605/121349017-56adb980-c929-11eb-9a01-785a07db3d46.png)

**Comment by bram2202** [comment]
The entry 
```
            {
                "schedule_id": "8fb07b",
                "timeslots": [
                    {
                        "start": "10:30:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "vacuum.start",
                                "entity_id": "vacuum.valetudo_robot",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "tue",
                    "thu",
                    "sat"
                ],
                "repeat_type": "pause",
                "name": "",
                "enabled": true
            }
```

**Comment by nielsfaber** [comment]
OK that looks pretty straight-forward.
So if I understand correctly, the timer was disabled (`enabled: false`) and at 20:30 it enabled itself AND executed the action?
Anything special about that 20:30 moment? Did do restart HA at that time by chance?

The problem seems very odd to me, never heard of something like this.

**Comment by bram2202** [comment]
oh sorry, no i enabled the task later that evening.
it was off at the time of trigger.

No nothing happen round that time, i was out for a walk and return to a busy vacuum.
I find it very strange too, and i cant explain it. the only thing i know is that it started after i started using the scheduler to control the vacuum's schedule. :man_shrugging:

**Comment by bram2202** [comment]
I added a extra trigger to send a notification at the same time, and it triggered only at 10:30, nothing in the evening.
And i still can find anything in the logs, with this i think the origin of the error resides at the vacuum side and not the scheduler like you suggested in the first comment.

**Comment by nielsfaber** [comment]
OK.
That would be a relief because I am a bit clueless on where to start looking.
Triggering a notification is a good idea, perhaps you could even mock a 'fake' generic vacuum (MQTT?) and trigger it simultaneously with your actual vacuum.
Keep me posted if you have more info on this.
