### ISSUE TITLE
Scheduler name not shown

### ISSUE THREAD

**Issue by vlumikero** [nielsfaber/scheduler-card#422]
The name of a specific schedule (selectable under options), is not shown after it's been set and saved.

**Comment by pdwonline** [comment]
This is my problem too: especially when I have multiple entities, it is not clear what schedule item/timer is represented.

see my screenshot:
![Screenshot at Jun 14 15-39-48](https://user-images.githubusercontent.com/6775870/121903546-b68cd180-cd28-11eb-86ab-bedac97c5e9f.png)

**Comment by daballiemo** [comment]
Same here; just started using the card. In my case I have a card "Central Heating" with 2 entities; weekdays and weekend. With the standard settings it is not so obvious which entity is which.

When I use the option for the entity the value is not saved. When using [Display Options](https://github.com/nielsfaber/scheduler-card#display-options) all entities are changed...

![Screenshot 2021-06-27 at 11 37 30](https://user-images.githubusercontent.com/16369502/123539875-25f8bd00-d73c-11eb-9e71-8e4f2c34125b.png)
![Screenshot 2021-06-27 at 11 37 54](https://user-images.githubusercontent.com/16369502/123539876-2a24da80-d73c-11eb-8482-0d6170d4e6cf.png)

**Comment by nielsfaber** [comment]
You can simple add to the config:
```
display_options:
  primary_info: name
```
To have the **name** of the schedule show up, rather than the **entity + action**.

This is also described in the [documentation](https://github.com/nielsfaber/scheduler-card#display-options).

Note that the setting affects all schedules, so its better to give **all** schedules a name if you want to use this.

**Comment by daballiemo** [comment]
Thanks for the quick answer (which I had to read 5 times). I guess what was not clear to me (and to TS) is that to have the name in the schedule:

1) you have to give it a name through "options"
2) add display_options to the configuration with "primary_info: name"

without the second step you change the name of the schedule but as it is not part of the default settings it will not show up.

kr

Han

**Comment by pdwonline** [comment]
Worked forme; thanks!
