### ISSUE TITLE
Scheduler.storage file disappears when the integration is reloaded

### ISSUE THREAD

**Issue by kaizersoje** [nielsfaber/scheduler-card#425]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]

### Actual behavior
[What actually happened]
I just noticed the scheduler.storage file just disappeared after I reloaded the integration, I had to go and copy the scheduler.storage file from the last backup. Any reason why this happens?

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by nielsfaber** [comment]
What would you expect to happen instead?
Reloading the integration results in resetting, so all previously created items will be gone.

**Comment by kaizersoje** [comment]
Well, I didn't know that. I reloaded the integration since I was getting this error and it was not going away.

![image](https://user-images.githubusercontent.com/54566217/125233179-69008600-e321-11eb-99ad-72f0b7e4002a.png)
