### ISSUE TITLE
Don't update de schedule after edit (chage the minut)

### ISSUE THREAD

**Issue by anarro** [nielsfaber/scheduler-card#43]
Hi,

I have a schedule, after this runs I want to edit and change a time (10 minutes later to try ...) but the switch doesn't change a schedule.

![image](https://user-images.githubusercontent.com/8436433/93383337-c774e900-f863-11ea-8e7f-cda7fbe45185.png)

![image](https://user-images.githubusercontent.com/8436433/93383409-e1aec700-f863-11ea-8798-4f408ee796a2.png)

the original time to be executed was at 2020-09-16T21:20:00+02:00 

I tried uninstalling and reinstalling it (with the latest versions) but the problem persists, it's correct?

Thank you,

**Comment by KTibow** [comment]
What's the problem? Try reloading devtools and the scheduler card, and trying again. It looks like it's working fine to me...

**Comment by nielsfaber** [comment]
This is a known bug.
It is a problem with the scheduler-component, not the card.
See here the bug report:
https://github.com/nielsfaber/scheduler-component/issues/14

**Comment by KTibow** [comment]
Consider closing @anarro? You can add a +1 to https://github.com/nielsfaber/scheduler-component/issues/14
