### ISSUE TITLE
New feature: add timer mode

### ISSUE THREAD

**Issue by martusi61** [nielsfaber/scheduler-card#432]
Thanks for the work done so far, but it would be useful to have a timer mode as well.

**Comment by nielsfaber** [comment]
I'm afraid this is out of scope for this integration.
I think it goes further than a _schedule_ (which is meant for triggering actions on certain moment of the day) so it would be complex to mix with the current interface.

This feature has been requested before, see: https://github.com/nielsfaber/scheduler-card/issues/397, https://github.com/nielsfaber/scheduler-card/issues/292 (and probably some more).
I think the HA dev team is working on an interface for creating timer automations.

**Comment by martusi61** [comment]
Thanks for the information, the use of HA timers is not exactly that easy and an interface for lovelace would be necessary.  Good job.
