### ISSUE TITLE
Possiblility to disable "select multiple entities"

### ISSUE THREAD

**Issue by Maxtropos** [nielsfaber/scheduler-card#436]
It would be very neat, if the option to select multiple entities could be disabled optionally.
For example I am using multiple scripts with different time settings in one group to control irrigation times. Selecting multiple entites would break these scripts. So disabling this would make this much more dad-safe.

![Screen](https://user-images.githubusercontent.com/48759416/130960019-d05ce62c-8773-47d2-8b7a-2eaf17c335ae.jpg)

Have a great day!

**Comment by nielsfaber** [comment]
I'm not planning to make this switch hide-able, sorry.
Why don't you just tell your dad not to use it?
