### ISSUE TITLE
When settings tags nothing happens

### ISSUE THREAD

**Issue by GEORGE-VASS** [nielsfaber/scheduler-card#437]
### Checklist
- [ v] I checked for similar existing issues (both open and closed) before posting.
- [ v] I am running the latest version.

### Expected behavior
[When adding tags on a card (e.g. tags: frontend) to be able to edit each schedule to that tag so it shows only these and hides the rest schedules with out a tag auto discovery off.

### Actual behavior
[No option to add a tag on each schedule, Is it the name in the options? tried that too nothing happens both cards show all schedule new or old doesn't matter they don't hide anything.]

### Steps to Reproduce
[Add to the card tags: frontend or daily that I want to use and then go to options to find no option for tag setting]

**Comment by clipse2004** [comment]
Are you sure this hasn't been released yet? 
I've also tried wildly but can't get it to work... but the documentation doesn't say anything about "not yet released" at least I couldn't find anything :/

**Comment by kbed72** [comment]
Looking at the scheduler.storage file and also the documentation for the scheduler component, it doesn't store the tag anywhere, so I think it makes sense to conclude that this feature hasn't launched yet, though I'd have to agree that the documentation suggests it has. Would love to see it though.

**Comment by nielsfaber** [comment]
Tags functionality will be part of the upcoming v2.2.0 release.
Sorry, I was on holidays, usually I didn't have the time yet to finalize it.
