### ISSUE TITLE
Received invalid command: scheduler_updated

### ISSUE THREAD

**Issue by mjsambol** [nielsfaber/scheduler-card#446]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [ ] I am running the latest version. - No, I'm running [60f176e](https://github.com/nielsfaber/scheduler-card/commit/60f176e9540c945bab518513592acaecff6cf287)

### Expected behavior
No errors in logs

### Actual behavior
I have started seeing several of these:

[2781316552] Received invalid command: scheduler_updated
2:21:35 PM – (ERROR) Home Assistant WebSocket API - message first occurred at 11:19:00 AM and shows up 6 times

There is no additional info in the log, which reads e.g.:

2021-09-05 11:19:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2781316552] Received invalid command: scheduler_updated

const.ts defines WebsocketEvent as 
```
export const WebsocketEvent = "scheduler_updated";
```

And this is used in scheduler-entities-card.ts:
```
  public hassSubscribe(): Promise<UnsubscribeFunc>[] {
    this.loadSchedules();
    return [
      this.hass!.connection.subscribeMessage(
        (ev: SchedulerEventData) => this.updateScheduleItem(ev),
        { type: WebsocketEvent }
      )
    ];
  }
```

### Steps to Reproduce
Build and deploy the latest code (prior to yesterday's check-in).

It is possible this is already addressed with yesterday's check-in, but it does not seem to touch this section of code and I am wary of upgrading to bleeding edge as otherwise things are working well.

**Comment by nielsfaber** [comment]
Which version of scheduler-component are you running?
If you use non-released code for scheduler-card, you should do the same for scheduler-component.
The websocket communication was updated on both sides to allow usage for non-admin users.

**Comment by mjsambol** [comment]
🤦 Duh - that makes sense. I'll roll back. Thanks for the quick reply.
