### ISSUE TITLE
[Feature request] - Add minutes and seconds to timer

### ISSUE THREAD

**Issue by DCG81** [nielsfaber/scheduler-card#450]
Great tool this is, but I am unable to add Minutes and Seconds while trying to schedule an automation, this would really help my requirement and also others. pls consider

**Comment by KTibow** [comment]
> Add minutes

![image](https://user-images.githubusercontent.com/10727862/135773144-89333a1d-6c3b-4198-9ce0-619b682e3277.png)

**Comment by nielsfaber** [comment]
As @KTibow says, it’s already possible to define schedules with 1 min resolution.
I don’t see a need for adding seconds to this. It would complicate the card, while I don’t think many users would make use of it.
