### ISSUE TITLE
Add support for the season sensor in the conditions

### ISSUE THREAD

**Issue by regevbr** [nielsfaber/scheduler-card#453]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I want to have different schedules for each season, without the need to set specific dates and rest them each year.

### Additional info
We can leverage the season built in sensor to perform the condition check

**Comment by nielsfaber** [comment]
You can already use the season sensor in a condition.
It will show up just as any other sensor entity, but you will have to enter the value to compare against yourself (scheduler-card does not offer you built-in spring/summer/etc options).

Just be aware that the card might not show the correct remaining time until the next trigger, as scheduler cannot determine/predict when the transitions of the season entity will occur. 
Conditions are evaluated after the timer triggers, and will block execution of actions but not affect the time display.
For displaying the timer accurately, assigning a date period is preferred.

**Comment by regevbr** [comment]
@nielsfaber thanks so much for the quick and detailed response!
I forgot I needed to add the sensor as an entity in order to see it in the list of conditions. I added that now :-)
About the display, yes I understand but I'd rather have it that way
