### ISSUE TITLE
In climate there are missing options like fan speed 

### ISSUE THREAD

**Issue by drorya1** [nielsfaber/scheduler-card#454]
### Checklist
- [ ] I checked for similar existing requests (both open and closed) before posting.
- [ ] My request is generic, other users may benefit from it too.

### Proposal
Adding the following options to scheduler will be great addition 👍 
hvac_modes:
  - auto
  - cool
  - dry
  - fan_only
  - heat
  - 'off'
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
current_temperature: 25
temperature: 25
fan_mode: low
friendly_name: MyHVAC
supported_features: 9

### Additional info
[some example of how the new functionality should look like]

**Comment by KTibow** [comment]
Can you fill in the issue template and use code formatting?

**Comment by drorya1** [comment]
> Can you fill in the issue template and use code formatting?

Can you kindly refer to the link I should use in order to put it in the right template ?

**Comment by nielsfaber** [comment]
Issue template is visible when you create a new bug report or feature request: https://github.com/nielsfaber/scheduler-card/issues/new/choose

It appears you deleted it for this issue.
For me it’s ok to leave it like this, but please use it next time.

As for your request, I believe that all is already available in the card, except choosing fan speed. Is this correct?
You can add your own action for this using `customize`, you can read about it here: https://github.com/nielsfaber/scheduler-card#actions

If you believe this functionality should become avails bye  in the card for all users, please elaborate (I don’t have a climate device with fan speed so I don’t know the use-case).

**Comment by drorya1** [comment]
I am attaching an example from other application which controls the A/C
![Capture](https://user-images.githubusercontent.com/79847067/147330245-88dc9992-8416-4974-a5d6-23b27fcdbe18.PNG)

https://user-images.githubusercontent.com/79847067/147330621-1f0e444c-b626-4cb9-9ec8-5bd1de848c29.mp4
Please let me know if any additional info is needed

**Comment by drorya1** [comment]
![Capture](https://user-images.githubusercontent.com/79847067/147330769-132813b9-3667-41b8-9c1d-ac61db412ae2.PNG)
Attached a JPG for the options I have to set the fan 
I would advise a slider as you have in the temperature 
Slider should have Speed 1,2,3,A ( Auto)

**Comment by nielsfaber** [comment]
Added an option for setting fan mode for climate devices:
![image](https://user-images.githubusercontent.com/16861605/150665244-d2cb2d1d-aad8-49bb-8f96-88c519797446.png)

I will let you know when this feature is released.

**Comment by nielsfaber** [comment]
Release v2.3.1 is out which contains this feature.
 Please test it and close the issue if your request is fulfilled, otherwise let me know.
