### ISSUE TITLE
Wrong value scheduled and displayed when set decimal requested value

### ISSUE THREAD

**Issue by mareklac** [nielsfaber/scheduler-card#468]
### Checklist
- [ Y ] I checked for similar existing issues (both open and closed) before posting.
- [ Y ] I am running the latest version.

### Expected behavior
When,  in heating  mode,  a temperature for specific timeslot is set by slider to decimal value e.g 20,5  then this decimal value (20,5) should be set and displayed. 

### Actual behavior
currently, the value is rounded up and displayed. So instead of temperature 20,5 ... the value 21 is set and displayed. 

### Steps to Reproduce
Set a decimal value for specific timeslot using slider and confirm it. The value will be rounded up and displayed

**Comment by nielsfaber** [comment]
I don't know what you mean.
For me all seems consistent, see below.
Please provide more info if you expect help.

**Schedule configuration:**

![image](https://user-images.githubusercontent.com/16861605/140634922-6e4a575d-7ec1-4e56-8f79-7dc8408408d9.png)

**Overview display:**

![image](https://user-images.githubusercontent.com/16861605/140634960-2a415b44-1c64-4f75-8958-7363f7882d92.png)

**Climate entity after triggering task:**

![image](https://user-images.githubusercontent.com/16861605/140634950-6f0f5716-bcd3-4ca1-810b-34aca27b31e7.png)

**Comment by mareklac** [comment]
it seems behaviour at my PC is different . Look into attached movie. I can
not set temperature with decimal .
Marek

niedz., 7 lis 2021 o 07:35 Niels Faber ***@***.***>
napisał(a):

**Comment by nielsfaber** [comment]
I have to apologize for lack of response from my side.
The movie you shared clearly shows that something is wrong in scheduler.
I just have no clue yet where the problem could be. For me the behaviour is correct.

Can you check the version of the card you are using?
You can see it in the [browser logs](https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs).
You should see something like this:
![image](https://user-images.githubusercontent.com/16861605/144705649-4a0b013a-ad8c-4981-9387-4ef8555f5990.png)

**Comment by mareklac** [comment]
Hi
After last update it works again ..and problem not repoducible
Marek

sob., 4 gru 2021 o 11:09 Niels Faber ***@***.***> napisał(a):

**Comment by nielsfaber** [comment]
OK I will close the issue for now, please re-open if it comes back.
I assume this is a problem of an older version of the card and fixed in the meantime.
