### ISSUE TITLE
Failed to call service scheduler/add. Service not found.

### ISSUE THREAD

**Issue by sndipz** [nielsfaber/scheduler-card#47]
I get following message when I add a schedule (Switch & Light entities).

 Failed to call service scheduler/add. Service not found.

I have installed scheduler-card usign HCAS.

**Comment by nielsfaber** [comment]
If you have problems with setting up or using this integration, please ask for support in the forums.
This kind of issue has been reported many times before. 
Please check the following:

- [ ] HA version >= 0.114.1
- [ ]  Platform `sun` is enabled (i.e. entity `sun.sun` exists)
- [ ]  In HA, the Scheduler Integration is set up in Configuration -> Integrations

After this, please let us know what is shown in the HA error log.

**Comment by sndipz** [comment]
I misread the documentation and have installed only lovelace component
I have unistalled it & reinstalled after integration component, and it work.
Apologies for raising an issue.

**Comment by nielsfaber** [comment]
@sndipz no problem! i will try to make the installation instructions more clear
