### ISSUE TITLE
Configurable Sorting Behaviour

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [nielsfaber/scheduler-card#472]
Earlier today, I wrote a post on using the scheduler component to control your home's HVAC schedules using the scheduler card... because at this time, It is the best GUI I could find for managing schedules on my HVAC system.

https://xtremeownage.com/2021/10/29/home-assistant-programmable-thermostat-gui/

Well, the ONLY issue I found- I could not find an option in the documentation for how to sort the card.

It would be ideal if we could customize the card's sorting, based on a custom field. In my case, it would allow the HEAT, COOL, and AUTO schedules to be grouped together, based on a naming standard. 

Nothing huge, but, it would be a nice feature.

**Comment by nielsfaber** [comment]
The card currently uses a sorting based on time, i.e. the schedule that will trigger soonest will appear on the top.
It would be possible to extend this and allow the user to choose to sort based on schedule name or entity name.
Is this what you are looking for?
Otherwise could you elaborate?

**Comment by XtremeOwnageDotCom** [comment]
My apologizes, I missed your reply.

I was looking for the potential option of customizable sorting by a given field. This could potentially open up a few additional use-cases.

**Comment by nielsfaber** [comment]
Could you elaborate what you mean by 'given field'?
Anything is possible, but so far it is vague to me what you are requesting.
As said, other than sorting by time I can only think of sorting by name instead (either schedule or entity name).
Is this what you are hinting at?

**Comment by XtremeOwnageDotCom** [comment]
By given field, I mean, add a configurable "sort_by" field.

Which can accept entity name, schedule, state, next run, etc, or any of the other fields available on this entity giving access to other not-yet-known use cases.

But, the core requirement I was looking for, was specifically to sort by "name"

However, to make this a more useful feature request, I would recommend the ability to sort by any available field on the entity.

**Comment by paulius2k** [comment]
Could this be re-opened?  
I would also support a feature to sort schedules by name.

**Comment by nielsfaber** [comment]
In version v2.3.1 I added the option to sort by name (it literally sorts by the text displayed on the first line per item).
In YAML mode you can configure this setting `sort_by`. In UI editor you have the following setting:
![image](https://user-images.githubusercontent.com/16861605/151051070-a98929b1-2b63-467f-80d9-155b9070b8f5.png)

Hope you like it, please let me know.

**Comment by XtremeOwnageDotCom** [comment]
I just updated to the latest version. I like the changes.

But, I would request one more option-
* Sort by Start Time (ie, sorted by start time numerically)

I do like the current two options however. Time remaining until next action is a pretty useful way of sorting as well.

**Comment by nielsfaber** [comment]
@XtremeOwnageDotCom I don't see that very practical. Usually a time scheme is defined from 00:00 to 23:59 so it is not possible to rank by start time.

**Comment by XtremeOwnageDotCom** [comment]
I meant,

Order by 00:00, to 23:59 in chronological order from midnight.

Your recent update already does this, but, starting from the current time.

**Comment by nielsfaber** [comment]
@XtremeOwnageDotCom My concerns stay the same.
A time scheme is defined from 00:00 to 23:59 (unless the user leaves slots unassigned) so this sorting wouldn't work.
