### ISSUE TITLE
Invisible close button

### ISSUE THREAD

**Issue by TTLucian** [nielsfaber/scheduler-card#475]
### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version.

### Actual behavior
Close button X icon disappeared in HA 2021.11.0. The button is there and it works but the icon is not visible.

### Steps to Reproduce
See attached image:

![Untitled](https://user-images.githubusercontent.com/1855276/140319975-c2dc25f2-4cc2-461e-a8ad-4b3dcbd84a70.jpg)

**Comment by Misiu** [comment]
I think that in HA 2021.11.0 the icons did change.
There is a way to check for HA version https://github.com/home-assistant/frontend/pull/10523/files#diff-91d04a65b8ce9f72f7a21072d6c305707820b0f64c84a4c92dca3480e81a889bR199 not sure if this is used here or if t can be used in custom cards.

**Comment by derekoharrow** [comment]
Yep - seeing this too - HA 2021.11.1

**Comment by nielsfaber** [comment]
This is indeed caused by a change in HA 2021.11.
The fix is on its way https://github.com/nielsfaber/scheduler-card/commit/82893cb000e15d5dfd5ccb9d71a89ece1ae6303d

**Comment by Misiu** [comment]
@TTLucian this should be fixed in the latest release.
If yes, please close this issue. Thank you.
