### ISSUE TITLE
What's the best way to make schemes run only once?

### ISSUE THREAD

**Issue by sddgit** [nielsfaber/scheduler-card#479]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

Apologies for posting here with something that's probably not a bug or a feature request! I tried the forum thread, but got no response.

I’m after some advice as to the best way to accomplish something…

I’d like to schedule some devices using schemes. I tend to group things according to tags, so the UI is split up into various sections, each containing the schedules for some like devices. I have a requirement to manually enable one group, which will run multiple schemes. I can do this using the show_header_toggle option. Then I can just toggle that for my group of multiple schemes. But sometimes I only want that particular group to run once, and disable itself at a certain time. The “stop” option doesn’t seem to help here, because it only stops the scheme at midnight (I think). Some of my schemes have devices that are turned on across midnight.

Hope I’ve made myself clear enough! Bit hard to explain…

**Comment by nielsfaber** [comment]
A scheme finishes at the end of the day.
If you select the stop option, it will run until the end of the day and then disable itself.
There is no support for stopping a scheme halfway the day (or similar).
You would have to do this externally (e.g. by automation).
You can easily turn them off since a schedule is just represented as a switch in HA.

**Comment by sddgit** [comment]
Thank you. That confirms my thinking. I could maybe have a non-scheme based schedule that executes a script to turn off the schemes at a certain time of day. It that could use the Stop option. And that could be part of my tag group (like in the attached screenshot). 

For all my tag groups, I set up HA groups that mirror them. Then I can turn on/off a group using automation very easily. In the setup I’ve attached, the non-scheme based schedule at 7am turns off the group that consists of all 3 schedules (another screenshot attached). Is it OK that the 7am schedule gets turned off by the action it’s invoking?

While I’m here, have you ever had a request to turn the `show_header_toggle` switch into an HA-exposed switch? This would save setting up HA groups for each tag group.

Thanks again for your help.
![3CC4A50E-F728-4C39-923E-F43BBE6BE22B](https://user-images.githubusercontent.com/76281052/144316691-65c737dd-efe8-453c-9c8d-6ab701c03e28.jpeg)
![E4EE2896-AA21-4882-B165-3727CC1A8D18](https://user-images.githubusercontent.com/76281052/144316714-0d8db668-9014-458b-beb6-67399eb0dfd6.jpeg)

**Comment by nielsfaber** [comment]
> For all my tag groups, I set up HA groups that mirror them. Then I can turn on/off a group using automation very easily. In the setup I’ve attached, the non-scheme based schedule at 7am turns off the group that consists of all 3 schedules (another screenshot attached). Is it OK that the 7am schedule gets turned off by the action it’s invoking?

Sounds a bit tedious, but if it works for you, fine with me.
There is no harm in turning off a schedule directly (the same would happen if you configure it to stop after triggering).

> While I’m here, have you ever had a request to turn the show_header_toggle switch into an HA-exposed switch? This would save setting up HA groups for each tag group.

Didn't have such request yet, no.
The problem with this is that the list of schedules shown in a card depends entirely on the card configuration (included entities, tags, etc.).
A separate switch entity would have to be handled by the backend (scheduler-component), but there is no knowledge there of which entities are in which card.

I think you should consider it similar to the toggle button for the [Entities Card](https://www.home-assistant.io/lovelace/entities/#show_header_toggle). The user has free choice here of which entities occur in the list, hence the behaviour of the toggle switch is completely defined in the card itself. Scheduler-card implements it in the same way.

I could possibly add `scheduler.turn_on_by_tag` / `scheduler.turn_off_by_tag` services, but it feels a bit exotic for me, I suppose you will become the only user of it. 
There is also (probably) an option to have scheduler auto-generate `group` entities for all schedules with certain tag, but my feeling is that more people (including me) will be bothered by the extra unused HA entities, than there are people who start using it.
Perhaps the manually created groups are a good solution after all.

**Comment by sddgit** [comment]
That’s fine. I’m happy doing it my way. Probably not that much call for the other enhancements.

**Comment by nielsfaber** [comment]
OK, I will close the issue since I don't think we need to follow-up on this.
If in a later point you see the need for a certain change or addition in the scheduler-card or component based on your use-case, feel free to open a feature request to discuss it.
