### ISSUE TITLE
Unable to set climate setpoint

### ISSUE THREAD

**Issue by nodoubleg** [nielsfaber/scheduler-card#480]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Selectable range includes usual desired temperatures in Fahrenheit or Celsius. Adjustment on temperature slider sets temperature. Adjustment of slider doesn't reset the range of the slider.

### Actual behavior
Slider shows default set point of 45 degrees, and position of slider is all the way to "max". Attempting to adjust slider causes the range in the slider to reset. Releasing the slider causes it to snap to the "max" end again, and now displays the set point of 95 degrees. Attempting to adjust from here doesn't reset the range further. When releasing the slider, it will snap to the "max" end again. The desired set point doesn't "take" 

### Steps to Reproduce
0. Have climate devices and Home Assistant all configured to use degrees Fahrenheit, not Celsius.
1. Create new schedule for climate device
2. Select "heat" for action
3. Observe slider at 45 degrees
4. Attempt to adjust slider.
5. Observe slider now set to 95 degrees.
6. Click save
7. Attempt to edit new schedule to adjust setpoint.
8. Observe setpoint at 95, and that it's still unable to be adjusted.

**Comment by nielsfaber** [comment]
Scheduler checks the properties of the climate entity to determine the slider range:
![image](https://user-images.githubusercontent.com/16861605/144704949-eb1024e3-cc65-416c-85a5-64ba80a71b3f.png)

Could you check in the Developer Tools -> States page which settings your climate device has and share them here?

**Comment by nodoubleg** [comment]
Looks like my integration for my thermostats might have a bug? There is no `target_temp_step` for these entities. Would that cause this odd behavior?

![image](https://user-images.githubusercontent.com/593401/145488745-cd7d35d0-8906-4ba9-92d5-96e73af064fd.png)

**Comment by nielsfaber** [comment]
Yes, this is causing the behaviour.
I am assuming your HA defaults to Fahrenheit as unit, else your thermostat would be more like a cooking stove.
In case the `target_temp_step` is not provided, the scheduler assumes it to be 1.
The same assumption is made in HA I believe, see [here](https://developers.home-assistant.io/docs/core/entity/climate/#properties) under precision.
At the same time your device seems to allow 0.5 step size, but it does not advertise as such.

Scheduler cannot handle a minimum limit with 0.5 resolution combined with a step size of 1, it gives you the glitches you experience with the slider.

I did some testing of this scenario and made a small change to have the min/max levels rounded internally to solve this issue for you, so it will be solved in the next release.

**Comment by nielsfaber** [comment]
Your issue should be fixed by updating to v2.3.0. 
Please test it out and close the issue if this is the case (otherwise please let me know).
