### ISSUE TITLE
Schedular not started stated in lovelace card 

### ISSUE THREAD

**Issue by Knightcort** [nielsfaber/scheduler-card#481]
### Checklist
- [V] I checked for similar existing issues (both open and closed) before posting.
- [V] I am running the latest version.

### Expected behavior
Working lovelace card. 

### Actual behavior
Installed Lovelace card and integration, restarted HA. But lovelave card gives an error "can't connect to service........".

When installed the schedular with help of HAVS and restarted HA, the lovelace card stated that no connection could be made to schedular. Also restarted the whole server of HA, and that gave the same result.

In the log of HA appears the following:
[140563837777136] Received invalid command: scheduler
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:89
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:26:48 (6 occurrences)
Last logged: 13:31:38

[140563837777136] Received invalid command: scheduler
[140563837777136] Received invalid command: scheduler_updated

### Steps to Reproduce
Install Lovelace card
Install Integration
Restart HA
Make a Lovelace card bases on installed frontend and receive noted error
Tried a previous version of the integration, with no luck.

**Comment by nielsfaber** [comment]
Is scheduler configured in the Integrations page of HA?

**Comment by Knightcort** [comment]
Ow .....thats a steep learning curve, I'm quitte new with HA (coming from Domiticz) and indeed I didn't load the integration in HA. Thnks for the fast response, I'm going to start with the schedular right now!

**Comment by nielsfaber** [comment]
If you need help setting up scheduler, you can ask in the forum thread: https://community.home-assistant.io/t/scheduler-card-custom-component/217458

I prefer if you start here, it’s a more gentle approach than claiming you experience a bug.

**Comment by Knightcort** [comment]
Hi,

I did look into the thread, because It’s quite extensive and thought I had already some experience, probably I read over it. Off course I will use you’re feedback in the near future, excuses for doing it by this way.

Gr. John
