### ISSUE TITLE
Can't create schedule to turn off humidifier

### ISSUE THREAD

**Issue by fabianluque** [nielsfaber/scheduler-card#486]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
An entry in the scheduler should be created upon pressing the save button

### Actual behavior
This error pops out: 

Something went wrong!
Message format incorrect: Entity ID turn_off is an invalid entity ID for dictionary value @ data['timeslots'][0]['actions'][0]['service']

Response error: 400

This is the payload being sent in the add request:
{"weekdays":["daily"],"timeslots":[{"start":"12:00:00","actions":[{"entity_id":"humidifier.boys_bedroom_humidifier","service":"turn_off","service_data":{}}]}],"repeat_type":"repeat","tags":[]}

For comparison, this is the payload being sent when choosing the turn on action instead:
{"weekdays":["daily"],"timeslots":[{"start":"12:00:00","actions":[{"entity_id":"humidifier.boys_bedroom_humidifier","service":"humidifier.turn_on","service_data":{}}]}],"repeat_type":"repeat","tags":[]}

### Steps to Reproduce

1. Click Add
2. Select Humidifiers in Group
3. Select the humidifier entity
4. Select the Turn Off action
5. Click Next
6. Click Save
7. Error occurs

**Comment by nielsfaber** [comment]
Thanks for reporting this. The fix is on its way! (https://github.com/nielsfaber/scheduler-card/commit/4531e48f8fb3156f40e60dd1f166b32f95213dae)

**Comment by nielsfaber** [comment]
Your issue should be fixed by updating to v2.3.0. 
Please test it out and close the issue if this is the case (otherwise please let me know).

**Comment by fabianluque** [comment]
Thanks for fixing it so quickly! I can confirm it works as expected now.
