### ISSUE TITLE
focus ios 15

### ISSUE THREAD

**Issue by tomg1970** [nielsfaber/scheduler-card#489]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hello thank you very much. Super blueprint.
It would be perfect if the selection of the iphone focus could still 
be selected, which focus it is. Since ios 15, different focus can be created.

lot of thanks
tom

### Additional info

IOS 15 > go focus sleep > timer starts

**Comment by nielsfaber** [comment]
As far as I know, the HA Companion App for iOS does not expose an entity which represents the current focus mode of your phone. In other words, scheduler does not have access to the focus mode of your phone.

You could consider following [this procedure](https://community.home-assistant.io/t/ios-15-focus-mode-accessible-to-hass/340789/2) to trigger an automation from your phone when the focus mode is changed.
You could for example create an [input_select](https://www.home-assistant.io/integrations/input_select/) with your focus modes as options, and use the automations in iOS (shortcuts app) to keep the input_select in sync with the enabled mode.
Scheduler can be configured with an input_select matching a certain state as condition.

I wouldn't know how to help you more than this.
Please close the request if the proposed method is an acceptable solution for you.
