### ISSUE TITLE
Condition based Temperature

### ISSUE THREAD

**Issue by DeeJaWue** [nielsfaber/scheduler-card#496]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I will start with an simple example:
I have a schedule für my radiator:
00:00 to 09:00: 17°C
09:00 to 18:00: 19°C
18:00 to 24:00: 17°C
So far, so good.

Now I want to change the day temperature (09:00 to 18:00: Default: 19°C) based on different Conditions:
If my girlfriend is at home (home office) it should be 21°C, and if we booth are away, it should be 16°C.
So it's like 
if(girlfriend at home = 21°C)
Else if (booth away = 16°C)
Else (19°C)

At the moment I have 3 schedules to build it, but it works only to change from the default temp, to the other two (girlfriend at home, oder booth away) but not back to the default value.

My idea for the feature is, that anyone can make conditions to every time slot (in my example just the timeslot from 09:00 to 18:00) in a schedule. And on top of that, to make different actions to different conditions (like above: person 1 at home: 21°C, person 1 and 2 away: 16°C).

I hope you know what I mean, otherwise write to me :)

### Additional info

See the text above.

**Comment by DeeJaWue** [comment]
Before I forget: this should works like now, with re-evaluate on states change.

**Comment by nielsfaber** [comment]
I don’t want to make the card more complex than it already is.
Different conditions per timeslot combined with if/else rules would definitely make things more complex.

I think it’s best to use 3 schedules for the different cases, if the conditions are defined correctly only 1 schedule will be active at a time, so no conflicts there.
You may also choose to combine the schedule with a script, which is triggered by scheduler every time the conditions change.
The script then contains the if/else rules for setting the correct temperature.

**Comment by DeeJaWue** [comment]
Thanks for the fast reply!

It's a good idea to use a script which will trigger by the schedule.

And I can understand, that you don't want to make it more complex :)
