### ISSUE TITLE
In display options, permit to display the time scheme

### ISSUE THREAD

**Issue by OCWs-Outillage** [nielsfaber/scheduler-card#497]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It could be interesting to allow display of the scheme in the "display mode"

### Additional info

![image](https://user-images.githubusercontent.com/26734754/148047030-cd36f9e3-2a02-4800-919d-e6ee37d4fe19.png)

**Comment by nielsfaber** [comment]
I decided to not add too many 'whistles and bells' to the overview page and kept the look similar to the [entities card](https://www.home-assistant.io/lovelace/entities/#buttons-row).
I understand that (especially if you only have 1 or 2 schedules in the card), displaying the full configuration can be practical, but with a long list I don't think this will look OK. 
I don't want to  support multiple flavors, it would double the effort in developing and maintaining it.
So I want to stick to the current layout.

I am considering to add an option to make an item in the list expandable (by clicking) for showing more details. Once I have the time to work on this, this could be a good next step. But it could be a while before I find the time for that.

**Comment by ErikSiemens** [comment]
I agree with OCWs, this would be an nice addicion. Maybe with a checkbox for showing/not showing ?

**Comment by s17911** [comment]
I don't know much about the mechanical part of this function but overall I would find it very useful

**Comment by Stevendebruijn** [comment]
I agree with OCW also. I my case, (with only a few schemes for controlling the thermostat), would realy like it to have them visible.

But wether you will build it in or not, Its a really nice card and works very well!
