### ISSUE TITLE
Integrate use of Workday component for Schedules

### ISSUE THREAD

**Issue by corvy** [nielsfaber/scheduler-card#498]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I have used this component to create automations that only execute when it is a worknight (day before a workday) or it is a workday. https://www.home-assistant.io/integrations/workday/

Could we use this bainary_sensor as an alternative to set the weekday for the schedule? 

![image](https://user-images.githubusercontent.com/138292/148641868-0c7af768-8935-4e00-8218-1c1bdfc382e2.png)

This sensor is updated on a per-country basis. So it will only be the relevant holidays for the country in question. 

Hope this can be considered! 

### Additional info

See above.

**Comment by nielsfaber** [comment]
This is already in place, read the [docs](https://github.com/nielsfaber/scheduler-card#choosing-the-days).

**Comment by corvy** [comment]
Thank you! :) I did not find this!

**Comment by corvy** [comment]
One more question @nielsfaber. Could this schedule be -1? So it would be worknight rather than worday? So for instance that the schedule would be the day before a weekend/holiday?

**Comment by nielsfaber** [comment]
No, the options are limited to what is possible with the workday integration, and it doesn't allow defining a part of the day as workday.
If you want to achieve such behaviour, you could configure the schedule to run daily and turn it on/off through an automation.
It is also possible to make your own version of the workday sensor, see [here](https://github.com/nielsfaber/scheduler-card/issues/329#issuecomment-850301968) (in his case he wanted friday night to be considered as weekend).
