### ISSUE TITLE
Make the time picker fields manually editable

### ISSUE THREAD

**Issue by zanna-37** [nielsfaber/scheduler-card#499]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be awesome to be able to manually edit the time-picker fields (hours and minutes) inside the `<div class="time-picker">`.
I would suggest to change them from being a `div` to an `input type="number"`.

The current behavior should be kept, but the user can also quickly adjust the time without having to press the arrows.

### Additional info

There are even different ways of hiding the built-in browser arrows while maintaining the data validation capabilities.
https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box

**Comment by nielsfaber** [comment]
There is actually an [input type=time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) which would be more suitable (especially on mobile devices).
However I am not sure whether this is worthwhile adding, due to the following:
* The time schemes still have to be created graphically and I think these are more used than the time picker, so it's a bit of a half solution
* The result will probably look worse (input field typically has a box and standard letters etc.) so for people who want to use the arrows its a step back
* It is (as far as I can see) not possible to define step size for the minutes, so I either have to apply correction to the user input or ignore the step size configured in the card

**Comment by zanna-37** [comment]
I think that a standard way of inputting the time would be preferred, especially because it is tedious to input the precise time with the arrows.
**BUT**, I understand what you say and it is the reason why I'm proposing to add the manual editing on top of the existing behavior. The arrows would still obey to the step size and everything but the user has also the possibility to edit it manually.

And to address your bullet points:
- Time schemes are not involved in the update, they are different
- The input field can be customized graphically but we can always choose to use `input type="number"` (or others) to be more flexible
- Applying a correction to the user input shouldn't be an issue to code:
  - This should work for the arrow up `( ( floor(minutes/step_size)+1 ) * step_size ) % 60`
  - examples:
    - `minutes=7 step_size=10 → (floor(7/10)+1)*10 → 1*10 = 10`
    - `minus=18 step_size=15 → (floor(18/15)+1)*15 → 2*15 = 30`

**Comment by zanna-37** [comment]
Keep open

**Comment by zanna-37** [comment]
keep open

**Comment by zanna-37** [comment]
keep open

**Comment by jorgemoralespou** [comment]
I also think this is important. It is really complicated to input a desired range with the sliders. In my case, I want one of the slides to be at 8:00 but I when sliding I can only get to 7:58 or 8:01 (despite having a step of 1). It would be nice to have a way to manually set the exact values, whether visually or in an editing mode (like lovelace does for the dashboard components where you can fall back to yaml editing if needed).

**Comment by zanna-37** [comment]
That's amazing news!
Thank you very much!
I'll be more than happy to test it.

**Comment by kaaspad** [comment]
Can this be added when doing a scheme as well? My big issue is I can’t get the slider past 11:18pm on the phone and on a browser past 11:30 pm. I’d like to set to 11:59 for example but can’t and I don’t was to have to do past midnight as that will mess up the days I want it to run. Thanks so much

**Comment by nielsfaber** [comment]
@zanna-37 This feature is added to release v2.3.5.
Could you please update to this version and test it out?
You can close the issue if the request is fulfilled, otherwise let me know.

**Comment by zwgmy** [comment]
The v2.3.5 although can enter a number, such as 15:42,but it is still 15:40 when saved. Can you skip steps per minute?

**Comment by zanna-37** [comment]
I tested it and everything seems perfect! 🎉
Thank you very much for your effort!
For my part I'm more than satisfied!

Anyway, I agree with @zwgmy, I think the step size should be ignored when manually inputting the time.
I also know that @jorgemoralespou and @kaaspad would like to see the manual input in the sliders of the scheme, but maybe that should live in another issue.

**Comment by kaaspad** [comment]
> 

@zanna-37 ok I can open a new request and you can go ahead and close this one

**Comment by nielsfaber** [comment]
The step size / resolution for time input applies to the whole card.
I’m currently not considering to change this.
When a user enters time manually it will be rounded off to the nearest time step if needed (as discussed in https://github.com/nielsfaber/scheduler-card/issues/499#issuecomment-1011250587).

For time schemes the user needs to enter the time by dragging the slots in the bar.
There is no field present which allows manual time input. I also don’t see it  possible to add this on short term (on the long term I would prefer to merge the input method for standard schedules with time schemes).

**Comment by zanna-37** [comment]
I don't agree, but I respect your opinion.
Anyway, I always use the step size to 1 (which is the reason why I much appreciate the manual input), so this decision won't affect me.
Since I'm very satisfied with the outcome of this issue I'm closing it now.
Thanks you again!
