### ISSUE TITLE
Auto enable schedule after time modification

### ISSUE THREAD

**Issue by zanna-37** [nielsfaber/scheduler-card#500]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

There should be a customizable flag to enable the automatic turn-on of a disabled schedule when I press "save" (and the time has been changed¹).

_¹ The requirement of the time being changed is not too important in my opinion_

### Additional info

If I have a schedule set, but turned off, when I change its activation time and press "save" I expect the schedule to be active. Instead I currently have to manually enable it after changing the time.

The new behavior would be consistent to what happens in other applications and I think the user expect this. For example the alarm on Android phones (maybe Iphone's too?) works like that.

**Comment by nielsfaber** [comment]
Iphone does this too 👍 
I agree with this change, pick this up when I can.

**Comment by nielsfaber** [comment]
When clicking 'save' button, scheduler will now check if properties have been changed.
If so, the schedule will be turned on if disabled.

I will let you know when a new release is out, so you can test it yourself.

**Comment by nielsfaber** [comment]
Release v2.3.1 is out which contains this feature.
 Please test it and close the issue if your request is fulfilled, otherwise let me know.

**Comment by zanna-37** [comment]
Perfect! Many many thanks, everything is working properly.
