### ISSUE TITLE
Renaming the schedule sometimes breaks it

### ISSUE THREAD

**Issue by eikowagenknecht** [nielsfaber/scheduler-card#502]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

latest

### Component Version

latest

### Bug description

See this animation for further details.

![Animation](https://user-images.githubusercontent.com/1475672/149314751-0e816736-acd1-4d1d-b9bb-9b0539fb9cba.gif)

### Steps to reproduce

1. Create a schedule
2. Rename it
3. Repeat 2 until error occurs

**Comment by nielsfaber** [comment]
Thanks for making a video, it makes the problem very clear.
I think the schedule is not actually 'broken'. I think refreshing the page / card already resolves the issue. Can you confirm this?
It is something related to the communication between the card and the component, but I don't know how to fix this currently.

**Comment by eikowagenknecht** [comment]
Yes, it seems that refreshing it is a valid workaround.

**Comment by nielsfaber** [comment]
I'm having troubles reproducing this issue.
In my HA instance, I can rename a schedule 10 times in a row without seeing this glitch.
It seems that also response time (of either browser or the HA backend) is a factor.
If you have any tips to make this appear more frequently, please let me know.

**Comment by eikowagenknecht** [comment]
Sorry I can't provide any more information. For now I stopped using this integration and switched to a handful of standard automation rules instead. Closing this as it can't be reproduced currently.
