### ISSUE TITLE
Add once to the days option

### ISSUE THREAD

**Issue by Roei-Bracha** [nielsfaber/scheduler-card#503]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

What about adding the option of "Once" to the days selection

### Additional info

lets say I want to create a schedule to turn on the light tomorrow at 8 am - just once with no repeats
I will choose the light set the time, press once and it will turn on the light the next time it will be 8am and never agein

extra - this can be a switch that will turn off after one time and every time I would ilke to turn on the light on 8AM I will toggle it on

**Comment by nielsfaber** [comment]
Once is not a day.
Use the [repeat behaviour](https://github.com/nielsfaber/scheduler-card#behaviour-after-completion) instead.
