### ISSUE TITLE
Calendar sensors integration

### ISSUE THREAD

**Issue by sanchezn80** [nielsfaber/scheduler-card#507]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Today, the use of calendar sensors is not easy.
I used sensor templates that triggers with calendar sensors and used them to add conditions in options panel.

It would be great to add the possibility to choose directly calendar sensors in the main configuration panel

### Additional info

![Capture d’écran 2022-01-21 à 09 27 12](https://user-images.githubusercontent.com/56150811/150495613-028da2fe-4f5f-4994-82bc-565da8adeaf6.png)

In the calendar section, the calendar sensors are showed (maybe only the one selected in configuration like the binary sensors used for conditional execution in options panel).

I think it's better to combine calendar sensors and days selection in order to use calendars for full weeks.

If you don't select a calendar sensor (including the NO CAL.), calendar sensors are not used.
If NO CAL. is selected, you only execute the action when no calendar sensor is active.
if one or more calendar sensor is selected, you execute the action when at least one calendar sensor selected is active.

**Comment by nielsfaber** [comment]
Is this related to [Google Calendar](https://www.home-assistant.io/integrations/google/)? 
I have no idea with a calendar sensor is to be honest, so I don't really know how it works and how it could be integrated in scheduler.

**Comment by sanchezn80** [comment]
Yes and no. It works the same for all calendar types I think.

calendar.something works just like a binary_sensor.

As an example, here is my calendar.vacation config:
    - device_id: **vacation**
      ignore_availability: true
      name: Vacances
      track: true
      **search: "vacation"**

if there's an event with the title matching "vacation" in the calendar, now, the sensor calendar.vacation is on.
If there's no event matching at the time, calendar.vacation is off.

To deal with the fact scheduler doesn't support calendar.xxx, I created a template binary_sensor with the config:
binary_sensor:
  - platform: template
    sensors:
      vacation:
        friendly_name: "Vacation"
        value_template: "{{ is_state('**calendar.vacation**', '**on**') }}"

Your scheduler is really great, and in my opinion, the only lack is the calendar support.
Maybe, as a first step (or only step), it's easy to add the calendar.xxx just like binary_sensors.

Let me know if I can help.

**Comment by nielsfaber** [comment]
I have my doubts about your proposal to have the calendar section added to the GUI.
From what I understand, the calendar implementation in scheduler is very rudimentary (I would rather expect the entity to show a list of dates+times than only on/off states).
Also seeing the number of users, I think it is not a priority.

> Maybe, as a first step (or only step), it's easy to add the calendar.xxx just like binary_sensors.

This sounds like a OK solution for now. I will pick this up when I can.

**Comment by nielsfaber** [comment]
Calendar entities should show up automatically under conditions now (if included in the card).
I will let you know when the release is out with this improvement.

**Comment by sanchezn80** [comment]
Thank yo uvera much Niels!
I'll try it as soon as possible!
