### ISSUE TITLE
Sunrise/Sunset option in schema view

### ISSUE THREAD

**Issue by davidclaesson** [nielsfaber/scheduler-card#510]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Button for adding a brakepoint depending on sunrise and sunset in the schema view. 

### Additional info

Example of how the function/gui could look like (inside red box)

![bild](https://user-images.githubusercontent.com/39413587/150633898-4bc82794-24b2-4aa2-be42-e679ea5ac6e9.JPG)

**Comment by nielsfaber** [comment]
This is already in place, see https://github.com/nielsfaber/scheduler-card/issues/289#issuecomment-989701840
