### ISSUE TITLE
Header toggle deactives scheduler entities of all cards

### ISSUE THREAD

**Issue by ASNNetworks** [nielsfaber/scheduler-card#511]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.0

### Component Version

3.2.6

### Bug description

If you have multiple Scheduler Cards in your dashboard, the toggle `show_header_toggle` turns off ALL scheduler entities of all cards. So if you use multiple Scheduler cards, using the toggle to quickly disable all scheduler entities inside that card, it will also disable the scheduler entities of other Scheduler cards. 

This makes no sense from a user perspective, since there is a reason you use separate cards. So the toggle should only control the scheduler entities visible in the card, not of other cards.

Suggestion: change the behaviour of the toggle so it only controls the visible scheduler entities in that card. 

### Steps to reproduce

Use the `show_header_toggle` toggle and view a different Scheduler card.

**Comment by nielsfaber** [comment]
I agree, I never knew this was the case, but looking at the code I understand your point.
Will fix it in the next release.

**Comment by nielsfaber** [comment]
I made some changes which should make sure only items in the list are toggled by the switch.
I will let you know when the release with this fix is out.

**Comment by ASNNetworks** [comment]
> I made some changes which should make sure only items in the list are toggled by the switch. I will let you know when the release with this fix is out.

Thanks, can't wait to test it out.

**Comment by nielsfaber** [comment]
Release v2.3.1 is out which contains this fix.
 Please test it and close the issue if the issue is fixed, otherwise let me know.

**Comment by ASNNetworks** [comment]
> Release v2.3.1 is out which contains this fix. Please test it and close the issue if the issue is fixed, otherwise let me know.

Thanks, works!
