### ISSUE TITLE
Condition slider range

### ISSUE THREAD

**Issue by Nik71git** [nielsfaber/scheduler-card#513]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V 3.2.6

### Bug description

In condition, when choose entity sensor, value minor to X, value slider can nove only from 0 to 255 instead of bigger values. In my case Power value must be minor to 3000 W not only 255 W.

### Steps to reproduce

Choose condition, every numeric sensor value cannot be bigger than 255

**Comment by nielsfaber** [comment]
This is the default setting. Sensors don't show their min/max values in the properties.
You can change the limits by defining the possible states for it in the card configuration, see [here](https://github.com/nielsfaber/scheduler-card#conditions).

**Comment by Nik71git** [comment]
Thank you very much.

Il lun 24 gen 2022, 05:49 Niels Faber ***@***.***> ha scritto:
