### ISSUE TITLE
Manual changes

### ISSUE THREAD

**Issue by Joparmen** [nielsfaber/scheduler-card#516]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V3.2.6

### Bug description

When zo manually change the state of a schedule the schedule stops working and I have to completely restart home assistant to make it working again.

for example I have a selector to choose which room is dominant for controlling the Central Heating. if one day, I use another room trough a input switch instead of following the schedule, I have problems with the card and the scheduler. How do you solve this? 

### Steps to reproduce

Make schedule 
Manually override schedule

**Comment by nielsfaber** [comment]
I don't understand this issue.
Schedules are switches in HA, so you can turn them on/off as you want.
By default a schedule only does something at the time (or entering a timeslot) that is configured, afterwards you can make changes as you please.
Could you share an example of what gives issues in your setup?
