### ISSUE TITLE
the scenes group is missing

### ISSUE THREAD

**Issue by iqueban** [nielsfaber/scheduler-card#517]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.1

### Component Version

3.2.6

### Bug description

I installed the component and the card on 3 different homeassistant installations. On two of them, the scene group is missing in the card. On the other one, the scenes do appear, and I can use them in schedules.

### Steps to reproduce

install the component and the card via hacs
add the card to lovelace 
the scene group doesn't appear in card config

**Comment by nielsfaber** [comment]
You have to configure the card to show scene entities.
Looks like you have configured them differently.

**Comment by iqueban** [comment]
on the working installation I had the 2.3.0 version of the card. After upgrading to 2.3.1, the scene group dissapears in card config as well.

**Comment by iqueban** [comment]
how can I do that? I configured the card via the UI and all the entities groups are there for selecting except the scene group.

> You have to configure the card to show scene entities. Looks like you have configured them differently.

**Comment by iqueban** [comment]
> on the working installation I had the 2.3.0 version of the card. After upgrading to 2.3.1, the scene group dissapears in card config as well.

in the yaml settings the scene group remains, but the group is not visible either in card config or while making new schedules

**Comment by iqueban** [comment]
![Screenshot 2022-01-27 10 55 31](https://user-images.githubusercontent.com/16131447/151325760-4cc5e544-160d-4fc4-ac15-ab21e27feda6.png)
![Screenshot 2022-01-27 10 55 17](https://user-images.githubusercontent.com/16131447/151325772-c97468b9-220e-4337-ba52-2f789d808815.png)
![Screenshot 2022-01-27 10 55 03](https://user-images.githubusercontent.com/16131447/151325783-32ab6fe6-6e1b-4138-b228-d6d7788058b5.png)
 This is how the card config looks now, after upgrading to card 2.3.1 on the installation that was showing the scene groups.

**Comment by iqueban** [comment]
after downgrading to 2.3.0 the scene group is back.

**Comment by nielsfaber** [comment]
I can confirm this is a bug introduced by v2.3.1, I just saw the same issue as well.
I could pinpoint it to a simple typo ('scenes' instead of 'scene', see [here](https://github.com/nielsfaber/scheduler-card/blob/main/src/standard-configuration/actions.ts#L309) ), so its an easy fix.
Will try to make a new release for this fix asap.

**Comment by nielsfaber** [comment]
This should be fixed in release v2.3.2. 
Please update and test if the problem is solved now, you can close the issue if so.

**Comment by iqueban** [comment]
Thank you! It works now.
