### ISSUE TITLE
Year Long Schedule

### ISSUE THREAD

**Issue by broyuken** [nielsfaber/scheduler-card#518]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I have some lights outside my house that I want to light up different colors based on the date. Pink if it's valentines, day, green if st. patricks, orange if haloween, red and green if christmas, etc. I also want those lights to light up a normal warm white on non-holidays. 

So far I've created an input select with the holidays and a None option. I have your component set up to Change the input select to the holiday based on date ranges. The issue I'm having is getting it to select None if its not a holiday. If I set up a daily schedule it will conflict with each holiday where it tries to set it to none, but also tries to set it to a holiday. 

What I'm looking for is something similar to this component
https://github.com/aneeshd/schedule_state
where if there is a default action, and if there is an overlap, the overlapping schedule takes precedent. 

### Additional info

Maybe make it so that any schedule with no period selected will be ignored if there is a time period with a period set that overlaps.

I could currently work around this by setting the "None" option schedule to every night at midnight, and the holiday ones to 12:01AM but then each day that there is a holiday, the input select would change twice. Not ideal, but it would work. This would be a cleaner solution.

**Comment by nielsfaber** [comment]
I don't really understand what changes you are looking for on the side of scheduler.
If I understand you correctly, you have an `input_select` which defines whether it is a holiday (and which) or not.
You could define multiple schedules like so:

- Schedule 1: turn on lights as normally (white color) with condition that `input_select` is `none`.
- Schedule 2: turn on lights in pink with condition that `input_select` is `valentine`
- Schedule 3: turn on lights in green with condition that `input_select` is `st patrick`

Additionally you need some automation (outside of scheduler) to update the `input_select` every day.
Is this what you are looking for or am I missing something?

**Comment by broyuken** [comment]
So forget about the lights for this part. It was just for the example. I want to have scheduler set the input select to a holiday name if it is a holiday, but if it’s not, set it to none. 

So for this, I made schedules for each holiday that trigger every day at midnight. And each one has a period set around those dates. That part works, but I want to have the input select go back to none if it’s not a holiday the next day. I’m not sure how to set up the schedule to do that. That’s why I was looking for a default schedule that triggers if none of the others match. 

Hope this makes more sense.

**Comment by nielsfaber** [comment]
I think an easier solution would be to use a template sensor:
```yaml
sensor:
  - platform: template
    sensors:
      holiday:
        value_template: >
          {% set day = now().date().day %}
          {% set month = now().date().month %}
          {% if month == 2 and day == 14 %}
            Valentines day
          {% elif month == 3 and day == 17 %}
            St. Patricks day
          {% else %}
            None
          {% endif %}
```
It will automatically recalculate every minute and of course you can add more holidays as you desire.
I didn't test the code above, but it should (more or less) work.

**Comment by broyuken** [comment]
Yea I could do it that way, but I wanted to be able to easily be able to do date ranges that may go across months. For example, I have my "Christmas" holiday active from after thanksgiving until the end of december. I do this because I set my lights to red and green during that time. 

If this isn't something you're looking to add to this tool that's fine. My workaround, while not perfectly ideal does work. Was just thinking that having a default item if none of the other schedules match might be helpful for other things as well.

**Comment by nielsfaber** [comment]
> Yea I could do it that way, but I wanted to be able to easily be able to do date ranges that may go across months. For example, I have my "Christmas" holiday active from after thanksgiving until the end of december. I do this because I set my lights to red and green during that time.

I was just thinking about a way to solve your use-case. 
I think it's always good to take into account all features HA already offers, before deciding that additional functionality is needed in scheduler.
In my opinion, creating a holiday sensor as I proposed is much simpler and elegant approach than what you're making, but of course you are free to design it as you wish.
Note that you could change my example to support ranges like so:
```
 {% if (month == 11 and day > 24) or (month == 12 and day < 26) %} # from thanksgiving until christmas
```

> If this isn't something you're looking to add to this tool that's fine. My workaround, while not perfectly ideal does work. Was just thinking that having a default item if none of the other schedules match might be helpful for other things as well.

Scheduler is created with an architecture where each schedule is independent of others (as all entities in HA are).
I indeed don't feel much for changing this concept as it would have dramatic impact for little benefit.
So the consequence is that you are responsible to configure schedules such that they don't have overlap with others.
There is no (and will be no) intelligence inside to detect whether other schedules might have actions acting on the same entity on the same time and/or day.
I think the solution you found for this is as good as it gets with scheduler 👍

**Comment by broyuken** [comment]
I may end up going with your template sensor after all, it does seem like a pretty good solution. And it would clean up my automation a little. 

That being said, I probably won’t need to use this component anymore, but I will be sure to keep it in mind for anything that might use it in the future.

thanks for all your help with this, even if you ended up telling me not to use your tool haha.
