### ISSUE TITLE
Action Buttons for Lights Schedule / Double "Off" button

### ISSUE THREAD

**Issue by codeHub-space** [nielsfaber/scheduler-card#519]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.1

### Component Version

v3.2.1

### Bug description

In the Actions setting for Lights with Schedule days and times appears two "Off" buttons.

### Steps to reproduce

Open an existing Light Schedule or create a new one.

**Comment by nielsfaber** [comment]
Woops, I am now seeing it too.
I will fix this and make a new release to revert the problem.

**Comment by nielsfaber** [comment]
This should be fixed in release v2.3.2. 
Please update and test if the problem is solved now, you can close the issue if so.

**Comment by codeHub-space** [comment]
Yes it is solved.
Thanks very much!
