### ISSUE TITLE
Different colors for actions in scheme edit mode

### ISSUE THREAD

**Issue by ChrislyBear-GH** [nielsfaber/scheduler-card#520]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hello,

Let me first say, that I love your integration! It makes life so much easier! And because I like it so much, I have a suggestion to make it even better:

When editing a time scheme the actions only are displayed in text when there is enough space for the text.

I think it would be better to have different colors for actions, like grey for undefined, green for on, red for off, etc. Of course it would also make sense, to make these colors configurable - maybe in the Scheduler Card options - since people have different color schemes in their home assistant.

This way you can see when which action takes place at a glance.

As an example why I think this would be a good idea, look at the following screenshot and tell me when my device turns on or off:
![image](https://user-images.githubusercontent.com/4168250/151656660-5220e292-be6d-4851-a9d9-e1b674a09704.png)
... and no, selecting each slot isn't an option.
Selecting single elements won't give you an overview. You can't see if the schedule is complete, or if you have forgotten to assign an action to a time slot.

What do you think about coloring the time slots?

Best regards,
Chris

### Additional info

![image](https://user-images.githubusercontent.com/4168250/151656799-1d281654-adc8-4310-97f6-a39171467b4e.png)

As you can see, having colors in the time scheme would be much clearer for the user. You can even see at a glance, that I forgot to set an action from 20:00 to 20:20.

**Comment by nielsfaber** [comment]
I agree this is a nice addition.
However, I’m not sure if it can be universally applied. In case of setting thermostat temperature, dimming lights etc. I think it’s not straight forward to provide meaningful colors. 
I would say that in temperature controls red=hot so I wouldn’t mark the slots where the thermostat is turned off in red.
What is your view on this?

About making it customisable, I’m not sure either. I think there are too many options already, it makes the card bloated. I rather make a choice that would appeal to the majority of people.
The history panel in HA also uses (non customisable) colors, perhaps it would be a solid choice to mimic its color palette.

**Comment by ChrislyBear-GH** [comment]
My view on this is, that you'll probably have a hard time implementing a color gradient for continuous settings like temperature, dimming percent, etc. because then you'll have to deal with people demanding to set up mutiple colors along the way like this:
![image](https://user-images.githubusercontent.com/4168250/151711928-3ceb4733-514a-457f-b74a-9367ca16e390.png)

But I think for discrete variables like on-off states and whathaveyou, this could be viable.

I also like the approach to mimic the HA history panel! Why not! People using HA are used to it, so the fact that it isn't customizable shouldn't be met with too much resistance, I think.

I don't know HA very well, but getting the state colors from the history component and displaying it would also give a sense of continuity throughout HA. The more I think about it, the more I like this apporach!

Unfortunately I can't contribute much in the way of actual code, since I'm not familiar with the HA integration and plugin model.

**Comment by nielsfaber** [comment]
I have done multiple attempts on implementing this, but I couldn't find a solution that works well for all actions.
For On/Off actions the colors may be easy to pick, but in case of a thermostat with multiple temperatures (and possibly combined with switching modes as well) it becomes really hard to define a good mapping to colors for all timeslots.
I close the request since I don't see a way forward.
