### ISSUE TITLE
conditions with GROUP entities

### ISSUE THREAD

**Issue by luka6000** [nielsfaber/scheduler-card#521]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.2

### Component Version

v3.2.6

### Bug description

I have group.residents entity which allows me to make conditions like 'if residents is away' or 'if residents is home'. This worked great up till v2.3.0 I think. Lately just noticed I can no longer change this condition for my group since groups are no longer available for conditions.
![2F231687-8712-450A-8F9C-B1037CE77F4C](https://user-images.githubusercontent.com/1110994/151694941-7a89d219-c36d-4d04-89d8-f59ac8d75be7.jpeg)
trying to edit
![5B5B2006-F2B0-43B1-8961-3F7DE50398F8](https://user-images.githubusercontent.com/1110994/151694938-48786925-650e-4854-8467-7c45712a00fa.jpeg)

### Steps to reproduce

make schedule
add condition
ENTITY GROUPS is not available for condition group selection
![09D83C63-FA03-4020-AAD2-6408598F2881](https://user-images.githubusercontent.com/1110994/151694923-163492e0-6ebf-473f-b7ce-6734430007dd.jpeg)

**Comment by febalci** [comment]
Same here, GROUP entites don't show up even tough i select it.

![Screen Shot 2022-01-30 at 13 58 27](https://user-images.githubusercontent.com/29440671/151696935-d88a9d85-2aff-467c-9aac-c0e75ba33d09.png)
![Screen Shot 2022-01-30 at 13 58 57](https://user-images.githubusercontent.com/29440671/151696928-3ca454aa-36ff-4f56-98f1-6dabda308985.png)

**Comment by nielsfaber** [comment]
@luka6000 I agree with this issue, will investigate what went wrong.
@febalci Your issue seems unrelated. I see you only have "1/3 selected" groups, so perhaps  your configuration is the issue? Scheduler only shows actions in case the entities have a common action. Is this the case?

**Comment by nielsfaber** [comment]
Apparently I left away some lines of code.
It is fixed by https://github.com/nielsfaber/scheduler-card/commit/f1fb97984c047fed2e2e5240108e6103b1218ac9
![image](https://user-images.githubusercontent.com/16861605/151697510-9cf6a0f9-e3ba-4714-98bc-76209ec9e6de.png)

Unfortunately I just released a new version 2 days ago, so I rather combine this improvement with others before releasing again.

**Comment by nielsfaber** [comment]
After updating to v2.3.3 the problem should be resolved.
Please test if this is the case, if so you can close the issue.
Otherwise please let me know.

**Comment by luka6000** [comment]
Your fix works as expected. Thank you!

**Comment by jackmcconnell** [comment]
I'm setting up a Scheduler Card but can't see 'Groups' under the 'Included Entities' that I can select from. 
I have a 'Family' group under Settings > Devices & Services > Entities with an entity ID of `group.family`. 
'Person' appears in the list of 'Included Entities' but not 'Group'. 

I'm using the latest version of the scheduler component and card from HACS - v3.3.6 and v3.2.13 respectively.
Can anyone offer any help in getting 'Groups' to show when setting up the card?
