### ISSUE TITLE
errors on startup

### ISSUE THREAD

**Issue by calisro** [nielsfaber/scheduler-card#523]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.2

### Component Version

3.2.6

### Bug description

Errors on startup.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:20:47 PM (2 occurrences)
Last logged: 9:20:47 PM

[548085209744] Received invalid command: scheduler
[548085209744] Received invalid command: scheduler_updated
```

### Steps to reproduce

upgraded to HA 2022.2.2

I only just installed this so I am not sure if this new to this version or if it is relevant to older versons...

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:20:47 PM (2 occurrences)
Last logged: 9:20:47 PM

[548085209744] Received invalid command: scheduler
[548085209744] Received invalid command: scheduler_updated
```

I saw this:

https://github.com/nielsfaber/scheduler-component/issues/77

but it is all installed and working just fine.

**Comment by calisro** [comment]
btw, downgraded to 2022.2.1 and no errors. I'll stay there till this is looked at.

**Comment by nielsfaber** [comment]
I am also on 2022.2.2, for me there are no issues.
I don't see any recent changes in the websocket_api component which might cause incompatibility.
I cannot help you.

**Comment by calisro** [comment]
I upgraded again and I don't see the issue.  I must have had something else going on (a number of issues with 2022.x).
