### ISSUE TITLE
Cannot remove conditions once set

### ISSUE THREAD

**Issue by Pigi-102** [nielsfaber/scheduler-card#524]
As the title says, I'm not able to remove a condition once I've created it on a schedule.
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
I go to the condition and pressing delete and then save she get removed

### Actual behavior
[What actually happened]
I go to condition, press delete then save, she seems to be removed but as i reopen the schedule she is back again.

### Steps to Reproduce
[Explain how to see the behaviour]
Create a schedule ( make scheme) ,  click on options, add a condition, save. 
Go in scheme again, click option, delete the condition, save
Go in scheme, click option, and the condition is still there.

**Comment by nielsfaber** [comment]
Thanks for reporting this. 
I saw the same behaviour, it was caused by a recent change I made.
The issue is patched in https://github.com/nielsfaber/scheduler-card/commit/309fb4699def774133487c136448cc5631e61f6f.
I will update you once this is released.

**Comment by nielsfaber** [comment]
After updating to v2.3.3 the problem should be resolved.
Please test if this is the case, if so you can close the issue.
Otherwise please let me know.

**Comment by Pigi-102** [comment]
It seems fixed. Thanks a lot !!!!
