### ISSUE TITLE
Enable Offset with multiple actions

### ISSUE THREAD

**Issue by Rasenkantenstein** [nielsfaber/scheduler-card#525]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I have some manually configured MQTT shutters that I want to schedule with the card (6 covers). 
However, I believe that opening or closing 6 covers at once is too much for my home assistant. I observed that only actions for four shutters are triggered concurrently.

I suggest to enable a sequence with maximal parallelism:

The sequence will control all (e.g. 6) entities. The max. parallelism is then a variable number, e.g. 2. And then there's an offset, which may also be configurable.

### Additional info

1. start of sequence
2. trigger the first max. parallel entites: 2
3. wait the offset time (e.g. 1 second)
4. trigger the next max. parallel entities: 2
5. wait 
6. trigger 2
7. sequence ended

**Comment by nielsfaber** [comment]
I think this is too complex for scheduler.
If you want to trigger entities at different times, you should simply make multiple schedules with different timing.
Alternatively you could use scheduler to run a script which executes a sequence as you describe.
