### ISSUE TITLE
Change Daily time Sunrise <--> Sunset is not saved

### ISSUE THREAD

**Issue by oferbar** [nielsfaber/scheduler-card#528]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.3

### Component Version

v3.2.6

### Bug description

I have multiple schedules. A specific one is turning off few lights 1 hour before sunrise daily.

When I change Sunrise to Sunset and then save the schedule, it is actually not saved. I open the card again and it is still showing Sunrise (not Sunset).

This behavior is consistent.

![image](https://user-images.githubusercontent.com/1737075/153040530-7aa547a7-7377-423b-9784-0ca885094c7f.png)

### Steps to reproduce

1. Set a daily schedule to turn off some lights 1 hour before sunrise and Save.
2. Open the card and change it to Sunset, Save.
3. Open the card again - it is back to Sunrise.

**Comment by nielsfaber** [comment]
Thanks for reporting this, I never noticed it.
It should be solved in v2.3.4.
Please test it and close the issue if it is resolved, else let me know.

**Comment by oferbar** [comment]
Yes, the issue was resolved after upgrading to v2.3.4
Closing the case, thank you!
