### ISSUE TITLE
Expose the generated schedule name as an attribute/friendly_name

### ISSUE THREAD

**Issue by LazyTarget** [nielsfaber/scheduler-card#529]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

One of these alternatives:

1. Add the generated schedule name as an attribute (non-breaking change)

    ![image](https://user-images.githubusercontent.com/959409/153073516-147b8148-57bd-40c9-ac8c-3e35d36ad057.png)

2. Replace the `friendly_name` attribute instead. This will break the existing names and could potentially not be unique anymore. _Note that the `entity_id` could still be unique._

### Additional info

Hi!
I really like the auto-generated name of the schedules created in the card. 

However if I tried to render the switch entity in say an auto-entities card, then the unique schedule name is displayed, example `Schedule #940581`

Instead I want to display the generated name based by the selections made, example: `Hall lights: Turn off`

![image](https://user-images.githubusercontent.com/959409/153071377-9c1bb563-c147-4c0b-b624-461a2fe71994.png)

If the "generated" schedule name was added as an attribute on the switch-entity, I could configure the auto-entities card to display the attribute instead.

My original reason for displaying the switches outside of the schedule-card is primarily for the possibility to add a "tap-action" and thus giving the option to run the schedules instantly (and also exposes schedules in as read-only way).

This could in a way solve #298 

Best regards,
//Peter

**Comment by LazyTarget** [comment]
I guess the same applies to the entity icon

**Comment by nielsfaber** [comment]
What you are referring to is not the name of a schedule, it is the action description.
All intelligence to create this description resides inside the card, so outside of the card you will not be able to access this.

However it is possible to customize the card such that it will look exactly like the entities card (hide the extra properties, also the 'add' button can be hidden).
