### ISSUE TITLE
Provide a service to re-assess if actions should fire based on scheduler and last timepoint

### ISSUE THREAD

**Issue by timdonovanuk** [nielsfaber/scheduler-card#530]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I saw the following in the documentation:

> "This means that if the conditions are not met, the timer event will be skipped. It will not be re-evaluated when any of the entities involved in the conditions change."

I am proposing a homeassistant service that may be called to have scheduler card reassess if any actions should trigger.

### Additional info

The use case is:

1. I use scheduler-card to control my heating
2. I create a "boost" button for my heating, that boosts the heating on for 60 mins at full blast
3.  scheduler-card checks if boost is on, and if it is on, it does not fire 
4. "boost" finishes and ideally I want scheduler-card to reinstate the natural order of things 
5. I would use an automation so when "boost" is off, it calls service.schedule-recheck 
6. service.schedule-recheck would look at the last relevant action that should have triggered and rerun/revaluate it

Thank you :) Just a thought, and completely understand if its too complex.

**Comment by nielsfaber** [comment]
There are numerous features already in place to solve your use-case:
1) As @sddgit says, you can toggle a schedule entity to re-trigger it
2) There is the service `scheduler.run_action` which you can use to re-trigger it 
3) In case you use timeslots, you can assign a condition and mark 're-evaluate when the conditions change'
