### ISSUE TITLE
Condition shown partially (no state value) IMHO

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/scheduler-card#534]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.3

### Component Version

v3.2.7

### Bug description

Condition editor show entered state:
![image](https://user-images.githubusercontent.com/15225823/154327873-24845c62-c3f4-415d-8787-fd40c5001872.png)

But in Options screen state not visible:
![image](https://user-images.githubusercontent.com/15225823/154328017-f3735a47-0ed2-4c83-99a8-a8bf793b35a7.png)

Is it expected ?

Same for f.e. illuminance sensor:
![image](https://user-images.githubusercontent.com/15225823/154328218-79ebee4c-bb98-459f-ad8c-9e87cdbc4e2a.png)

### Steps to reproduce

Created condition.

**Comment by nielsfaber** [comment]
Thanks for reporting this, I never noticed it.
It should be solved in v2.3.4.
Please test it and close the issue if it is resolved, else let me know.

**Comment by Masterz69** [comment]
Yes, now (v2.3.4) condition visible in full:
![image](https://user-images.githubusercontent.com/15225823/156897080-7ed2f7cc-9f93-4185-a5a1-ef36f4373075.png)

Thank You very much.
