### ISSUE TITLE
Changed existing  schedule time 

### ISSUE THREAD

**Issue by menocode** [nielsfaber/scheduler-card#536]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.3

### Component Version

3.2.7

### Bug description

expected to save 

received this error message 

Something went wrong!
Message format incorrect: value must be one of ['and', 'or'] for dictionary value @ data['timeslots'][2]['condition_type']

Response error: 400

Please [report](https://github.com/nielsfaber/scheduler-card/issues) the bug.

### Steps to reproduce

moved slider on existing Climate schedule that has been working. Received message to report. tried several times, happened every time.

**Comment by SunilKhusal** [comment]
I also tried to change the times on a schedule and when press save I get the following error and reverts back to original schedule:

```
Something went wrong!
Message format incorrect: value must be one of ['and', 'or'] for dictionary value @ data['timeslots'][3]['condition_type']

Response error: 400

Please [report](https://github.com/nielsfaber/scheduler-card/issues) the bug.
```

**Comment by nielsfaber** [comment]
I'm unable to reproduce this problem.
Could you share the configuration of the schedule for which this happens?
Does it have conditions configured?

**Comment by dsgcasa** [comment]
good morning
I have the same problem at the moment of saving when I try to move a time slot, 
attach images thank you

Something went wrong!
Message format incorrect: value must be one of ['and', 'or'] for dictionary value @ data['timeslots'][1]['condition_type']
Response error: 400
Please report the bug.

![Cattura01](https://user-images.githubusercontent.com/98041633/156993745-b621523e-2d00-45a6-a6ad-11a83d14d9d8.JPG)
![Cattura02](https://user-images.githubusercontent.com/98041633/156993776-1602a2b2-cf0a-48ae-9e6a-90dd4a8fe616.JPG)

**Comment by dsgcasa** [comment]
now I have tried deleting and recreating the time slots. it is now possible to edit and save the time change, however the lovelace page hangs
![Cattura03](https://user-images.githubusercontent.com/98041633/156998086-7df1b07e-87f5-4d6b-911a-64d4ab9fac2b.JPG)
.
