### ISSUE TITLE
Add options to disable changing days & action of a schedule

### ISSUE THREAD

**Issue by JeffersonBledsoe** [nielsfaber/scheduler-card#537]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

There is currently an option to disable the `add` button to prevent users from adding other schedules. It would be nice if we were able to have even more control over what can be used on the card by having options to enable/ disable the action chooser, the day chooser and/ or the time chooser. My use case for this is for somebody in my house to be able to use the schedule card to select the time for a script to be triggered, but for them not to be able to change the action that is performed or the days it is performed on. Having separate options for each part of the UI would make this change more generic. This would be a backwards compatible change as the option would be enabled by default.

### Additional info

The option to show/ hide the add button is currently only available in the YAML editing mode. Another couple of keys to enable/ disable the 'ACTION', 'DAYS' and 'TIME' parts of the UI would match this functionality.

**Comment by JeffersonBledsoe** [comment]
Not stale

**Comment by nielsfaber** [comment]
Why should a user have the possibility to change the time for a schedule but not the day?
This sounds like a very specific request to me, I doubt that anyone besides you would benefit from such functionality.

**Comment by JeffersonBledsoe** [comment]
> Why should a user have the possibility to change the time for a schedule but not the day?

Hi @nielsfaber. One setup I can imagine this being useful is using the scheduler card for setting an alarm on a dashboard. Users could set times, but the day would be fixed by the 'admin'. This is do-able with input helpers with core Home Assistant currently, but I figured having the user experience all tied together by the scheduler card could be useful? Happy to close this issue if you feel it's too specific!
