### ISSUE TITLE
Scheduler - Scheme Mode - Thermostat Auto

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [nielsfaber/scheduler-card#544]
### Card Version

Latest release

### Bug description

I just discovered the "Make Scheme" button, which is absolutely fantastic for thermostat scheduling.

First of all, THANKS for making this feature. Its amazing. I sent you a "few cups of coffee"

Second of all-

You cannot set a temp when using auto mode. 

You can only set temp when using heat or cool. However, many mini splits have auto mode. 

This functionality does exist within home assistant (and works via the climate card), however, the make scheme card cannot seem to handle this.

Also, this may or may not be a duplicate of https://github.com/nielsfaber/scheduler-card/issues/531

**Comment by XtremeOwnageDotCom** [comment]
![image](https://user-images.githubusercontent.com/5262735/160001493-c2032d8a-a6b7-45ea-88e5-38711b571485.png)

**Comment by XtremeOwnageDotCom** [comment]
![image](https://user-images.githubusercontent.com/5262735/160001555-47c59d2f-6595-4563-98be-9e4a45a699c1.png)

**Comment by nielsfaber** [comment]
Thanks a lot for the coffees! It's a good motivation to keep improving things 👍 

As for your issue, it has been addressed multiple times. See https://github.com/nielsfaber/scheduler-card/issues/541#issuecomment-1066100709 for my response.

**Comment by XtremeOwnageDotCom** [comment]
Hey, You deserve far more for the work you have done on home assistant.

Between this, and alarmo, those are two extremely solid integrations.

Thanks for a response/solution!
