### ISSUE TITLE
Let the auto-turn-on-after-edit feature be disabled (to get back the previous behaviour)

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#547]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Commit 10e5db904d819ea82a096e9ac705af4830b045fd fixing #500 added line [L292](https://github.com/nielsfaber/scheduler-card/blob/main/src/scheduler-card.ts#L292), so currently after any modification the schedule is turned on.

I have a lot of schedules and automations are turning them on and off. Before this breaking change, it was possible to edit a disabled schedule, ie. fine tune some "future" parameters without affecting current system behaviour. Currently when I modify a schedule in a slightest way, it gets turned on momentarily and an automation has to turn it off immediately, but this glitch turns on relays, pumps, etc. momentarily, and this is not healthy for them.

Auto-reenable is useful if we have only a few schedule, or most of them are turned off and we want to "edit-and-enable" one of them, but with a complex system this is a pain.

### Additional info

An optional card configuration option something like `auto_reenable` with default `true` would be a great help to set it manually to `false` and restore the original behavior.

**Comment by sddgit** [comment]
I agree with this request. I’ve been caught out a couple of times with schedules being activated after an edit, and it’s caused some “dangerous” situations with equipment dependencies.

**Comment by lmagyar** [comment]
In my view it was a breaking change.

I can't develop UI projects on my old environment, but I'm happy to test it, if somebody creates a PR.

**Comment by lmagyar** [comment]
I've tried to build this project on github with a workflow/action, but I've failed miserably. If anybody can help to build it on github, I will try to make a PR with this functionality restored optionally. See: https://community.home-assistant.io/t/scheduler-card-custom-component/217458/1639

**Comment by nielsfaber** [comment]
I think this is a very subjective request.
To my opinion the changed functionality is useful for the majority of users, but as with anything there are always exceptions.
We can debate whether this is intuitive, but as discussed in #500, you will see the same behaviour when you change the settings for a disabled timer in Android and iOS, so it's definitely not a unique choice.

It's hard to keep all users satisfied, I have to make choices here and there (this function was definitely not added to bother you).
I don't feel much for adding additional configuration parameters. If you ask me, there are already too many, the card editor GUI is simply too full.

Maybe as a compromise solution: would it be helpful if the card shows a popup upon saving changes to a disabled schedule with whether or not you want to enable it?

**Comment by sddgit** [comment]
Oh yes, that would be perfect I’d say!

**Comment by lmagyar** [comment]
Yes, for a simple alarm like use case it perfectly makes sense. Absolutely agree. I use it every day on my phone. "But"...
- An alarm like _schedule_ makes an action **in the future**, so a temporary on-off glitch is not a problem in the present.
- Meantime a _time-scheme_ makes actions **immediately**, it changes relay states, room target temperatures etc. immediately, a glitch is a problem (eg. 1kW AC motors and their relays are not happy with this glitch).

I think a popup would disturb most of the people, usually less click is better. But it is only a guess.

Maybe we should differentiate between _"schedule"_ and _"time scheme"_.
- Auto-enable-after-edit a schedule (the thing that has a time in the future to do an action), current version
- **Do not** auto-enable-after-edit a time scheme (the thing that has a 0-24h pattern, and when turned on it executes an action immediately), maybe this change only is enough

I think this small change is better then a popup, less interaction, less config.

**Comment by lmagyar** [comment]
Not stale, the problem still exists.

**Comment by nielsfaber** [comment]
@lmagyar I decided to add a dialog and leave up to the user whether a schedule needs to be re-enabled.
I personally see it unintuitive if the behavior depends on the type of schedule, I think we shouldn't assume people will fathom this.
Could you please update to the v2.3.5 release and test it out?
I hope we can close the issue now, otherwise please share your findings.

**Comment by lmagyar** [comment]
Really thank you for the modification! Yes, it's perfect!

And excuse me for my extreme slow reply, I wanted to modify my scrips also before closing, but certainly this is independent from this solution.
