### ISSUE TITLE
Home Assistant 2022.4 appears to have broke the card. Integration not loaded error

### ISSUE THREAD

**Issue by BrandonSanders48** [nielsfaber/scheduler-card#548]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.4

### Component Version

3.2.7

### Bug description

Card shows "Could not connect with scheduler component. It needs to be installed as integration before this card can be used"

Both the card and integration are installed. Integration is loaded and is shown on integrations page.

### Steps to reproduce

Update HA to 2022.4

**Comment by nielsfaber** [comment]
I'm running HA 2022.4 here without issues.
Please update the scheduler-component to 3.2.8, it contains some change for compatibility with the new HA release.

**Comment by denniskoenders** [comment]
Had the same issue after HA update 2022.4. Fixed after Scheduler update 3.2.8 :) 
Thanks.

**Comment by BrandonSanders48** [comment]
Perfect, thank you!

**Comment by pacmac** [comment]
Hmm, I am on the latest HA 2022.4 and version 3.28 and it's broken for me:
<img width="509" alt="Screenshot 2022-04-08 at 6 55 03 PM" src="https://user-images.githubusercontent.com/2349856/162422203-12026646-d41f-46ff-9cf7-3da8b466d576.png">

**Comment by mariusmotea** [comment]
Seams this issue triggered again on the release 2022.5.1
