### ISSUE TITLE
After restart HA automation is turned on

### ISSUE THREAD

**Issue by shevu** [nielsfaber/scheduler-card#55]
Step to reproduce:
1. Set schedule and turn it off
2. Turn off host: Supervisor -> System -> Host system SHUTDOWN
3. Run system again
4. After system run the schedule is turned on

Maybe it is not a bug and I missed something?

**Comment by nielsfaber** [comment]
Sounds like a bug, thanks for reporting.
Can you please add your issue here: https://github.com/nielsfaber/scheduler-component/issues ?
This repo is only for the Lovelace card, your bug is caused by the custom_component itself.
