### ISSUE TITLE
Randomize times

### ISSUE THREAD

**Issue by TorbenEC** [nielsfaber/scheduler-card#550]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Please add the option to randomize times.

### Additional info

For instance, if "Randomize times" is set to 30 min, it will trigger  between 15 min before and 15 min after the selected time.

**Comment by ajavibp** [comment]
I think it would be a very interesting feature to program presence simulations during the holidays. Now you can do it with the programmer, but the hours are always repeated, and that is very easy to detect.
I sign up to the request

**Comment by volodiakira** [comment]
I would also like this feature to be integrated; the basic scheduling system is very well designed, but it lacks this function for vacation absences.
