### ISSUE TITLE
Add personal condition curtains

### ISSUE THREAD

**Issue by ZeroKing666** [nielsfaber/scheduler-card#552]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

add more condition to blinds/curtains instead of just open or closed conditions

### Additional info

add condition to blinds/curtains like "when open more than 60%" or "less than 80%" instead of just open or closed

**Comment by ZeroKing666** [comment]
Is it necessary to add more information to the request?

**Comment by nielsfaber** [comment]
No, but it will not be added. 
In scheduler you can only use the state of an entity as condition, else things become quite complex real quickly.
I would recommend to create some template binary sensor which indicates whether the position is more than X.
