### ISSUE TITLE
Unable to set temperature

### ISSUE THREAD

**Issue by Exit2Studios** [nielsfaber/scheduler-card#555]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.4

### Component Version

v3.2.8

### Bug description

I am unable to set temperature values for my climate entity since I updated it from ZHA to Zigbee2mqtt.
![image](https://user-images.githubusercontent.com/16908875/165999575-c6510879-4282-47ce-a130-448fe5267445.png)

I have the following attributes available in the climate entity, so not sure why it's not working.
![image](https://user-images.githubusercontent.com/16908875/165999682-20ee865c-fe5b-46f2-bbef-589b2e8b475d.png)

### Steps to reproduce

Add new card and create schedule scheme.

**Comment by nielsfaber** [comment]
Supported_features=10 means your entity does not support setting a temperature.
I can not help you I’m afraid, also this is not a bug in scheduler-card.

**Comment by nielsfaber** [comment]
For completeness, see here: https://developers.home-assistant.io/docs/core/entity/climate/#supported-features
The `TARGET_TEMPERATURE` (=1) is not advertised by your entity. Supported_features have an odd (uneven) value in case it does.
