### ISSUE TITLE
Feature request: Change climate preset

### ISSUE THREAD

**Issue by aeklo** [nielsfaber/scheduler-card#56]
Really like the scheduler! Have you considered the option to change climate preset (home/away) at selected times instead of temperature?

**Comment by nielsfaber** [comment]
Do you mean using [climate.set_preset_mode](https://www.home-assistant.io/integrations/climate/#service-climateset_preset_mode)?
I don't have a very smart thermostat in my house, I just send it a setpoint and it will decide whether it should turn on.
It does not support setting a preset.

[Looks like](https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/__init__.py#L342) i can read `supported_features` to detect whether a thermostat supports presets and i can also read the list of presets.
So it should be fairly simple to add this.

**Comment by aeklo** [comment]
Would be happy to test. I set both my comfort and eco temp using the native HA thermostat, but I miss a way of scheduling the changeover :)

**Comment by mycanaletto** [comment]
+1

**Comment by KTibow** [comment]
@mycanaletto please don't keep giving me notifications, just hit the +1 button.

**Comment by mycanaletto** [comment]
ok
OK, I had some ideas but first I was looking at what was required.

And bravo for what is already done!

**Comment by nielsfaber** [comment]
I added the `set_preset_mode` in the v1.5.0. It works for me, but please test it as well 🙂 
If you use standard_configuration (enabled by default), it should come up automatically with the right options.
See more [here](https://github.com/nielsfaber/scheduler-card#list-action-variable)

**Comment by aeklo** [comment]
Yes, this works great now! Thanks! :-)

**Comment by KTibow** [comment]
Consider closing?
