### ISSUE TITLE
Include option to exclude disabled items

### ISSUE THREAD

**Issue by pterisaur** [nielsfaber/scheduler-card#564]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I like how we can customize the card to only include specific tags. It would be great to also have the option to hide disabled schedule tasks — these would still be available behind the "# excluded items" link.

### Additional info

This option could be a toggle in the configuration, or just a true/false in the YAML.

**Comment by nielsfaber** [comment]
As alternative for your request I would propose to have schedules automatically be assigned with a tag `enabled` or `disabled` depending on their state. 
Then you can filter them by assigning these 'built-in' tags to the card (same way as there is currently tag `none` assigned to schedules having no tags).

**Comment by nielsfaber** [comment]
This feature is added to release v2.3.5.
Schedules are now automatically assigned with a `enabled` / `disabled` tag based on the switch state.
Could you please update to this version and test it out?
You can close the issue if the request is fulfilled, otherwise let me know.
