### ISSUE TITLE
Not all operation modes being choosable for climate devices

### ISSUE THREAD

**Issue by Chaos02** [nielsfaber/scheduler-card#568]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

Latest

### Bug description

I have a (custom) integration providing multiple modes for an AC device. At the moment there are following actions to choose when selecting the AC device and `Set mode`: 
- `Dry`
- `fan only`

However the modes, that the integration provides are:
- `Heat/Cool`
- `Heat`
- `Cool`
- `Dry`
- `Fan only`
- `off`
This same issue persists with fan modes iirc.
This renders me unable to for example change to the cooling operation from using 'dry' via the scheduler card, or even turning off the device.

> (Yes, there is a turn off button as an action but this vastly differs from HA's native layout when clicking the three dots on an entity (entity details menu))

A solution for this would be to read the corresponding device mode dictionaries for the selected device like when doing the call via service.

Also would it be great to have multiple scheduled actions I.E. for different devices but this is incompatible with the current configuration layout ('walk-through' style)

### Steps to reproduce

Use the card with more or less uncommon integration control.
This issue may also arise with many other integrations, tho.

**Comment by nielsfaber** [comment]
Scheduler checks the `supported_features` as well as the `hvac_modes` of the climate entity to decide which actions show up.
> However the modes, that the integration provides are:
Heat/Cool
Heat
Cool
Dry
Fan only
off

These modes are all supported by the card. 
However:
* For modes Heat/Cool, Heat, Cool separate actions are created, which also allow the user to set the temperatures (IMO setting such mode without temperature is not useful). 
* For mode off (not much of an operation mode IMO) there is the action 'Turn off'. Some climate entities support climate.turn_off, other require climate.set_hvac_mode with mode=off. Scheduler shows the best fit.
* Which leaves only Dry, Fan Only, Auto modes as options under the 'Set Mode' action.

Example for a climate entity (this particular device doesn't have support for the Heat/Cool and Dry modes):
![image](https://user-images.githubusercontent.com/16861605/173248167-ba742539-d5fa-4f28-aa13-e7cb43e8d11f.png)

What exactly is missing from your point of view? I don't really understand the request (/bug?).

**Comment by Chaos02** [comment]
Okay then I'd like to rephrase my issue to: inconsistent user interface in comparison to Lovelace. ^^'
It is difficult to navigate the interface if one already learned another interface in the same context.
I agree that one should be able to set the temp but I would also argue that lovelace would let me suggest that it just turns the device on.

**Comment by Chaos02** [comment]
it indeed would be a step backwards, I completely agree!
But: sometimes uniformity is better than having two ways of handling the same thing in the same context :shrug:
