### ISSUE TITLE
Feature Request: Sun Elevation

### ISSUE THREAD

**Issue by jasonalsing** [nielsfaber/scheduler-card#57]
I like your scheduler card, am looking to possibly migrate my simpler automations (those without conditions) but I realize one of my outdoor lights is scheduled based on sun.elevation (less than -4 degrees, eg "dusk")

Is it possible to add this type of time variable (I know there is already "sunset" but that is quite too early to put on the lights)

Thanks!

**Comment by KTibow** [comment]
You can offset by a set amount of time.

**Comment by jasonalsing** [comment]
Yes I was about to edit my comment, I'm aware of the offset but that changes throughout the year...

**Comment by KTibow** [comment]
So then as well as:

- A toggle between before or after
- A toggle between sun offset and fixed time

You also want a toggle between time and elevation?

**Comment by jasonalsing** [comment]
well it would be an alternative to those. so no time element or offset or sunriset/sunset. just trigger when the elevation goes below/above a value. this is what it looks like in my current setup:
![image](https://user-images.githubusercontent.com/38263272/93796615-b845c080-fc00-11ea-910c-b40082bf102c.png)

**Comment by nielsfaber** [comment]
I never used sun elevation myself, but my understanding is that it tells something about the season, not the time of the day.
A low sun angle indicates a darker period, say winter months. Right?

**Comment by KTibow** [comment]
The sun is low at night, and high at day. It's how high the sun is in the sky.

**Comment by KTibow** [comment]
Also @jasonalsing you don't need the value template now, you can use the attribute value.

**Comment by nielsfaber** [comment]
Ah ok, so i was probably talking about azimuth instead. Or something. 😕 
Well, my understanding of it is very limited.
 I guess very few people know what they will get when they program a schedule to trigger at certain sun angle.
One of my key goals for this card is to keep it intuitive, not too many whistles and bells.
I would say that this kind of feature is quite complex to understand.

If if would help you if dusk and dawn are added, or you want to allow higher offset w.r.t. sunrise/sunset, this is discussable though.

**Comment by KTibow** [comment]
Maybe you could add a tooltip like "How high up the sun is in the sky".

**Comment by jasonalsing** [comment]
> Also @jasonalsing you don't need the value template now, you can use the attribute value.

Yes, Thanks that is a great new update. 

>I would say that this kind of feature is quite complex to understand.

Perhaps you are right, this scheduler is probably better suited for basic time schedules.  I think "dusk" or "dawn" is simple enough as well, though there brings in other nuance such as various "dusk" (civil, nautical, astronomical) to use.

**Comment by nielsfaber** [comment]
I will consider to add dawn and dusk to the options. The times will be taken from the sun.sun entity.

**Comment by nielsfaber** [comment]
I am closing this request, don't want to create the false expectation that support for triggering on sun elevation will ever come.
The scheduler-component has support for dawn and dusk options, but I don't see an easy way to integrate it in the card..

**Comment by hubikj** [comment]
> ...The scheduler-component has support for dawn and dusk options, but I don't see an easy way to integrate it in the card..

Can you please tell me where is this feature documented? I did not find it anywhere.

**Comment by sddgit** [comment]
> Can you please tell me where is this feature documented? I did not find it anywhere.

I believe this is referring to the scheduling component that sits behind the scheduler card. Or maybe you already knew this…

**Comment by hubikj** [comment]
I searched both repositories and did not find it.

**Comment by Otiel** [comment]
> > ...The scheduler-component has support for dawn and dusk options, but I don't see an easy way to integrate it in the card..
> 
> Can you please tell me where is this feature documented? I did not find it anywhere.

I'm also interested, and [could not find anything in `scheduler-component`](https://github.com/nielsfaber/scheduler-component/search?q=dusk).

Although like @jasonalsing original request, I would prefer to be able to use `sun.elevation` as a trigger. It would allow to configure more finely a dusk / dawn time, while staying valid throughout the year unlike an offset against sunrise/sunset.

It's well explained in Home Assistant docs [here](https://www.home-assistant.io/docs/automation/trigger/#sunset--sunrise-trigger):
>Since the duration of twilight is different throughout the year, it is recommended to use sun elevation triggers instead of sunset or sunrise with a time offset to trigger automations during dusk or dawn.

and [here](https://www.home-assistant.io/docs/automation/trigger/#sun-elevation-trigger):
>Sometimes you may want more granular control over an automation than simply sunset or sunrise and specify an exact elevation of the sun. This can be used to layer automations to occur as the sun lowers on the horizon or even after it is below the horizon. This is also useful when the “sunset” event is not dark enough outside and you would like the automation to run later at a precise solar angle instead of the time offset such as turning on exterior lighting.
>[...]

> I am closing this request, don't want to create the false expectation that support for triggering on sun elevation will ever come. 

Maybe you would be inclined to change your mind since then? ☺
