### ISSUE TITLE
Make it work for mower / vacuum

### ISSUE THREAD

**Issue by cm86** [nielsfaber/scheduler-card#572]
### Checklist

- [x] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Is it possible to add the behavior to work with a mower?
I have a landroid mower it's connected to home assistant via landroid cloud (my mower is visible as vacuum).

So i wan't to make a schedule via home assistant.

So if i add a schedule it looks like this...
![image](https://user-images.githubusercontent.com/14919688/174767314-ac174808-7154-4128-89a2-6d6a907d9972.png)

But actually my mower is docked and fully loaded but it doesn't start.
So here another trigger could be interesting.

Also it could be nice to have some option condition to set just a certain timeframe to (so if the mower should start, the battery should be over 90%, but this should not be used for the timeframe where he should not mow)

### Additional info

To edit the trigger would be nice. 

Maybe you add an extra option for every timeframe.

**Comment by nielsfaber** [comment]
> But actually my mower is docked and fully loaded but it doesn't start.
So here another trigger could be interesting.

This seems device specific.
Scheduler only implements generic functions.
If you know which service to call to make the mower start, you can add it manually to the card ([example](https://github.com/nielsfaber/scheduler-card#actions)).

> Also it could be nice to have some option condition to set just a certain timeframe to (so if the mower should start, the battery should be over 90%, but this should not be used for the timeframe where he should not mow)

If you have a sensor entity for the battery level, you could add a condition that it should be above 90 (click 'options' in the card).

**Comment by cm86** [comment]
> This seems device specific.
Scheduler only implements generic functions.
If you know which service to call to make the mower start, you can add it manually to the card ([example](https://github.com/nielsfaber/scheduler-card#actions)).

I know wich Service to call.
But if my timeslot is lets say from 01:00 AM until 08:00 AM the mower just starts at 01:00:00 AM (if the conditions match)

> If you have a sensor entity for the battery level, you could add a condition that it should be above 90 (click 'options' in the card).

Yes i have a sensor for the battery-level but it looks like the conditions also have to match if i want the mower to stop/go home

**Comment by nielsfaber** [comment]
To me it is not clear what you want to achieve and what you cannot configure using scheduler.
