### ISSUE TITLE
Minimum hour: 0:30 / maximum hour: 23:30

### ISSUE THREAD

**Issue by LeidenSpain** [nielsfaber/scheduler-card#575]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v 2.3.5

### Component Version

v 3.2.10

### Bug description

Hi,

I have created a scheduler with the idea of starting a socket at the earliest of the day and turning it off at the latest (0:05 - 23:55).
But the card won't let me go below 0:30 and not even above 23:30
![image](https://user-images.githubusercontent.com/45803748/175820857-26808f58-a9ca-45bf-a80d-d6acd6510777.png)

I have tried to create another schedule on the same tab, and that one does appear at 0:20, but when the new one appears again at 0:30.

I have the card configured so that the time jumps are 10 minutes.

Regards

### Steps to reproduce

1) Create a scheduler with planning
![image](https://user-images.githubusercontent.com/45803748/175821098-cb3f26ad-9f68-4840-b40c-51172191ae2b.png)

2) Move the on and off position to the extremes
![image](https://user-images.githubusercontent.com/45803748/175821134-142ebd14-3ae7-4cda-a230-e207dd2743a6.png)

**Comment by LeidenSpain** [comment]
Hi,
Is there any answer regarding this problem?
Regards,

**Comment by nielsfaber** [comment]
@LeidenSpain This is not a bug.
What you are seeing is just the limitations of the card.
It is mainly due to the lack of card width.
Some people choose to modify this, for example see https://community.home-assistant.io/t/how-to-make-a-card-wider-using-layout-card/401624

**Comment by ed-holland** [comment]
Would an alternative input of the Time be an alternative?
