### ISSUE TITLE
Cannot Set Date Period in Schedule Options

### ISSUE THREAD

**Issue by taylormia** [nielsfaber/scheduler-card#576]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.5

### Component Version

3.2.10

### Bug description

When I attempt to set a date period on a schedule untder Options, selecting a From and To date in the pop-up calendar does not change the Start and End dates. I have also tried just changing the text of the Start and End dates but with no effect. See attached GIF.

### Steps to reproduce

See attached animated GIF
![brave_LucQeTER8X](https://user-images.githubusercontent.com/34145387/176237583-d29eca8d-761a-4d93-b04d-811455edf47f.gif)

**Comment by nielsfaber** [comment]
This is a bug in HA. It's not caused by scheduler card.
You can click the text (date) instead of the icon, and it should work.

**Comment by taylormia** [comment]
OK. Clicking on the date text allows setting the period, but that's screwed up too. When I select the actual date in the pop-up calendar, it enters the previous date in the text. So, to get my correct date period of Jul 1 to Jul 5, I need to select Jul 2 ro Jul 6 in the calendar. Any idea when this will be fixed? btw, thanks for this wonderful component and card !!
![brave_2J1rcTnMRO](https://user-images.githubusercontent.com/34145387/176243100-07671011-c56d-4540-9863-49eb8cec56a3.gif)

**Comment by nielsfaber** [comment]
You should report your problems in the [HA frontend repo](https://github.com/home-assistant/frontend/issues), not here. It's out of my control.

**Comment by taylormia** [comment]
Sounds Good. Thanks
