### ISSUE TITLE
anyway to hide time remaining until next action if only condition is active?

### ISSUE THREAD

**Issue by Marcoske23** [nielsfaber/scheduler-card#578]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Some automations I have do not depend on the schedule but on sensor states so it is not necessary that I have the remaining time because it does not really exist. any way to hide it?

### Additional info

Show only time remaining when the time is set. Otherwise, return state of sensor if exist

**Comment by nielsfaber** [comment]
This is not possible.
Scheduler does not keep track of the conditions continuously.
The conditions are only checked on the scheduled time.
So it is not known in advance whether a scheduled time needs to be skipped.
If you want this, its better to turn off/on the schedule completely based on conditions (with an external automation).
