### ISSUE TITLE
Multiple switching points in the schedule (e.g. 5x. only ON) without defining an ON-OFF-range

### ISSUE THREAD

**Issue by Hannah-Bee** [nielsfaber/scheduler-card#581]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

When I create an entry I have either the choice between
- a one-time switch on/off (at 12:00 ON)
- or a schedule, where I have to define ranges from when to when something should be switched on/off. (from 12-12:10 ON and from 16-16:10 ON  and from 20-20:10 ON.

What I miss (and what would help me a lot) would be a schedule where I can define (like with one time switching) several e.g. ON-times, without having to define an ON-OFF-range. (at 12:00 ON and at 16:00 ON and at 20:00 ON). 
The input of several such switching times (e.g. 5x ON-times) would also be much easier and faster without the need to define a range.

The background is that I start a script at the respective time that switches off automatically after expiration or when other triggers occur. The schedule does not have to do that. On my contrary, I am even afraid that the script will be activated again by the scheduler if it switches itself OFF within a defined ON range.

### Additional info

At the moment you have to select the range in the schedule and define whether the range should be switched on or off. 

For my request, it would no longer be necessary to select the range, but only the individual switching time. If this is selected, one can define beside the "Time Control Mode" also simply whether the switching time is to be switched on or off.

![ha](https://user-images.githubusercontent.com/84235452/179394184-9486b012-dd4f-419b-a79f-0e177274bda7.jpg)

**Comment by nielsfaber** [comment]
I'm sorry but there is a limitation in the scheduler to choose between:
- Single timepoint
- Time scheme, consisting of several time slots, where each slot has a start and end time

A combination of time scheme with single timepoints is currently not possible (and would be a lot of work to make possible). The limitation is mainly GUI related.
The best option for now would be to either split the schedule in multiple single timepoints, or create time scheme with very short slots (in between you can add slots without action).
