### ISSUE TITLE
Add "button" domain

### ISSUE THREAD

**Issue by larry-glz** [nielsfaber/scheduler-card#582]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The "button" domain does not show up in the "INCLUDED ENTITIES" list.  Adding "- button" to the include: section via yaml does not work.  

### Additional info

Add the ability to add "button" domain.  For example:

type: custom:scheduler-card
include:
  - button

Thanks!  Great work on this one...

**Comment by nielsfaber** [comment]
I added this just now: https://github.com/nielsfaber/scheduler-card/commit/23f943f546bbb6885c756fad9434f081b3e41fc5
It will be part of the next release.
I will trigger you when this release is out.

**Comment by nielsfaber** [comment]
This feature is included in the v3.2.6 release.
Please update to the latest release and verify whether the functionality is OK for you.
You can close this issue if so, otherwise let me know.

**Comment by larry-glz** [comment]
Looks good. Thanks!
