### ISSUE TITLE
Can't add "Custom Scheduler Card" on Lovelace dashboard , item not found

### ISSUE THREAD

**Issue by jdenouel** [nielsfaber/scheduler-card#583]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.5

### Component Version

v3.2.10

### Bug description

I tried 2 times, installation from scratch, defininig a new dashboard, addind a new card do not display Custom Scheduler Card

I also found HACS error message (Red)
Not loaded in Lovelace
You have 1 Lovelace elements that are not loaded properly in Lovelace

Regards, 

### Steps to reproduce

Install with Balena Etcher lastest image x64 image 
https://github.com/home-assistant/operating-system/releases/download/8.2/haos_rpi4-64-8.2.img.xz

Default language : FR

Config Account and location

Install Terminal & SSH 
wget -O - https://get.hacs.xyz | bash -

Restart
Hacs install  Scheduler Integration and Interface 
Reboot

Create a new dashboard, take control
Add + card --> Custom Scheduler Card item not present

HACS Display error message 

Kind regards,

**Comment by jdenouel** [comment]
Sorry, Found the solution : https://github.com/nielsfaber/scheduler-card/issues/70

**Comment by navels** [comment]
@jdenouel can you say what exactly you did to resolve the issue?

**Comment by elektrovert** [comment]
I'm having the same problem

**Comment by ssancese** [comment]
Same behaviour here, no solution.

**Comment by Fertigmensch666** [comment]
If anyone sees this and looks for an solution: I solved it by adding this to the Lovelace resources

`/hacsfiles/scheduler-card/scheduler-card.js?v=0`
