### ISSUE TITLE
Wrong translation in Korean

### ISSUE THREAD

**Issue by kmchoi1540** [nielsfaber/scheduler-card#584]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.5

### Component Version

v3.2.10

### Bug description

I'm using in Korean and every translation turns opposite.
In Korean, 'on' is '켜기' and 'off' is '끄기' but in the card, 'on' is '끄기' and 'off' is '켜기' in all types of entities like lights, switches, etc. It works fine when I set the language in English.

### Steps to reproduce

Just set the language in Korean.

**Comment by nielsfaber** [comment]
There is no korean translation for this card.
All texts in the card which you see in Korean come directly from HA.

For example, for the states of a light you should see:
> 
            "off": "꺼짐",
            "on": "켜짐"

As defined here: https://github.com/home-assistant/core/blob/0317cbb388e685ec00d77a49849693c418aa7ee4/homeassistant/components/light/translations/ko.json#L20-L25
