### ISSUE TITLE
"Could not connect with the scheduler component. It needs to be installed as integration before this card can be used."

### ISSUE THREAD

**Issue by stanogustafik** [nielsfaber/scheduler-card#585]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.5

### Component Version

v3.2.10

### Bug description

Probably after update of Home Assistant OS scheduler card stopped to work properly. Instead of usual card in lovelace view the announcement "Could not connect with the scheduler component. It needs to be installed as integration before this card can be used." appeared.  Schedules made with card user interface work, but it is not possible to edit them. Scheduler integration shows up among other integrations in normal way. On the HACS card there is warning "Not loaded in Lovelace - You have 1 Lovelace elements that are not loaded properl in Lovelace"

### Steps to reproduce

I have updated OS to 8.4 (which is not very possible to restore to previous version). I have updated HA core to 2022.7.7 but when I restored 2022.7.5, the issue was the same. 

### Additional info

After issue has appeared, I was trying to edit resources according to solutions in older issues, but nothing happened, still the same... when I redownload scheduler card and also component, in first moment everything seems to work... warning in HACS card disappears... but the problem in Lovelace still persists

**Comment by stanogustafik** [comment]
Ok, here is the solution:

1. download scheduler.storage from config/.storage and store it anywhere
2. delete integration + uninstall scheduler card + uninstall scheduler component
3. restart HA
4. install scheduler component
5. restart HA
6. add integration + install scheduler card
7. add any scheduler card in lovelace - that creates the new scheduler.storage file in config/.storage
8. copy all content of old scheduler.storage ant paste it to newly generated scheduler.storage
9. restart HA
10. find that all non-working scheduler card items are now working and appearing in lovelace

I hope this will help someone in the future...

Bye :)

**Comment by nielsfaber** [comment]
Simple solution? 😕 
I wish I could experience the problem you were having, such that I could see what causes this.
Unfortunately I’m running HA via Docker hence I cannot update the OS. Updating to 2022.7.7 is very unlikely to be the cause of this issue (but I will try).

**Comment by stanogustafik** [comment]
I was trying to find anything in logs, but there was just nothing... everything that I could see is written in the issue description... I needed to solve it quickly, because many of my automations are based on your great component...

I have no idea if it was really caused by Home assistant OS update... it is interesting, that there is none else with the same problem! :/

**Comment by stanogustafik** [comment]
so... here we go again... problem occured again the same way, but it´s not caused by any installation or update... after this log

Logger: frontend.js.latest.202208020
Source: components/system_log/__init__.py:227
First occurred: August 3, 2022 at 23:18:45 (15 occurrences)
Last logged: 01:19:15

http://192.168.x.xxx:8123/core_configurator/dashboard:0:0 Uncaught
http://192.168.x.xxx:8123/lovelace-basic/weather:0:0 Uncaught
http://192.168.x.xxx:8123/lovelace-basic/grafy?edit=1:0:0 Uncaught
http://192.168.x.xxx:8123/lovelace-basic/sprinklers:0:0 Uncaught

... my favourite warning "Could not connect with the scheduler component. It needs to be installed as integration before this card can be used." appeared again
