### ISSUE TITLE
weird German translation any=(k)eine?!

### ISSUE THREAD

**Issue by boarder876** [nielsfaber/scheduler-card#587]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.5

### Bug description

I was just wondering how I can link conditions with OR instead of AND. 
The reason is that in the german translation, the slider behind conditions is labeled "keine" and "alle", which means NONE and ALL. At the beginning i thought that I can turn on and off the conditions, which is a missunderstanding. I switched to english language and the ANY and ALL makes much more sense.
 
So please change the german translation for ANY from "keine" to "eine"

### Steps to reproduce

set up new schedule and go  to options

**Comment by nielsfaber** [comment]
The translations of the card are maintained by the users.
Feel free to edit the german translation file here: https://github.com/nielsfaber/scheduler-card/blob/main/src/localize/languages/de.json

**Comment by boarder876** [comment]
I'm new to GitHub so I'll give it a try
