### ISSUE TITLE
"DISCOVERY EXISTING" set to false, but new card populated with previously schedules

### ISSUE THREAD

**Issue by adizag** [nielsfaber/scheduler-card#590]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.5

### Component Version

v3.2.10

### Bug description

Started a new scheduler card. I want to have multiple cards, split into different functional schedules,  so I don't want to see previously set schedules in each card.
As far as I understand, that is exactly what "DISCOVERY EXISTING" set to false should do.

still, as I add entities type, the old schedules are automatically added without the option to remove them.

https://user-images.githubusercontent.com/17390016/184819990-7ac1ca24-4f55-4811-b4a1-54e696900bfb.mp4

### Steps to reproduce

creating a new card, adding climate entities (for example), after having other climate schedules

**Comment by nielsfaber** [comment]
I think you misunderstand the behaviour.
Once you tell the card to include climate entities, all schedules for climate entities will show up.
The `discover_existing` cannot be used to avoid that. This setting can be used to remove the `+x excluded items` on the bottom of the card, i.e. hide schedules which were found in HA but not included in the card configuration.
If you want to split your schedules into multiple cards, its best to use `tags`.

**Comment by adizag** [comment]
OK, tnx, I got it now.
the right way to work with this great tool is by right tagging the card, then each automation may get 1 or more tags so it can be shown in the relevant card/s.

GREAT TOOL!!
Many thanks to the developer @nielsfaber  :)

After using the tool for a few days I have a few improvements and bug reports, I'll do it soon.
