### ISSUE TITLE
Versioning vent wrong! Typo! v3.2.6 released instead of v2.3.6

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#592]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.6

### Bug description

But this is out, I really have no clue how to force a "downgrade" from v3.2.6 to v2.3.7 (as another new release) in HACS.

### Steps to reproduce

x

**Comment by nielsfaber** [comment]
I see now that I indeed misspelled the version number, sorry about that.
The error only applies to the release tag in github, the actual scheduler-card.js code will show v2.3.6.
I corrected the release just now.

I have no idea how HACS works with this, but I am assuming it takes the available versions from the github repo, so v3.2.6 shouldn't show up anymore.
For me it shows up correctly now in HACS:
![image](https://user-images.githubusercontent.com/16861605/185787691-f822306a-a815-4e8b-a54b-dfdf78cfb8bd.png)

**Comment by lmagyar** [comment]
FYI: I used the "Redownload" function in the "..." menu, and now HACS shows v2.3.6 everywhere.

I've tried "Update Information", but that didn't changed the version showed by HACS, even though it is only a github tag, it _**seems**_ HACS uses that info instead of the version in the component.

I think this way I won't miss the next release of the nearly most important component of HA. :)
