### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by Protoncek** [nielsfaber/scheduler-card#593]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I just translated scheduler card to Slovenian language

### Additional info

I'm not familiar with github, so i don't know exactly what i did - i took en.json, translated and saved (uploaded) as sl.json. Please check if if i made all ok or not... i can't even find my upladed file... sorry for that.

**Comment by Protoncek** [comment]
I found my file (via browser's history). I hope you'll see it , too:
[https://github.com/nielsfaber/scheduler-card/commit/0c37764dea62248c00d23937b5552910f399b1e3](url)

**Comment by nielsfaber** [comment]
Thanks for your effort.
Please create a pull request for the translation file.
You can do so by going to https://github.com/nielsfaber/scheduler-card/tree/main/src/localize/languages
and click 'add file':

![image](https://user-images.githubusercontent.com/16861605/186211090-8d750623-a3b7-47aa-8a28-436214115c30.png)

I think github should automatically guide you through the steps.

**Comment by Protoncek** [comment]
I did "something"...hopefully correct (says 1 workflow waiting for approval).

**Comment by Protoncek** [comment]
I confirm that Slovenian language works. Time will tell if i made any mistakes, needed correction.
Thanks!

**Comment by nielsfaber** [comment]
Ah I’m sorry for not mentioning that your contribution is released, normally I do that.
Good that you found out yourself 👍

**Comment by Protoncek** [comment]
No problem... main thing is that it's there.
