### ISSUE TITLE
Test Button

### ISSUE THREAD

**Issue by 9812ga98sd** [nielsfaber/scheduler-card#594]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

A test button would be useful when creating a new schedule to see if the action actually works. 

### Additional info

The button would ideally be on the same page when you create the schedule. Preferably in the action area.

**Comment by nielsfaber** [comment]
Why wouldn’t an action work?

**Comment by 9812ga98sd** [comment]
Not everything works all the time.. bugs happen. For example when I created a schedule using a scheme when you close the scheme it executes the action for some reason turning something off.
