### ISSUE TITLE
Closing schedule created with a scheme triggers the action

### ISSUE THREAD

**Issue by 9812ga98sd** [nielsfaber/scheduler-card#595]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.6

### Component Version

v3.2.10

### Bug description

When I created a schedule using a scheme when you close the scheme it executes the action for some reason turning something off. 

i then recreated it and changed it and every time I save the schedule it triggers the command and send the execute. Eg it turns the TV off.

### Steps to reproduce

Create schedule. Use the scheme. Click save. UI closes and sends the trigger.

**Comment by nielsfaber** [comment]
This is by design.
See [documentation](https://github.com/nielsfaber/scheduler-card#timeslots):
> If you create (or edit) a new time scheme: the schedule will determine which timeslot is active, and trigger this action immediately.
