### ISSUE TITLE
resource entry

### ISSUE THREAD

**Issue by daverow** [nielsfaber/scheduler-card#598]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

Frontend 20220802.0 - latest

### Component Version

Firmware: 3.2.10

### Bug description

on restart of home assistant resource entry for scheduler-card disappears and card not displayed
rentering the resource details and card works ok

### Steps to reproduce

restart ha

**Comment by nielsfaber** [comment]
This seems more like a bug in HA to me than the card itself.
The card doesn’t contain code related to the resource registration, so I wouldn’t know how to influence it.
