### ISSUE TITLE
Schedule with deleted entity cannot be removed

### ISSUE THREAD

**Issue by mad8max4** [nielsfaber/scheduler-card#599]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.6

### Component Version

3.2.10

### Bug description

I uninstalled an integration and the entities associated with it.
If I now try to remove the associated schedules I get an error message:
Something went wrong!
Could not compute actions for schedule #cdf7c8.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/91310916/187292124-ee105e4d-8d7f-417a-afc9-38a5df8199a6.png">

### Steps to reproduce

I uninstalled an integration and the entities associated with it.

**Comment by nielsfaber** [comment]
Thanks for reporting this. I probably never tested this specific scenario, but I agree that it should be at least possible to delete the obsolete schedule. 
I will try to work out a solution whenever I have the time for it.
As a workaround, you can use the `scheduler.remove` service to manually remove this item.

**Comment by nielsfaber** [comment]
I could not reproduce the problem.
If I delete entities used in the schedule, they show up like this:
<img src="https://user-images.githubusercontent.com/16861605/190861849-cb132283-2682-41c8-aae0-161e35ba8784.png" width="50%" height="50%">
I can still click on the schedule and modify/delete it.

Can you share some more details to help reproducing this issue?

**Comment by mad8max4** [comment]
Hi Niels,
I would really like to provide more details, what would help you?
It is still unchanged for me, when I click on the plan I get the error message.

**Comment by nielsfaber** [comment]
It would be helpful to know which entity is controlled by the schedule.
Also it would be helpful to know if you used a built-in action or defined your own via YAML customization.

**Comment by nielsfaber** [comment]
Without more input for reproducing this specific scenario, I don't know how to make a fix for it.
