### ISSUE TITLE
slider disappear itself during schema settings

### ISSUE THREAD

**Issue by tomaszduda23** [nielsfaber/scheduler-card#602]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.6

### Component Version

v3.2.10

### Bug description

Slider disappear itself during schema settings. After 1-5 sec slider is gone. You need to click again to make it viable.
https://user-images.githubusercontent.com/35012788/189616134-46bbf5dc-3b69-4424-a8b5-7940a0771cdd.mp4

### Steps to reproduce

Add schema for climate.

**Comment by tschut** [comment]
I have the same thing, it's really annoying. Thanks for the workaround though!

**Comment by vTomTom** [comment]
same here... directly hitting this thing.

**Comment by nielsfaber** [comment]
This seems to be the same issue as #601 
I hope to be able to make a fix for this in the upcoming weekend

**Comment by nielsfaber** [comment]
This issue should be fixed by updating the card to v2.3.7.
@tomaszduda23 Please try it out and close the issue if so. Otherwise let me know.

**Comment by tomaszduda23** [comment]
@nielsfaber It works. Thanks
