### ISSUE TITLE
[enhancement] more complex logic for conditions

### ISSUE THREAD

**Issue by bsafh** [nielsfaber/scheduler-card#604]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

scheduler component 3.2.0
scheduler card 2.3.7

I would like more complex logic in the conditions on the options page. Currently you can only select "all" or "any of" (="one"), but you can't build more complex scenarios without creating a ton of additional HA boolean helpers outside of the card (which clutter the HA helpers page quite a bit)

Current condition selection:

![image](https://user-images.githubusercontent.com/106388187/190911981-76f50c37-7bc3-4376-a49f-4c085399e5c8.png)

It would be much more convenient if it would be possible to create something like in the new automatic editor, so e.g..

```
("someone is at home"   AND   "windows are closed")
OR
("heating_manually is set"    AND "outside_temp_is below 16°C")
AND 
"time is between 8am and 8 pm"
```

### Additional info

perhaps it can be done like in the new HA automations editor

![image](https://user-images.githubusercontent.com/106388187/190912243-3180aa33-1224-4c70-9ce1-64ca9baa2167.png)

**Comment by nielsfaber** [comment]
I rather keep the card simple than extending it to allow such nested conditions.
If you want to create a complex condition, you could define a template binary_sensor for it and use this in the card.
