### ISSUE TITLE
Setting correct parameters for TRV TSO601 correct operation

### ISSUE THREAD

**Issue by cunninr2** [nielsfaber/scheduler-card#606]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.7

### Component Version

v3.2.10

### Bug description

I am using TSO601 TRV.  From the various documentation I have read online, for this TRV to work properly (controlled accurately by Home assistant) it must be in the following modes: 
        hvac_mode: auto (with a temperature setting)
        preset_mode: manual

When I build a schedule for this Climate entity, I can only choose for hvac mode (heat or auto). If I choose heat, I am able to then set temperature. If I choose auto, I cannot set temperature. 

I can also choose 'set preset' and then can select auto,manual,holiday.

I can need to action both properties above together, which I believe is needed for correct operation.  If I were to do this in YAML it would be as below :

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.trv_harrys_room
        temperature: 20 
        hvac_mode: auto
    - service: climate.set_preset_mode
      target:
        entity_id: climate.trv_harrys_room
      data:
        preset_mode: "manual"
![Screenshot scheduler - auto setting](https://user-images.githubusercontent.com/25829766/191283824-03b3cbf0-39f8-48ec-b733-3c23e71e716f.png)
![Screenshot scheduler - heat setting](https://user-images.githubusercontent.com/25829766/191283829-7dd9444e-3f1d-4cfe-a2a4-7180dbc5f4af.png)

### Steps to reproduce

tried using latest version of scheduler with TSO601.

### Additional info

my customize file is for the climate card is below, but I do not think this would affect the issues above. 

climate.trv_harrys_room:
  hvac_modes:
  - heat
  - auto
  preset_modes:
  - auto
  - manual
  - holiday

**Comment by nielsfaber** [comment]
Did you read this: https://github.com/nielsfaber/scheduler-card#customizing-built-in-actions

**Comment by Kingo71** [comment]
I have the same TRV and I can confirm that when you select "Manual" as preset the card doesn't allow to change the target temperature.
Basically we need the ability to change temperature (slider) when in "Auto" mode and "Manual" preset.

**Comment by nielsfaber** [comment]
The link I shared before contains an example on how to modify the 'heat' action such that you can set the target temperature and simultaneously set the mode to 'auto'.
This has been used by others having the same TRV.

**Comment by cunninr2** [comment]
Thank you for your advice. I will implement the customize element as you have indicated. I did not realize that customize allowed an action to be scripted.  For information, the newer generation of thermostats which I have just purchased (TV02) and I am using with current version of zigbee2mqtt requires that 'HVAC: heat' and 'Preset: manual' is selected to be able to set temperatures in HA. Using 'Preset:auto' will use the local stored trv schedule.

E.g. 
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.trv_harrys_room
    - service: climate.set_preset_mode
      target:
        entity_id: climate.trv_harrys_room
      data:
        preset_mode: manual

**Comment by nielsfaber** [comment]
@cunninr2 Unfortunately scheduler doesn't support sending a sequence of actions.
As workaround, either you can:
* Have scheduler trigger a script instead of the climate device, and define the sequence in this script.
* Create an automation that sets the preset_mode to manual in case the hvac_mode was changed
* Create a second schedule (or separate timeslots) to set the preset_mode
* Keep the preset_mode to manual forever

Please consider to close this bug report, as there is no bug. The device just doesn't behave according to the definitions of HA for climate devices, so customization is required.

**Comment by cunninr2** [comment]
Thank you. I have solved the problem by creating a schedule scheme matched to boiler on off timings which toggles an input_Boolean to trigger an automation to reset TV02 TRV's. I have a second scheduler scheme to alter the climate temperatures.  At least this way I can still benefit from the powerful scheduler.  I will close the issue
