### ISSUE TITLE
Unable to select options in Card

### ISSUE THREAD

**Issue by jimmyeao** [nielsfaber/scheduler-card#607]
When trying to select daily, work day or weekend, it always flips back to weekend. As a result, unable to edit schedules
Using Chrome Version 105.0.5195.127
Works fine in Edge

**Comment by nielsfaber** [comment]
You can solve this by clearing the browser cache.

**Comment by jimmyeao** [comment]
Awesome, thanks!

**Comment by jimmyeao** [comment]
Ok reopening this - this is occurring in Chrome, Edge and Firefox, clearing cached not working, and in private does not help either
unable to edit any schedules. See video here for how it looks in practice.
[Video](https://deviousweb-my.sharepoint.com/:v:/p/jimmy/EUVTw5EvzctKq3IrchugCzoBR48LNKiFo7VdQcMRG20V7g?e=bqltzg)
I suspect there may be a conflict with another card, but not really sure how to troubleshoot

**Comment by nielsfaber** [comment]
Can you please open your [browser logs](https://help.zapier.com/hc/en-us/articles/8496199434765-View-and-save-your-browser-console-logs) and double-check that you are running v2.3.7 ?

**Comment by jimmyeao** [comment]
SCHEDULER-CARD  
  Version: v2.3.6

Hacs doesnt show an update, is it a case of doing it manually?

**Comment by jimmyeao** [comment]
Sorted it, updated to 2.3.7 manually, all working now, thank you :)
