### ISSUE TITLE
 scheduler-timepicker-card Direction:ltr

### ISSUE THREAD

**Issue by moshiko2312** [nielsfaber/scheduler-card#608]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal
In the Hebrew language the inscription is from right to left
I would appreciate it if you made a correction
for time because it is reversed   if you could fix it, to ltr 
thanks

### Additional info

![time rtl](https://user-images.githubusercontent.com/48163773/192112802-64f34286-ff76-406b-976d-127d0de902ec.jpeg)

**Comment by nielsfaber** [comment]
I think a lot of things need to be adapted to support LTR viewing mode in this card.
Currently I don't have time available to make these adaptations myself.
If someone (preferably who uses LTR) could contribute a PR with these changes I would be happy to add it to the card.

**Comment by moshiko2312** [comment]
Thanks 
Shlomki
