### ISSUE TITLE
Unable to edit existing schedule, value resets back after a while

### ISSUE THREAD

**Issue by daha76** [nielsfaber/scheduler-card#611]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.7

### Component Version

v3.2.10

### Bug description

I have existing time schedule - time scheme -and when I try to edit it I experienced issue with resetting changed/modified values back to the previous values. Like to example if I would like to change target temperature for climate device for some time frame, the temperature will reset back after a second or so. Same thing happen also when I try to create a new schedule - time scheme. I have to be pretty fast to change the value and hit save button. I use chrome browser ant also official Home Assistant android application. I tried to reload Scheduler integration, a tried to reboot the whole RPi where HA is running and finally I removed Scheduler integration from HA and install it back. None of these steps helped... and I cant even create a new time schedules as one has to be pretty fast to change value and hit save button.
![image](https://user-images.githubusercontent.com/16493975/192220113-b9b58731-b6ba-4be5-8be4-1253d641cc95.png)
here is the link to the recorded video:
[https://drive.google.com/file/d/14ejacCpQTyvzOnc2ZoBHnXyZKDCRVdFq/view?usp=sharing](https://drive.google.com/file/d/14ejacCpQTyvzOnc2ZoBHnXyZKDCRVdFq/view?usp=sharing)

### Steps to reproduce

1. open existing schedule
2. select some time frame
3. try to change any value, like time frame start/end time or target temperature, ...
4. changed value reset back to previous value

**Comment by sddgit** [comment]
Try updating to the latest version of the card.

**Comment by daha76** [comment]
But v2.3.7 is the latest one, isn't it? Ok I try to reinstall the card, that I haven't tried yet.

**Comment by moshiko2312** [comment]
Try cleaning cash from your internet explorer or chrome

**Comment by daha76** [comment]
Seems like reinstalling cards and cleaning caches helped. THX for tips
