### ISSUE TITLE
Name top os scheduler

### ISSUE THREAD

**Issue by RoelHermus** [nielsfaber/scheduler-card#612]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The name of the scheduler in Dutch is "Tijdplanner". For so far I can see is it not posible to change it. I like it if I can change it, for example "klokprogramma" for the central heating or "dagprogramma" for the daily info.

### Additional info

.

**Comment by nielsfaber** [comment]
You can change the title as you desire, by going to the card editor or yaml code of the card.

**Comment by RoelHermus** [comment]
I found it. Thank you for your info. The scheduler works perfect, I'm very glad with it.
