### ISSUE TITLE
Combination of time AND sun trigger

### ISSUE THREAD

**Issue by pachi81** [nielsfaber/scheduler-card#614]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

At the moment, it is only possible to create a schedule on a fixed time OR in relation to sun.
It would be great if there is a combination of both, for example, the cover should open 10 minutes before sun-rise, but not before 7 o´clock.
Same for closing...

The only possibility at the moment is to set a time-frame and use as option the attribute of sun above-horizont, but 10 minutes before sun-above-horizont is nearly impossible (only with some additional automations).

### Additional info

Cover scheduler: 

1. Open 10 minutes before sun-rise, but not before 7 o´clock
2. Close 10 minutes after sun-setting or at 10 o´clock PM.

**Comment by nielsfaber** [comment]
I'm afraid this is not in scope for scheduler. The main problem is that it would require quite extensive changes in the card as well as the backend (scheduler component) to make this possible. I don't feel like making these efforts.

I would say it's quite easy to workaround this issue, by changing the schedule from relative to sunrise/sunset to fixed time and vice versa, should only be needed twice per year.
You can use scheduler to send you a (one time) push notification as reminder when sun is (not) up at 7:00 or similar. You can use the sun state as condition to achieve this.

**Comment by papadi** [comment]
I was looking for the exact same thing for the exact same automation scenario. It would be too much trouble to add one extra line such as No 1 in the screenshot or allow adding a time based condition (No 2)?

![image](https://github.com/nielsfaber/scheduler-card/assets/3359377/a938cb85-6694-44aa-bdb9-0fa6075f4049)
