### ISSUE TITLE
Show TAGs on schedule-card

### ISSUE THREAD

**Issue by RASBR** [nielsfaber/scheduler-card#616]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Firstly, big thank you to all participants for their efforts and generosity in sharing their work

My suggestion: 
Since the card has the TAGs functionality, & referring to ['For your protection, it is enabled by default'](https://github.com/nielsfaber/scheduler-card#schedule-discovery:~:text=It%20could%20occur,enabled%20by%20default.) I think it would be very useful to:

1. Have the TAGs (COLORED & VISIBLE) showing on the card for each schedule in the list next to the 'Primary Info'.
2. Ability to sort the list according to TAGs (might be challenging with more than one tag on the cards!).

Thanks

### Additional info

**Example:**
Given a house with the following: Pool, Irrigation System, Front Garden, Back Garden, and Terrace. I would assume the schedules could be tagged as follows:
### TAG-1: Essentials
**_Description:_** For systems that could cause lots of harm if they don't run properly either with loss of water or excessive financial costs and one can't afford to have them not run for a long time.
**_Entities:_**
- Pool related entities such as Filter & Smart valve to fill in the tank
- Irrigation related entities such as Pumps & Zone valves
### TAG-2: Lighting
**_Entities:_**
- Front
- Back
- Terrace

**Comment by nielsfaber** [comment]
There is some basic support for displaying tags in the overview page, see [display options](https://github.com/nielsfaber/scheduler-card#display-options).

Please give it a try, see if it helps your needs.

**Comment by RASBR** [comment]
That's exactly what I am talking about. I don't know how I missed that!

thanks and sorry for the inconvenience.
