### ISSUE TITLE
Scheduler for climate - Tuya

### ISSUE THREAD

**Issue by kowalczykrafal** [nielsfaber/scheduler-card#617]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hi, 
In pull request https://github.com/Koenkk/zigbee-herdsman-converters/pull/4898 we are discussing using auto mode for Tuya thermostat and mapping modes from HA by Z2M to Tuya.
The temperature can be changed in lovelace HA for the thermostat card when selecting the auto mode. However, in scheduler-card when selecting auto mode there is no such possibility.
Please and change in your supplement so when selecting auto you could set the temperature.
This change will make the scheduler-card compatible in lovelace in HA.
Thanks

### Additional info

Thanks

**Comment by nielsfaber** [comment]
This has been discussed many times.
As you can read [here](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes), for a climate entity in Home Assistant the mode 'auto' is intended as a mode where the device internally regulates its setpoint.
Setting mode 'auto' with a target temperature is incorrect.
I believe that mode 'auto' should be renamed to 'heat' to be in-line with HA specification.

I don't want to change the card for your device, as it deviates from the HA definition and will negatively affect users who have a device with _properly_ implemented mode 'auto' (as their devices will not accept a setpoint in this mode).
You can apply the workaround described here: https://github.com/nielsfaber/scheduler-card#customizing-built-in-actions

**Comment by diabl0** [comment]
@nielsfaber Hit the same issue today, and it takes me a lot to understand that customization should be made in card YAML, and not in global HA customization section. It may be worth making it clearer in README.

**Comment by programmdesign** [comment]
@nielsfaber, I ran into the same issue. I have been testing three devices: Homematic IP Evo, Bosch Thermostat II and Aqara E1. I was trying to use your scheduler to replace similar features of the manufacturer's own apps. At the time of taking the screenshot, all three devices where in "Auto" mode. However, the way the devices use the auto mode is different.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/4633284/208196207-c3f9522c-84c3-472d-83d5-52c666c4d1a7.png">

My understanding of the auto mode is that you set a target temperature and the device managed itself if it should heat or not. In contrast, if you set the device to heat, it always heats, not matter if the target temperature is reached or not. 

If I use the scheduler, I get the following screens: 

**Aqara**

<img width="413" alt="image" src="https://user-images.githubusercontent.com/4633284/208196484-e3376f91-3aaa-4151-bf73-4ae0aeefa89d.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/4633284/208196524-2803470e-1a5c-4dc7-8513-629537a099c6.png">

**Bosch**

<img width="420" alt="image" src="https://user-images.githubusercontent.com/4633284/208196573-860302cf-202b-4bfb-a724-59b30ed5a06b.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/4633284/208196582-bf46921f-8215-495e-8aaf-35a94a12855d.png">

*Homematic*
<img width="397" alt="image" src="https://user-images.githubusercontent.com/4633284/208196612-ad1ec69c-7486-4477-b9af-06f0c6ad89d8.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/4633284/208196638-cd97ccd1-2346-4947-a88d-438971dbe92f.png">

In none of the cases, I can set a new target temperature for the day / time / schedule. That works only, if I select the "Heat" option. However, the "Heat" option for Aquara works even totally different than for the other two devices. 

Maybe, I have totally misunderstood the auto mode. But when I set a target temp and auto mode, my devices stop heating when the target temperature is reached. If I select heat, they keep heating and turn turn off/down. Hence, I also think, there should be an option to set the target temperature when auto mode is selected, well knowing that "auto mode" seems to be implemented in various ways, as seen above with the different devices. Would be great to see this feature, as this would enable HA to really by the place for managing thermostat schedules. If I can help with any debugging, more input, etc. -- let me know. 

In any case, thanks for this great integration! :)
