### ISSUE TITLE
Temperature regulation is still faulty...

### ISSUE THREAD

**Issue by crux2006** [nielsfaber/scheduler-card#621]
A/C Temperature adjustment problems persist.  Temperature regulation, schematic capabilities are currently not working.  Reverts after click

https://user-images.githubusercontent.com/59333074/201467270-2c4bf034-1308-445f-8be9-389aa5795fbe.mp4

**Comment by sultanhq** [comment]
This also happens for me, even in a normal chrome window, incognito chrome window, and mobile app.

**Comment by nielsfaber** [comment]
@sultanhq can you please check in your browser log which version of the card is running? 
You should be able to see something like this:
![image](https://user-images.githubusercontent.com/16861605/201508177-ef9f05b1-0d8c-47d4-961a-3a652b0e2348.png)

**Comment by crux2006** [comment]
v3.2.11

**Comment by nielsfaber** [comment]
@crux2006  This version doesn't exist for scheduler card.

**Comment by skirchgeorg** [comment]
Same problem persists for me on chrome and in the app. Scheduler component 3.2.11 and card is 2.3.7

**Comment by nielsfaber** [comment]
Please check the actual version in [browser logs](https://help.zapier.com/hc/en-us/articles/8496199434765-View-and-save-your-browser-console-logs) and share a printscreen.

**Comment by gafain** [comment]
Similar problem. When a try to change temperature of climate I move the slider but after a variable moments (1 to 4 sec) it come back to the previous value. 
If I'm fast enough I can hit the save button and take the correct value.

I try with chrome and Forefox with the same result.
Scheduler Card is the last version updated today (but) it continue to report version 2.3.6 (in the debugger console)
So I force a reinstall and now I get the versione 2.3.8 without this BUG

**Comment by sultanhq** [comment]
For some reason, HACS failed to download the new fixed version correctly, a couple of attempts and its all good now 👍

**Comment by skirchgeorg** [comment]
It was fixed for me after the last update. Thanks! Can be closed.
