### ISSUE TITLE
Increase time from dawn and sunset

### ISSUE THREAD

**Issue by pmogas** [nielsfaber/scheduler-card#622]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Be able to add or subtract more than 2 hours (present limit) in order to trigger the scheduled action.

### Additional info

![image](https://user-images.githubusercontent.com/2027167/201910708-5895bb33-9e73-46da-82c2-29409912c7a0.png)
Limit could be -12 to +12 hours or limit by total day or night time in your parallel degrees.

**Comment by nielsfaber** [comment]
Why? What is the practical use case?

**Comment by pmogas** [comment]
I want to run my pool proportional to sunlight. If I turn on at dawn+2 hours and turn it off at sunset -2 hours, the pool runs too much time. I would want to limit this time by adding or subtracting more than 2 hours.

**Comment by nielsfaber** [comment]
Isn’t the sun completely up 2 hours after sunrise? 
And still completely up until 2 hours before sunset?
As far as I know there are no locations in the world where the complete sunrise/sunset takes more than 2 hours.

**Comment by pmogas** [comment]
The problem is the interval between sunrise+2h and sunset-2h. It depens of course on the time of the year, but in my location it goes from 9 hours in winter to 15 hours in summer. Nine hours minus 4 hours (sunrise+2 and sunset-2) is five hours total. This five hours is too much for my pool, as in this radiation rate it should run for 2 hours. The same happens in summer 15 hours minus 4 is 11 hours, too much for the pool as it should run for 8 hours.
From the examples I have an excess time of three hours. If I can select sunrise+3.5h and sunset-3.5h I would have the problem solved.

**Comment by pmogas** [comment]
Thank-you very much
