### ISSUE TITLE
Costum element does't exist: scheduler-card

### ISSUE THREAD

**Issue by lynntryanderror** [nielsfaber/scheduler-card#623]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.8

### Component Version

3.2.12

### Bug description

I use the scheduler card now for a couple of weeks and today i saw that the scheduler card didn't work any more.

![image](https://user-images.githubusercontent.com/101171559/202484047-b2fc0b0b-f565-4a11-a759-dc5e848ea30d.png)

### Steps to reproduce

I redownloaded it. Didn't work.
I removed it and downloaded it again. Also not working.

Thanks a lot for the help in advanced
Lynn

### Additional info

Home Assistant Core 2022.11.2

**Comment by Zombie-Toad** [comment]
Hey, it seems that the *.zip file is not extracted automatically, I did this manually via the terminal. After extracting the file, you should see the card in your card overview.

**Comment by nielsfaber** [comment]
Hmm maybe I did something wrong when making this release.
I will check it out when I have the time, keep you posted.

**Comment by Zombie-Toad** [comment]
The zip file is located in /console/www/community/scheduler-card/scheduler-card.zip. After extracting you should also see scheduler-card.js in this folder.

For other cards, the archive is a .gz file. Maybe that is why the automatic extraction is not working.

**Comment by lynntryanderror** [comment]
So i find the zip and extracted it. Could be that after removing and downloading it it didn't get extracted,
So it didn't work but i*m not sure what i should use as resources url
/local/scheduler-card/scheduler-card.js?v=0 this is in the documentation
/hacsfiles/scheduler-card/scheduler-card.js?hacstag=2862701572 this was for the previous installation

**Comment by lynntryanderror** [comment]
I deleted both files and downloaded it again. the file .js and .gz are in the folder.
I refreshed the resources and now it worked.

THanks a lot for the help

**Comment by lynntryanderror** [comment]
Ok thanks. I did it :-)

**Comment by nielsfaber** [comment]
Since multiple users reported issues with upgrading to v2.3.8, I decided to make a new release v2.3.9 which doesn't have any changes but hopefully solves the updating via HACS.
