### ISSUE TITLE
Disable all schedules

### ISSUE THREAD

**Issue by oscarx80** [nielsfaber/scheduler-card#628]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I would like to disable schedules with the tag: "no home" when I'm not at home

### Additional info

It would be useful to expose the entity to enable and disable all programming related to a given tag. For example, through node red I have a gate that closes when I'm not at home and if I could also manage the programming with the same command it would be useful. Thank you
![image](https://user-images.githubusercontent.com/77801136/203492479-7c24ccd3-c273-4dc1-bd0e-26ffb1538632.png)
![image](https://user-images.githubusercontent.com/77801136/203492624-e6b5b284-1a30-4c98-9059-adb8b29854a1.png)

**Comment by nielsfaber** [comment]
I think this request is too specific to add to scheduler.
Why don't you just loop over the scheduler entities in your node-red routine and filter out the ones having this tag?

**Comment by oscarx80** [comment]
okay. It can be done in other ways. I thought it could be a convenient function for everyone because I think that a need for many is to deactivate the timers or activate them based on whether or not they are in the house without using node red. Thanks
