### ISSUE TITLE
Breaking checkboxes

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#63]
The new release causes this problem and breaks stuff like the UI card editor add dialog:
![image](https://user-images.githubusercontent.com/10727862/93931008-1642d880-fcd3-11ea-94aa-4d78c00c6d5a.png)

**Comment by nielsfaber** [comment]
Are you in HA 0.115? 
The dev team decided to remove the checkbox and sliders from the HA frontend. 
That's why the card loads its own version.
But combining old and new will cause these kind of conflicts yea.

**Comment by KTibow** [comment]
Yup, 0.115.

**Comment by nielsfaber** [comment]
I guess you only get this conflict if you are on a page with another checkbox as well?

**Comment by KTibow** [comment]
I guess.

**Comment by nielsfaber** [comment]
Well i give up for now.
I put a oldskool checkbox for the time being.
See [v1.4.1](https://github.com/nielsfaber/scheduler-card/releases/tag/v1.4.1
)

**Comment by nielsfaber** [comment]
Version [v1.4.2](https://github.com/nielsfaber/scheduler-card/releases/latest) brings back the old checkbox by triggering the loading via the HA frontend.
Please test if it works for you, if so, then close the issue.

**Comment by nielsfaber** [comment]
Assumed to be fixed.
