### ISSUE TITLE
vacation mode missing from alarm control panel

### ISSUE THREAD

**Issue by stevem405** [nielsfaber/scheduler-card#636]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.9

### Bug description

"vacation" mode is missing from the alarm implementation.  Strangely, this is not shown in the Home Assistant [docs](https://www.home-assistant.io/dashboards/alarm-panel/) but it is available on the the actual card and has been for some time.  I'd like to use this arming mode state conditionally to run automations.

### Steps to reproduce

Scheduler -> Add -> Alarm Control Panel

**Comment by stevem405** [comment]
Just checked - vacation is documented in the [developer docs](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/)

**Comment by nielsfaber** [comment]
Sure I can add this.

**Comment by nielsfaber** [comment]
This is added in v2.4.0
Please update to the latest version and check if your request is satisfied.
Yo u can close the issue if so.

**Comment by stevem405** [comment]
Works great.  Thanks for implementing!
