### ISSUE TITLE
Not able to assign different day Scheme in Choose option

### ISSUE THREAD

**Issue by Knot83** [nielsfaber/scheduler-card#637]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.9

### Component Version

3.2.12

### Bug description

I setup the scheduler card for two types of TRV valves using climate entities and the big issue I’ve so far is that I’m not able to correctly set Scheme as I would. 
I’d like to assign on each day of the week my personal time scheme, but if I select or deselect days the time scheme remains always the same and if I change time, it will applied to the other days. So basically I’d like to assign a specific Scheme to each day, similarly as Tuya app permit. 

### Steps to reproduce

1) Add a Scheduler card
2) Select your Climate entity
3) In the scheduler card then select Climate, the valve entity and Make scheme
4) then select Choose and try to set different scheme for each day
![205BDC8B-91E1-4C0A-9E45-22251E5E2BAA](https://user-images.githubusercontent.com/54513388/206114331-23521f77-e26e-47f4-a68c-139e3a33a630.png)

**Comment by Dutchy-79** [comment]
Same here, I tried making a schedule for a climate device.
I can't add temperature or another time frame.

**Comment by Knot83** [comment]
Is there anyone else having the same issue? Any possible workaround? Shall I open a feature reuqest?

**Comment by nielsfaber** [comment]
There is no bug here.
You can create separate schedule for each day if you'd like.

**Comment by nielsfaber** [comment]
Just click 'add' in the bottom of the card, and create another schedule for another day.
