### ISSUE TITLE
Can't move slider around midnight when creating a scheme (Mobile and PC)

### ISSUE THREAD

**Issue by SellA** [nielsfaber/scheduler-card#638]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.9

### Component Version

v3.2.12

### Bug description

As already mentioned in that issue (https://github.com/nielsfaber/scheduler-card/issues/499) it is not possible to set times too close to midnight when creating a scheme and using the sliders. To me it seems that the amount you can slide the divider is limited by the width of the divider image that is placed in the middle of the divider. Here's attached an image of the problem:
![time scheduler](https://user-images.githubusercontent.com/2340861/206900293-31cd75b0-dc45-42b4-b4af-3d3dc4e66a20.png)

### Steps to reproduce

Create a new schedule and set it to scheme.
Try to slide the time dividers to left and right close to midnight.
It is not possible to set something like 00:10 or 23:50.
The amount of non-selectable time seems to be related to divider logo image width.

**Comment by nielsfaber** [comment]
This is not a bug, just a limitation of the card.
Some people choose to give scheduler card the full width to solve the problem.

**Comment by SellA** [comment]
ICan we try to find a solution that would work for anyone using it or we'll leave it like it is?
I think a temporary workaround would be to include 2 time input under the scheme and show the start and end time of the current selected period. This way, at least, we could set all times (restricted to settings as per TURN ON or TURN OFF). Maybe hide or disable them when nothing selected.
Do you think that would be possible and, moreover, do you think is it nice or have other ideas?

**Comment by nielsfaber** [comment]
I agree this could be improved.
Your proposal seems like a good idea to me.
Note that you can already click on the tooltip above the slider displaying the current time, then you can choose between fixed time and relative to sun.
It seems best to me to add a field here to manually enter a time.

As for the actual implementation, I don't have time to work on this myself any time soon. 
If you could submit a PR with the change I'd be happy to add it.
Otherwise you could create a feature request (or edit this one into a feature request) as a reminder for future improvement.

**Comment by SellA** [comment]
I'm sorry but i'm not familiar with this code and don't want to overestimate my abilities to write a PR for that. I would be happy to edit that in a feature request. Can you do it? i didn't find a way editing the post.

**Comment by rubicon** [comment]
Would love to see this resolved.

**Comment by SellA** [comment]
@nielsfaber any news on that? I saw that the scheduler is updated regularly (at least i get notificafion on my HA installation). Wuold be really cool if you could get to work on that still persisting problem after almost 2 years. Thank you
