### ISSUE TITLE
input_button not available

### ISSUE THREAD

**Issue by elgatho** [nielsfaber/scheduler-card#639]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hello, please add input_button to button filter. 
Currently only button can be added, but when we create a helper, there is no possibility to use it

### Additional info

when you chose button, should show input_button as well.

**Comment by nielsfaber** [comment]
This is added in v2.4.0
Please update to the latest version and check if your request is satisfied.
Yo u can close the issue if so.
