### ISSUE TITLE
scheduler-card not available up after v1.4

### ISSUE THREAD

**Issue by casang** [nielsfaber/scheduler-card#64]
Hi, after I upgraded to v1.4.0 the card is not available on HA anymore. I tried to remove and reinsert the card but the card is not available on "insert cards".
Find attached some screen shots

Best
Carlos
![Screen Shot 2020-09-22 at 17 07 39](https://user-images.githubusercontent.com/16803911/93932250-451e7600-fcf6-11ea-9e96-d7b8b013f9e0.png)
![Screen Shot 2020-09-22 at 17 08 16](https://user-images.githubusercontent.com/16803911/93932258-48b1fd00-fcf6-11ea-8f71-2ad8b08dc1ee.png)

**Comment by nielsfaber** [comment]
@casang  Funny enough is due to conflict between the HA checkbox and the card checkbox. See  #63 
It is fixed by updating again.. Sorry for this.

**Comment by casang** [comment]
works perfect again after 1.4.1...
Thanks a lot
