### ISSUE TITLE
input_select does not permit selection of option

### ISSUE THREAD

**Issue by henriklund** [nielsfaber/scheduler-card#643]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.6

### Component Version

3.2.15

### Bug description

I have tried to create a new schedule using an input_select entity. Whenever I get to the selection of option, I can click on any option, however, the selection instantaneously is revert to the first (possible) selection. 

### Steps to reproduce

- Create a new entity using the input_select helper. Add +2 different options
- Create new schedule using the newly create entity

### Additional info

Another observation I have made is that I am unable to change:
- schedule or action on an existing schedule (going from eg. boolean to input_select). It appears as if these are ignored when saved
- name of schedule (any additions / changes are immediately reverted)

**Comment by nielsfaber** [comment]
Upgrade the card before reporting problems.

**Comment by henriklund** [comment]
Interesting...Card version reported in HACS was 3.2.6. Redownloading the card shifted that to 2.3.9 and issue resolved. Closing this one.
