### ISSUE TITLE
Conditions Not Re-Evaluating when Conditions Change

### ISSUE THREAD

**Issue by jleach87** [nielsfaber/scheduler-card#648]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.4.1

### Component Version

v3.2.14

### Bug description

Upon updating to Card Version 2.4.1, the conditions no longer re-evaluate when they change. Several of my schedules monitor an "input_boolean.home_occupied" entity which is updated when the home is occupied or not. Normally, before the 2.4.1 update, those conditions outlined in the schedules would be re-evaluated when changed, but not any more.

### Steps to reproduce

They will "re-evaulate" if I open a schedule, un-check the "Re-evaluate when conditions change" and save. But that seems to be a one-off..

### Additional info

![image](https://user-images.githubusercontent.com/61998767/209498455-d6365703-e2ca-4ab7-ac40-f01b160bc53f.png)

![image](https://user-images.githubusercontent.com/61998767/209498465-5e0a7ddf-177d-46d9-a31b-d134012c87cb.png)

![image](https://user-images.githubusercontent.com/61998767/209498482-590a38cf-dc75-4f0a-836a-1a173da9a83b.png)

**Comment by smenzer** [comment]
I'm having the same issue - was this ever resolved @nielsfaber? I'm on v3.2.14 of the scheduler component and v3.2.9 of the scheduler card
