### ISSUE TITLE
Adding/Viewing/Modifying schedules does not work anymore inside a popup using browser_mod

### ISSUE THREAD

**Issue by antihero05** [nielsfaber/scheduler-card#649]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.4.1

### Component Version

3.2.14

### Bug description

After upgrading to 2.4.x scheduler card it is not possible to add/view/modify schedules anymore when you use the scheduler card inside a popup using browser_mod (https://github.com/thomasloven/hass-browser_mod). This was working prior to updating to 2.4.x versions and browser_mod version (using 2.1.3) was not updated in the meantime.

Example or Lovelace configuration:
###
      - type: button
        name: Zeitplan
        icon: mdi:thermometer-lines
        icon_height: 30px
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              content:
                type: custom:scheduler-card
                include:
                  - climate.trv_livingroom
                title: Temperatursteuerung
                show_add_button: false
                discover_existing: false
                sort_by: relative-time
###

### Steps to reproduce

Can be reproduced by installing browser_mod (version 2.1.3) from HACS on Home Assistant 2022.12.8 and using the lovelace configuration posted in the bug description.

**Comment by ErikT80** [comment]
I have the same issue. Also using the scheduler card within a popup. Would be nice if there was some configuration to choose whether scheduler card uses a popup for the schedule or keeps working as before 2.4.0

**Comment by nielsfaber** [comment]
The 2.4.0 release uses a dialog window for editing schedules. 
This change  announced here:
https://community.home-assistant.io/t/scheduler-card-custom-component/217458/1802?u=neliss

There has also been a heads-up about this change with a poll, the result was unanimous in favor of the change:
https://community.home-assistant.io/t/scheduler-card-custom-component/217458/1722?u=neliss

I can imagine that opening a dialog inside a dialog might not work (I don't use browser_mod myself, so I haven't tested this).
If this is the case, you might need to move scheduler to the dashboard.

I don't consider this a bug, but it is rather a breaking change.
There is no possibility for me to combine the new layout with the previous.
In your case you might want to keep using version 2.3.9. 
I cannot guarantee this version will keep working with HA in the future.

**Comment by elvissaba** [comment]
Breaking change - right. All my thermostat automations made in this are broken in middle of winter. Changes can't be saved in too. Reevaluating conditions is not working. My heating is turning on and off randomly since update. Sadly, i was stupid enough and avoided backup step.

**Comment by nielsfaber** [comment]
@elvissaba Apart from the visual/layout changes this update doesn't contain any changes.
If you experience issues, you can open a bug report (or multiple) to share your findings. I'm not aware of any of the issues that you are describing.
Be aware that the schedules are living in the scheduler-component, so changes in the card will never cause you to lose your schedules or stop them from being triggered. 
Please keep the conversation respectful (but I understand your frustration)

**Comment by antihero05** [comment]
@nielsfaber: Thanks for your fast reply. I will stick with 2.3.9 for mitigation at the moment and may consider reworking the dashboards if combability issues arise in the future as technical limitations prevent you from enabling same behavior in 2.4.x and newer releases.
Thanks a lot for your development of this extension and sorry I didn't find the thread at home assistant forums. I will close this conversation as everything necessary has been mentioned.

**Comment by elvissaba** [comment]
> @elvissaba Apart from the visual/layout changes this update doesn't contain any changes. If you experience issues, you can open a bug report (or multiple) to share your findings. I'm not aware of any of the issues that you are describing. Be aware that the schedules are living in the scheduler-component, so changes in the card will never cause you to lose your schedules or stop them from being triggered. Please keep the conversation respectful (but I understand your frustration)

Please accept my apology. It is unfair to say this to someone who puts in so much effort without any compensation for the benefit of the community. The least we can do is provide useful feedback to make the product even better. Best regards.
