### ISSUE TITLE
Request to add duration (time)

### ISSUE THREAD

**Issue by stevem405** [nielsfaber/scheduler-card#650]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I know requests for timers have already been made but this is a simplified form which may be(?) easier to implement and less clutter on the UI than #292.  HAI (leviton) Omni uses the syntax <some entity> ON FOR 20 MINUTES which cuts the number of schedule entries down dramatically because most often, you don't need to specify an off time if you can include a duration. It might be a single spinner control right below time, and okay if it only worked for lights, switches, binary, and other two state devices.

Following a review, I've determined that 75% of my scheduled off times would be eliminated with this feature, and I suspect others out there would see a similar reduction in schedule entries too.

Thanks for considering this feature.  Scheduler-card is great.

### Additional info

See proposal.

**Comment by nielsfaber** [comment]
This has been discussed numerous times.
I don’t see how this fits within this project since it is not time-based behaviour. 

If I understand you correctly you want to have an action triggered when enabling a schedule (with the flip switches)? And a second one X minutes later?

**Comment by stevem405** [comment]
Rather than trigger a separate action X minutes later, this request limits the scope to returning to the opposite binary state after hh:mm of elapsed time  This behavior is especially common for lights or switches where you want to give a house a lived in look while you are away lights periodically turning on and off.  For example:
  - Turn on the porch light at sunset for 6 hours
  - Turn on the den light at 8:00PM for 3 hours
  - Turn on the kitchen light at 9:00PM for 15min
  - Turn on the bedroom light at 11:00PM for 30min
In this case, 8 schedule entries are reduced to 4.

I understand if you don't want to implement this given your time constraints.  It's a "nice to have" feature.
