### ISSUE TITLE
Please allow more than 2 hours before/after sunset/sunrise

### ISSUE THREAD

**Issue by nl0pvm** [nielsfaber/scheduler-card#653]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The current schedule does not allow to select more than 2 hours before/after sunset/sunrise.

### Additional info

Please allow more (24h as a maximum?) before/after sunset/sunrise.

**Comment by kris86k** [comment]
Hi.
I need it too!

**Comment by nl0pvm** [comment]
Please don't close this issue as it is still relevant.

**Comment by cornfeedhobo** [comment]
This could be broadened to treating the given time as an offset from sun rise/set.

**Comment by nielsfaber** [comment]
What is the purpose for a schedule with more than 2 hours offset from sunrise/sunset?
As far as I know, the sun will be already completely up/down at this time.

**Comment by cornfeedhobo** [comment]
> What is the purpose for a schedule with more than 2 hours offset from sunrise/sunset?
As far as I know, the sun will be already completely up/down at this time.

@nielsfaber The sun would still act as the mental/circadian anchor. I'm learning about HA from through friend's journey right now, and they like going to bed roughly 3 hours after sundown, and yes, it's relative to sundown and shifts with the seasons. I honestly don't think we need a real use case to justify this though.

**Comment by nielsfaber** [comment]
Due to the many requests/complaints I received about this subject, I changed this.
The maximum offset is now increased to 6 hours, which should cover all use-cases.
Please be aware that the offset should be chosen such that the time will not shift to a previous/next day.
This might break functionality, I cannot predict how the result will be in practice.

@nl0pvm Please update the card version to v3.2.8 and test it locally.
You can close the issue if the request is fulfilled, otherwise please let me know.

**Comment by kaaspad** [comment]
@nielsfaber thank you so much for finally doing this, we were running a separate branch to allow this, and that was a total pain in keeping up with your updates. There are 10's if not more users who needed this for a very specific reason and without it we had to go back to the original cumbersome automations. Thanks again, this really allows us to now solely use scheduler for all scheduling needs!! :-)
