### ISSUE TITLE
Wider popup option

### ISSUE THREAD

**Issue by mikulik86** [nielsfaber/scheduler-card#654]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hello and thank you for this great integration.

I'd just like to suggest (if possible at all) adding a setting for changing the width of the popup window. I thing that user should have a choice between this standardized, mobile-friendly window and more user-friendly, wider, for comfortable schedule editing on bigger screens intended window.

### Additional info

If enabled in the card settings, the popup where the schedule is edited would be wider. Possibly according pre-set pixel width.

**Comment by nielsfaber** [comment]
You can click on the title of the pop-up and it will fill the screen width.
I suppose this is enough functionality.

**Comment by mikulik86** [comment]
That is perfect! Thanks.
How did I miss it? I double checked, but can't find where is it written.

**Comment by nielsfaber** [comment]
It is not written, but it’s some convention used by HA. Works for most dialogs, so I thought it was most intuitive for the user.
