### ISSUE TITLE
Repeat a command multiple times during timeslot

### ISSUE THREAD

**Issue by Legendhidde** [nielsfaber/scheduler-card#657]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

My airconditioner doesn’t always respond to commands and it might take 15 minutes to start back up again. Therefore it would be nice if I could specify something that repeats the commands during the time of the schedule. 

### Additional info

I would like to add a repeat every X minutes command that would repeat the command of that timeslot in case an error makes the device miss the command.

**Comment by nielsfaber** [comment]
Choose from the following:
- split the timeslot into multiple smaller slots (e.g. 15 minutes apart)
- create a script which executes a sequence with the delay, and call this from scheduler

I don’t see a way to change scheduler for your needs.

**Comment by Legendhidde** [comment]
Thank you so much for the suggestion! I had indeed already tried to create a couple of extra time slots to retry the command but I was wondering if there was a smarter way to do it, changing the temperature for a time is a little more of a hassle but it works!
