### ISSUE TITLE
Thermostat regulate missing when current mode is not in regulate mode

### ISSUE THREAD

**Issue by tykeal** [nielsfaber/scheduler-card#658]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.4.1

### Component Version

v3.2.14

### Bug description

When a thermostat is currently not in regulate mode (it's in heat, cool, or off) it is not possible to configure a schedule that configures regulate.

I'm not 100% certain, but I believe this bug may have been introduced with 12565a871284ea9617180eaa335c501a0ffbf083

### Steps to reproduce

* Set thermostat to any mode that is not regulate
* Attempt to configure a new schedule and select the climate device
* Notice that there is no regulate option

### Additional info

I don't know if this is a by-product of the thermostats that I'm using, but I've got access to two different brands of thermostats:

* Honeywell Lyric
* Radio Thermostat

In both cases, when not configured to be in the regulate mode, both brands report having `target_temp_high` and `target_temp_low` attributes which are set to `null` while the `hvac_modes` available are `off`, `heat`, `cool`, `heat_cool`

**Comment by nielsfaber** [comment]
`target_temp_high` and `target_temp_low` must not be `null` but type float.
See also [here](https://developers.home-assistant.io/docs/core/entity/climate/#properties).
Scheduler uses these properties to evaluate whether the setpoints need to be updated or are equal to the current setpoint.

**Comment by tykeal** [comment]
That may be, but I have zero control over what the climate device is reporting when it is in a different mode. I'm seeing this same behavior with two different brands of thermostat, so it might be the climate device / entity itself doing this. I dunno. But the device reports that `heat_cool` is an available `hvac_mode` and the regulate option does _not_ show up when building out schedules for these devices unless the device is _currently_ in `heat_cool`. As soon as the device switches to that mode then the `target_temp_high` and `target_temp_low` do have values and you can then create schedules around it that way.

My biggest issue is that I've got some variability in how I need my schedules set. During the warmer months, I need to make sure that I've got a regulate schedule in play as temperatures around my properties can vary from very cold in the morning to very warm during the day and fairly late into the night, but during colder months, I need the schedules in a pure heat only mode.

Makes it hard to properly build out the schedules when you can't access an item because the device is in a specific mode that the card doesn't seem to recognize

**Comment by tykeal** [comment]
I will note, that once a schedule is created, turning it on does the correct thing. It's just a little painful getting it properly created if the climate device isn't in a regulate mode while doing it.
