### ISSUE TITLE
Schedule not triggered when sensor is equal value

### ISSUE THREAD

**Issue by terriblefox** [nielsfaber/scheduler-card#659]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.4.1

### Component Version

3.2.14

### Bug description

I have a schedule that triggers when temperature is below 29 degree. But its not triggering when the temerature ist 29 degree at this moment. ist there a way to set it to eqal and below this temperature?

### Steps to reproduce

Set schedule. Temperature condition to temperature. When schedule is triggered an temperature is equal to the is below condition its not triggering.

**Comment by jleach87** [comment]
same as [issue 648](https://github.com/nielsfaber/scheduler-card/issues/648).
