### ISSUE TITLE
No edit/add of schedules in browser mod popup card

### ISSUE THREAD

**Issue by MeisterW** [nielsfaber/scheduler-card#660]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.4.1

### Bug description

Since card version 2.4.0 it's not possible to add or edit schedules if the card is used in a browser mod popup card. If I place the card directly on a dashboard all is working fine.

### Steps to reproduce

Here is a simple example config I used for testing:
![Screenshot_2023-01-05-21-04-06-550-edit_io homeassistant companion android](https://user-images.githubusercontent.com/53051509/210870088-13fbdfe0-ae76-4c3b-907c-709623f5600e.jpg)

**Comment by nielsfaber** [comment]
This is not a bug.
The card is not designed for working with browser mod.

**Comment by MeisterW** [comment]
Before version 2.4.0 I used the card also with the browser mod popup card and it was working

**Comment by nielsfaber** [comment]
I believe you.
Version 2.4.0 (and onwards) use a pop-up dialog for editing schedules.
It may be that a pop-up inside a pop-up is not possible.
This usage is at your own risk I’m afraid. I am not using browser mod.

**Comment by MeisterW** [comment]
Ok I understand...so would it be possible to "reactivate" the old behaviour with a new config option? Or are the code changes are to big between the 2 handling variants?

**Comment by adizag** [comment]
same here.
it is very unfortunate that this matter won't be fixed...
