### ISSUE TITLE
Change always immediately cancelled in a schedule

### ISSUE THREAD

**Issue by argonaute199** [nielsfaber/scheduler-card#668]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

Last

### Component Version

Last

### Bug description

The scheduler component worked fine for more 1 year. But since a couple a weeks, I am not any more able to make changes in the schedulers.
If I change or add a period in a existing schema, or if I change a value, the changes are automaticaly canceled after 1 or 2 second, and the previous schema and values are restored. I don't have time to save.
For information, I have about 20 schedules, and several scheduler-cards.

### Steps to reproduce

Edit an existing schedule. The change are canceled.
Code :
    - type: custom:scheduler-card
      title: false
      show_add_button: false
      discover_existing: false
      show:
        labels: true
        labels_secondary: false
      display_options:
        primary_info: name
        secondary_info: ' '
      include:
        - input_number.chauffage_cuisine_consigne

**Comment by sddgit** [comment]
This sounds like a problem that was addressed a while ago. Are you sure you have the latest version, and have restarted HA/cleared caches etc?

**Comment by argonaute199** [comment]
Hello,Yes I am sure. The Scheduler component version is v3.2.14. I have the problem for a couple of weeks and I did a lot of restart in the period.I have the same problem in a web explorer, iphone app and ipad app. Yes I tried to clear the cache and reload the component.I have posted my problem in a forum and somebody else has the same problem.Let me know if you need anything to identify the problem. Or can I try something to fix this ? Thank you.Le 29 janv. 2023 à 03:38, sddgit ***@***.***> a écrit :﻿
This sounds like a problem that was addressed a while ago. Are you sure you have the latest version, and have restarted HA/cleared caches etc?

**Comment by nielsfaber** [comment]
Please follow these instructions: https://github.com/nielsfaber/scheduler-card#checking-card-version

**Comment by argonaute199** [comment]
Got it, Thank you !!! I checked in the dev console (Edge) and it was version V2.0.5. Probably installed manually with the Scheduler component (?)

So I reinstalled it with HACS and it works. Thank you very much and congratulation for this great component which fill a huge gap of Home Assistant.

I report the point in our forum (french forum HACF).

 

 

De : Niels Faber ***@***.***> 
Envoyé : dimanche 29 janvier 2023 11:45
À : nielsfaber/scheduler-card ***@***.***>
Cc : Argonaute ***@***.***>; Author ***@***.***>
Objet : Re: [nielsfaber/scheduler-card] Change always immediately cancelled in a schedule (Issue #668)

 

Please follow these instructions: https://github.com/nielsfaber/scheduler-card#checking-card-version

**Comment by simbesh** [comment]
same thing happened to me I was stuck on 2.3.6 (console)
but in HACS it said I was on version 3.2.6. (this was probably causing auto-updates to break as its a greater version than exists)
Redownloaded in HACS and now I'm on the correct 2.4.1
