### ISSUE TITLE
Add the capability for multiple actions

### ISSUE THREAD

**Issue by CygnusX2112** [nielsfaber/scheduler-card#673]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be nice to have the ability to trigger multiple actions. 

### Additional info

For example, when selecting a climate device, i would like to have some cooling periods where i have a different fan setting without needing to create separate schedules for this action to occur. It may also be beneficial to be able to trigger automatons as part of a climate schedule such as enabling fans during certain heating or cooling periods.

**Comment by devildant** [comment]
+ 1 for this task
