### ISSUE TITLE
Allow broader set of conditions to be evaluated

### ISSUE THREAD

**Issue by CygnusX2112** [nielsfaber/scheduler-card#674]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be nice to have the ability to check for a broader range of conditions to evaluate.

### Additional info

In climate scheduling, it is currently not possible to evaluate whether the thermostat preset is in Eco mode. If one is using automatons to set the thermostat to "away" the schedule will override that setting when the next scheduled action is triggered. If the schedule is able to use conditional values derived from the thermostat's current settings such as HVAC mode or preset, it will allow schedules to run only when they are meant to.

**Comment by mill1000** [comment]
Also would like to see this feature. My use case is identical. I would like the schedule to not apply when the climate entity is set to certain presets.
