### ISSUE TITLE
Provide access to HA timer helpers in schedule conditions

### ISSUE THREAD

**Issue by caribo** [nielsfaber/scheduler-card#676]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [ X] My request is generic, other users may benefit from it too.

### Proposal

Provide access to HA timer helpers in the schedule conditions page so that schedules can be made conditional upon a timer becoming either "active" or "idle". 

### Additional info

My use case is to have a BOOST timer which ramps the temperature up when started and goes back to the scheduled temperature when the timer has finished. So two schedules - a BOOST schedule with a condition that timer.heating_boost IS active, and a regular schedule with the condition that timer. heating_boost IS idle.

I recognise that I can do this by setting up a binary sensor and using that, but the absence of timer entities in the schedule seems like an omission.

**Comment by nielsfaber** [comment]
Yes, I could add support for timer entities in the conditions.
You can also add it yourself by following the instructions here: https://github.com/nielsfaber/scheduler-card#conditions
It comes down to knowing which possible states a timer entity can have, then you can pick one from the list in the conditions menu.
From what I can see, the options are "active", "paused" and "idle".

**Comment by bbiegun** [comment]
This customisation works like a charm. Thanks! I have had missed it before

**Comment by nielsfaber** [comment]
This is now implemented in version v3.2.10 of the card.
