### ISSUE TITLE
Changing script entity won't be saved

### ISSUE THREAD

**Issue by adizag** [nielsfaber/scheduler-card#677]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.7

### Component Version

3.2.14

### Bug description

when trying to change script in a schedule, the change won't be saved.

https://user-images.githubusercontent.com/17390016/219490186-77986267-835e-425c-9945-a9e86e70171c.mp4

### Steps to reproduce

edit a schedule, change entity (script) to be scheduled, hit save.
then entered again to edit, and noticed the ols script is still selected.

### Additional info

When scheduling a new schedule - there is no problem to use the other script, just changing scripts shows problem.

I'm not sure about the schedular card version. the explenations given are not clear what and where to search in DevConsole. I took the version from the HACS installation.

**Comment by nielsfaber** [comment]
I can confirm this bug. The same problem happens for me.
I need to investigate what's going on and fix it, I will let you know later.

**Comment by nielsfaber** [comment]
This should be fixed in the v3.2.8 release.
Please update the card version and test it locally.
You can close the issue if the problem is solved, otherwise please let me know.

**Comment by adizag** [comment]
It is working!
thanks for taking care!
