### ISSUE TITLE
No way to distinguish between "Heat/Cool" and "Heat" for HVAC

### ISSUE THREAD

**Issue by mgartin** [nielsfaber/scheduler-card#680]
First, thank you for the great integration!

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I have a Mitsubishi heatpump that is registered via the [MELCloud](https://www.home-assistant.io/integrations/melcloud) integration. In the Scheduler card it would be good if I could distinguish between "Heat" and "Heat/Cool".

### Actual behavior

Both Heat and Heat/Cool modes are shown as "Heat".

![Screenshot_20230225_185918](https://user-images.githubusercontent.com/25937034/221372851-63a4fb07-5e06-4196-aa1a-62ea09578013.png)

### Steps to Reproduce
Addd a schedule, notice that "Heat" is repeated twice. One of them sets the action "Heat/Cool". The order of the two seems to depend on the language used in the app.

**Comment by mgartin** [comment]
Hi, thank you for replying! 
Yes: Here in Norway, people quite often have both a heat pump and a fireplace. This means that if the heat pump is set to "heat/cool" at 22 C, and you light the fire in the fireplace, the heat pump will try to cool while you try to heat using wood.
Yes, I think it will start cooling if the temperature reaches 23.
Yes, I think in general this is the desired behavior if I choose "heat/cool", but in my situation, I will be careful choosing "heat" to make sure there will be no cooling during winter when I light the fireplace.

This is the attributes of `climate.1_living_room`:
```
hvac_modes: off, heat, dry, cool, fan_only, heat_cool
min_temp: 10
max_temp: 31
target_temp_step: 0.5
fan_modes: auto, 1, 2, 3, 4, 5
swing_modes: auto, 1_up, 2, 3, 4, 5_down, swing
current_temperature: 19
temperature: 18
fan_mode: auto
swing_mode: auto
vane_horizontal: 3
vane_horizontal_positions: auto, 1_left, 2, 3, 4, 5_right, split, swing
vane_vertical: auto
vane_vertical_positions: auto, 1_up, 2, 3, 4, 5_down, swing
friendly_name: HVAC 1 Living room
supported_features: 41

```

Hope this is useful, I'm happy to share more logs etc if needed!

**Comment by nielsfaber** [comment]
Thanks for the context.
I wasn't sure whether it would be useful to have both actions show up instead of hiding one.
Obviously there are cases where you want to choose, so I will make sure the heat/cool action will get a different name.

**Comment by nielsfaber** [comment]
This is now added in the v3.2.8 release. The action will be renamed to 'Heat/Cool' (same as HA).
Please update the card version and test it locally.
You can close the issue if the problem is solved, otherwise please let me know.

**Comment by mgartin** [comment]
Thank you! I have updated and it seems to work just fine.
