### ISSUE TITLE
Simplify scheduling one-time or irregularly scheduled events

### ISSUE THREAD

**Issue by reggleston4** [nielsfaber/scheduler-card#681]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The user experience could be improved by improving the ability to schedule one-time events, or reschedule irregular events. It is possible to schedule one-time events currently, however it is not very intuitive.

**Quick list of changes requested, more details below:**
1. Add repetition option NONE for single-event actions.
2. Make the user interface friendly for scheduling and re-scheduling one-time events.

**Why:**
(example) I am a doctor/nurse and I work irregular days and hours. I would like a very quick and simple way to queue up a single-event scheduled action, such as turning on the coffee maker at 4:00am, or maybe 4:00pm if I’m working overnight. I appreciate that this is possible but would like to simplify the interface. I like that old events are stored, because I can easily set a new time for an event and reactivate it.

Other use cases may be setting up an automation for a single-event holiday light show, or birthday party. Or turning on the sous-vide machine at 3pm for dinner.

### Additional info

Specific Changes on the TIME tab:

1. Change “DAYS” heading to “REPEAT”
2. Add “NONE” option for single-event scheduled actions.
3. Change “CHOOSE” to “OTHER”
4. Bonus feature: Add MONTHLY and ANNUAL options, just to round out the options.

Before changes:
![image](https://user-images.githubusercontent.com/124750885/222625611-ca82e26c-232e-4c3d-b855-6d774250a1a3.png)
After changes:
![image](https://user-images.githubusercontent.com/124750885/222625642-0bc691b9-9e05-49d7-89d6-2cdcc53006fb.png)

Specific changes on the OPTIONS tab:
5. Delete 3-way toggle under Behavior. Replace with toggle switch for “Delete After Completion”
Note on behavior:
“Repeat” is the default behavior if the action is recurring.
“Stop” is the default behavior if the action repetition is set to NONE.
“Delete” is set only when if “Delete After Completion” is checked.

Before changes:
![image](https://user-images.githubusercontent.com/124750885/222625783-b62540f3-bafd-406a-bcd2-01724465c332.png)
After changes:
![image](https://user-images.githubusercontent.com/124750885/222625819-491d0714-9244-4a46-9132-04b68e338714.png)

With these changes implemented, scheduling a new one-time event becomes simple and intuitive.  Re-scheduling and re-activating a one-time scheduled event also becomes very simple.

**Comment by JasonBSteele** [comment]
I came here to ask for this and fund this excellently documented feature request already here!  +1

**Comment by reggleston4** [comment]
Although it is not critical, I am still interested in this mod. I use this functionality frequently.
