### ISSUE TITLE
Titles for 2 schedule cards not refreshing

### ISSUE THREAD

**Issue by isablend** [nielsfaber/scheduler-card#69]
I have defined 2 schedule cards in HA.  One controlling schedules for some window vents, the other for defining activities in the Garden.   The both have defined titles and are show on different pages in HA.   When I move from one page to the other the title of the schedule card is not refreshing.  I.e. when I am on the Garden page and move to the the vent page the schedule card displays "Garden".   Not sure if this is a card issue or a Chrome issue.   If I press CTRL-F5 after moving pages it forces a refresh of the name of the schedule card.

**Comment by KTibow** [comment]
Please only post in the GitHub, not the GitHub and the forum. If you do that I get two notifications, because I'm watching the forum thread and the GitHub repos.

**Comment by nielsfaber** [comment]
I made a fix for this in v1.5.0.
Please test if it solves the issue for you.

**Comment by KTibow** [comment]
Consider closing @isablend?
