### ISSUE TITLE
Is the "Customizing built-in actions" part in the documentation still valid?

### ISSUE THREAD

**Issue by cserem** [nielsfaber/scheduler-card#690]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.8 -but i don't think it matters

### Bug description

I have tried to implement the masking of 'heat' mode to 'auto' on a Tuya TS0601, but nothing is happening. (the mode is not set to auto when i set the temperature when trying with 'climate.set_temperature' service call)

I am pretty sure my settings are good, as it changes name when i give it a "friendly_name".

https://www.home-assistant.io/docs/configuration/customizing-devices/ has a list of the supported platforms and climate is not listed.

### Steps to reproduce

apply customize: code from documentation

**Comment by nielsfaber** [comment]
Please see here: https://github.com/nielsfaber/scheduler-card#configuration

The 'customize' as defined in the documentation refers to a setting that can be applied to the card (YAML code).
This is not the same as the customize as used in HA to modify entities.

You can modify the built-in actions within scheduler-card, this does not modify the actual entities.

**Comment by cserem** [comment]
Ohh, I see, thank you, and sorry!
