### ISSUE TITLE
Time scheme every 2, 3 or 4 days, no matter what day of the week is

### ISSUE THREAD

**Issue by eHc-HA** [nielsfaber/scheduler-card#691]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be useful to have a time scheme that fires every 2, 3 or N days, no matter what day of the week is.
Br,
eHc

### Additional info

N/A,  I think that it is straightforward.

**Comment by ulises3131** [comment]
I support the motion.
It is a good idea. It is a function that I need for a long time
