### ISSUE TITLE
Feature Request: Add sunrise/sunset option when building a scheduling scheme

### ISSUE THREAD

**Issue by larry-glz** [nielsfaber/scheduler-card#692]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Propose to add a sunrise/sunset option(s) when building a scheme.  

### Additional info

As a use-case example, I'd like to build a scheme that turns the lights on at Sunset and off at Sunrise.  The reason for using a scheme vs the time schedule option is that the scheme option seems to detect a device state that becomes available (from "unavailable") during a scheme "slot" and performs the appropriate action.  The standard time scheduling option doesn't - if a device is "unavailable" when a time schedule occurs, the device is not actioned and doesn't detect when the state changes to "available."

**Comment by nielsfaber** [comment]
You can click on the marker that shows the configured time and switch to sunrise or sunset.

**Comment by larry-glz** [comment]
Excellent!

**Comment by smenzer** [comment]
Did this break/go away? I used to have some schemes configured on sunset, but now the option seems to be gone:

<img width="560" alt="image" src="https://github.com/nielsfaber/scheduler-card/assets/624392/336de0f3-697a-4735-b65f-cc970662644d">

I'm on version 3.2.11
