### ISSUE TITLE
Use Scheme to set heat/cool settings

### ISSUE THREAD

**Issue by smenzer** [nielsfaber/scheduler-card#698]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

My thermostat supports heat, cool, and "heat/cool" modes. This scheduler card supports the heat and the cool perfectly. However, if I want to set a "scheme" that set's a heat/cool value, I can't. What I would like to do is in the scheme, set the max temp before it turns on the AC, and at the same time set the minimum temp before the heat turns on. At this time, I'm only able to set a heat or a cool temp.

### Additional info

In the Scheme settings for a time period, allow "heat/cool" with options to set the max and min temperatures to activate the A/C/heating

**Comment by smenzer** [comment]
I am able to see the Heat/Cool option, but there's no way to set the min / max temp because there's only a single temperature bar:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/624392/233854286-195a0ff1-e30a-4fcd-b3db-6cb82e109638.png">

**Comment by wez** [comment]
I just started using this card and I'd also love to be able to set both set points this way!

**Comment by smenzer** [comment]
this is still a critical feature request for me - it's really limiting how I can manage my climate control at home.

**Comment by nielsfaber** [comment]
@smenzer Can you make a screenshot of your climate entity properties under developer tools -> states?

**Comment by smenzer** [comment]
sorry for the delay @nielsfaber, but here you go! let me know what else you need or how I can help

<img width="1062" alt="image" src="https://github.com/nielsfaber/scheduler-card/assets/624392/4b504cbe-e406-4fad-ae0f-671865a66f61">

**Comment by nielsfaber** [comment]
I found out that the scheduler card was having trouble with the `target_temp_high` and `target_temp_low` set to 'null'. 
The card checks whether these properties exist to determine whether your device supports setting temperature with a low/high range.

To reproduce the scenario I created a climate device with the same setting and saw that the sliders were not shown.
After changing the code to allow these properties to be set to 'null' the sliders showed up.
I will let you know when this change is released, I assume it will fix the problem for you as well.

**Comment by nielsfaber** [comment]
Version v3.2.10 of the card is now released, could you please update to this version and verify this solves the issue for you?
If so, you can close the issue.

**Comment by smenzer** [comment]
I can now see the min and max temp sliders! thanks @nielsfaber

**Comment by lordbah** [comment]
I think I'm having the same issue, except in my case it's called AUTO instead of HEAT/COOL. Venstar Explorer Mini. Scheduler card 3.2.13. Scheduler 3.3.3. HA 2024.4.4.
![Screenshot from 2024-05-09 14-19-56](https://github.com/nielsfaber/scheduler-card/assets/24962539/b6c9ff15-7ce1-414b-81a4-252827276c55)
![Screenshot from 2024-05-09 14-20-51](https://github.com/nielsfaber/scheduler-card/assets/24962539/80f8a08f-f9e3-4c6e-8dd7-3dc75bf3445a)

**Comment by lordbah** [comment]
Okay, it looks like the behavior which Venstar calls "auto" is what HA calls "heat/cool", which is different from the behavior which HA calls "auto". This device has no AI or learning. Those target_temp attributes aren't even present unless I use the Mode switch on the device to get it into auto mode. Should the Venstar integration be translating the available hvac_modes to account for this?
