### ISSUE TITLE
Condition editor per action 

### ISSUE THREAD

**Issue by erikmex-root** [nielsfaber/scheduler-card#699]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Currently there’s a condition editor that applies to the whole schema and works fine e.g to turn the heaters ON only when it’s below 19 degrees. I want the scheme to also turn them OFF between 10-15hrs (when nobody is home) but it won’t do it because the condition “only when temp is < 19 degrees” is not fulfilled at 10:00 when the heaters have been running for a while.

To solve this, my request/proposal is to have the possibility to add a condition editor per action and not per schema. 
I.e 
1. turn the heaters/AC on between 4-10 am only if the temp is < 19 degrees 
2. Turn the heaters/AC OFF between 10-15 regardless of the temperature (no condition here, only follow the scheme based on time)

### Additional info

One way to do it in a simple way is to include a checkbox per action indicating if the “schema condition” applies to that action. 

A more complete and flexible way to do it is to include a condition checkbox and a condition field per item in the schema. This is a bit more complex and might impact user friendliness

**Comment by nielsfaber** [comment]
I have considered this but I have no idea how to adapt the card in a way that this remains intuitive.
In my opinion the best solution would be that the user can define per timeslot a set of conditions.
Since we are talking about multiple sets, adding a checkbox will not be sufficient for this.
