### ISSUE TITLE
Custom element doesn't exist: scheduler-card.

### ISSUE THREAD

**Issue by GiladShoham** [nielsfaber/scheduler-card#70]
Hi,
This card looks just awesome!

I've installed the scheduler-component successfully (added the integration as well)
Now I've downloaded the card js file and put it like any other card I downloaded.
but once I tried to add the card to the UI I got `Custom element doesn't exist: scheduler-card.`
any idea?

thanks!

**Comment by nielsfaber** [comment]
You need to add it to the Lovelace resources, and reload the resources.
If you use HACS its should be done for you, if not, you should go to Configuration -> Lovelace -> Resources and add the link to the local location.
Resources button in Lovelace will only be shown if you have the advanced mode enabled in your HA account settings.

**Comment by GiladShoham** [comment]
I have added it to the resources like I always do (I'm not using hacs), but it still not there

**Comment by GiladShoham** [comment]
![image](https://user-images.githubusercontent.com/3840769/94285247-1b668880-ff5c-11ea-81d6-5bf5359e8fab.png)

**Comment by nielsfaber** [comment]
I am not sure if `/plugins/` is the right place.
My recommendation is to place the file in `/www/scheduler-card/scheduler-card.js`
This would translate to `/local/scheduler-card/scheduler-card.js?v=0` in resources.

**Comment by KTibow** [comment]
Can you access it with a browser?

**Comment by GiladShoham** [comment]
All my custom cards are inside plugins folder and works properly.

**Comment by GiladShoham** [comment]
> Can you access it with a browser?

yes. works without any issues.
`http://my-ip:8123/local/plugins/scheduler-card.js?v=0`

**Comment by GiladShoham** [comment]
that's suddenly just start working right now.. don't know why.. i did nothing.. 
Now I can start really play with it:)

**Comment by comtsamsmith** [comment]
I have installed it.  It displays some times and sometimes not.  Even had two windows in Chrome open.  On one tab it displayed, the other it did not.  Most odd....?

**Comment by comtsamsmith** [comment]
I have the Scheduler UI working fine but sometimes it did not display.  But now it no longer displays:
![image](https://user-images.githubusercontent.com/5856447/106605695-198b8200-6559-11eb-9263-65c707f7010c.png)

I have tried various suggestions in the Configuration >> Lovelace Dashboards >> Resources
![image](https://user-images.githubusercontent.com/5856447/106605861-493a8a00-6559-11eb-9d49-d1811871f1e7.png)

The files are in place:
![image](https://user-images.githubusercontent.com/5856447/106605950-6a9b7600-6559-11eb-8aae-fa9edbeb7ddd.png)

It looked like its trying to reference the customer element, as the console reports:
![image](https://user-images.githubusercontent.com/5856447/106606056-90c11600-6559-11eb-9cbe-ee47ffabe4fc.png)

I guess a config file somewhere sets these references, but I cannot find it.

Any ideas why its not working.  It worked for a day or two, but intermittently failed.

**Comment by nielsfaber** [comment]
@comtsamsmith I don't know about this, haven't heard it before.
Maybe the best approach would be to add another custom card to your HA setup.
If it experiences the same problems, the issue is probably caused by HA itself.

**Comment by comtsamsmith** [comment]
> @comtsamsmith I don't know about this, haven't heard it before.
> Maybe the best approach would be to add another custom card to your HA setup.
> If it experiences the same problems, the issue is probably caused by HA itself.

Yes tried what you said.  Added "Zigbee2mqtt Networkmap Card" and it does not show either, so yes it must be something to do with HAcks or something...  Christ it's all very technical. I'm a programmer and its been a fair bit to lean, nto into UNIX or YAML.  Anyway your add on is quite smart, should be part of the core system.  FAB if I can get the card working again...

**Comment by KTibow** [comment]
@comtsamsmith it's not `/local/`, it's `/hacsfiles`.

**Comment by comtsamsmith** [comment]
> @comtsamsmith it's not `/local/`, it's `/hacsfiles/`.

Tried it, over several days, all nothing worked.   So reinstalled the whole system...  Very time-consuming but not your fault.  All works fine again now.

I did notice a lot of errors from the database being corrupted, but I think that's for device history only.  So on new installation bought a UPS battery so no power outages can take the system down.  Thanks for your help.  Love this card its great,

**Comment by andkuzmich** [comment]
I have the same trouble. Looks like a bug in HA?

**Comment by snoozer** [comment]
Hmmm..... I have been trying this for days now on a R-Pi as well as on a VM of Home Assistant. All works well to the point where I want to add the  custom car. I use the copy buttong from the website here:

https://github.com/nielsfaber/scheduler-card#installation

juust to be sure I have no wrong whait spaces etc. I get the message:

Configuration errors detected: Custom element not found: scheduler-card

Also the documentation refers to a "ui-lovelace.yaml", I can not find that anywhere. I am stuck and don't know how to proceed. If I use the browser and point it to the file manually is is displayed in the browser. My URL is:

http://MYIP:8123/local/scheduler-card/scheduler-card.js?v=0

Help would be much appreciated
Kind Regards
Jan P.

**Comment by kkaefer** [comment]
If you’ve come here because you can’t add the scheduler card: Try reloading the HA webpage in your browser.

**Comment by abakus2k2** [comment]
> If you’ve come here because you can’t add the scheduler card: Try reloading the HA webpage in your browser.

Whoa, the solution was so easy, thank you so much! It almost drove me crazy after doing researches for over an hour to add the scheduler card.
