### ISSUE TITLE
Re-evaluate on change doesn't revert to "normal" state

### ISSUE THREAD

**Issue by smenzer** [nielsfaber/scheduler-card#701]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.9

### Component Version

3.2.14

### Bug description

I'm having a very similar issue to https://github.com/nielsfaber/scheduler-card/issues/648, but it might be slightly different so opening a new one. If this belongs in the component instead, please let me know.

My schedule is to turn an air purifier on during working hours (8am-6pm on workdays) when my occupancy sensor shows me as home, and keep it off the rest of the time. My scheduler card for this schedule works perfectly:

However, if I leave or arrive during the middle of the day, the air purifier stays in whatever state it was in. 

What I was hoping would happen is that when the condition of "Scott Home Status is NOT Home", then I just want the air purifier off. I was hoping this single schedule would do that.

If I add a 2nd schedule, that runs every day and sets a scheme to "Off" for all hours of the day, but with a condition "Scott Home Status is NOT Home", then the air purifier properly turns on when I'm home during weekdays and off when I'm not. But this means managing a 2nd schedule with similar conditions, which is both an extra step during setup and is more prone to forgetting about if i make changes later. Is this how the scheduler card is supposed to work or is there a way to have more of a "fallback state" in my first/main scheduler?

### Steps to reproduce

Here are some screenshots of my setup:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/624392/235473257-153aafe2-8022-45ca-84ef-46c7661a8cb3.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/624392/235472494-eeff142a-84dd-4687-bc4d-5fb03217d7a3.png">

**Comment by smenzer** [comment]
this is still relevant in my opinion.

**Comment by nielsfaber** [comment]
This is not a valid bug.
Your expectations are just not aligned with the implemented behaviour.
Scheduler will only execute the actions as defined in the time slots, it will not assume an opposite action has to be executed if a condition fails.
In fact the condition applies to all time slots so performing the opposite action may result in undesired behaviour in the first and last timeslot.

**Comment by smenzer** [comment]
ok thanks for the explanation, i think i understand your logic better now. i'll stick with using two schedules (one for home, one for away) ... thanks!
