### ISSUE TITLE
Scheduler Card using self.async_update_ha_state(), without enabling force_update

### ISSUE THREAD

**Issue by lichenophile** [nielsfaber/scheduler-card#702]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.9

### Bug description

Home assistant is reporting this issue on boot. Perhaps since updating HA to 2023.5.0.

`Entity switch.schedule_a4ac24 (<class 'custom_components.scheduler.switch.ScheduleEntity'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`

### Steps to reproduce

Reboot Home Assistant

### Additional info

I have not yet had a chance to test if schedules still function in spite of this error.

**Comment by lmagyar** [comment]
I've tried, and that is causing other errors, so it doesn't seem to be a good fix:
```
2023-05-05 15:10:57.062 ERROR (MainThread) [homeassistant.util.logging] Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('6ad0bf',)
Traceback (most recent call last):
  File "/config/custom_components/scheduler/switch.py", line 259, in async_timer_updated
    await self.async_write_ha_state()
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by FredWst** [comment]
await self.async_write_ha_state()
Remove await

just : self.async_write_ha_state()

**Comment by nielsfaber** [comment]
This should be solved by updating the scheduler-component to the latest version.
