### ISSUE TITLE
Unable to set temperature for thermostat

### ISSUE THREAD

**Issue by tekelectron** [nielsfaber/scheduler-card#703]
Hi

Used to be able to set temperature for climate but now it snaps back to 10 degrees and wont let me modify it. However it did work and I still have entries in the schedule with temperatures set. But this even I tried to turn the temperature down on an entry and it just immediately snaps back to 10 degrees and wont set. This occured after updating to the latest home assistant release and wasn't an issue before

I wish I hadnt tried changing the temperature now!
![slider_greyed_out](https://user-images.githubusercontent.com/67764276/232239999-5057aff9-c91d-4a29-b62f-3f8e59a2b377.png)
![shecule_temperature](https://user-images.githubusercontent.com/67764276/232240029-510dc2be-af54-4099-ac9a-efaf052165ba.png)

**Comment by glienart** [comment]
I have this exact same issue here is my state:

```
hvac_modes: heat, off
min_temp: 18
max_temp: 40
target_temp_step: 1
preset_modes: silence, smart, turbo
current_temperature: 28
temperature: 28
hvac_action: idle
preset_mode: smart
error: OK
error_2: 0
icon: mdi:hot-tub
friendly_name: IPS heatpump
supported_features: 17
```

**Comment by nielsfaber** [comment]
@glienart 
I created an entity with the same properties as yours to debug this problem:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/cdeacdc3-f056-42bb-abd7-82a74537e345)

If I create a schedule for setting the temperature all shows up as I would expect it:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/28008d9f-34d6-4158-ace6-61b0e264d3b0)

I am able to save the schedule and if I edit it afterwards, all looks the same.

Can you please elaborate what is not wroking for you?
Can you share some pictures or a screen video to illustrate the problem?
Which version of scheduler card are you using?
