### ISSUE TITLE
Cant see the scheduler card in the dashboard

### ISSUE THREAD

**Issue by Mari143** [nielsfaber/scheduler-card#705]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.15

### Bug description

Downloaded via hacs and added the integration and restarted HA.
Then when I go to dashboard and press edit dashboard, I dont see the scheduler card...

### Steps to reproduce

Mentioned above

**Comment by nielsfaber** [comment]
You need to install the card as well via HACS.
