### ISSUE TITLE
Schedule for each day in one Scheduler

### ISSUE THREAD

**Issue by duczz** [nielsfaber/scheduler-card#708]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Is it possible to create !one! Scheduler with multiple Start times? (i hope im not blind and these function is not exist^^)

For example climate: Monday to Thuesday - 16:00 - 22:00, friday: 13:00 - 22:00, Weekend 07:00 - 22:00?

### Additional info

-

**Comment by nielsfaber** [comment]
This is not possible, you will have to create different schedules to do so.

**Comment by duczz** [comment]
is it mabe possible to integration a helper variable for these feature (already exists)?

![image](https://github.com/nielsfaber/scheduler-card/assets/25475385/587fceed-292d-407d-b85f-779e1e0a1541)
