### ISSUE TITLE
Wrong icons for lock

### ISSUE THREAD

**Issue by jgirardet** [nielsfaber/scheduler-card#709]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.9

### Component Version

3.2.15

### Bug description

About a  lock:
Lock icon is for unlock and unlock icon is for lock
which should be the opposite.

![image](https://github.com/nielsfaber/scheduler-card/assets/30120358/83d02ed5-c83f-41cc-a3a1-1803ec785b98)

thanks for this great addon

### Steps to reproduce

just set up a condition with a lock

**Comment by nielsfaber** [comment]
Well spotted!
I swapped the icons in the code, it looks OK now:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/20283816-b6a0-4850-8d0a-8357a0c524cd)

I will follow up on this when the change is released.

**Comment by nielsfaber** [comment]
Version v3.2.10 is now released, the issue should be solved after updating.
