### ISSUE TITLE
Allow diferent types of entities to work in one schedule

### ISSUE THREAD

**Issue by gajotnt** [nielsfaber/scheduler-card#711]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Im trying to use two **select** entities but because they have diferent fields (it think thats whats causing it), it doenst allow me continue.

![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/ede84041-4dd4-451a-8c53-94a49d9fb4cf)

Or the best case scenario:
![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/e0420012-b934-4193-b1a8-17bda47db200)

It gets me to the next page but then i cant add the action.

### Additional info

The options the select entities have:
![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/7c6296c6-5326-45c7-976c-8e4b86e7ac6f)
and
![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/102524a8-a3d2-4238-bf29-82b8c15c483f)

**Comment by Tofil** [comment]
Yes that would be great especially for changing multiple scenes through the day. Right now i can only launch them all at the same time 
![image](https://github.com/nielsfaber/scheduler-card/assets/38903221/9e8ba851-46e8-495c-b62f-2d90968a2027)
