### ISSUE TITLE
Display schedule name plus action as primary info

### ISSUE THREAD

**Issue by Nightenom** [nielsfaber/scheduler-card#712]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hi,
I am missing option which would display "\<schedule name>: \<action name from task summary>"

### Additional info

Given schedule "test" with many switches and "turn on" between noon and midnight and "turn off" otherwise it would display: "test: turn on" (between noon/midnight) and "test: turn off" otherwise

Current options are "\<schedule name>" or "\<entities>: \<action name>"
![image](https://github.com/nielsfaber/scheduler-card/assets/17338378/3aed74b6-e583-46fe-bb86-fa75efeab3b6)

**Comment by Nightenom** [comment]
Not stale

**Comment by nielsfaber** [comment]
This can be done via YAML mode (as described in your other issue report).
I prefer not to provide all possible options (and combinations) in the UI editor, as it will become confusing for a lot of users.
For the configuration of this card you could say UI = basic mode, YAML = advanced mode.
