### ISSUE TITLE
Single time execution 

### ISSUE THREAD

**Issue by roydestroy** [nielsfaber/scheduler-card#715]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be great if there was an option for a one time execution. So for example let's say we go to bed and start watching tv. We could use the specified card as a sleep timer for the tv so that we can define a specific time for the tv to turn off only that time and after that the specific schedule would be automatically deleted. 

### Additional info

This would be very useful as a countdown timer for various devices like water heaters ovens etc.

**Comment by nielsfaber** [comment]
This already exists.
Check the ‘options’ tab and look for the ‘behaviour after triggering’.
You can choose to have a schedule turn off or completely delete after it was triggered.
