### ISSUE TITLE
In the time selection, in addition to daily, weekdays, and weekends, can we add an additional function of "one-time"?

### ISSUE THREAD

**Issue by horacecar** [nielsfaber/scheduler-card#716]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

In the time selection, in addition to daily, weekdays, and weekends, can we add an additional function of "one-time"?

### Additional info

none

**Comment by nielsfaber** [comment]
No. One time is not a day.

**Comment by horacecar** [comment]
Not that I mean to add a countdown is a one-time countdown, for example, I want to have a plan today, turn on the air conditioner before I get home at 7 pm, this one-time countdown

**Comment by nielsfaber** [comment]
Try this option:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/0480c75e-a98b-426f-a859-98dc454d49cf)
