### ISSUE TITLE
No group defined - Impossible to select an entity

### ISSUE THREAD

**Issue by kalhimeo** [nielsfaber/scheduler-card#717]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.10

### Component Version

v3.2.15

### Bug description

When I try to add a new schedule, the scheduler card windows shows no group and there is no possibility to select an entity (see screenshot).

![Capture d'écran 2023-08-12 192300](https://github.com/nielsfaber/scheduler-card/assets/6355373/8c9ed69a-0c65-4171-bd98-bdb7a58cbb33)

Note that this problem started to happen after one of my schedule became corrupted (state unavailable). I tried to uninstall and re-install both components (card and integration) and restart HA, but I still have the problem. It looks like there are some data remaining from my previous installation. Note that I tried to force a cache update of my browser (ctrl+F5) and even tried from an other device, but that did not help.

Let me know if I can help with debugging.

Best regards,
Laurent

### Steps to reproduce

I simply add a new card with :

`  - type: custom:scheduler-card`

and then click the "ADD" button

**Comment by kalhimeo** [comment]
For unknown reason it s working again, I can't explain why. I just restarted the full server a couple of times since my bug report (although I did that during debugging as well). I close the report for now :-)

**Comment by EPicLURcher** [comment]
I am now seeing the same - even after several restarts
