### ISSUE TITLE
Feature request: custom time range for timeslot editor

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#72]
I saw above a working screen shoot for the thermostats programming, I think it would be good to foresee that if a start is at 20:00 for example it can end the next day at 01:00 after midnight…

**Comment by Misiu** [comment]
@mycanaletto I think that this would be an overkill.
You can always scheduler something from 20:00 to 00:00 and from 00:00 to 01:00. This will have the same effect if you check every day.

![image](https://user-images.githubusercontent.com/1741838/94790745-01eb9380-03d7-11eb-9fb0-0a771ae57159.png)


@nielsfaber if I remember correctly the scheduler does its job at the start of the time slot, so in the above example the action will be called twice. In the case of a thermostat that really doesn't matter.

There is one possible place for improvement. In the above case when you schedule an action from 20:00 to 00:00 and the next one from 00:00 to 01:00 and it is **THE EXACT SAME ACTION**, then the second action can be skipped.
I'm looking at this from the perspective of scheduling thermostats, so there can be other use cases.

What do you think?

**Comment by mycanaletto** [comment]
@Misiu Of course I can make two schedules, I'm not completely dumb. But when we design something we try to propose the best user experience. Hence this proposal.

**Comment by Misiu** [comment]
> @Misiu Of course I can make two schedules, I'm not completely dumb.

I didn't say that.

My intention was to say that it will be hard to build UX that satisfies every need/requirement.
I've used and I'm still using a couple of planning/scheduling software and in any of them, I didn't saw the option to create a scheduler that exceeds the max time.
In a 24 hours view, the min is 00:00 and the max is 24:00.

Something that you are proposing would be ok if this component would allow creating scheduler for the whole week, but not for 24 hours.

But that's just my opinion.

**Comment by nielsfaber** [comment]
For the time being you will have to live with timeslots that stop at midnight.
If you want to extend this, you should add a small block in the next day, like @Misiu suggests.
The release is of this feature is planned for the end of the week, and I expect a lot of feedback...

Currently there is nothing in place in the `scheduler-component` to check if an action has any effect, or it is a duplicate of a previous action.
There is not even a check in place to verify if an entity exists or the service_call is valid.
Lots to be done, but first things first.

**Comment by nielsfaber** [comment]
I am adding this little check in the `custom_component` such that it will be at least _possible_ to have start time=23:00 and end time=01:00 etc.
```
    if (end_time - start_time) < 0: 
        end_time = end_time + datetime.timedelta(days=1)
```

**Comment by mycanaletto** [comment]
It's just a proposal.

But I made this proposal because Jeedom (a French competing home automation solution) already proposed it 5 years ago...

This is one of the things I regret the most with Jeedom, his planner. For the rest I am very happy to have abandoned it.

Watch this video again, it's in french but the images speak for themselves...
https://www.youtube.com/watch?v=EBuvIabg3Cc

Having said that, this possibility was not an emergency, but it would be an undeniable plus.
