### ISSUE TITLE
Scheme time selection notncovering whole day

### ISSUE THREAD

**Issue by pamatika** [nielsfaber/scheduler-card#720]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.10

### Bug description

When I try to select time that starts earlier than 00:28 it is not possible. Same happens after 23:32. I have tried with Samsung Tab s8 ultra and phone Samsung A72.
Probably some gui limitation. I don't mind if the time selection resolution is not accurate but selecting starting time 00:00 should be possible.
![Screenshot_20230902_200354_Chrome](https://github.com/nielsfaber/scheduler-card/assets/11091266/63a5da8b-8dd3-45e1-9451-ee3c99d9f474)

### Steps to reproduce

Add new scheme and try to adjust start time 00:00 or 23:59

**Comment by nielsfaber** [comment]
You are changing the starting point of the second timeslot.
It cannot move all the way to 00:00 since it would become overlapping with the first timeslot.
Why not delete the middle timeslot, and stretch the first one?

**Comment by pamatika** [comment]
Now I feel really stupid....  :)

Thanks for great tool.

**Comment by nielsfaber** [comment]
No problem, I'm glad the problem is solved for you.
