### ISSUE TITLE
no option tab on the card with HA version 2023.9.1

### ISSUE THREAD

**Issue by raytedjaja** [nielsfaber/scheduler-card#722]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.10
### Component Version

3.2.15

### Bug description

something is broken after i update HA to 2023.9 maybe?

for now i cannot rename the card or change conditions (missing tab header)
no entity/time/options tab

![chrome_kJMq3LZson](https://github.com/nielsfaber/scheduler-card/assets/24861287/b8841caf-d262-43d3-b4a1-1ffb85314c70)

### Steps to reproduce

when i click the card (not in edit dashboard mode)

**Comment by pbranly** [comment]
Same issue

**Comment by cdenfert** [comment]
Same issue here

**Comment by derekcentrico** [comment]
New to this (just installed via HACS running 9.1) and can't even find the Scheduler card.  Assume this is related.  Following.

**Comment by sky7176** [comment]
same issue

**Comment by derekcentrico** [comment]
Not intending to start a HOWTO discussion here, but I want to ensure this bug is what I'm experiencing vs. newbishness.  I'm now on 2023.9.2 which has the same issue.

I assume we add scheduler content by going to settings -> devices -> selecting the added Scheduler and doing so there.  I don't see Scheduler anywhere else to manipulate.  If I'm wrong, please tell me.

This is what I see when attempting to do my steps:
<img width="934" alt="image" src="https://github.com/nielsfaber/scheduler-card/assets/1930094/b6f289d3-1173-40ab-9b31-d36d27fe52fc">

Adding an entity is just a blank gray screen.

**Comment by oliskippy** [comment]
On top: from 2023.9.2 changes in an existing timer is not saved any more. It sticks to the old setting. 

Only deleting the old timer an adding a new one works.

**Comment by raytedjaja** [comment]
> Not intending to start a HOWTO discussion here, but I want to ensure this bug is what I'm experiencing vs. newbishness. I'm now on 2023.9.2 which has the same issue.
> 
> I assume we add scheduler content by going to settings -> devices -> selecting the added Scheduler and doing so there. I don't see Scheduler anywhere else to manipulate. If I'm wrong, please tell me.
> 
> This is what I see when attempting to do my steps: <img alt="image" width="934" src="https://user-images.githubusercontent.com/1930094/267643553-b6f289d3-1173-40ab-9b31-d36d27fe52fc.png">
> 
> Adding an entity is just a blank gray screen.

no, start with install the card [https://github.com/nielsfaber/scheduler-card#installation](url)
then edit dashboard to add new card "custom: scheduler card"

**Comment by raytedjaja** [comment]
> 't even find the Scheduler card.

well if you new to HACS the scheduler card repo is in "fronted" categories, not "integrations". good luck

**Comment by derekcentrico** [comment]
@raytedjaja yeah I have the frontend added in HACS as well.  I see no new cards anywhere for this so I started thinking maybe I need to do something in integrations.  But, then found this error report and it dawned on me maybe I see nothing and it's all related to this.  (other setups I have on HA went bonkers as well so kind of makes sense in my odd mind).  Alas, I guess I must wait to see when this is repaired to find out if a card will appear for me to work from.

**Comment by raytedjaja** [comment]
@derekcentrico we talking about after you add the card to dashboard right, mine looks like this normally ![Screenshot_20230913-215815_Home Assistant.png](https://github.com/nielsfaber/scheduler-card/assets/24861287/8b028e57-72b2-4bbd-8537-f888f1d5c187)

**Comment by petebanham** [comment]
Same issue for me, no tabs now so can no longer edit any schedules

**Comment by oliskippy** [comment]
> Same issue for me, no tabs now so can no longer edit any schedules

Yes, and even if you reach the edit mode with "Edit Dashboard" button (3 dots on top right), one of my both scheduler card do not save the new settings (changed the script to execute, and sticks to previous script).

**Comment by raytedjaja** [comment]
![image](https://github.com/nielsfaber/scheduler-card/assets/24861287/5203d392-24af-4a57-a936-1bef1ddaef60)

the card is fine if you open in **edit dashboard** mode

**Comment by nielsfaber** [comment]
@raytedjaja Sorry for the late response, I was on holidays.
It seems that the 2023.9 HA update indeed broke the tabs, the element is not loaded by default (only in edit mode).
I will try to change the card to restore the previous functionality, I will post here when I have an update.

**Comment by nielsfaber** [comment]
I just released version 3.2.11 which should fix the issue.
@raytedjaja Could you update to the new version to confirm this solves the issue for you? If so, this can be closed.

**Comment by raytedjaja** [comment]
@nielsfaber i cannot sorry. I have an electric outage since my neighbors house got fire

**Comment by petebanham** [comment]
Working for me now in the mobile app. Thanks so much for sorting.

**Comment by pbranly** [comment]
It works thanks a lot 
Phil

**Comment by IsaacBreuer** [comment]
Thanks,  works

**Comment by ekain-fr** [comment]
Works for me both on mobile iPhone app and on Safari; using HA 2023.9.2.
Thanks @nielsfaber, great job!

**Comment by sky7176** [comment]
Working for me now in the mobile app. Thanks so much for sorting.
