### ISSUE TITLE
Option to retrigger scheme on manual change

### ISSUE THREAD

**Issue by kylerw** [nielsfaber/scheduler-card#723]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I'd like to be able to set a scheme that will retrigger if the entity gets manually turned on/off. 

### Additional info

An example is Landscape lighting. If it gets manually turned off from the UI or the physical device but the scheme is still in the "on" state, I want it to turn back on and same for during the day - if it gets turned on, I want it to be turned off if the scheme is "off".

**Comment by nielsfaber** [comment]
Scheduler is not designed to overrule or interfere with other actions.
It does not keep track of the target entity state and what triggers a change to it (I don't think this information is even accessible in HA, other than in the logbook).
I also don't see a way or a need to do so, hence I'm afraid I cannot fulfill your request.

>  An example is Landscape lighting. If it gets manually turned off from the UI or the physical device but the scheme is still in the "on" state, I want it to turn back on

I would say it is very unintuitive if a user tries to turn off a lamp but it keeps turning back on. 

But if this is really desired, my recommendation would be to use some automation (with condition logic) between the button which the user has to operate the lamp, and the action of turning on/off the lamp.
In the condition logic some information of the related schedule (switch) entity could be used, such as the current timeslot ( property `current_slot`) and the associated action (under property `actions`).

Another way to achieve your goal is by assigning a condition to the schedule and use the option 're-evaluate if condition changes' to have the schedule re-trigger.
However, it is only possible to assign conditions on the complete schedule, so it would have to be splitted into two schedules:
- A schedule with 'turn on lamp' timeslots and condition 'lamp is off'
- A schedule with 'turn off lamp' timeslots and condition 'lamp is on'
Which should obviously not have any overlapping actions (empty/unassigned timeslots are OK).
However, I wouldn't recommend this route as you may experience short blinking of the lamp before the schedule is re-triggered.

Hope this helps.
