### ISSUE TITLE
Feature request: Entity Multi-Select

### ISSUE THREAD

**Issue by avariorss** [nielsfaber/scheduler-card#73]
It would be useful to be able to select multiple entities when creating a schedule. For example to click on the LIGHTS group, and then select 3 specific light entities before selecting the ACTION and clicking NEXT

**Comment by nielsfaber** [comment]
Fair request 👍  I had it in mind already. 
Many preparations for this are in place actually, I only need to figure out how to make it easy to work with.
I will keep you posted if there are updates on this.

**Comment by nielsfaber** [comment]
@avariorss Would you be OK with the action being the same for all entities?
The thing is that it would be possible to give each lamp its own brightness level (or switch some ON, switch some OFF), but I think it will result in a messy configuration page.

Also, did you check out the [scene](https://www.home-assistant.io/integrations/scene/) and [group](https://www.home-assistant.io/integrations/group/) integrations?
They could give you the same functionality.
Scenes are already supported by the scheduler, for groups I have to add some way to find out which actions are suitable.

**Comment by KTibow** [comment]
[Light groups](https://www.home-assistant.io/integrations/light.group/) should be supported by default, because they create `light` entities.

**Comment by avariorss** [comment]
Yes, I agree it could quickly get too confusing to have multiple actions within a single schedule (better to run a scene/script for that). My thought would be to select a number of entities (of the same type, eg cover) and then the action + time settings would apply to all of them. For example, if I wanted all the curtains in the house to close at 8pm. I think this could also be achieved with the [Cover Group](https://www.home-assistant.io/integrations/cover.group/) but I believe that dynamically creating the collection (ie "group") of entities when creating the schedule would be more intuitive/flexible and more convenient to do in the GUI also.

**Comment by febalci** [comment]
I also support this request and what @avariorss said, since i installed scheduler component just for this, for my house shutters. I have 12 shutters (covers), i made automations to make some of them open with sunrise and some others with 8am. Instead of creating different Cover groups, it would be much more flexible and easier to select them dynamically at schedule creation time. That would be superb for on/off covers and switches. So that the action will be the same for all entities...

**Comment by nielsfaber** [comment]
In v2.0.0 of the card, I (finally!) added a switch, that allows you to select multiple entities (of the same type):

![image](https://user-images.githubusercontent.com/16861605/102869014-4f5a2880-443b-11eb-8860-2a2c8192248b.png)
The card should automatically adapt the available actions to your selection.
So if you select for example dimmable and non-dimmable lights, you only have the turn-on/turn-off capabilities without brightness option.

Please test it and let me know if stuff needs to be improved.

**Comment by KTibow** [comment]
IMO the text should be before the switch.

**Comment by KTibow** [comment]
Is this just because this is stale?

**Comment by nielsfaber** [comment]
Request has been fulfilled, issue poster is not responding so I am assuming he’s happy 🙂
