### ISSUE TITLE
Scheduler does not contol temperature

### ISSUE THREAD

**Issue by kalda123** [nielsfaber/scheduler-card#732]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.11

### Component Version

3.2.15

### Bug description

Hi, I have Scheduler card to control 4 of my thermostats (brand is Tesla, but it´s TS0601), they are connected via Z2M. 
I have the time and temperature set in Scheduler card, but the thermostats only turn on/off at the given time, the temperature does not change. The only way to control the temperature is by the user. Back in the spring, everything worked great with the same setup. I tried heating mode and auto mode, but the temperature remained set according to the last setting. 

This problem occurs at a different pre-set temperature (lower temperature after a few hours), or after the user changes the temperature, when, for example, I change the temperature manually to 25, after a few hours the thermostat turns off as planned, in the morning it turns on as planned, but not to the set temperature of 22 , but to the manually set value of 25.

![image](https://github.com/nielsfaber/scheduler-card/assets/95139261/2b1433db-0603-41b0-b619-4653e1c475e2)

Is there anything new I´m missing in settings?

### Steps to reproduce

Error occurs at any thermostat setting (auto/heat)

**Comment by rogerjak** [comment]
Same issue here, doesn't change the temperature :(
