### ISSUE TITLE
[issue]  layout problem

### ISSUE THREAD

**Issue by devildant** [nielsfaber/scheduler-card#736]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.11

### Component Version

v3.2.15

### Bug description

it sometimes happens that the map takes time to appear which breaks the display and displays everything in column

### Steps to reproduce

i can reproduce with ctrl + shift + f5 on chrome

### Additional info

![394268900_735627691753870_4707497779200945714_n](https://github.com/nielsfaber/scheduler-card/assets/8700106/9900e48b-49f1-405a-af76-dc6a58d7fb49)

**Comment by devildant** [comment]
ping

**Comment by devildant** [comment]
Ping

**Comment by nielsfaber** [comment]
> it sometimes happens that the map takes time to appear which breaks the display and displays everything in column

I see, but I don’t see why this is reported as a bug.
Both the loading time and the dividing of the cards on the page are not something I can change. This is part of HA.
