### ISSUE TITLE
When editing scheduler entity and action isn't selected

### ISSUE THREAD

**Issue by Misiu** [nielsfaber/scheduler-card#740]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.11

### Component Version

3.2.15

### Bug description

When trying to edit the scheduler I noticed that entity and action aren't preselected.
I was able to successfully edit the time condition, but it looks weird when there is nothing selected in the first tab:

https://github.com/nielsfaber/scheduler-card/assets/1741838/00829d8b-b072-4e9f-8b1a-4733a84d0349

I'm not sure if this "bug" existed from the beginning, but ideally the entity and action should be selected when we enter the edit mode.

### Steps to reproduce

Add scheduler and after that try to edit it. You should notice that in the first tab (Entity) the entity and the action isn't selected

**Comment by Misiu** [comment]
still actual

**Comment by wardpieters** [comment]
Please re-open, still active.

**Comment by madz12345** [comment]
The issue still persists, especially cumbersome when I utilize the 'multiple' option - as I need to select and remember which ones I've marked.

**Comment by Misiu** [comment]
@nielsfaber can you please reopen the issue? Sadly still actual :/
I've tried to find the cause but no luck.

**Comment by Misiu** [comment]
@nielsfaber any hints on how can I debug this?
I'm not making a lot of changes in my schedulers, but lately, we had a daylight-saving time change (from winter to summer time) and I had to update some entries.
