### ISSUE TITLE
define public holidays

### ISSUE THREAD

**Issue by milanov8** [nielsfaber/scheduler-card#741]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

on public holidays i want my heater as on e.g. sunday, so it would be greate to define them in the UI. 
some of the public holidays ar calculated and some oft them are always the same date...

### Additional info

![119147784-2f5f7d00-ba4c-11eb-9de4-5e62ff5e71a8](https://github.com/nielsfaber/scheduler-card/assets/96972939/d1be6c62-68bc-46f1-8f23-cd3acd70ca75)

**Comment by Cadsters** [comment]
Holidaydays  are already used if you use the workday integration and set it up correctly.
Under days you have already choosen workdays so it's now important to set this properly and according to your wishes.
Have a look here: https://www.home-assistant.io/integrations/workday/

**Comment by mribeiro** [comment]
As @Cadsters mentioned, this already exists.

Maybe you want to set the manually thinking of regional holidays or vacation time? The way I did it was creating a Google calendar with my time off and I have a template binary sensor named "really is working day" setting to "on" whenever is a working day and my time off calendar is off
