### ISSUE TITLE
Midnight shouldn't be considered as beginning of new timeslot

### ISSUE THREAD

**Issue by maia** [nielsfaber/scheduler-card#742]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

A timeslot that begins before midnight and ands after midnight should not be considered as two timeslots ending/beginning at midnight. The reason is the following:

I control my thermostat regulated valves (TRVs) with versatile_thermostat and scheduler_card. In my bedroom I use a timeslot during the night, where I set the "comfort" preset for the room temperature at 20°C. During the day (when noone is in that room) I set it to the "eco" preset with 18°C. Sometimes it's very cold&windy outside, so I manually increase the room temperature to 21° and would like it to stay that way until I wake up. Unfortunately HA considers midnight as the end of a timeslot and the beginning of a new one, so at that moment the scheduled preset "comfort" with 20°C is activated, overwriting my manually set room temperature of 21°C.

I understand the behaviour from a technical perspective, but other than that there should be no reason that midnight splits a timeslot in two pieces (and therefor is the moment where a manually set action is overwritten with a preset)

### Additional info

If the same preset/action/scene/… is configured for the time before and after midnight, this should be considered as a single timeslot.

**Comment by mribeiro** [comment]
I agree with you but maybe there's a way to workaround this.

Say you set the slot from 19:00 to 23:59 with eco 18º. What if you don't change the slot starting at midnight. Nothing will happen iirc

**Comment by maia** [comment]
> What if you don't change the slot starting at midnight. Nothing will happen iirc

The issue is that any manual setting is replaced by the preset at midnight. So e.g. I am sick and want it warmer in the bedroom, so I turn the temperature to a warmer setting than the default preset at 10pm – and two hours later while I'm asleep the default preset kicks in and the temperature drops again.

**Comment by nielsfaber** [comment]
The scheduler made for this project spans from 00:00 to 23:59, so covers one full day.
If you want schedules that last longer than a day, this project is not for you.

As @mribeiro says: it’s your own choice to have a schedule start at midnight. You can also leave slots empty when you don’t want scheduler to do anything.

There is no intelligence in place to detect that two consecutive time slots have the same actions and so the second one should be skipped. In fact, the skipping is not desirable for everyone.

Since scheduler creates switch entities per schedule, you can disable any schedule when you want. This should cover your needs (but requires some additional automation).

**Comment by maia** [comment]
> Since scheduler creates switch entities per schedule, you can disable any schedule when you want. This should cover your needs (but requires some additional automation).

Oh, thanks, I didn't think of disabling the midnight preset in such cases. Do you have any suggestion on how to do that? Ideally I'd want a switch/button/… in the UI that all family members can easily use in such situations.
