### ISSUE TITLE
error :Defective schedule entity: switch.schedule_19bcf8 

### ISSUE THREAD

**Issue by apas2** [nielsfaber/scheduler-card#743]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

last one

### Component Version

v 3 2 15

### Bug description

using only UI:
i had a scheduler with 2 items: week days & week end wich controls 1 thermostat > it works for few weeks = ok
i add a new scheduler for testing home/away conditions with another thermostat only for testing...i get:
**Defective schedule entity: switch.schedule_19bcf8**
so
i erase new scheduler card
reboot HA
i get always the same error **Defective schedule entity: switch.schedule_19bcf8**
wich is added to the first card despite using options: **SHOW ALL SCHEDULES** on or off (same)
how to erase this error ?
![2023-10-28_09h28_50](https://github.com/nielsfaber/scheduler-card/assets/35702564/5fe434ad-2447-4fde-8770-c66379e52843)
no way to remove manualy the schedule :
![2023-10-28_09h45_24](https://github.com/nielsfaber/scheduler-card/assets/35702564/3360dc62-f5a4-4562-833a-3a2e8feda216)

### Steps to reproduce

I dont know how to erase this error
but it appears when testing a scheduler with 1 minute step (may be it takes a lot of resources for computing ?)

**Comment by Spegeli** [comment]
Any Solution for this Problem? I got the same issue.

Even when i delete the Entry out of .storage/core.entity_registry and .storage/scheduler.storage and i restart HassIO, the entrys are added back to the files.
