### ISSUE TITLE
Separate conditions for use with climate entity

### ISSUE THREAD

**Issue by raenji-sk** [nielsfaber/scheduler-card#747]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Is it possible to have two conditions when using scheduler for controlling climate with the "Make Scheme" option enabled?

### Additional info

Like this:
Rise the climate entity set temperature to a higher value if condition 1 applies (sensor.thermometerXY < xy°C)
Lower the climate entity set temperature if condition 2 applies (sensor.thermometerXY > xy°C) or ignore the condition 1 to always lower the temperature at given time point.

**Comment by patriiiiiiiiiick** [comment]
I think this is precisely what I am wondering how to do. I set up a scheme where I have a presence condition. What happens if the condition is false? Or how do I register an ELSE statement for what to do then?

**Comment by patriiiiiiiiiick** [comment]
Actually, it seems this has already been dealt with: https://github.com/nielsfaber/scheduler-card/issues/496.

**Comment by raenji-sk** [comment]
@patriiiiiiiiiick Nice find, thanks. But I wanted to avoid multiple schedules as I already have 5 of them. Main thermostat + shelly radiator valves in multiple rooms. The idea was that the heating should turn on for example at 1pm but only if the temperature is below lets say 19.5°C. If it is warmer outside or the sun is shining it can turn on at a later hour possibly saving some costs.

So I made a helper entity (toggle). This is turned on when temp drops below 19.5 degrees so the schedule can run. It is still on when the shcedule calls for lower temperature on the main thermostat so the condision is met and it does decrease it.

When it calls for lower temp an automation detects it and turns the helper toggle off. So the schedule won't increase the temperature and call for heat unless both time and temperature conditions are met. 

Been runing it like this for the last few days and it works great for me.
