### ISSUE TITLE
[documentation] re-evaluate option is not taken into account

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [nielsfaber/scheduler-card#752]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

0

### Bug description

The documentation states:

> ⚠️ Note: Conditions are only evaluated at the time the actions should fire. This means that if the conditions are not met, the timer event will be skipped. It will not be re-evaluated when any of the entities involved in the conditions change.

This could be replaced by a description of how the re-evaluate option works.

### Steps to reproduce

Read the doc.

**Comment by ministryofsillywalks** [comment]
Is there any documentation of exactly how re-evaluate works?
The release notes also don't contain a lot of info.

**Comment by patriiiiiiiiiick** [comment]
Hopefully, this will remove the stale label.

**Comment by ranalloatl2** [comment]
+1. The re-evaluate option does not seem to have any effect on my schedule and is not described in the documentation
