### ISSUE TITLE
Option panel is missing

### ISSUE THREAD

**Issue by drkng** [nielsfaber/scheduler-card#754]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.11

### Component Version

v3.2.15

### Bug description

Hello.
I cannot find the option panel, also adding a new scheduler or modifying an existing one
The options (name, tag, ecc) are impossible to add or modify 
When modify an existing scheduler is no longer possible to modify the type (on, off, run) or the entity
Thanks in advance

![Screenshot 2023-11-15 alle 06 55 12](https://github.com/nielsfaber/scheduler-card/assets/62808277/67f0c136-7f00-4725-aee0-6d94386b6bcd)

### Steps to reproduce

I cannot find the option panel, also adding a new scheduler or modifying an existing one
The options (name, tag, ecc) are impossible to add or modify 
When modify an existing scheduler is no longer possible to modify the type (on, off, run) or the entity

**Comment by nielsfaber** [comment]
The issue does not occur for me.
And since you did not provide any steps to reproduce it, I cannot help you.
Did you try using the card on another device?

**Comment by drkng** [comment]
Hello, thank you for answering. The issue occurs both using browser (Safari 16.5.2 ) and iOS App (2023.7)
but it doesn't happen with browser Chrome on Mac (119.0.6045.123)
Here the screenshot: on Safari and iOS  the part marked in yellow in the image is disappeared
![Screenshot 2023-11-16 alle 23 30 30](https://github.com/nielsfaber/scheduler-card/assets/62808277/1f1364e2-55f2-4aae-936f-f39d1895efcc)

**Comment by drkng** [comment]
Hello
the last update fix the problem on Safari
Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2

**Comment by drkng** [comment]
The issue is not fixed by the last update 
Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2
