### ISSUE TITLE
Feature request: Humidifier

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#76]
With the newly added humidifier integration, with the help of `generic_hygrostat`, you can control a switch based on a humidity sensor. See https://github.com/home-assistant/core/pull/36759
Any plans to add this to generic config?

**Comment by nielsfaber** [comment]
`humidifier` is now added to the standard configuration.

**Comment by nielsfaber** [comment]
Ah and it's also released in v1.5.1, so you could try it out.

**Comment by KTibow** [comment]
Not showing, others are.

**Comment by nielsfaber** [comment]
Well, you should still add `humidifier: true`

**Comment by KTibow** [comment]
Great, now there just needs to be some images.

**Comment by nielsfaber** [comment]
Actually, you can edit the `standard-configuration.json` yourself.
It is pretty straightforward.
Most work goes into finding suitable icons..

**Comment by KTibow** [comment]
Okay, PR sent. Seems resolved to me.
