### ISSUE TITLE
[FR] Duplicate action

### ISSUE THREAD

**Issue by LukaszP2** [nielsfaber/scheduler-card#760]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Add action to duplicate schedul.

### Additional info

Many times I do simillar schedulers and I must do it from beginning. This will help expecially with very expanded one.

**Comment by jj-uk** [comment]
I was just about to request this.

Use-case:
I'm setting up the scheduler for a heating system. I have several rooms to control.
Each room needs a schedule for each day of the week, as the trigger times are different for rooms; I need approx 40 schedules.

If the editor allowed editing in yaml it would be easier to copy/paste, but I guess there's other background reasons why there's no 'edit in yaml' option for this card.

**Comment by imbryk** [comment]
One more upvote for this ⬆️ 

My usecase is a little bit different - I have different rooms with same time schedule (based on my electric tariff), but temperatures should be a tad different, so in bathroom I will always keep it a bit warmer.
I would like to duplicate schedule, and just modify the temperatures in those rooms, as opposed to creating the time slots from the start

**Comment by jj-uk** [comment]
Commenting to prevent stale status.

**Comment by jasonalsing** [comment]
Would love to have this. Currently looking to modify a schedule from daily to separate schedules for weekdays and weekends, would be nice to make a quick copy and just change days and parameters real quick.

**Comment by jj-uk** [comment]
Commenting to prevent stale status.

**Comment by jj-uk** [comment]
@nielsfaber Is is possible to disable the automatic 'stale -> close issue' for feature requests?

**Comment by nielsfaber** [comment]
@jj-uk I agree this feature could be useful, but I don't have the time to work on this. So if no one else takes the initiative to implement the feature there I don't see the point of keeping it open forever, so i think stale issues are unavoidable.

**Comment by jj-uk** [comment]
> @jj-uk I agree this feature could be useful, but I don't have the time to work on this. So if no one else takes the initiative to implement the feature there I don't see the point of keeping it open forever, so i think stale issues are unavoidable.

Do you have an explanation of setting up the a dev environment? I might try to add this feature.

**Comment by jj-uk** [comment]
I still think this is a worth while addition- willing to give it a try if you can explain how to set up a dev environment on windows.

**Comment by jj-uk** [comment]
Can anyone explain for to setup a debug enviroment?

**Comment by Gandulf78** [comment]
Having myself a lot of schedules to set up, I agree it would be a very valuable feature.

**Comment by MilesTEG1** [comment]
It would be a powerful addition to be able to duplicate settings.

In the meantime this is developed, is there a way to have the yaml (or other) code for the schedules? If we can get the code, we can copy/paste it and modifying it.

**Comment by Gandulf78** [comment]
I've seen in https://github.com/nielsfaber/scheduler-component documentation there's a scheduler.copy action. I may be the may.

**Comment by MilesTEG1** [comment]
> I've seen in https://github.com/nielsfaber/scheduler-component documentation there's a scheduler.copy service. It may be the way.

Ho! But I don't see any copy button in the card...

**Comment by Gandulf78** [comment]
It is working here: 
<img width="1773" alt="Capture d’écran 2024-12-05 à 22 58 55" src="https://github.com/user-attachments/assets/7a7b5a82-7bbe-4571-ba7a-3935157b2b4c">
