### ISSUE TITLE
Setting time to sunset/sunrise in scheme is broken

### ISSUE THREAD

**Issue by smenzer** [nielsfaber/scheduler-card#762]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.12

### Component Version

v3.2.15

### Bug description

I can no longer see the option to choose sunset/sunrise when setting a scheme. Per https://github.com/nielsfaber/scheduler-card/issues/692, this was added as a feature and it used to work for me, but it doesn't anymore. The option DOES appear if I just choose the "Turn On/Off" rather than a scheme.

### Steps to reproduce

Create a new schedule, choose "scheme" and select a time slot. the option to adjust to sunrise/sunset does not appear.

**Comment by tjkcc** [comment]
I came here to request this feature, but then saw your post and went to check if I missed it somewhere. 
Found it - when setting a scheme click on the time and see if the options below appear. It doesn't work for you @smenzer ?
<img width="638" alt="image" src="https://github.com/nielsfaber/scheduler-card/assets/47875364/c7ee5246-73d7-42e8-a112-76b520349b9d">

**Comment by smenzer** [comment]
@tjkcc no i don't see the time control mode at all! 

<img width="558" alt="image" src="https://github.com/nielsfaber/scheduler-card/assets/624392/316c61d7-c16a-4647-bb4c-5dc475cec813">

i've included "sun" as an entity in the card settings, but not sure if there's something else I'm supposed to do some place to make this work?

<img width="675" alt="image" src="https://github.com/nielsfaber/scheduler-card/assets/624392/4eb2d43c-c3ca-443d-bd29-96120b60f597">

**Comment by tjkcc** [comment]
@smenzer so what happens when you press on that 8:15 or 16:00 sliders above? It should turn orange and controls should appear at the bottom.

**Comment by smenzer** [comment]
@tjkcc nothing happens. here's a loom to show what i see: https://www.loom.com/share/1bc83d3e754e4a528df2db82b1f8332b?sid=0813867e-bbf7-43df-905c-6e9c00b2827e

**Comment by tjkcc** [comment]
You are close @smenzer . You need to click on the time indicator, right on the digits.

**Comment by smenzer** [comment]
omg 🤦 

thank you! this should be documented in the readme file. maybe i'll put in a PR

**Comment by tjkcc** [comment]
I agree. Only figured it out because I saw it being mentioned here

**Comment by baruchiro** [comment]
On version 4.0.7 I can't see how to apply both sunrise and sunset, is it broken?

![Screenshot_20251016-232948.png](https://github.com/user-attachments/assets/f1fecd9a-1eae-4183-9a47-983984abc21d)

**Comment by nielsfaber** [comment]
@baruchiro the sunset or sunrise mode can only be enabled with a maximum of 3 hours offset.
If you drag the start or end time closer to the actual hour of sunrise of sunset, the mode becomes available for selecting in the dropdown menu you showed.

**Comment by baruchiro** [comment]
I made it work, but it takes me too long, so I didn't reproduce it.

I think the trick was to set the sunset first. When I started with a sunrise split, the sunset was not available.
