### ISSUE TITLE
Description / Function to re-apply the Schedule

### ISSUE THREAD

**Issue by dolezeldavid** [nielsfaber/scheduler-card#763]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I did not find an answer to my need - it would be great if a feature / better description would work as follows (not sure how to describe it):
- I have a schedule running, for instance, a temperature on a thermostat
- I change with some another action the temperature - for instance, automatization "arrived home"
- with leaving home I want the temperature to return back to the scheduled temperature, not keeping this from "arrived home"

### Additional info

Not sure - a service, a function,...

**Comment by claysam75** [comment]
Looking for a way to do exactly this. Would be happy to test any possible implementations

**Comment by dolezeldavid** [comment]
resolution: found out that the scheduler works as a switch - so it is possible to turn it off as a switch, do whatever you want, and when turned on the schedule returns back to the scheduled plan

**Comment by dolezeldavid** [comment]
resolution: found out that the scheduler works as a switch - so it is possible to turn it off as a switch, do whatever you want, and when turned on the schedule returns back to the scheduled plan
