### ISSUE TITLE
[FR] Add multiple schemes for other days

### ISSUE THREAD

**Issue by mutasim** [nielsfaber/scheduler-card#764]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be great to be able to set different schemes on the same schedule. So certain days follow one scheme and other days have a different scheme. 

### Additional info

This should be configurable in the time tab of a schedule. 

The previously selected days should be non selectable in the additional scheme.

**Comment by jj-uk** [comment]
https://github.com/nielsfaber/scheduler-card/issues/760 may be related to this?

**Comment by Ga-Re** [comment]
"I would also appreciate that. This way, I wouldn't have to create a new plan for the same action on different days."

**Comment by rsporsche** [comment]
I would also like this feature.
I have one schedule for weekdays and another for the weekend. 
It would be convenient to be able to see and edit the schedule for a single device in one place.

**Comment by eviatarLevi** [comment]
I would be willing to pay the labor time of the guy who created such an option

**Comment by nielsfaber** [comment]
Thanks all for expressing your enthusiasm for this project!
This feature has been requested many times, and frankly I agree it currently works a bit impractical.
However, adding such function is not as easy as copy-pasting the time bar, it requires changes on many parts including the scheduler-component side.

Over the past weeks I have been working on a completely new version of scheduler-card.
The version is supposed to address many of the quirks/limitations including this FR.
I ask you all for your patience. I expect i will need around two months before I have something that could replace the current card.
Anyone who is willing to participate in beta-testing (and accepts the possibility of losing their existing configured schedules), can respond below, this may come in handy later.

@eviatarLevi 
This is a very nice gesture, but I don't think you can afford that (no offense) given my hour-rate at my job and the amount of time that probably goes into the change.
But donations are always appreciated and a good motivation to keep spending free time on this (and sending my GF for a spa-day so I can spend some time on this). There's a paypal link in the readme page. I humbly thank you in advance.


I will try to post an update here when I have some sneak preview material.

**Comment by eviatarLevi** [comment]
:)
I'm happy to try the beta version of the new card
Regardless I promise to give a small donation

**Comment by jarthod** [comment]
@nielsfaber happy to help testing the beta version too :)

**Comment by Ga-Re** [comment]
@nielsfaber 
If I can help with testing the beta, I would be happy.

**Comment by mutasim** [comment]
@nielsfaber hey is this possible with V4.x? Just making sure I'm not missing it if it's already there!
