### ISSUE TITLE
Hide hidden entities

### ISSUE THREAD

**Issue by dankarization** [nielsfaber/scheduler-card#765]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Option to exclude all entities hidden in home assistant will greatly benefit setting up this card, because now you need to do it twice

Good example of doubled entities, both of which now goes into this card- `change switch type`, entities added to groups that should not be controlled 1by1 or a lot of other entities a user is not ment to see.
![image](https://github.com/nielsfaber/scheduler-card/assets/26330178/b55416de-89b0-499f-a679-52ac9877b936)

### Additional info

For example
exclude:
            - hidden_by: "*"

**Comment by dankarization** [comment]
I'm still interested

**Comment by nielsfaber** [comment]
I looked into this, but I don't really understand how hidden entities work in HA.
If I make an entity hidden like this:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/8457d413-0adb-41a6-868f-c0cfa76f79b0)

It still shows up in the lists of entities like any other:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/6f8f7bd2-140b-46d7-bcd2-76458e699b81)

There is also not any property assigned that can be used to check the hidden status, so I wouldn't know how to filter them out in the scheduler-card.

**Comment by nielsfaber** [comment]
I don't know how to implement this request. And since other cards don't hide such entities either, i don't see it that important either.
