### ISSUE TITLE
Add field to specify start and stop time of Scheme Events

### ISSUE THREAD

**Issue by bigFin** [nielsfaber/scheduler-card#774]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

A textbox should exist on the New Schedule page to specify start and stop time of Scheme Events with full precision

### Additional info

Scheme event times are currently set by dragging the edge of a time-slot boundary in the New schedule window, or by editing /PATH_TO_YOUR_CONFIG/.storage/scheduler.storage

Add a form box to specify the time of an event to the minute.

**Comment by nielsfaber** [comment]
This function is planned for the next version.
It may take ~2 months before this is ready.

**Comment by lordlightman** [comment]
Hello @bigFin, when I'm making changes in _scheduler.storage_ file they are not applied in Scheduler cards. Are any additional steps required for the card to load new schedules from storage?

**Comment by bigFin** [comment]
@lordlightman iirc changes to scheduler.storage executed if the scheduler card was NOT opened after editing the file. Perhaps the card has some validation that updates this file?
