### ISSUE TITLE
Template Support for Config Options

### ISSUE THREAD

**Issue by ahmadtawakol** [nielsfaber/scheduler-card#776]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Can we get template support for config options? More info below:

### Additional info

For example, I would like to use a template in the `include` option to include all entities in a certain area. Like this:

`include: {{ area_entities("Bedroom") }}`

This way, any new entity that is added will automatically get added to the scheduler card that I have set up for that room as well. This would also be useful for `exclude`, `groups`, `title`, and `customize`.

**Comment by EnriqueBesuman** [comment]
I agree...
