### ISSUE TITLE
Multiple Or based Conditions

### ISSUE THREAD

**Issue by danielBreitlauch** [nielsfaber/scheduler-card#777]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Atm all conditions are AND based. The scheduler executes the action if all conditions are met.
I would like to execute the action if one of the conditions is met.

One use case would be having the workday sensor and the school holiday sensor as conditions and as action heating the flat in the morning depending of one of these is active.

Build in HA automations allow this by setting: 'condition: or'.
There are workarounds to get it done with more and more helper entities but it would be helpful to be able to directly configure it in the scheduler.

### Additional info

Option near the condition list to execute if all conditions are met or just one. Default should be: all. This way it is backwards compatible.

**Comment by nielsfaber** [comment]
This is already implemented.
There is a toggle switch in the card which lets you choose between all / any (which you can interpret as AND / OR) condition logic.

**Comment by danielBreitlauch** [comment]
Sorry I missed it since I only had one Condition in there.
