### ISSUE TITLE
More advanced conditions

### ISSUE THREAD

**Issue by TechyGuy17** [nielsfaber/scheduler-card#780]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Ive been looking for a way to set a condition depending on command, so for example: "if condition is x allow command "turn on" "
The usecase would be for automations like turning on lights depending on light level, so that if the lux value is greater than x its allowed to turn off, but if the value is lower then x it can turn on. Currently you can only set conditions depening on one if statement which limits this usecase

### Additional info

See proposal

**Comment by Strauman** [comment]
It's already implemented I believe
![Uploading Screenshot_20240104_100051_Home Assistant.jpg…]()

**Comment by Strauman** [comment]
Is this what you're looking for? 😁
![Screenshot_20240104_100051_Home Assistant](https://github.com/nielsfaber/scheduler-card/assets/1666236/c4825771-780b-44ed-989a-0e027267903e)

**Comment by AlessandroTischer** [comment]
I was looking for this exact feature! Hope it will be added someday...
