### ISSUE TITLE
Choose to not have 'add' or edit

### ISSUE THREAD

**Issue by Strauman** [nielsfaber/scheduler-card#781]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hi 👋 What an amazing card!
Is it possible to have an option in the card edit that removes the "add" at the bottom? (Or is it too much work?). 

It'd be cool to have similar options whether it can be enabled/disabled or whether it should show on/off button.

Thank you so much

### Additional info

When adding a card to the view, or editing existing lovelace scheduler card, the following options could show:
- Allow adding schedules
- Allow toggle schedules
- Allow editing existing schedules

**Comment by nielsfaber** [comment]
The options you are requesting already exists:
https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#configuration
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/7101bada-477f-4582-81bb-431e5e73e89a)
