### ISSUE TITLE
FIBARO Valve

### ISSUE THREAD

**Issue by mjasinsk** [nielsfaber/scheduler-card#782]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.12

### Component Version

 3.2.15

### Bug description

Hi Everyone. My problem today is related to Scheduler Card. It works quite very well with my Blinds and Fibaro thermostats (valves) integrated by MQTT with original HC3 central station . Recently I decided to start move my zwave devices to Z-Wave JS. I started from my room in order to observe if something strange or specific will happen, before I move my whole instalation from Fibaro HC3 to Z-Wave JS. All devices within my room works very well including Fibaro valve (with external temperature sensor). I can change values, I can change mode, i can use valve without any problem. The one and only one but serious issue for me is that valve stop working with my Scheduler card. It means that all other valves which are managed by MQTT and HC3 reacts  on schedule but not this one (previously inegrated by MQTT worked fine) . Of course i removed  valve from HC3, inegrated after full factory reset int Z-Wave JS and once again added new  values to scheduler card. I changed everything in terms of settings. I don’t know how to code so i didn’t look into editor because for sure i won’t find anything. To sumHi Everyone. My problem today is related to Scheduler Card. It works quite very well with my Blinds and Fibaro thermostats (valves) integrated by MQTT with original HC3 central station . Recently I decided to start move my zwave devices to Z-Wave JS. I started from my room in order to observe if something strange or specific will happen, before I move my whole instalation from Fibaro HC3 to Z-Wave JS. All devices within my room works very well including Fibaro valve (with external temperature sensor). I can change values, I can change mode, i can use valve without any problem. The one and only one but serious issue for me is that valve stop working with my Scheduler card. It means that all other valves which are managed by MQTT and HC3 reacts  on schedule but not this one (previously inegrated by MQTT worked fine) . Of course i removed  valve from HC3, inegrated after full factory reset int Z-Wave JS and once again added new  values to scheduler card. I changed everything in terms of settings. I don’t know how to code so i didn’t look into editor because for sure i won’t find anything. To summarize valve works manually, it is fully operational or remotely by any thermostat card but doesn’t change values in scheduler card in selected time and also doesn't react on additional tasks within scheduler card as is window opening. This last option works for this valve for example using blueprint, so it means that after migration more or less valve works fine.  It is related only to this valve .Other operate on schedule but until today i still cannot understand that they shows future settings (next settings) not actual one in thermostat card. marize valve works manually, it is fully operational or remotely by any thermostat card but doesn’t change values in scheduler card in selected time and also doesn't react on additional tasks within scheduler card as is window opening. This last option works for this valve for example using blueprint, so it means that after migration more or less valve works fine.  It is related only to this valve .Other operate on schedule but until today i still cannot understand that they shows future settings (next settings) not actual one in thermostat card. 

### Steps to reproduce

 i removed  valve from HC3, inegrated after full factory reset int Z-Wave JS and once again added new  values to scheduler card. I changed everything in terms of settings

**Comment by nielsfaber** [comment]
I'm sorry but your long story was a bit confusing to read for me.
Next time please keep it short and to the point.

If I understand correctly you have a climate entity that doesn't work fine with scheduler.
If you create a new schedule, does it show up in the card and all actions are as you would expect?
If yes, the issue is related with the entity not responding to the scheduled actions?
Maybe a screenshot would help. 
You can also share information from the history page to show that the device did not change when the scheduled action was triggered.
