### ISSUE TITLE
Make it possible to define 2 schedules into 1 schedule-entity for easier support of scene-entities

### ISSUE THREAD

**Issue by loovanloon** [nielsfaber/scheduler-card#784]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I use the Schedule integration for presence simulation with the help of scenes. By design scenes can only be switched ON. So in the scheduler, a scene will be switched ON during the time-period of the schedule. When this time-period is over / has passed the scene remains switched ON. This is not my intention.

If I want to "switch the scene off" I have to switch a different (counter-part) scene ON. I can do that by creating a second schedule (- entity ).  But these two "coupled" schedules will be two different "schedule-entities" with each their own states.

It would be nice if these two states/scenes would be in one schedule-entity with each their own attributes and as overall state of this entity the value (scene) of the schedule-attribute that is active (ON) at a particular period in time. Or in other words: that the second scene would be automatically mirrored on the first scheme.

![image](https://github.com/nielsfaber/scheduler-card/assets/25280600/3e7928e9-9f49-4f0d-8ba9-cc8304da39cb)

### Additional info

I know there several ways to achieve the result by other means (schedule groups, schedule more than 1 entity in 1 schedule) but using scenes adds a lot of functionality and possibilities to finetune the result and better maintenance by splitting outcome (scene) and schedule.

**Comment by gacopl** [comment]
Would love to be able to schedule scene run, currently i have to add automations to activate scene, and only then i can add schedule

When i click add schedule i dont have scene group at all

**Comment by loovanloon** [comment]
Remove stale label
