### ISSUE TITLE
FR: enable entities per schedule, to avoid confusion showing schedules in new cards

### ISSUE THREAD

**Issue by erkr** [nielsfaber/scheduler-card#786]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V3.2.12

### Bug description

I removed all tags for a scheduler card. Even after a refresh of the browser, the previous tag filter remains active. This is what I get when I open the code editor on the card:
![image](https://github.com/nielsfaber/scheduler-card/assets/4363599/3f55d81d-ac72-4aba-b86c-622574018587)
Marked with green, although no tags, part of the schedules are hidden

### Steps to reproduce

Remove tags from the card options

**Comment by erkr** [comment]
Update:
I found out this happens the schedules that remain hidden use entities that are not enabled in the new card. This is quite confusing when creating a card as it is not easy to remember all entities used by the existing schedules.

**Comment by erkr** [comment]
@nielsfaber 
It would be nice if you have time to look to this issue. It's confusing. 
I thought a little longer about this and I think that entity selection in the card is not really logic. I think it should be per schedule. But I can imaging technically that it's not easy.

**Comment by erkr** [comment]
It would be nice to hear of this is something to fix

**Comment by nielsfaber** [comment]
I did not respond to this issue since it seems there is no bug reported here, instead you expected the behaviour to be different than how it is implemented.

What you are experiencing seems to have nothing to do with tags.
If you don’t like the ‘X excluded items’ you have two options:
* set `discover_existing` to false to hide the text
* add the entities used by the discovered schedules to your `include` list

**Comment by erkr** [comment]
Hi Niels, 

You are right. Initially I thought it was a bug, later I found out this happened due entities where are not enabled in the new card.

So it is a confusing mechanism to enable entities per card. I will make it a FR to select entities per schedule.

Best Eric

**Comment by erkr** [comment]
Still valid, but Niels, feel free to close it if you won't pick it up. No hard feelings, it's probably a huge chance
