### ISSUE TITLE
Can't load Scheduler Card.

### ISSUE THREAD

**Issue by theze0es** [nielsfaber/scheduler-card#787]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.12

### Component Version

v.3.2.15

### Bug description

Can't load Scheduler Card.
Also impossible to remove

### Steps to reproduce

Using a HA core in a docker container.
Install HACS
Install scheduler-component and activate the integration 
Install scheduler-card and register the resource. Clean Cache.
RESULT: The card is not loaded. It is not possible to force reload 

![image](https://github.com/nielsfaber/scheduler-card/assets/49099947/dab04bdd-28f4-4410-a412-f67723af5146)

**Comment by standard-adam** [comment]
Is it this one? I think I'm up against it, too. I get this error, repeating very rapidly.

```
scheduler-card.js?hacstag=286270157:1826 Uncaught TypeError: Cannot read properties of undefined (reading 'every')
    at _o (scheduler-card.js?hacstag=286270157:1826:597)
    at scheduler-card.js?hacstag=286270157:1826:4066
    at Array.filter (<anonymous>)
    at scheduler-card.js?hacstag=286270157:1826:4056
```

**Comment by jimlocigno** [comment]
I have this same issue.
