### ISSUE TITLE
can not remove a schedule

### ISSUE THREAD

**Issue by niouniou49** [nielsfaber/scheduler-card#788]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V3.3.0

### Bug description

Hello here
i m just unable to delete a schedule; Is there a way to do it manually?
can i find the list of schedule in a yaml file? if yes where? can i edit the file and remove the schedule manually?

### Steps to reproduce

just create a schedule and then i see it in the configuration list, but i can not remove it
<img width="408" alt="Screenshot 2024-01-25 at 19 14 19" src="https://github.com/nielsfaber/scheduler-card/assets/72173152/5b87a54c-d50a-45ef-9aae-653cc9705754">

**Comment by nielsfaber** [comment]
You can use the scheduler.remove service

**Comment by niouniou49** [comment]
cool, but how to do that?
