### ISSUE TITLE
Option to hide the "Excluded items" line

### ISSUE THREAD

**Issue by derandiunddasbo** [nielsfaber/scheduler-card#791]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Please add an option to hide the "+xx excluded items" line on the bottom of the scheduler list.

### Additional info

It should be possible to hide this item for saving space on the card.

**Comment by nielsfaber** [comment]
This is controlled with the discover_existing setting in yaml, or this GUI setting
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/207c4493-b750-4396-8cbd-a42d719584a5)

**Comment by derandiunddasbo** [comment]
Oh, ok. Sorry. I was sure, I tried this setting and still saw the excluded items line before opening this ticket, but now it's obviously working as expected. Maybe this was a cache issue on my side.
