### ISSUE TITLE
Support (not only the Sun integration but also) the  DECONZ-daylight sensor integration

### ISSUE THREAD

**Issue by loovanloon** [nielsfaber/scheduler-card#792]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Please support the [DECONZ-**daylight sensor** integration](https://www.home-assistant.io/integrations/deconz/#sensor) to set up a scheme. The DECONZ-times integration features more time periods during an 24-hrs day-cycle, that will help to configure specific dayime periods that depend on the time of the year.

[DECONZ-**daylight sensor**](https://www.home-assistant.io/integrations/deconz/#sensor) supports the following states: nadir, night_end, nautical_dawn, dawn, sunrise_start, sunrise_end, golden_hour_1, solar_noon, golden_hour_2, sunset_start, sunset_end, dusk, nautical_dusk, night_start.

For example I want to turn ON my garden lights _during **Sunrise_start** until **Sunrise_end** in the morning_ and from _**sunset_start** until **night_start**_.

With the current sun-integration I need to use some fixed extra (+ or - ) to get close to this (as it differs during the time of the year). 

But with the states of the DECONZ-daylight sensor, it is exactly how I want it, representing the complete correct daylight periode.

PRO's:
- it is more acurate
- it simplifies setting up a scheme that will work during the entire year

CON:
- some people find the DECONZ-daylight sensor more complex to understand in the beginning
 

### Additional info

The sensor also has an attribute called “daylight” that has the value true when the sensor’s state is golden_hour_1, solar_noon, or golden_hour_2, and false otherwise. This comes close to the SUN-integration.

These states can be used in automations as a trigger (e.g., trigger when a certain phase of daylight starts or ends) or condition (e.g., trigger only if in a certain phase of daylight).

Please note that the deCONZ daylight sensor is disabled by default in Home Assistant. It can be enabled manually by going to your deCONZ controller device in the Home Assistant UI.

**Comment by nielsfaber** [comment]
Scheduler uses the `next_rising` and `next_setting` attributes of the sun entity in HA to calculate next trigger moment.
I don't know about the Deconz sensor, but it should at least expose something similar to make it possible to use it instead.

**Comment by loovanloon** [comment]
Nb: The DeCONZ integration offers more than only the Daylight Sensor. But it is the Daylight-sensor part of DeConz that is useful. 

**deCONZ Daylight Sensor**

The deCONZ Daylight sensor is a special sensor built into the deCONZ software since version 2.05.12. It is represented in Home Assistant as a sensor called sensor.daylight. **The sensor’s state value is a string corresponding to the phase of daylight** (taken from https://github.com/mourner/suncalc, on which the deCONZ implementation is based)

It offers the following **states** (that will always be in that particular order unless doom-day has began):

States: nadir, night_end, nautical_dawn, dawn, sunrise_start, sunrise_end, golden_hour_1, solar_noon, golden_hour_2, sunset_start, sunset_end, dusk, nautical_dusk, night_start

Furthermore the sensor offers the following attributes: 
daylight: false
**next_change: 2024-01-31T18:41:43+01:00**
device_class: enum
icon: mdi:weather-sunset-down
friendly_name: Deconz Daylight

**Comment by nielsfaber** [comment]
Unfortunately `next_change` will not provide sufficient information for scheduler.
Scheduler will need to know at any point in time when is the next upcoming sunset and the next upcoming sunrise.
The information needs to be known upfront, since the timer for a next task is programmed upfront (e.g. a schedule triggering at sunset will be reset in the minute afterwards to trigger at the next sunset).
With the Deconz entity it seems that scheduler will become unable to plan a task for the next sunset, until all other phases have past and the sunset is already nearby.
If the Deconz sensor would be split into multiple entities per phase, or it would provide additional attributes with timestamp per phase, this would work. In the current state I don't see it possible to implement support for this.

**Comment by loovanloon** [comment]
I (think I) understand. Thank you for your efforts. Ticket closed?
