### ISSUE TITLE
Cannot disarm alarm?

### ISSUE THREAD

**Issue by deanfourie1** [nielsfaber/scheduler-card#798]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.12

### Component Version

3.3.0

### Bug description

When choosing the option to disarm alarm based on a schedule it fails with error wrong code provided.

### Steps to reproduce

Setup a schedule to disarm alarm area.

### Additional info

When attempting to disarm an alarm area, it fails with error wrong code provided. However arming works without any issues.

**Comment by nielsfaber** [comment]
It seems your alarm requires a code for disarming.
Scheduler does not know this code, so it only performs a disarming action without any code.
You could add a custom action to the card with a code as extra service_data parameter, see https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#customize.
