### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#80]
Once all PRs are closed, it might be a good idea to rename the default branch to main.

**Comment by nielsfaber** [comment]
Why

**Comment by KTibow** [comment]
https://www.zdnet.com/google-amp/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by nielsfaber** [comment]
🤣 🤣 🤣 🤣
Seriously?

**Comment by KTibow** [comment]
You can Google it... It's unneeded, and I haven't done it on all of my repos, but for my new repos that's my default branch name.

**Comment by nielsfaber** [comment]
Done
