### ISSUE TITLE
"Add item" button missing. 

### ISSUE THREAD

**Issue by Stooovie** [nielsfaber/scheduler-card#810]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.12

### Component Version

3.3.3

### Bug description

The "Add item" button is missing. 

![IMG_8850](https://github.com/nielsfaber/scheduler-card/assets/10572373/76bbf5a4-cb2c-4159-a522-1e33f574ad13)

### Steps to reproduce

Have Scheduler card visible. No Add Item.

**Comment by patienttruth** [comment]
Just stopped by to say the same thing.

It's there for clicking, but you can't see it.

I do have card mod and a couple front end mods active, but they're not being referenced by these cards or dashboard

**Comment by Inglan** [comment]
Apparently they fixed it in dc2ef5feef7b6831a8e8cc5258ba3e7c1d368777 but I am still experiencing it

**Comment by patienttruth** [comment]
This looks fixed to me after the update. Thank you for this awesome card @nielsfaber!!

**Comment by moshiko2312** [comment]
hi me to hide  add button, running  on HA 2024.4.3
![WhatsApp Image 2024-04-20 at 08 55 18](https://github.com/nielsfaber/scheduler-card/assets/48163773/b0170ce1-74d2-42fe-896e-4c19804852f8)
