### ISSUE TITLE
scheduler-card - Continiously repeating 'Uncaught error from Chrome 123.0.0.0 on Windows 10'

### ISSUE THREAD

**Issue by LoznOz** [nielsfaber/scheduler-card#812]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V3.2.13

### Bug description

I see in Home assistant Log Viewer a continuously repeating (approximately every minute)  Error logged as follows:
"2024-04-11 11:10:11.129 ERROR (MainThread) [frontend.js.latest.202404041] Uncaught error from Chrome 123.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'every')
bo (/hacsfiles/scheduler-card/scheduler-card.js:1827:597)
/hacsfiles/scheduler-card/scheduler-card.js:1827:4066
/hacsfiles/scheduler-card/scheduler-card.js:1827:4056"

the above is repeated over and over the only difference between each being the date & time updates of course.

### Steps to reproduce

simply look at the logs - this appears to me to be endlessly repeating. It's not apparent to me to the cause or what I could do to rectify this apparent repeating error?

### Additional info

From Logs:
Logger: frontend.js.latest.202404041
Source: components/system_log/__init__.py:320
First occurred: April 10, 2024 at 7:59:33 PM (72900 occurrences)
Last logged: 11:20:03 AM

Uncaught error from WebKit 605.1.15 on Mac OS 10.15.7 TypeError: undefined is not an object (evaluating 'e.timeslots.every') bo (/hacsfiles/scheduler-card/scheduler-card.js:1827:596) filter ([native code]::) /hacsfiles/scheduler-card/scheduler-card.js:1827:4062
Uncaught error from Chrome 123.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'every') bo (/hacsfiles/scheduler-card/scheduler-card.js:1827:597) /hacsfiles/scheduler-card/scheduler-card.js:1827:4066 /hacsfiles/scheduler-card/scheduler-card.js:1827:4056

**Comment by shlomki** [comment]
Same error message as in #809 , probably due to the same bug
