### ISSUE TITLE
Allow non modulo 5 minutes time (like 06:28)

### ISSUE THREAD

**Issue by dimagoltsman** [nielsfaber/scheduler-card#814]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Allow non modulo 5 minutes time (like 06:28) 

### Additional info

Sometimes its very important

**Comment by tjandras** [comment]
I think what you want can be configured on the scheduler card. You need to go to the Other tab, and adjust the time step slider. See attached picture.
![image](https://github.com/nielsfaber/scheduler-card/assets/5464525/734d3abf-30ed-41d7-9cb5-c0450ff5d19b)

**Comment by dimagoltsman** [comment]
never knew its there, THANX!
