### ISSUE TITLE
Use any datetime object instead of just "sun"

### ISSUE THREAD

**Issue by mikeage** [nielsfaber/scheduler-card#815]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Support for the sun integration is excellent, but I have some other times that are either set explicitly based on conditionals or rather complicated derivations of sun times, and it would be excellent if I could use those for setting times. Is there any chance this might be possible?

### Additional info

.

**Comment by mikeage** [comment]
This would still be useful

**Comment by mikeage** [comment]
maybe there's still a chance?

**Comment by L1ttl3b4k3r** [comment]
Interested too

**Comment by mikeage** [comment]
still interested, fwiw

**Comment by L1ttl3b4k3r** [comment]
me too :)

**Comment by mikeage** [comment]
/freshen (I know that's not a real command)

**Comment by mikeage** [comment]
still interested, but kinda losing hope :-)

**Comment by L1ttl3b4k3r** [comment]
Still full of hope...
