### ISSUE TITLE
Add option to hide/show toggles

### ISSUE THREAD

**Issue by roldengarm** [nielsfaber/scheduler-card#816]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It can be helpful for a tablet dashboard, have an option to hide the toggles that enable/disable a schedule.

### Additional info

It was also proposed in this issue: https://github.com/nielsfaber/scheduler-card/issues/526

**Comment by nielsfaber** [comment]
This is already in place for years.

**Comment by nielsfaber** [comment]
Sorry, I misunderstood the request.
What's in place now is `show_header_toggle` which hides/shows a toggle switch to control all schedules in the card **simultaneously**.
There is no option in place to hide the toggles for individual schedules.
I also don't see the need for this. Schedules are switch entities so they are supposed to have toggles in the dashboard. This is the same for any other switch entity within the entities card.
