### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used

### ISSUE THREAD

**Issue by ridderr** [nielsfaber/scheduler-card#824]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V3.2.13

### Component Version

V3.3.4

### Bug description

I do get some errors in the logfile. I'm not aware I had these errors with the previous release of the Scheduler Component.

### Steps to reproduce

No steps known. They just appears (at least for me)

### Additional info

Logger: frontend.js.latest.202407030
Source: components/system_log/__init__.py:333
First occurred: 07:29:45 (3 occurrences)
Last logged: 09:12:25

Uncaught error from Chrome 126.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/scheduler-card/scheduler-card.js:43:68 /hacsfiles/scheduler-card/scheduler-card.js:43:83 t (/hacsfiles/scheduler-card/scheduler-card.js:15:334) /hacsfiles/scheduler-card/scheduler-card.js:275:847 /hacsfiles/scheduler-card/scheduler-card.js:1998:295
Uncaught error from Chrome 126.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading '_leaflet_pos') _leaflet_pos (src/dom/DomUtil.js:247:11) getPosition (src/map/Map.js:1488:9) _getMapPanePos (src/map/Map.js:1505:66) _getNewPixelOrigin (src/map/Map.js:1224:27) _move (src/map/Map.js:1726:7)

**Comment by ridderr** [comment]
Still an issue at my side. Any ideas how to solve?

**Comment by raspB975** [comment]
I have the same error in the logs

**Comment by apocaliss92** [comment]
Hi, there is a similar issue for the component `settings-row`, would it be possible to use specific names for this component? this is breaking already 2-3 components

**Comment by ridderr** [comment]
I don't know why we do to get any response but this issue is still actual. Please do not close

**Comment by nielsfaber** [comment]
In case the issue is caused by conflicts between alarmo and scheduler-card, this should be resolved by updating alarmo to v1.10.5.
For conflicts with other (custom) integrations (of which I am not aware), the fix could be made either in this card or in the other integration. Note that scheduler-card v3 will not get anymore updates. I advise to switch to scheduler-card v4 (which is currently in beta), future improvements will only be made here.
Please let me know if problems are still existing and which integration(s) cause this.

**Comment by apocaliss92** [comment]
Thanks the conflict with alarmo is now gone and both beta version of scheduler and alarmo work again! I believe there is another conflict with the Button-Card extension but I need to investigste on what is causing it. If it's related to this I'll open another issue.
 Thank you again

**Comment by ridderr** [comment]
Hi @nielsfaber , I'm now on version 4.0.0.b1 but still these error's

`Uncaught error from Chrome WebView 129.0.6668.71 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/scheduler-card/scheduler-card.js:43:68 /hacsfiles/scheduler-card/scheduler-card.js:43:83 t (/hacsfiles/scheduler-card/scheduler-card.js:15:334) /hacsfiles/scheduler-card/scheduler-card.js:275:847 /hacsfiles/scheduler-card/scheduler-card.js:1998:295
Uncaught error from Chrome WebView 129.0.6668.70 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/scheduler-card/scheduler-card.js:43:68 /hacsfiles/scheduler-card/scheduler-card.js:43:83 t (/hacsfiles/scheduler-card/scheduler-card.js:15:334) /hacsfiles/scheduler-card/scheduler-card.js:275:847 /hacsfiles/scheduler-card/scheduler-card.js:1998:295
Uncaught error from Chrome WebView 129.0.6668.71 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /local/scheduler-card/scheduler-card.js:43:68 /local/scheduler-card/scheduler-card.js:43:83 t (/local/scheduler-card/scheduler-card.js:15:334) /local/scheduler-card/scheduler-card.js:275:847 /local/scheduler-card/scheduler-card.js:1972:295
Uncaught error from Chrome 129.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /local/scheduler-card/scheduler-card.js:43:68 /local/scheduler-card/scheduler-card.js:43:83 t (/local/scheduler-card/scheduler-card.js:15:334) /local/scheduler-card/scheduler-card.js:275:847 /local/scheduler-card/scheduler-card.js:1972:295
Uncaught error from Chrome WebView 129.0.6668.81 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/scheduler-card/scheduler-card.js:43:68 /hacsfiles/scheduler-card/scheduler-card.js:43:83 t (/hacsfiles/scheduler-card/scheduler-card.js:15:334) /hacsfiles/scheduler-card/scheduler-card.js:275:847 /hacsfiles/scheduler-card/scheduler-card.js:1998:295`

**Comment by ridderr** [comment]
I have removed the custom button-card HACS component which is/will not be maintained since 2023. Error has gone :-)
