### ISSUE TITLE
Cannot change Name

### ISSUE THREAD

**Issue by pvklink** [nielsfaber/scheduler-card#827]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.0.b0

### Component Version

v4.0.0.b0

### Bug description

I cant change name. When i type a character its deleted directly

### Steps to reproduce

After installing scheduler card from 3.2.13 to this release i try to change the name of an existing schedule.
It is also strange that some off the schedules need a logical name when there ws one before the update

**Comment by nielsfaber** [comment]
Thanks for your feedback!

> I cant change name. When i type a character its deleted directly

Could you update the card to v4.0.0.b1? This version contains quite some fixes that may already resolve your issue.
With this version I cannot reproduce your issue, editing a name works as expected.

This is what I am seeing:
https://github.com/user-attachments/assets/574932b7-8737-41a9-9618-5059022c74b1

> It is also strange that some off the schedules need a logical name when there ws one before the update

Could you share an example? I don't fully understand what your mean.

**Comment by pvklink** [comment]
> Thanks for your feedback!
> 
> > I cant change name. When i type a character its deleted directly
> 
> Could you update the card to v4.0.0.b1? This version contains quite some fixes that may already resolve your issue. With this version I cannot reproduce your issue, editing a name works as expected.
> 
> This is what I am seeing: https://github.com/user-attachments/assets/574932b7-8737-41a9-9618-5059022c74b1
> 
> > It is also strange that some off the schedules need a logical name when there ws one before the update
> 
> Could you share an example? I don't fully understand what your mean.

My hacs dont offer an update to v4.0.0.b1, is there a way to force that? My schedule cards shows v4.0.0.b0

i have a raspberry pi 4, and use hass in a  docker with the latest hass beta image from 6 aug
i use HACS to install your card

**Comment by nielsfaber** [comment]
Apparently the more recent version v4.0.0.b1 is interpreted by HACS as an older revision than v4.0.0.b0.
To download it from HACS, you need to click Frontend and then click on the Scheduler card. In the top-right you have a 3 dots button with option 'Redownload' which gives you the freedom to install any version. Here the v4.0.0.b1 should be listed. 

I would appreciate it if you could thoroughly test this version for your usage and give me feedback about all aspects that require improvement. I have been using it for a couple of weeks now without any issues, but I'm sure there are some issues still, this is why it's still in beta.
Note that you can always roll back to the v3.2.13 using the same method described above in case of issues.

**Comment by pvklink** [comment]
> Apparently the more recent version v4.0.0.b1 is interpreted by HACS as an older revision than v4.0.0.b0. To download it from HACS, you need to click Frontend and then click on the Scheduler card. In the top-right you have a 3 dots button with option 'Redownload' which gives you the freedom to install any version. Here the v4.0.0.b1 should be listed.
> 
> I would appreciate it if you could thoroughly test this version for your usage and give me feedback about all aspects that require improvement. I have been using it for a couple of weeks now without any issues, but I'm sure there are some issues still, this is why it's still in beta. Note that you can always roll back to the v3.2.13 using the same method described above in case of issues.

Thanks, it worked, i have the latest beta now.
And yes, i will test your version and react.
Very happy with this schedule software!

**Comment by pvklink** [comment]
Hi, i tested the latest release v4.00b1 today and everything works again!
The Gui problems are gone, Gui b1 looks like the old one in version 3, or something has go wrong with the update?
HASS frontend says b1....

Only thing i can suggest is the usage of the tags. It looks easier to understand when the default labels of HASS are used.
These labels can also be added to entities like switch.<scheduler> and should be the same as when adding or updating a tag to the device in the scheduler card!

Very happy that it all works again for me!
