### ISSUE TITLE
One or more actions are missing a required setting

### ISSUE THREAD

**Issue by redlegoman** [nielsfaber/scheduler-card#828]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.0.b0

### Bug description

If I try to add a new schedule I just get the error "One or more actions are missing a required setting".
OI had existing schedules, but could not add another. I  have even deleted **all** my other schedules and now I cannot add another.
![image](https://github.com/user-attachments/assets/15325986-4dd8-444b-ad1c-41fe33855008)

![image](https://github.com/user-attachments/assets/814f9c35-7b22-4e57-9955-c5a208533853)

![image](https://github.com/user-attachments/assets/b20f7aae-3d74-4038-be8a-c3fa3c47b07f)

### Steps to reproduce

Click "add", configure schedule, click "save"

**Comment by nielsfaber** [comment]
Please update to the v4.0.0.b1 release. It contains multiple fixes of the b0 version.
Somehow it does not show up as newer release in HACS but you can manually select which version to install.

**Comment by redlegoman** [comment]
> Please update to the v4.0.0.b1 release. It contains multiple fixes of the b0 version. Somehow it does not show up as newer release in HACS but you can manually select which version to install.

Thanks, that seems to have fixed it. As you say it doesn't show up as an update in HACS or the updates section. 

For anyone else, you need to go to HACS in the HA menu, then filter by "scheduler card"

![image](https://github.com/user-attachments/assets/1711eb76-1b5d-4e5f-a114-f4f43d9d291b)

click the three dots and choose "Redownload"

When you get there, you need to click "Need a different version?"
![image](https://github.com/user-attachments/assets/9b613683-d804-459a-a017-cf58aa1d60bc)

and then choose the version from the drop-down (drop-up?)
![image](https://github.com/user-attachments/assets/9e742d86-3a60-4398-a6ae-47d520c87e10)
