### ISSUE TITLE
Cannot remove Defective Schedule Entities

### ISSUE THREAD

**Issue by Stephonomon** [nielsfaber/scheduler-card#829]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.13

### Component Version

HACS

### Bug description

Not able to edit/remove defective entities from card.

<img width="541" alt="image" src="https://github.com/user-attachments/assets/6ceca279-2140-4ce1-9b3e-bc35d60129f7">

### Steps to reproduce

I open the card and they show at the bottom. Any attempt I try to get to the YAML fails.

**Comment by eric10k93** [comment]
I recently swapped out my thermostat and it has a different entity name.  This leaves a bunch of broken schedules that I cannot delete... I had to manually go into the storage file to remove them.  I was hoping to reuse the same schedules and just update the entity name, but I can't do that from the UI.  It would be great to allow the option of either deleting or reconfiguring the existing schedules to use new entities.
