### ISSUE TITLE
Card/component won't let me change temp.

### ISSUE THREAD

**Issue by fabianbonte** [nielsfaber/scheduler-card#834]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.0.b1

### Component Version

v3.3.6

### Bug description

No mather what i try, update/deleting component & card + all of the conf files (.storage and /community) 
I can't seem to alter the temperature, it always remains on the 18° that is set standard when hitting the set temperature button.

![Knipsel](https://github.com/user-attachments/assets/a3cd081c-4431-4615-b987-6470b67e739e)

### Steps to reproduce

Its the same problem  with every entity (2 normal thermostats + 1 heatingpump) schedule + temperature related 
There's nog problem in controlling the thermostats manualy

### Additional info

normal thermostats are controlled by KNX 
heating pump is controlled by the FG_Lair component.

**Comment by nielsfaber** [comment]
Could you please update the card to v4.0.0.b2 and test if this works?

**Comment by fabianbonte** [comment]
Can’t seem to find the b2 version on git

 

Van: Niels Faber ***@***.***> 
Verzonden: dinsdag 10 september 2024 19:10
Aan: nielsfaber/scheduler-card ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nielsfaber/scheduler-card] Card/component won't let me change temp. (Issue #834)

 

Could you please update the card to v4.0.0.b2 and test if this works?

**Comment by fabianbonte** [comment]
Hello Niels, where can i find version v4.0.0.b2?

**Comment by fabianbonte** [comment]
Hey Niels. A litle update. Used chrome browser on windows 11 and now it does work. In the ios app on the other hand still have te same problem with version b1. But i’m glad i could fix the heating in the bathroom again 😇 seems summer is over again 😝
