### ISSUE TITLE
No valve entities selectable

### ISSUE THREAD

**Issue by pacorola** [nielsfaber/scheduler-card#836]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V3.2.13

### Bug description

No valves selectable in list of entities 

### Steps to reproduce

Create new card, select entities and search for valves. They dont show. Also, if adding them manually through yaml, they still dont show in the card.

**Comment by pacorola** [comment]
![Captura de pantalla 2024-09-24 090819](https://github.com/user-attachments/assets/6ab514d4-54f1-49a5-a071-b671e19768f9)
As you can see, there is no valves category on the list. 
![Captura de pantalla 2024-09-24 090953](https://github.com/user-attachments/assets/8b40331d-bfa8-4b0c-b731-434996fb0617)
I even thought of manually adding the valve entities through YAML on the card, however they don't show anywhere after being added.
![Captura de pantalla 2024-09-24 091053](https://github.com/user-attachments/assets/0cc7f75d-a5c3-4a97-af27-1be9c8a47f31)
To me is particularly troublesome because this controls garden irrigation and there is no workaround (valve entities cannot be changed into switches for instance).

**Comment by TheEmperor80** [comment]
@pacorola I had the same issue and I simply created an input_boolean (toggle) helper, according automations to open and close the valve accordingly, and used that helper in the schedule

**Comment by emilianogetino** [comment]
Tengo el mismo problema, se van a incluir en un futuro las valvulas?
