### ISSUE TITLE
Error One or more actions are missing a required setting

### ISSUE THREAD

**Issue by byronward85** [nielsfaber/scheduler-card#838]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.0.b0

### Component Version

3.3.7

### Bug description

Whilst trying to modify or even add new climate schedule, I get the following error

Error
One or more actions are missing a required setting

Its worth noting that the existing climate schedules work fine. I just cant alter any or start new. 

If I create a boolean or switch schedule it works so its just a problem with climate. 

I'm using better thermostat if that makes a difference.

### Steps to reproduce

Simply trying to modify an existing climate schedule or create a new one reproduces the error

**Comment by byronward85** [comment]
Thank you it now works Sent from my iPhoneOn 26 Sep 2024, at 19:00, Niels Faber ***@***.***> wrote:﻿
This should be resolved by updating to the v4.0.0b1 version.
It is not listed in hacs as latest release (somehow) but you should still be able to install this version.

**Comment by mendipmac** [comment]
Took a bit of time over the last few days checking for this issue in HA help, but eventually came to it in your GitHub. Your advice to update to  v4.0.0b1 version worked for me too thanks. Not sure if it needs to be raised in HA itself? As I am sure we are not the only ones having this issue
