### ISSUE TITLE
Add conditions to run specific tasks

### ISSUE THREAD

**Issue by silkyclouds** [nielsfaber/scheduler-card#839]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I use the scheduler card for lots of things, and one of these things is to start my stove in the morning to warm my home. 

<img width="458" alt="image" src="https://github.com/user-attachments/assets/4b25061b-dc43-4ffc-b272-26b75af58f86">

Thing is, each time we are out of home for a few days, I need to think about disabling the start of the stove, manually. 

I'd like to have a way to tell scheduler that, if no one is home, and therefore entity zone.home is equal to 0, the task should not be run. 

This would automate the scheduler and only run these kind of actions if someone actually is present at home. 

### Additional info

nope. I think I've said it all :)

**Comment by silkyclouds** [comment]
in the meanwhile, I've created an automation to disable that specific scheduler task when no one is home. it's a possible workaround.

**Comment by vincemue** [comment]
i just started using this card today.
why cant you use entity zone.home in the condition?

![image](https://github.com/user-attachments/assets/7b50e8ae-81bf-4f58-acbb-6b76315cde61)

**Comment by charlesomer** [comment]
I don't think this should be closed :) I'm also looking to use the zone.home condition, thank you

**Comment by AlessandroTischer** [comment]
> i just started using this card today. why cant you use entity zone.home in the condition?
> 
> ![image](https://github.com/user-attachments/assets/6675abec-e84c-4eb6-a905-28a81ca98085)

If you go out when the stove is turned on, it won't be turned off, and that's a problem. In my opinion there should be a per-action condition, so that (for example) the turn off command can be executed anytime, while the turn off command can be executed only if the "at home" condition is satisfied
