### ISSUE TITLE
Turn On/Off/Toggle the card header toggle

### ISSUE THREAD

**Issue by loganizzi** [nielsfaber/scheduler-card#847]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I'm unable to find a way to trigger an action on the card header toggle.   It would be useful to be able to enable or disable all schedules shown in a card with a single command just as we can by manually hitting the header toggle.

### Additional info

For the device an action should be available that toggles/on/off the header toggle for the card

**Comment by jackmcconnell** [comment]
I believe this has been asked before: https://github.com/nielsfaber/scheduler-card/issues/573
