### ISSUE TITLE
No changes or creation of schedules possible

### ISSUE THREAD

**Issue by rolarndt** [nielsfaber/scheduler-card#849]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.0.b0

### Component Version

v3.3.7

### Bug description

After creating a new or changing an existing schedule it is not possible to store this. I get the following error message: "One or more actions are missing a required setting".
I can not store new schedules and the changes are not accepted. The error message also appears with no changes made after select "store".

### Steps to reproduce

trying to create schedules or change existing schedules

### Additional info

<img width="675" alt="Bildschirmfoto 2024-11-08 um 11 18 33" src="https://github.com/user-attachments/assets/0482e910-85eb-4984-8ab7-b0b8af6f5d2e">

**Comment by MStapelfeldt** [comment]
I can confirm this bug. I have exactly the same issue, while trying to adjust a working schedule.
It would help to see what is missing, but I can't find anythink, even if I change all avaible controls.

**Comment by nielsfaber** [comment]
This is a known issue, it was tackled in the v4.0.0.b1 release.
I am aware that for some reason this release is not shown as the latest in HACS, but it is definitely an improved release.
Please update (manually) to have the issues resolved.
**Any feedback on the v4 release is very welcome. I would like to release it for the public, but only once it has been thoroughly tested and people like it better than v3.**

**Comment by rolarndt** [comment]
Hello  @nielsfaber, thank you for the quick answer. I installed v4.0.0.b1 and now all is working well again.

**Comment by MStapelfeldt** [comment]
Can confirm. Went to HACS, Scheduler Card, 3 dots top right corner, download again, other version, v4.0.0.b1, download, refresh browser, working!

Thanks a lot. Now I'm finnally able to change my temprature again. :D
