### ISSUE TITLE
be able to close a details window by clicking outside of the window

### ISSUE THREAD

**Issue by spongebyte** [nielsfaber/scheduler-card#850]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I have a `type: custom:scheduler-card` on my dashboard, with a few scheduler entries. If I click on one, it will open a window where I can adjust the schedule.
In order to close that window, I need to click the X at the top-left. It would be great to just be able to click anywhere outside of the window to close the scheduler window, just like with entities or seemingly all other clickable items.
Many thanks for the great work!

### Additional info

.

**Comment by nielsfaber** [comment]
I deliberately blocked this from happening.
Why? Because I personally experienced that when creating a new schedule, a misclick could get all settings to get lost.
What is the problem with clicking the X button?

**Comment by spongebyte** [comment]
Thanks for your response.
I understand why you made it this way. It's fine as is.
If feasible, allowing click-outside-to-leave if no change has been made, and disallowing if discard/save is required, could be more ergonomic while still addressing your initial issue?
