### ISSUE TITLE
Bug on cover set position slider to 0%

### ISSUE THREAD

**Issue by alfonsolsl** [nielsfaber/scheduler-card#86]
Steps to reproduce:
- Choose Cover
- Choose Undefined service (should be set_cover_position)
- Select Week Days
- Keep the slider in ZERO, (this trigger the bug)
- Save

The automation sets to everyday by itself and the level of the cover sets to NaN%

![image](https://user-images.githubusercontent.com/6255385/94495240-d5593100-01b6-11eb-8b42-7e604bf5846f.png)

**Comment by nielsfaber** [comment]
Thanks for reporting this.
I fixed it in the v1.5.2 release (i think).
Please try it out, see if it is resolved for you.

The 'set cover position' translation text should be fixed as well.

**Comment by alfonsolsl** [comment]
Hello! @nielsfaber i try and the bug itself is not fixed, the translations and NaN are fixed.

If you repeat the steps the scheduler put itself in every day instead weekdays.

**Comment by KTibow** [comment]
@alfonsolsl Consider closing, duplicate of #90, a dedicated issue

**Comment by alfonsolsl** [comment]
Closed.
Duplicated on #90
