### ISSUE TITLE
Feature request: Graphical timeslots

### ISSUE THREAD

**Issue by aeklo** [nielsfaber/scheduler-card#91]
As your scheduler now becomes more and more versatile in a rapid tempo, my number of schedules grows accordingly.
Example: I want my bedroom to comfort temp at wake-up, then eco mode until bedtime, comfort for an hour, then eco again until the next morning. This alone requires four schedules.

There might be different needs here, but at least for climate, I believe slots of 15 mins in a matrix (time slots / weekday) would work great. Tick the box to activate given action for the marked timeslot.

Grouping of schedules could be a quick-fix to avoid flooding.

**Comment by nielsfaber** [comment]
This is actually a work in progress currently.
See an example here: https://community.home-assistant.io/t/scheduler-card-custom-component/217458/253?u=neliss
I need to make some changes to the custom_component so it understands timeslots, then i will release it.

**Comment by aeklo** [comment]
Great work! This add-on is making lots of progress :-D
